### ISSUE TITLE
[ASRangeController] interfaceState may not be updated when items are reloaded.

### ISSUE THREAD

**Issue by frankenthumbs** [facebook/AsyncDisplayKit#1019]
Hey guys,

I don't know if my understanding of what the ASRangeController is responsible for is incorrect, but it seems like if we call reloadData on a collectionView (or ASPagerNode), `ASRangeController`'s `_updateVisibleNodeIndexPaths` never calls `[rangeHandler node:node enteredRangeOfType:rangeType];` and thus, fetchData is never called.

Should something else be responsible for calling `fetchData`?

**Comment by appleguy** [comment]
@frankenthumbs you're right - this is a bug, and is why I am rewriting ASRangeController (in progress right now) to remove almost all of the state that it independently maintains and to reliably set ASInterfaceState (a brand new property in the framework, so we're just now taking full advantage of its expressive power).

If you look at the implementation of ASNetworkImageNode, you'll see it calls -fetchData on itself in -displayWillStart.  This is, in many cases, a workaround for this problem because display is guaranteed to occur for anything in the display range or visible range, whereas the -fetchData call may not occur for initially-visible items or certain types of item reloads.

I apologize for this unfortunate rough edge of the API.  IMO, it is unacceptable to have this kind of subtly unreliable behavior in a framework, which is why it has now reached the top of my priority list. Most of my development work in the last several weeks (including the very creation of ASInterfaceState and ASHierarchyState) has been motivated specifically to enable the rewrite of ASRangeController to a functional architecture that should prove far easier to have an extensive library of unit tests and consistently reliable call behavior.

**Comment by appleguy** [comment]
@frankenthumbs could you try out my patch, #1020, which is now in master / 1.9.4?  It might not fix your case, but I'm curious.

If you check out the code I added to examples/VerticalWithinHorizontalScrolling (it is gated with #if 0), and try running it, you'll see that indeed fetchData and visibilityDidChange:YES are being called when an individual row is being reloaded.  How do I reproduce the issue you're reporting?  Is it only when you reloadData the entire view at once?

**Comment by frankenthumbs** [comment]
@appleguy it seems like patch #1020 has fixed the bug i was running into.

the case was when `reloadData` was being called on `ASPagerNode`'s `view` after `ASPagerNode` has shown it's first view (which successfully called `fetchData` for `ASCellNode`s in range).

code snippet for the reload:
```
func reload(initialPage initialPage: Int? = nil) {
    pagerNode.view.reloadDataWithCompletion({ [weak self] () -> Void in
        // goto initial page
        if let initialIndex = initialPage {
            let indexPath = NSIndexPath(forItem: initialIndex, inSection: 0)
            self?.pagerNode.view.scrollToItemAtIndexPath(indexPath, atScrollPosition: .Left, animated: false)
            self?.currentPageIndex = initialIndex
        } else {
            self?.currentPageIndex = 0
        }
    })
}
```

Thank you so much!!

**Comment by levi** [comment]
Great to hear it, Joon. The latest master has methods on ASPagerNode for reloadDataWithCompletion and scrollToPageAtIndex so you no longer need to load the view unnecessarily.
