### ISSUE TITLE
[Layout Specs] Best way to center ASTextNode with attributed string?

### ISSUE THREAD

**Issue by yxztj** [facebook/AsyncDisplayKit#1031]
Hi,

Repro steps:
1. Create a ASTableView, implement dataSource
2. Create CellNode, which containing a subnode, which contains a ASTextNode with attributedString in turn.
3. When the cells are first rendered on screen, the text is centered with an unexpected offset(The string should be "TEST TEST TEST", but now the latter part is outside text node so you can only see "TEST T"). Looks like the attributes "thinks" the node has a bigger size, so the text is centered in a bigger frame rather than its actual frame. 
After scrolling down and up again(re-render the cell), the issue goes away.

Attached gif:
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/3334458/12083416/124eabd0-b2de-11e5-82fd-7dddc106fdb1.gif)

I've created a repo to demonstrate the issue. Please let me know if I'm missing anything.
https://github.com/yxztj/ASTextNodeTest

Thanks!

**Comment by appleguy** [comment]
@yxztj this is a good test case.  It might be that you need to set .flexGrow or some other ASLayoutable / ASStackLayoutable property.

Have you tried using ASCenterLayoutSpec?  Let me know what that does for you.  I will debug this by the end of the weekend - hopefully tomorrow, though.

**Comment by yxztj** [comment]
@appleguy The frame of the text node is correct. The problem is that text is not rendered correctly in the text node, instead it has an unexpected horizontal offset.(Looks like the text inside the node is centered in a larger frame)
We are using text attributes to align the text at center, so if there are multiple lines they are all centered.
Expected:
┌─────────┐
│  TEXT TEXT TEXT│
│            TEXT           │
└─────────┘
Actual
┌─────────┐
│                    TEXT T│
│                              T│
└─────────┘

**Comment by bsmith11** [comment]
I'm running into the same problem and it seems to have only started after I updated to ADK 1.9.4.

I don't think it's related to layout specs since I'm still using the old style of manually setting frames. It seems to only happen if `paragraphStyle.alignment = NSTextAlignmentCenter`. Below are screenshots showing `NSTextAlignmentCenter` and the default value `NSTextAlignmentLeft`. The frame of the `ASTextNode` has a white background so we can see that it's sizing itself correctly.

`NSTextAlignmentLeft`
<img width="377" alt="screen shot 2016-01-08 at 1 26 06 am" src="https://cloud.githubusercontent.com/assets/7103810/12191914/cf977296-b5a7-11e5-873c-87b91d54a1f2.png">

`NSTextAlignmentCenter`
<img width="377" alt="screen shot 2016-01-08 at 1 25 28 am" src="https://cloud.githubusercontent.com/assets/7103810/12191919/d92b8446-b5a7-11e5-8c6e-3d48aa22abf6.png">

**Comment by AttilaTheFun** [comment]
I'm having this issue as well with a text node inside a horizontal stack layout spec.

**Comment by yxztj** [comment]
@appleguy Several guys ran into the same issue. Seems more like a bug instead of layout issue?

**Comment by appleguy** [comment]
@yxztj Thanks again for this.  You should always use ASCenterLayoutSpec or another layout means to center text, whenever that is possible.  If you must mix the text and can't use different text nodes, and still need centering for part of the text, using NSParagraphStyle is acceptable.  The reason to prefer layout is that it can result in the text node being smaller, and a minimal size text node that is simply positioned where you want will use significantly less memory.  Please test master / 1.9.6 as the paragraph style centering should now work reliably.

**Comment by Mattmlm** [comment]
I ran into an issue while centering multi-line ASTextNodes, and found that if you use NSParagraphStyle with NSTextAlignmentCenter for an attributed string, you must wrap the ASTextNode in a horizontal ASStackLayoutSpec, with ASStackLayoutAlignItemsStretch. Once you've stretched the ASTextNode to fit it's container, the NSTextAlignmentCenter handles the centering of the text, and you can center the ASStackLayoutSpec in another layout.
