### ISSUE TITLE
Resize ASCellNode with tap gesture

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#1035]
Happy New Years guys!! I am trying to expand and contract an ASTextNode in an ASCellNode in an ASTableView and I have not been able to figure out how to do so. What I am using is:

```Objective-C
- (void)toggleDescriptionExpansion {
    NSLog(@"");
    
    self.isExpanded = !self.isExpanded;
    
    if (self.isExpanded)
        descriptionMaxLines = 0;
    else
        descriptionMaxLines = condensedLines;
    
    self.descriptionTextNode.maximumNumberOfLines = descriptionMaxLines;
    [self invalidateCalculatedLayout];
    [self setNeedsLayout];
}

condensedLines is a constant that I have currently set to 8 and set as default on init

I'm not sure how to use the layoutDelegate - when I call the above method, the cell does not change in height. Can you point me in the right direction to implement this simple functionality for the user? Thanks guys

**Comment by robmontesinos** [comment]
I'm not sure why but removing [self invalidateCalculatedLayout]; makes it work

**Comment by nguyenhuy** [comment]
Because setNeedsLayout [needs a constraint size to remeasure](
https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L758)
and therefore [expects isMeasured flag to be true](
https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L754),
but invalidateCalculatedLayout [turns off the flag](
https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L1660
).
On Th 3, 05 thg 1 2016 at 02:03 Roberto Montesinos <notifications@github.com>
wrote:

> I'm not sure why but removing [self invalidateCalculatedLayout]; makes it
> work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/AsyncDisplayKit/issues/1035#issuecomment-168849570>
> .
>
-- 

Regards,
Huy Nguyen

**Comment by nguyenhuy** [comment]
Because setNeedsLayout [needs a constraint size to remeasure](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L758) and therefore [expects isMeasured flag to be true](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L754), but invalidateCalculatedLayout [turns off that flag](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L1660
).

P.S: apperantly one can't simply write markdown in an email reply and expects GitHub to parse it properly :(

**Comment by robmontesinos** [comment]
Thank you @nguyenhuy - that makes sense I suppose. You guys have done an amazing job with this library. And are always quick to help a noobie like me. Thank you so much.

**Comment by nguyenhuy** [comment]
You are welcome! Let we know if these methods (and the ways they work) are confusing, even just a tiny bit, and any ideas to improve them. Feedbacks are always appreciated.

Otherwise, please close this ticket :P
