### ISSUE TITLE
[ASRangeControllerBeta] Performance

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#1044]
I was profiling collection view on iPad 3 (which is a rather challenging device :) and noticed that `ASRangeControllerBeta` is quite a bit slower than `ASRangeControllerStable`.

```
Running Time	Self (ms)		Symbol Name
1461.0ms    8.8%	3.0	 	       -[ASRangeControllerBeta _updateVisibleNodeIndexPaths]
785.0ms    4.7%	1.0	 	            -[ASCollectionViewLayoutControllerBeta indexPathsForScrolling:rangeType:]
773.0ms    4.6%	5.0	 	             -[ASCollectionViewLayoutControllerBeta indexPathsForItemsWithinRangeBounds:]
637.0ms    3.8%	1.0	 	              -[UICollectionViewFlowLayout layoutAttributesForElementsInRect:]
50.0ms    0.3%	12.0	 	          -[__NSSetM addObject:]
22.0ms    0.1%	7.0	 	              -[UICollectionViewLayoutAttributes indexPath]
20.0ms    0.1%	0.0	 	              objc_object::sidetable_release(bool)

```
-vs-
```
Running Time	Self (ms)		Symbol Name
937.0ms    5.2%	2.0	 	          -[ASRangeControllerStable _updateVisibleNodeIndexPaths]
332.0ms    1.8%	0.0	 	           -[ASCollectionViewLayoutControllerStable indexPathsForScrolling:rangeType:]
324.0ms    1.8%	4.0	 	            -[ASCollectionViewLayoutControllerStable indexPathsForItemsWithinRangeBounds:]
267.0ms    1.5%	0.0	 	             -[UICollectionViewFlowLayout layoutAttributesForElementsInRect:]
20.0ms    0.1%	6.0	 	             -[__NSSetM addObject:]
```

It seems that quite a lot of time is spent in `[UICollectionViewFlowLayout layoutAttributesForElementsInRect:]`. But visible and display ranges are subset of fetch data, wouldn't it be possible to only ask for layout attributes for nodes in fetch range and then select visible/display manually from these?

**Comment by appleguy** [comment]
@knopp yes, optimizing down the UICollectionViewLayout stuff is a big priority, but unfortunately we are limited in part because most folks don't want to adopt an asynchronous class for this.  In an ideal world, we could use something like ASFlowLayoutController (which could be used on a background thread), and then even the ASRangeController updates could be done asynchronously (except for visible range changes, which would have to wait on those updates - still would be a lot better).

The user retains the right to set the tuning parameters to anything, so they could even make the FetchData range 0.  However, it is definitely possible to check whether the range encompasses the other ranges.

The concern is that something needs to check whether each indexPath is in a certain range.  Even with the old implementation, this was pretty heavy weight--since collection layouts can be totally arbitrary, with items not even shown in contiguous order, we need to ask the layout what indexPaths exist inside each range separately so we can tell when a path changes from one to the other.

I think the cause of this is actually in the ASLayoutController classes. Previously, there was a suspicious bit of code (look for updateBounds) that limited the frequency of range updates.  I'm not convinced this is the right approach, but there is probably a balance that can be achieved where performance is /better/ than it was previously and still more frequently updated.

All this said, the class is still Beta considering that I haven't yet run a profiler on the new implementation (something I'm naturally quite passionate about).  It's been one of the most intense work-weeks of my career getting back to the office after the holiday weeks being focused on ASDK, so I'm really bummed that I am not going to have time to make big progress here until each weekend (and some nights).  In total, by late January, I should have this code in better shape.

Thank you for testing it and sharing your detailed findings!

**Comment by knopp** [comment]
@appleguy, thanks for the reply. I understand completely that you're busy

What I meant by the optimization is that instead of 3 calls to `[_collectionViewLayout layoutAttributesForElementsInRect:]` there would be only one. That should be doable, regardless of underlying layout.

The rect would be fetch bounds. After that you iterate over layout attributes and if the attribute frame is within visible / display range bounds, you add the attribute index path to appropriate set.

To do this however, `ASLayoutController` would need another method, something like `NSDictionary<ASLayoutRangeType, NSSet> indexPathsForScrolling:(ASScrollDirection)scrollDirection`, so that it could provide index path for all range types in one call.

I'll try doing this - I'm wondering if it makes noticeable difference.

**Comment by appleguy** [comment]
@knopp I think each independent range set is mandatory to perform the containsObject: calls which OR each flag in the interfaceState bitfield, right?

Fortunately, I did profile this code running against Pinterest on some ideal older device hardware - iPad mini 1, etc.  I found numerous possible optimizations and will be working on them in the next few days.  If you are able to look at this area, please do, because the single most impactful optimization is actually going to be in the scheduleDisplayForNode: and setInterfaceState: application code paths, with the UICollectionViewLayout ranges being a close third.  This is a very important issue that will definitely need investigation and optimization, so let me know when you reach a point where you are ready to pause investigation and hand off (even if it turns out a win is too hard to implement)

**Comment by appleguy** [comment]
One thing that will help is giving more direct access to _completedNodes without as many layers of method calls.  There is other stuff like that, reducing overall method call weight and looking at data structure handling, excessive retains / releases of each individual object, indexPath handling, etc that could benefit hugely from using something like ASIndexPath contained in C++ vectors or other approaches.

**Comment by knopp** [comment]
I meant something like this for a start https://github.com/knopp/AsyncDisplayKit/commit/865560054016cefd48aefc23e29bfefa638ecaf4?diff=unified

This way, `[_collectionViewLayout layoutAttributesForElementsInRect:]` is only invoked once. 
```
Running Time	Self (ms)		Symbol Name
1107.0ms    6.6%	6.0	 	           -[ASRangeControllerBeta _updateVisibleNodeIndexPaths]
472.0ms    2.8%	12.0	 	            -[ASCollectionViewLayoutControllerBeta indexPathsForScrolling:]
312.0ms    1.8%	0.0	 	                 -[UICollectionViewFlowLayout layoutAttributesForElementsInRect:]
```
in my case it reduced time spent in `_updateVisibleNodeIndexPath` from 8.8 to 6.6%. 

However I'm afraid the reason why `ASRangeControllerStable` performs as well as it does is that it is doing *much* less than `ASRangeControllerBeta`. That is because for fetch range, `_layoutController shouldUpdateForVisibleIndexPaths:rangeType:` returns NO most of the time, so during most scrolling updates nodes in fetch state are not processed at all. I'm not sure it is good behavior, but it's definitely fast :)

I think what could really help during fast scrolling is to dynamically reduce range tuning parameters. It's a lot of work to process 5 pages of nodes, and it is often done completely redundantly when scrolling gets really fast.

**Comment by appleguy** [comment]
@knopp Thanks for your work on this - I will check out your diff very soon.

Last night I came up with what I think is a very good idea.  I am going to move the calculation and application of the render and fetch data range to the background.  This will be a bit tricky, because a new main thread update may come in before those have finished, but I have ideas on how to do this.  Visible range will of course still be processed on the main thread to make sure that the call is 100% reliable in meaning "exactly visible".

This makes a lot of sense because then -fetchData will be called in the background, which is better for the work that it takes to put together a network request or database query - and also -scheduleNodeForDisplay can be called in the background, reducing work adding stuff to collections and gathering draw parameters for the display pass.  These two operations are inherently designed to be asynchronous and are supposed to be triggered before something is onscreen, so the /exact/ runloop in which they occur is not important.

What do you think about this?  My greatest concern is:

- fetchData would be called in the background, which it wasn't previously.  Some existing user code may not work with this.  That said, it is fairly rare to implement fetchData yourself - ASNetworkImageNode and ASMultiplexImageNode are the most common usages of it and they should be thread safe, and their safety is something I can audit and then ensure.
- the draw parameters method is normally called on the main thread, and ideally this would move it to a background thread.  Same problems apply — users may need to use some kind of locking mechanism to ensure that while this method is being run, any changes on the main thread to their properties are blocked on the lock.  This would be OK because the threading model states the main thread can be blocked on any background thread when needed, and that a background thread must NEVER block on a synchronous dispatch to the main thread.  Safer option would be to call system draw parameter methods like for ASImageNode and ASTextNode in the background, which these are the most common and expensive ones by far anyway, and find a way to continue calling third party implemented ones on the main thread.

Let me know your thoughts!

**Comment by knopp** [comment]
This indeed does sound very tricky. I assumed drawParameters was meant to be called on main thread, given that it accesses bounds and possibly other UIKit attributes. You'd still need call layoutAttributesForElementsInRect for every scrolling iteration on main thread, but yeah, everything else on top of it probably could be moved to background thread if you think it's worth the headache :). 

There are some other things that I've noticed in profiles, such as using NSIndexPath and NSSet in loops. ASIndexPath in std vector would probably be lot faster (if you know there aren't going to be duplicates).

**Comment by appleguy** [comment]
@knopp indeed you're right about drawParameters so I'm going to have to consider that one more carefully.  Harvesting it on the main thread is still feasible even if we're dispatching the range handling to the background, but it would be best especially if ASTextNode and ASImageNode can have a custom locking setup to allow them to harvest draw parameters in the background because those specific classes are fairly heavy.

I am planning to add another method to the "...LayoutInspector" protocol to allow indexPathsForElementsInRect: to be called in the background.  This can be backed by ASFlowLayoutController for UICollectionViewFlowLayout, and for custom layouts, a developer can optionally implement it if they want higher performance.  The idea would be to only include the indexPaths, not an entire UICollectionViewLayoutAttributes, which in addition to being in the background would help a lot.

**Comment by knopp** [comment]
Well, the thing is - with my patch 1.8% of CPU time is spent in `[UICollectionViewFlowLayout layoutAttributesForElementsInRect:` (as opposed to 3.8 without it), and that's with quite a lot of items and 5 pages of fetch tuning parameters. So the other stuff that's going on (i.e. setting interface state on nodes) does take significantly more time than this.

My concern is that a lot of stuff is being done in vain during scrolling. Nodes in 5 pages are being updated every iteration, even during fast scrolling, but they won't last in fetch state long.

**Comment by knopp** [comment]
@appleguy, this is indeed much faster with your latest commits
```
Running Time	Self (ms)		Symbol Name
838.0ms    3.3%	3.0	 	           -[ASRangeControllerBeta _updateVisibleNodeIndexPaths]
397.0ms    1.5%	0.0	 	            -[ASCollectionViewLayoutControllerBeta indexPathsForScrolling:rangeType:]
392.0ms    1.5%	0.0	 	             -[ASCollectionViewLayoutControllerBeta indexPathsForItemsWithinRangeBounds:]
3.0ms    0.0%	0.0	 	             -[ASCollectionViewLayoutControllerBeta rangeBoundsWithScrollDirection:rangeTuningParameters:]
1.0ms    0.0%	1.0	 	             DYLD-STUB$$objc_msgSend
1.0ms    0.0%	1.0	 	             -[ASAbstractLayoutController tuningParametersForRangeType:]
285.0ms    1.1%	1.0	 	            -[ASDisplayNode recursivelySetInterfaceState:]
32.0ms    0.1%	0.0	 	            -[NSMutableSet unionSet:]
```
I'll play with it some more to see if the behavior is correct, but for now it seems on par (or even better?) than `ASRangeControllerStable`

**Comment by knopp** [comment]
@appleguy, looks like I did miss something. When things seem too good to be true, they probably are. I ran the previous test with fetch/display range tuning set to 0; This is with correct default values
```
Running Time	Self (ms)		Symbol Name
1071.0ms    5.9%	5.0	 	      -[ASRangeControllerBeta _updateVisibleNodeIndexPaths]
574.0ms    3.1%	0.0	 	            -[ASCollectionViewLayoutControllerBeta indexPathsForScrolling:rangeType:]
564.0ms    3.1%	3.0	 	             -[ASCollectionViewLayoutControllerBeta indexPathsForItemsWithinRangeBounds:]
6.0ms    0.0%	0.0	 	             -[ASCollectionViewLayoutControllerBeta rangeBoundsWithScrollDirection:rangeTuningParameters:]
2.0ms    0.0%	2.0	 	             DYLD-STUB$$objc_msgSend
1.0ms    0.0%	1.0	 	             DYLD-STUB$$_Unwind_SjLj_Register
1.0ms    0.0%	1.0	 	             -[ASAbstractLayoutController tuningParametersForRangeType:]
239.0ms    1.3%	0.0	 	            -[ASDisplayNode recursivelySetInterfaceState:]

So it is still slightly worse than `ASRangeControllerStable`

**Comment by appleguy** [comment]
@knopp Thanks for your focus on this - I am far from done optimizing here, but I think we're in a good enough state that performance relative to Stable is not a defining element in when we can switch.

One of the senior engineers at Pinterest will be working on a change next week to allow asynchronous allocation of ASCellNodes.  We'll follow that up with a longer-term project (probably have a diff up by latter half of February) to split the allocation / assembly of the layer and view hierarchy across multiple turns of the runloop (thereby giving time for the runloop to decide to execute touch handlers, timers / displaylink, etc).  Naturally if an element enters the visible range, we'll block on finishing the allocation and assembly of the hierarchy at that point, but this should make a revolutionary difference in the largest remaining main thread impact in most apps.

Additionally, also next week, we're moving the display methods of ASTextNode and ASImageNode to a locking-based instance method (FrameworkPrivate for now) rather than creating the display parameters — this should be a pretty substantial win in the cost of the display range.

So with all three - async ASCellNode, direct instance display for key classes, and runloop amortization for hierarchy materialization - we should be at a radically improved state compared to today's framework on Stable.  Granted, most of these optimizations could be used with the Stable range controller too, but at that point I think holding parity as the bar for adopting a higher degree of correctness wouldn't be the right thing.  Still though, there are more wins to be had in the Beta range controller calculations itself, including the async application of interfaceState to nodes that aren't in the visible range.
