### ISSUE TITLE
[ASCollectionView] Improve support for animated / interactive layout changes.

### ISSUE THREAD

**Issue by Cabus** [facebook/AsyncDisplayKit#1057]
I created an ASCollectionView with custom layout and layout inspector objects. Everything works fine, no issues so far.
Now I need to animate to a new layout object (in this case a POUICVFL -> FlowLayout ;)). The collection view does animate the changes to the new layout. However, all cell nodes stay the same size and do not resize to the 'itemSize' specified on the flow layout.

Do i need to change the 'layoutInspector' property before setting the new layout?
Digging through the code of ASCollectionView, I can see that the only place '_layoutInspector' is set is in the initialiser whenever layout is of kind UICollectionViewFlowLayout.

Strangely enough, 'constrainedSizeForNodeAtIndexPath' of my custom layout inspector is not called after / during layout changes.
Do I need to manually signal the collectionView that the constrained sizes for its nodes changed?

Am i missing something here or does ASCollectionView not support layout changes?

**Comment by ankitthakur** [comment]
As per the code in ASCollectionView 

- (void)setAsyncDataSource:(id<ASCollectionViewDataSource>)asyncDataSource

Please try to setAsyncDataSource again, before calling reloadData on collectionview with new layout.

**Comment by appleguy** [comment]
@Cabus thanks for asking about this.  This is almost certainly on the cusp of working, but not quite there.  I have actually never tried an animated layout change, and neither has anyone asked me about it, which is pretty surprising...but for that reason we probably need a few lines of changes within the framework.

Example causes might be:
- We need to ensure all of the cells have calculated their new layout in order to animate; this may have to be forced to occur synchronously.  Good news is we have facilities to block the main thread on a concurrent background operation, so this should literally double performance compared to UIKit normally.
- itemSize is not fully integrated with the layout system, because it is not as expressive / well-integrated with the layout system as constrainedSize is.  It's also trapped by the non-threadsafe UICollectionViewLayout object :).  That said, this really is a bug / limitation more than anything else: particularly if constrainedSizeForItemAtIndexPath: is not implemented, we should be using itemSize.  I think there might already be some code to do this, but it hasn't been rigorously tested, and we might need something like an invalidateLayout call when itemSize changes etc.

@levi are you familiar with collection view animations?  I'm wondering if you could audit the code for issues in the area of fixed itemSize and animations / transitions, just to highlight what areas might need work, even if you don't have time to make the change.

**Comment by appleguy** [comment]
@Cabus @ankitthakur - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
