### ISSUE TITLE
[Framework Target] ASDisplayNode+FrameworkPrivate.h Not Available

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1062]
I'm using ASDK from Swift with Cocoapods `use_frameworks!`. In this context, the header is completely inaccessible since it's marked as "Project".

My use case is to mark some multiplex image nodes as `shouldBypassEnsureDisplay = false` because I'm confident the image will be available before appearance.

**Comment by appleguy** [comment]
@Adlai-Holler this is also true for the static library, not just for the framework target. Of course, the name should imply this, but the current exposure of the file is completely intentional :)  the use case you're referencing is certainly valid, but this is pretty clearly not the right way to address that use case.

Feel free to move that method to ASDisplayNode+Beta.h or a similar location intended for APIs in transition or with a limited number of users who are aware of the associated risks. The API surface for controlling the detailed behavior of synchronous concurrency has not been audited, and so the naming and functionality is likely to change in the future, but I suspect this is not a significant issue for your app!
