### ISSUE TITLE
[ASEditableTextNode] Add support for scrollEnabled property while preserving workaround for longstanding Apple bug.

### ISSUE THREAD

**Issue by lkzhao** [facebook/AsyncDisplayKit#1063]
I wonder if this is a design decision made previously. But why isn't the ASEditableTextNode support scrolling.
If we want to be able to scroll the textnode when text are long, what is the best way to do it with ASDK?

**Comment by appleguy** [comment]
@lkzhao I got some answers on this from the original author of the code.

"Hey Scott — following up on the radar. Apple closed it as behaving correctly. I clarified the bug in the radar — the bug is really that "When `scrollEnabled` is NO, UITextView no longer updates its `contentSize`."  This makes it impossible to tell how large the text is / how big to make the text view if you want to embed it inside of another custom UIScrollView."

So basically in Paper we had to leave scrollEnabled as YES so the sizing calculation was done, /but/, we actually did not want it to scroll by itself, because we needed the text to scroll inside a shared scroll view with a bunch of other elements alongside the text.

@lkzhao can you make a change so that _ASDisabledPanUITextView is instead named ASPanningOverriddenUITextView, and then add an instance variable for "_shouldBlockPanGesture"?  The ASPanningOverriddenUITextView should also override setScrollEnabled:.  It should always call [super setScrollEnabled:YES], but then just set the value appropriately for the _shouldBlockPanGesture.  Then the instance variable can be used in the UIGestureRecognizer method.

I know this feels hacky, because it is, but I don't want this change to break Instant Articles that probably still depends on this behavior - the Apple behavior is really not correct in my opinion.

Lastly, please expose a scrollEnabled property on the ASEditableTextNode in the header.  Ideally you can implement this in such a way that it does not trigger the view to be created, because it is extremely expensive to create a UITextView, and ASDisplayNodes are sometimes created and destroyed without their view ever being loaded.  The value for scrollEnabled: can be applied in -didLoad.

**Comment by appleguy** [comment]
This is fixed.
