### ISSUE TITLE
Sizing a collection view header

### ISSUE THREAD

**Issue by lappp9** [facebook/AsyncDisplayKit#1071]
So I was trying to convert some of my manual layout code to layout specs and I can't seem to figure out a good way to get my collection view headers to be the right size.  It seems like it should be really easy but I can't quite get it there.  The problem in my mind, is that I don't see a place to specify the size range for the layout spec.  Since the min is {0, 0} and the max is {375, 45} I'm getting a bar that only fills up half the width since the buttons are only so big.  Is there a way to get the stack layout to expand to take the entire width or a way to just specify the min and max for a collection views supplementary view? @nguyenhuy ?

<img width="375" alt="screen shot 2016-01-16 at 2 56 14 pm" src="https://cloud.githubusercontent.com/assets/432875/12374446/7178d5f4-bc61-11e5-94dd-25070d7d698e.png">

My layout spec:
```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.cameraButtonImageNode.preferredFrameSize = CGSizeMake(50, 50);
    self.notificationsButtonImageNode.preferredFrameSize = CGSizeMake(50, 50);
    self.radiusButtonImageNode.preferredFrameSize = CGSizeMake(25, 25);
    self.settingsButtonImageNode.preferredFrameSize = CGSizeMake(50, 50);
    
    ASStackLayoutSpec *stack = [[ASStackLayoutSpec alloc] init];
    stack.direction = ASStackLayoutDirectionHorizontal;
    stack.justifyContent = ASStackLayoutJustifyContentSpaceAround;
    stack.alignItems = ASStackLayoutAlignItemsCenter;
    
    stack.children = @[self.notificationsButtonImageNode, self.radiusButtonImageNode, self.cameraButtonImageNode, self.settingsButtonImageNode];
    
    return stack;
}
```

* if the button names are confusing I'm in the middle of swapping out the buttons, lol

The desired look, in case my description wasn't clear:
<img width="375" alt="screen shot 2016-01-16 at 3 20 09 pm" src="https://cloud.githubusercontent.com/assets/432875/12374564/b731a898-bc64-11e5-869b-f2bd8ce52c3b.png">

**Comment by nguyenhuy** [comment]
Sure, happy to help. 

The first thing to do (and seems like the missing piece here) is to tell the stack to fill the entire width available. There are a few ways that I can think of to achieve this:
1. Return a fixed constrained width (min width equals max width) via `-collectionView:constrainedSizeForSupplementaryNodeOfKind:atIndexPath:`. This method is defined by `ASCollectionViewLayoutInspecting` protocol. I honestly haven't played around with collection view inspector and so don't know off the top of my head where to implement/override this method. @levi must know though.
2. Wrap the entire stack inside a static spec, and assign to the stack a size range that has an exact 100% width.
3. As a general tip, if you have a horizontal stack inside a vertical stack, make sure to set the horizontal stack's `alignSelf` property to `ASStackLayoutAlignSelfStretch`.

As soon as the stack is required to fill the entire space, it will try to figure out how to eat up that much space. Since none of the buttons can grow, justifyContent will be considered. I think you will use either "space between" or "space around", probably the former. You also may need to set `spacingBefore` for the first button and `spacingAfter` for the last button, or to wrap the stack inside an inset spec.

Let me know if this helps!

**Comment by lappp9** [comment]
Thanks!  The static spec ended up working out! Though I am interested in ASCollectionViewLayoutInspecting, since I was hoping that delegate method existed somewhere, lol.  Also thanks for the stretch tip, that seems like it'll be useful.

**Comment by nguyenhuy** [comment]
Yeah, I would prefer using delegate method as well. Again, @levi knows about collection view layout more than me.

**Comment by appleguy** [comment]
@lappp9 did you try using SpaceBetween, as suggested in #1073 ?  I'd like to know if that does or doesn't work for your use case here.  Were there any followup questions to this or are you set?  Don't hesitate to reopen the task if more could be covered.
