### ISSUE TITLE
[ASButtonNode] Centering button title vertically.

### ISSUE THREAD

**Issue by Krisiacik** [facebook/AsyncDisplayKit#1074]
I have a ASButtonNode using 1.9.3. How can I position the button title to be in the vertical centre?

**Comment by nguyenhuy** [comment]
The easiest way is to update to v1.9.5 (or v1.9.4 at least, although there is no reason to avoid the latest version) and use contentVerticalAlignment. The default value is ASAlignmentCenter, so you don't even need to set it yourself.

**Comment by Krisiacik** [comment]
Unfortunately we had stability issues with 1.9.4 so we had to roll back to 1.9.3. Is there any way to achieve that with 9.3 version?

**Comment by nguyenhuy** [comment]
Sorry to hear that! You can also apply this patch to your local copy: https://github.com/facebook/AsyncDisplayKit/pull/963.

**Comment by nguyenhuy** [comment]
Actually alignments should already work before this patch. Can you give me what you are seeing in your code and a code snippet? I will try to figure out what is going on

**Comment by Krisiacik** [comment]
Hi 

Pls see attached files.  I updated to 1.9.5...unfortunately, there are 2 issues. 

1) alignment works unreliably i cannot align to vertical center no matter what, the grey-coloured area is the area of buttons.
2) There are four tabs, we use a pager controller. That means it supports horizontal swiping between tableviews embedded in pages. Once i swipe from NEWEST to OLDEST tab, the tableview is rendered. However the contents of buttons specifically the arrows sometimes rendered out of bounds. 

[CommentCellNode.swift.zip](https://github.com/facebook/AsyncDisplayKit/files/94661/CommentCellNode.swift.zip)
![img_2128](https://cloud.githubusercontent.com/assets/9870899/12396581/199885fa-be00-11e5-8731-ef1e1c53adbf.PNG)
![img_2129](https://cloud.githubusercontent.com/assets/9870899/12396582/19af466e-be00-11e5-9238-ba086d0e5995.PNG)

**Comment by appleguy** [comment]
@Krisiacik My personal apologies on the stability issues with 1.9.4.  I took a diff late in the release for ASRangeController, and should not have done so.  1.9.5 does resolve all the reported stability issues with 1.9.4, and overall is a small and conservative release that is very unlikely to regress anything further, so I'm glad you've adopted it.  Remember, you can email me directly at asyncdisplaykit@gmail.com any time, especially for something as terrible as a stability issue that blocks your adoption of a release.

Are you using ASPagerNode and ASTableNodes inside that?  If you do this, you will see very substantial performance improvements for your use case, because of the smart 2D preloading feature.  You may have already seen this, but here's a segment on the nested orthogonal scrollers and some of the intelligence that ASDK provides. https://youtu.be/RY_X7l1g79Q?t=19m43s

@RuiAAPeres are you also working on this same app?  Wondering if I could help debug it in the context of the app itself, let me know if you need any other assistance with the performance profiling stuff.

@nguyenhuy could you take a look and weigh in on any tweaks necessary to fix the layout?  Thanks!

**Comment by Krisiacik** [comment]
@appleguy Yep, it's two of us with Rui. No need to apologise, we are happy this framework exists at all. It's kind of a miracle from my perspective, given UIKit is 8 years old afaik and it shows sometimes.   

Guys I managed to stabilise the behaviour of button contents, that means the "reply" title now lays out properly when paging happens, though I had to use some counterintuitive odd values. 
Vertical alignment doesn't work at all though.

**Comment by Krisiacik** [comment]
@appleguy @nguyenhuy Guys I reverted back to 1.9.3 and managed to stabilise the layout.
I used measureWithRange with a nonZero minimum size on buttons so they are now always positioned correctly in all the cell. 
However with this I lost ability to centre vertically, which did not work anyway.

**Comment by hannahmbanana** [comment]
@Krisiacik: Are you still on 1.9.3? Is this still a problem?

**Comment by appleguy** [comment]
This should definitely be possible now. I believe they were new properties, called something like content vertical alignment, which have been present for several months. Definitely update to a newer version, there were a few quite important issues fixed in the versions since 1.9.3.

**Comment by Krisiacik** [comment]
Guys...this was quite a long time ago. Eventually I settled with a separate ASImageNode working alongside with ASTextNode.

**Comment by maicki** [comment]
I'm currently looking into it as there seems like a bug in `ASButtonNode` with laying out text and image via `contentVerticalAlignment` and `contentHorizontalAlignment`

**Comment by maicki** [comment]
Ok I think I figured out what is going on and want to provide more context. `contentVerticalAlignment` and `contentHorizontalAlignment` are working correctly if the node's layout process get's triggered the right way. It's not enough to just set a `frame` of a node in the `layout` method. The layout needs to be triggered either by calling `measure:` or `measureWithSizeRange:` with a exact size otherwise the `ASButtonNode` will try to shrink as small as possible.

To make this even easier I added support for `preferredFrameSize` to `ASButtonNode` via PR: #1806. How to probably measure and layout a node here is a small example as well as comparison between the old and new method.

```Objc
#pragma mark - WrapperNode

@interface WrapperNode : ASDisplayNode
@property (strong, nonatomic) ASDisplayNode *subnode;
@end

#define UseManualLayout YES

@implementation WrapperNode

- (CGSize)subnodeSize
{
    return CGSizeMake(200, 200);
}

- (void)setSubnode:(ASDisplayNode *)subnode
{
    _subnode = subnode;
    [self addSubnode:subnode];
    
#ifndef UseManualLayout
    _subnode.preferredFrameSize = [self subnodeSize];
#endif
}

#ifndef UseManualLayout
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    return [ASStaticLayoutSpec staticLayoutSpecWithChildren:@[_subnode]];
}
#endif


#ifdef UseManualLayout

- (CGSize)calculateSizeThatFits:(CGSize)constrainedSize
{
    return [self subnodeSize];
}

- (void)layout
{
    [super layout];
    
    CGSize measuredSize = [self.subnode measureWithSizeRange:ASSizeRangeMakeExactSize([self subnodeSize])].size;
    self.subnode.frame = (CGRect){.origin = CGPointZero, .size = measuredSize};
}

#endif

@end
```

I will close that issue as it's working as expected. Please reopen if this is not the case. Thanks!

**Comment by Krisiacik** [comment]
For future readers and clarification, at the time when I created this issue, the alignment did not work even with measure calls happening.

**Comment by maicki** [comment]
@Krisiacik Definitely thank you very much for filing that issue back than as it seems like it didn't work the way it should! Really glad that it seems like it's working now.
