### ISSUE TITLE
[Performance] GCD can spawn too many threads, reducing efficiency.

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#1080]
I'm still not quite happy with some performance aspects, so I have put together small project that tests AsyncDisplayKit overhead here

https://github.com/knopp/AsyncDisplayKitKiller (requires some patience upon start, it creates 5000 cell nodes)

Main problem with this example is, that during somewhat faster scrolling, after a while the app gives up and starts dropping a lot of frames, which looks very bad (even on iPad Air 2). I could live with the scrolling not running 60fps in this case, if the performance was at least somewhat consistent, but unfortunately it is not.

One thing I noticed is that there are over 60 rendering threads. Even though most of them are waiting on `__ASDisplayLayerConcurrentDisplaySemaphore`, it still seems that scheduling the call simply using `dispatch_async` is rather wasteful. It would probably be better if a queue was maintained internally (similar to how `NSOperationQueue` works) so that AsyncDisplayKit could limit number of spawned threads. 

This would also allow to have less overhead when cancelling rendering, the operation could simply be removed from internal queue (whereas now the block needs to be scheduled and executed anyway, just to compare the displaySentinel value).

There are probably other things too. Any ideas on how to make the performance more consistent are very welcome.

**Comment by knopp** [comment]
So, it looks like this might be a red herring. While there is certainly room for improvement, it seems that in my actual project the main cause for frame drops is setting the rendered image layer content. Which doesn't make me very happy since there doesn't seem to be much else to do.

**Comment by knopp** [comment]
So, this is not as much of a red herring as I though. The issue with setting `_layer.contents` was mostly caused by display range of 0, which means all items that were rendered were already onscreen. Setting layer content on onscreen element is obviously more expensive and it blocks until the image is ready to be displayed. Relaxing the display range significantly alleviated this.

But the main issue of dozens of threads killing the CPU persist - it's especially obvious on slower devices (iPad 3). I did a very ugly hack to get _ASAsyncTransaction to process the rendering sequentially and the performance on iPad 3 was much smoother.

**Comment by appleguy** [comment]
This is a great piece of performance research.  I wish we were working together 1-1 on a day to day basis, @knopp!

I've been worried about this for some time now, but assumed it was primarily an issue if there was excessive / abnormal blocking of blocks like display blocks contending on a lock.  However, it makes sense that could happen if decoding relatively high resolution images on a slow CPU (the iPad 3 being an ideal test case here).  The symptoms match what I'm seeing in just the last few days of starting to profile our new Pinterest implementation on iPad 3, where I'm now focusing all of the optimization time.

The change you've made is very important, although I'm not sure if it is the easiest way to achieve what we need — I'm fine with the approach it uses as long as we increase the concurrent display count to /at least/ 2* the CPU core count.  Starting at 2x cores is fine for now, as there will of course be layout operations, network parsing, main thread, etc but we do want a pretty high degree of saturation without excessive context switching.

I'll merge the change as soon as 1.9.6 is out, and start testing it heavily in Pinterest - and ask the ASDK community leaders to start doing the same in their apps :).

**Comment by knopp** [comment]
@appleguy, there are some benefits to my implementation :)

It doesn't modify much of ASDisplayKit code. The `ASAsyncTransactionQueue::Group` works very similarly to `dispatch_group_t`, including possibility of manual enter and leave.

It is also quite flexible. I went ahead and did a proof of concept implementation of drawing priority here https://github.com/knopp/AsyncDisplayKit/commit/99d78fb24b06b51548d52a89783872a93430f00a

In this branch it is possible to assign any `ASDisplayNode` custom drawing priority, where nodes with higher priority render first. In our case we have several labels in each node and one rather large thumbnail image. We definitely want the labels to be rendered before the thumbnails. In the branch I linked to this is as simple as setting `imageNode.drawingPriority = ASDefaultDrawingPriority - 1;` and it seems to work quite well.

Do you think this could be something generally usable or do we have weird use case?

**Comment by knopp** [comment]
Out of curiosity, @appleguy, why do you insist on `2 * activeProcessorCount` threads? I tried it on iPad 3, and during scrolling the experience seems worse than having just `activeProcessorCount` threads.

**Comment by appleguy** [comment]
@knopp very interesting.  In your testing, you find it clearly & unambiguously worse in terms of visual assessment of frame drops?

My findings during the development of Paper implied that having a few extra concurrent operations allowed the system to continue running another operation when one blocked on a system call or other resource.  In some cases the display method may load from a disk cache, for example, which isn't that unreasonable of a pattern (although fetchData is intended for this, that range could be zero'd out or set to the same as the display range, or the logic to retrieve from cache could just be put in the display method itself).

This would be particularly true when the main thread is not active, potentially allowing incremental increases in efficiency / total throughput of rendering operations (a very good things to preload ahead of the user as fast as possible).

The other reason, which is probably even more important, is to ensure that a small number of very large / long render operations (e.g. decoding fullscreen images) don't block small and fast operations (e.g. decoding a tiny icon, rendering a small label, etc).  Also, image decoding and text decoding engage different parts of the system stack that has often-inefficient internal lock contention, so it's preferred to have one thread doing text and another doing images than getting two images stuck in the pipeline and blocking all the text labels.

That said, your empirical finding today is a lot more meaningful to me than investigations I conducted a few years ago.  With that knowledge, I agree we should land with this current value and not change it until any further research is conducted.  Though it would be difficult to tune, we might want to look at something like whether a displaylink shows any frames are being dropped at all (say for the past several seconds) and dials back the concurrency count if there are any drops - and otherwise sets it higher.  But that would only make sense if I could re-verify and quantify the magnitude of any throughput increase from more heavily loading the CPU, which would have to be great enough to overcome context switching costs of course.

The "right" solution here is to invest in further sophistication of this system in at least two respects: separate queues (text & images at a minimum), and more dynamic prioritization to be able to always ensure the visible area is prioritized, the offscreen upcoming area is next, and anything unrendered in the outgoing area is last.

**Comment by knopp** [comment]
@appleguy, that's the nice thing about custom queue. Here I did a simple prioritization https://github.com/knopp/AsyncDisplayKit/commit/446c62a7a1595ca9f77ca20694ba6d5d0e159294 as a proof of concept, but it could be easily done in a way where you can schedule text and image drawing on different threads.

As for `CADisplayLink` I find it very unreliable. It often invokes the callback 60 times per second, even if there are obviously frames being dropped.

**Comment by appleguy** [comment]
Hmm, regarding CADisplayLink, that behavior should only happen if the frame drops are on the render server side - either GPU bound or CPU hierarchy scanning to set up the GL context for compositing.  Very interested though if you discovered other cases.

Should we close this task or rename it to be more general in tracking this space of work?

**Comment by knopp** [comment]
@appleguy, I didn't mean that it is entirely useless. In my experience it helps with simpler cases when you do something heavy in main thread, or the main thread gets smothered by several render threads, but ASDK is sort of past that. It's the other, more frustrating cases, i.e. when setting layer.contents causes occasional jerk on iPad Air 2, even though there's plenty of CPU time to spare, and CADisplayLink happily fires 60 times a second. I guess this falls under GPU bound.

I don't mind keeping this issue open for now, but if it's getting out of hand you can create the more general one.

**Comment by appleguy** [comment]
@knopp what do you see as the highest leverage next step for this? Most of our active work is now moved into the Ship bug tracker, which I would love to have you be a part of it if you're interested, and I mainly wondering how to translate this task -- such as if it should be broken up into a few different subsystems that can benefit from custom thread pools.

**Comment by knopp** [comment]
Hi @appleguy, I finished the prototype I was working on and am currently working on something completely unrelated (desktop component). Hopefully I should get back to iOS related things in couple of months.

**Comment by maicki** [comment]
After a brief discussion with @appleguy we will move this task into Ship.

@knopp Would love to get another performance review though if you have some time as this would be tremendously valuable on our road to 2.0.
