### ISSUE TITLE
[ASDisplayNode] Support UIMenuController

### ISSUE THREAD

**Issue by czechboy0** [facebook/AsyncDisplayKit#11]
I found two identifiers that were only mentioned in comments but the types themselves aren't defined anywhere:

`ASDisplayNodeView`, seems like a protocol that any view usable in a async display node would need to implement, mentioned in `_ASPendingState.h:25`.

`ASDisplayNodeAsyncView`, seems like a subclass of `UIView` that would too be usable in a node (also the way of adding more async views by subclassing), mentioned in `ASDisplayNode.h:22`.

Could you please add more details on these types? Plus some sort of a documentation of how to add a custom async view class. Thanks!

**Comment by appleguy** [comment]
Here's another duplicate - https://github.com/facebook/AsyncDisplayKit/issues/1017  Task #11, meet task #1017!

This feature has been rarely requested, but the fact that it's come up about three times now definitely indicates we should find a good solution.  Any thoughts from the community on the tradeoffs / requirements that we should define?

From my note to @tuyuan2012 --  I think it is possible to hook up the UIMenuController, though it is not very flexible and so there was some discussion about whether it would be best to build a custom callout bubble (that style of button selector). Are you wanting to use the full selection system with ASEditableTextNode, or just the menu controller with static ASTextNode ? Do you need to be able to use the selection handles to select a range, or just copy all in a given block? If you're able to upload an image of the case you're looking at in the UI that you'd like to implement, that would be a helpful guide for us to think through the possibilities (the two main branches being - integrate with UIKit's menu controller stuff, or instead just make something custom that is more flexible).

**Comment by appleguy** [comment]
@czechboy0 @secretiverhyme @zetachang @toulouse - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Comment by appleguy** [comment]
Closing issue.
