### ISSUE TITLE
[Tests] Update snapshot reference images to support 3x testing

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#1129]
Often my default simulator is the iPhone 6s Plus and running tests fail because the snapshot tests are looking for a 3x image. @nguyenhuy mentioned that it's a pretty straight forward process, albeit I have no idea right now how the snapshot library works.

**Comment by appleguy** [comment]
@levi - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
