### ISSUE TITLE
Node must be in a hierarchy to use -recursivelyEnsureDisplay

### ISSUE THREAD

**Issue by mtorcutt** [facebook/AsyncDisplayKit#1144]
Can anyone give me some insight on what might be causing this?

`ASDisplayNodeAssert(self.inHierarchy && (self.isLayerBacked || self.view.window != nil), @"Node must be in a hierarchy to use -recursivelyEnsureDisplay");`

I update my rows via the following method. The views window should not be nil. 
`self.tableView.insertRowsAtIndexPaths(indexPaths, withRowAnimation: .None)`

**Comment by zintus** [comment]
@mtorcutt reason for this is changing contents of table view, when table is out of window views hierarchy (read: not visible onscreen)

That's exactly what assert text states.

**Comment by appleguy** [comment]
@mtorcutt - There's been a recent behavior change that ensures that asynchronously displayed nodes are more tolerant to undergoing view rehosting events. Previously moving even the parent view of a node hierarchy to a different part of the view hierarchy, as occurs during a view controller transition, could cause the nodes to clear their contents, and this could negate a manual call to -recursivelyEnsureDisplay.

This has been fixed in recent versions and I am very interested to know if the same code you had before now works as you expect. Please let me know if you have time!

In general, for ASCellNodes that you would like to use "synchronous concurrency" type display, you should enable the .neverShowPlaceholders property for ASCellNode before you return it from the dataSource method. Also, if you have not adopted it yet, look at the newer variant of the data source method that returns a block, and in this case, simply set the property before the cell is returned from that block. 

If this approach works, it should remove any need for manually calling -recursivelyEnsureDisplay, but be aware that scrolling faster than the pre-display can keep up with, will cause some scrolling stutters. 

Feel free to reopen this issue, if you have any questions or the behavior is not fixed for you. I'd be happy to help!
