### ISSUE TITLE
[ASRangeController] Question about new range controller.

### ISSUE THREAD

**Issue by n8-g** [facebook/AsyncDisplayKit#1151]
There are a few blocks of code in ASRangeController.mm that create a mutable copy of a set from _rangeTypeIndexPaths, modify that set, and write it back:
```objectivec
    for (NSInteger i = 0; i < ASLayoutRangeTypeCount; i++) {
      id rangeKey = @((ASLayoutRangeType)i);
      NSMutableSet *rangePaths = [_rangeTypeIndexPaths[rangeKey] mutableCopy];
      for (NSIndexPath *path in _rangeTypeIndexPaths[rangeKey]) {
        if ([indexSet containsIndex:path.section]) {
          [rangePaths removeObject:path];
        }
      }
      _rangeTypeIndexPaths[rangeKey] = rangePaths;
    }
```

But _rangeTypeIndexPaths is initialized as an empty mutable dictionary. The only place where it will be properly populated seems to be -[ASRangeController _updateVisibleNodeIndexPaths], which isn't getting called first in my case.

The funny thing is, this doesn't cause a crash on iOS 9.2, because setting nil on mutable dictionaries doesn't seem result in an assertion failure any more (verified on both device and simulator).

**Comment by appleguy** [comment]
@n8-g thanks for the report! What version of the framework are you on? This code is no longer in the execution path of 1.9.6, and I believe the issue you are referencing was also fixed in the version before that.

If you take a look at the code, you will see that ASRangeControllerBeta is being used everywhere by default. The "Stable" version is actually fully deprecated at this point, I just haven't had a chance to rename Beta and completely delete Stable. The awesome news is that the most active members of the community have been helping me test this new range controller for a couple months, and after extremely extensive usage as well as the 1.9.6 launch enabling it by default, there have been no bug reports related to the new implementation. I think this is an indication of how much cleaner and well architected the implementation is, which the old version most definitely was not :)

Please let me know if you have any trouble updating to the latest version, whether it is a build issue or other compatibility issue, or a change in behavior that affects your app.  e-mail me anytime at asyncdisplaykit@gmail.com, or certainly don't hesitate to create GitHub issues like this one for API usage questions too!

**Comment by appleguy** [comment]
@n8-g this was fully replaced a little while back - good catch, but thankfully that whole area of the code was already deprecated and is now gone (for the good of the community!)  Please do file any new issues / ideas and email me if you have more questions :)
