### ISSUE TITLE
[Documentation, ASLayoutSpec] Create sandbox project that demonstrates ASStackLayoutSpec

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#1166]
After talking to a few on the Pinterest team on the issues they've been facing while adopting ADSK, the one commonality I hear is the complexity of understanding ASStackLayoutSpec. Flexbox itself is a complex beast, but I have found it helpful in the past playing around with this sandbox project to help my understanding: https://demos.scotch.io/visual-guide-to-css3-flexbox-flexbox-playground/demos/.

We should create a similar project that allows simple edits to properties of a stack layout and animates between the changes. It should be relatively trivial to achieve once the spec transitioning functionality is available in master.

**Comment by appleguy** [comment]
@levi the Ray Wenderlich three-part tutorial series should help this a lot.  @RCacheaux and @lappp9 are writing it now and it should be ready in a few weeks.  @nguyenhuy also linked to an interactive edu-game thing that tries to teach some of this stuff, but yours is a really excellent resource too.

@lappp9 maybe you could prioritize adding a new page to the.org website with a collection of links, Similar to the two interactive ones mentioned? Especially until the tutorial is available, and even after then, I think having a set of links to a wide variety of flex box related documentation and examples Will really help people get off the ground.  We can link to the page in questions here, and also add a callout to it on the homepage at some point. It would be really nice to do a very basic update to the homepage to callout a bullet list of some of the 2.0 features, and put the link to the layout spec resource page there.

**Comment by appleguy** [comment]
@levi: There is definitely still a need here, and there has been some work in this area. Moving this one to the new feature tracker for now. 

---------

The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
