### ISSUE TITLE
[Pedantic] Replace Percent with Fraction where Appropriate

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1179]
"Percent" refers specifically to the portion out of 100 units. Apple uses the word "fraction" in NSProgress to refer to this [0, 1] kind of value and I think it's very appropriate.

So I propose changing `ASRelativeDimensionTypePercent` to `ASRelativeDimensionTypeFraction` and all the related names, and update the word "percentage" in the documentation to "fraction".

I'm glad to knock the change itself out, but only if y'all are interested. Since it's breaking API it might be appropriate for 2.0.

**Comment by nguyenhuy** [comment]
I think it is a reasonable change. Thanks for bringing it up :+1:

**Comment by appleguy** [comment]
I _love_ this suggestion.  Hadn't considered it but strongly agree.  We should do this before 2.0.

**Comment by appleguy** [comment]
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
