### ISSUE TITLE
Question - how to resize frame of a node

### ISSUE THREAD

**Issue by avnerbarr** [facebook/AsyncDisplayKit#124]
I am using nodes as drop in replacement for their respective UIView.
I have a custom UIView with several text/image nodes.
In layoutSubviews I want to resize the node frame in the background - but getting an exception.
What is the proper way to do these calculations in the background?

**Comment by robmontesinos** [comment]
I'm scratching my head trying to get this work. I am observing for the presence or absence of an ad banner - sometimes the iAd is not available and is moved off screen and returned when it is available. Some resizing of the screen is necessary. I have a view controller with some nodes that I would like to resize - which is simple to do with views  but since I spent so much time converting this view controller to nodes, I really want to get this right. 

The frame variables are set with 'dispatch_async(dispatch_get_main_queue()' in viewDidLoad and they work until KVO calls showAdBanner or hideAdBanner and these three nodes disappear while the other nodes outside of those methods remain untouched. Thank you in advance

```ObjectiveC
#pragma mark - Ad Banners

- (void)showAdBanner {
    [super showAdBanner];
    
    self.containerNode.frame = CGRectMake(containerFrame.origin.x, containerFrame.origin.y, containerFrame.size.width, containerFrame.size.height - kBannerHeight);
    self.hashtagNode.frame = CGRectMake(videoHashtagFrame.origin.x, videoHashtagFrame.origin.y - kBannerHeight, videoHashtagFrame.size.width, videoHashtagFrame.size.height);
    self.descriptionTextView.frame = CGRectMake(descriptionFrame.origin.x, descriptionFrame.origin.y, descriptionFrame.size.width, descriptionFrame.size.height - kBannerHeight);
    
    NSLog(@"containerFrame: %@", NSStringFromCGRect(self.containerNode.frame));
    NSLog(@"videoHashtagFrame: %@", NSStringFromCGRect(self.hashtagNode.frame));
    NSLog(@"descriptionFrame: %@", NSStringFromCGRect(self.descriptionTextView.frame));
}

- (void)hideAdBanner {
    [super hideAdBanner];
    
    self.containerNode.frame = containerFrame;
    self.hashtagNode.frame = videoHashtagFrame;
    self.descriptionTextView.frame = descriptionFrame;
    
    NSLog(@"containerFrame: %@", NSStringFromCGRect(self.containerNode.frame));
    NSLog(@"videoHashtagFrame: %@", NSStringFromCGRect(self.hashtagNode.frame));
    NSLog(@"descriptionFrame: %@", NSStringFromCGRect(self.descriptionTextView.frame));
}
