### ISSUE TITLE
[ASDataController] App level code seems to have caused deadlock.

### ISSUE THREAD

**Issue by CodeEagle** [facebook/AsyncDisplayKit#1266]
![image](https://cloud.githubusercontent.com/assets/2311352/13280857/5e93d0a0-db1b-11e5-9176-544b621e4e0d.png)

when push and pop swifty, It seems like occur some problem

**Comment by appleguy** [comment]
@CodeEagle please provide the full output of "bt all", and I can tell you why your app deadlocked.  This is most likely caused by either core data or some other model level locking code that has created a deadlock situation...

**Comment by appleguy** [comment]
Note: your app code must never wait on the main thread.  ASDK never does that, which allows it to avoid deadlocks.  If you have, for example, code in an ASCellNode initialization that waits on the main thread - this is a possible result.  I can help you eliminate that dependency if full info is available.  Sorry for the trouble, hope I can help.

**Comment by appleguy** [comment]
@CodeEagle - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it and I would be happy to help. I hope you have been able to use the framework!
