### ISSUE TITLE
[ASTableView] indexPathForRowAtPoint returns nil

### ISSUE THREAD

**Issue by Arko4576** [facebook/AsyncDisplayKit#1325]
So I've been trying to implement 3d touch previewing into ASTableView now I've been running into the roadblock that indexPathForRowAtPoint, a necessary function to use 3D touch previewing, returns nil when trying to use it. Is their a replacement function that currently exists or is this something that is in the pipeline for later down the road?

Thanks for any help,
Best Regards,
-Aaron

**Comment by hannahmbanana** [comment]
@Arko4576 could you provide some more details on where / how you are using indexPathForRowAtPoint:? 

I modified the GradientTableNode (an ASTableNode) in the VerticalWithinHorizontalScrolling example app to print out the indexPathForRowAtPoint: of a UITapGR's locationInView: and it gives me the correct indexPath. Diff is attached below. 

[indexPathForRowAtPoint.txt](https://github.com/facebook/AsyncDisplayKit/files/180679/indexPathForRowAtPoint.txt)

**Comment by hannahmbanana** [comment]
@Arko4576 - are you still having this issue?

**Comment by appleguy** [comment]
@Arko4576 - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it or ping us on ASDK's Slack channel (#1582). I hope you have been able to use the framework!
