### ISSUE TITLE
[ASTableNode] Create a node wrapper for ASTableView.

### ISSUE THREAD

**Issue by secretiverhyme** [facebook/AsyncDisplayKit#133]
ASTableView (ASTV) and ASCollectionView (ASCV) are a convenient way to transition from views to nodes, but since they aren't nodes, they can't be used as first-class asynchronous objects in node hierarchies.  Some considerations:
* ASCellNode.supernode is always `nil`, even if its superview has a node wrapper, so the node hierarchy breaks down.  (See #110 for more on this.)
* ASTVs and ASCVs can't be used as cells in other ASTVs and ASCVs.  This problem may be obviated by the introduction of ASPageNode.
* The new explicit `-recursivelyDisplay` API can't be used on ASTV or ASCV — it's possible to force an offscreen node hierarchy to render itself, for preloading purposes, but not cell nodes.

Some potential solutions:
* Provide official node wrappers for ASTV and ASCV.  This would be _really_ clunky, since ASTV and ASCV are themselves wrappers for UITV and UICV, and we'd have to expose both the node and view variants for the two usecases.
* Add (more) hacks to ASTV and ASCV, so any wrapper node magically does the right thing.
* Add an explicit `-recursivelyDisplay` method to ASTV and ASCV.

**Comment by ide** [comment]
I actually think a hypothetical ASTableNode and ASCollectionNode are worth exploring in the long run. With the current ASTV and ASCV I ended up painting myself into a corner once I wanted to adjust the content offset and content inset of the scroll view since they aren't synchronized with cell insertion / deletion (for example, if you want to preserve the user's scroll position while adding new cells, you can't save the content offset, insert the cells, and then set a new content offset because those operations don't happen serially). I ended up writing a shim that lets UITableView synchronously render ASCellNodes and it worked out but I gave up the benefits of ASTV.

The rough idea I have in mind for ASTN is for it to provide a complete UITV API like ASDisplayNode does for UIViews. You should see a consistent view of the world as long as you always access the ASTN and not the backing UITV. A couple things are especially tricky: the UITV does get modified by external sources (namely scroll gestures but also automatic content inset adjustment if you have a UINavigationController, for example) and these modifications need to get synced back to the ASTN in a way that preserves consistency and the semantics of UITV.

**Comment by secretiverhyme** [comment]
ASTableView and ASCollectionView node wrappers that fully abstract the underlying APIs are an interesting idea — we should revisit this down the line once ASTV and ASCV are feature-complete.

In the meantime, I think either implementing ASPageNode (which should solve this problem in the common case) or providing simple node wrappers for ASTV And ASCV (with asynchronous display wired up) is the best way to proceed for now.

**Comment by ryanfitz** [comment]
As a user potential user of AsyncDisplayKit, I'd vote for an ASPageNode. I run into many use cases where I need a vertical table or collection view and then able to page through few simple views on each row.

I don't know enough info yet of how to build more complicated nodes, but would offer help in building out a PageNode if possible

**Comment by SRandazzo** [comment]
Subscribing to this issue

Was wondering if there are any known workarounds for this (apart from refactoring out existing tableview in favor of manually building a list of nodes?)
Thanks!

**Comment by SRandazzo** [comment]
Update for others who are in search of a temporary solution:

I was able to bypass the crash by using a `UITableView` instead of `ASTableView` at the top level (ie, the `UITableView` will contain `UITableViewCell`s which contain a ASDisplayNode/ASTableView)

I assume this means i'm losing some of the benefits of AsyncDisplayKit, but at least in thise case I won't have to go back and convert my code to standard UIKit. Additionally, in the future I can pretty easily make that `UITableView` an `ASTableView` once this feature is supported 

This makes me wonder however if there would be a way to tell ASTableView (which is just a UITableView anyway) to not perform any Async actions (thus allowing met o continue using ASTableView, while avoiding the crash).  

Fore reference:
- AsyncDisplayKit v 1.2.1
- All ASTableViews have `asyncDataFetch` set to `NO`

**Comment by appleguy** [comment]
@SRandazzo @ryanfitz @ide not sure if any of you have run into this recently (still using ASDK by chance?  I'd be curious, as some of the earliest commenters on the project!).

ASCollectionNode has been available for a couple months, and I would like to add an ASTableNode soon.

The fabled ASPagerNode is a high priority for Pinterest and should be built & upstreamed by the end of December at the latest.

**Comment by ide** [comment]
We're using React Native since its goals are lined up closer to our own. RN has some of the benefits (and challenges) of asynchrony that ASDK has, and we also liked the cross-platform aspect and dynamism of RN -- things that understandably aren't goals of ASDK.

**Comment by appleguy** [comment]
@ide That's really cool!  I am quite excited to start seeing more large mobile apps written with RN.

FWIW, ASTableNode was added a few weeks back, so anyone following this task should take a look :)
