### ISSUE TITLE
[ASTableView] Strange artifacts when changing the device orientation

### ISSUE THREAD

**Issue by gonzalezreal** [facebook/AsyncDisplayKit#1361]
Hi there,

I am seeing strange artifacts in `ASTableView` when changing the device orientation. There are some white boxes appearing on top of the content during the rotation animation. I have uploaded a video that shows what happens:

https://www.dropbox.com/s/wks3zy6kl1q5kj2/Untitled.mov?dl=0

Is there something I am doing wrong? I have seen the same effect in the kittens sample.

Thanks in advance!

**Comment by hannahmbanana** [comment]
@gonzalezreal - woah. that is an interesting bug! Are you using clipsToBounds? or a solid background color? It may not be an ideal fix, but it would help us debug if you see a visible change when setting clipsToBounds = NO and backgroundColor = clearColor

**Comment by appleguy** [comment]
indeed, especially on the ASCellNode and any containing / overall subnodes

**Comment by gonzalezreal** [comment]
@hannahmbanana Thanks for the suggestion, but there is no visible change if I tweak `clipsToBounds` or `backgroundColor`.

Will it help if I send you the code to reproduce the issue?

**Comment by hannahmbanana** [comment]
@gonzalezreal - Yes, a sample project would be the best way to proceed from here.

**Comment by gonzalezreal** [comment]
@hannahmbanana You can find the sample code [here](https://www.dropbox.com/s/icrikxl6suykx4k/GroupConversation.zip?dl=0)

Please let me know if there is anything else I can do to help. Thanks!

**Comment by hannahmbanana** [comment]
@gonzalezreal - sorry it took us so long to get around to this. Would you be able to upload the sample project again? there is no longer a file at link above.

**Comment by lsnpatryks** [comment]
@hannahmbanana - I am not sure if it is the same problem but I created a sample project with some artifacts while rotating. You can find a github repo here: https://github.com/lsnpatryks/adk-artifact - in order to recreate this bug you must select a row and then rotate the device / simulator. I am also able to recreate this while having ASTableView selection disabled - but in a much more complex example (so there is a chance that there is broken within my code). Hope this will be helpful.

screenshots:
![screenshot1](https://cloud.githubusercontent.com/assets/5601741/20305455/02e4d588-ab36-11e6-89a5-5444d73cdeb6.png)
![screenshot2](https://cloud.githubusercontent.com/assets/5601741/20305463/0b77676a-ab36-11e6-990d-ca31e3ab1783.png)

**Comment by lsnpatryks** [comment]
@hannahmbanana - ok, I added one additional commit https://github.com/lsnpatryks/adk-artifact/commit/42b7f33104aa5e954819957515ab9a800ef2d7f0 - now you do not need to select a cell to see that bug (so basically making `flexShrink = true` causes the problem - otherwise the label is not line-wrapping and there is no error).

**Comment by hannahmbanana** [comment]
@lsnpatryks - thanks for putting together a sample project! 

FYI - ASDK does not support Auto Layout, so I replaced 
```
view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[v]|", options: NSLayoutFormatOptions(), metrics: nil, views: ["v":tableView]))
view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[v]|", options: NSLayoutFormatOptions(), metrics: nil, views: ["v":tableView]))
```
with 
```
override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        tableView.frame = self.view.bounds
    }
```
You're right about the `.flexShrink` on line `69` being the issue. @maicki - can you comment on whether this is expected behavior?

**Comment by hannahmbanana** [comment]
Just to check, I upgraded the code to use ASDK 2.0 and the problem persists. 

[adk-artifact-master.zip](https://github.com/facebook/AsyncDisplayKit/files/593696/adk-artifact-master.zip)

**Comment by appleguy** [comment]
@maicki this has existed for a long time - we should definitely check what's going on to be confident in the 2.0 implementation.  Let's try it against the new setNeedsLayout as that is the future :)
