### ISSUE TITLE
Forcing a horizontal ASStackLayoutSpec to limit children's width on first layout pass

### ISSUE THREAD

**Issue by wpK** [facebook/AsyncDisplayKit#1368]
Hi,

Before I begin, I just wanted to say thanks to all of the project contributors. This project makes building responsive UI intuitive and easy to maintain.

I'm trying to use ASLayoutSpec (AsyncDisplayKit v1.9.7) to generate a layout that I'm not 100% sure is possible. I've created a [gist with a Swift file](https://gist.github.com/wpK/a41546401db2111a2ded) that displays the following:

![width_test](https://cloud.githubusercontent.com/assets/243156/13712079/b79a80ec-e78f-11e5-9589-09406a3dca71.jpg)

My goal is for the box to be smaller (the red is the "extra" spacing). I'm still learning how the new layout system works so this might not be completely accurate:

The initial layout pass gives the TextView an infinite width because it's inside of a horizontal stack. When the TextView comes back with a size thats larger than can fit, and flexShrink is set to true, it will try laying out again, with the "remaining" width available.

Now where the TextView makes things complicated: Most views simply "shrink" to the exact amount left, but due to the TextView rearranging the text to fit, the most "optimal" size is not the exact size that the horizontal stack provided.

My first assumption was as long as the TextVIew returned a new size, the horizontal stack would simply shrink to that size. I assume this is not the case as it would cause issues if two nodes are constantly "jumping" switching back and forth with different sizes while trying to find the most "optimal" size.

So my question is: Is there anyway that I can tell the horizontal stack to limit the width of it's children to it's parent (the vertical stack) on the first "layout" pass? I've experimented with flexBasis, ASStaticLayoutSpec with sizeRange, etc and have had no luck yet.

Layout code:

``` swift
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    let hStack = ASStackLayoutSpec(
      direction: .Horizontal,
      spacing: 0,
      justifyContent: .Start,
      alignItems: .Start,
      children: [self.textNode])

    hStack.alignSelf = .Stretch

    let vStack = ASStackLayoutSpec(
      direction: .Vertical,
      spacing: 0,
      justifyContent: .Start,
      alignItems: .Start,
      children: [hStack])

    return ASInsetLayoutSpec(
      insets: UIEdgeInsetsMake(8, 8, 8, 8),
      child: ASStaticLayoutSpec(children: [vStack]))
  }
```

Thanks,
William

**Comment by jellenbogen** [comment]
@wpK Looking at your example code, I have a few questions / things to note.

First to try and answer your question. Are you just trying to get calculateSizeThatFits on your textNode to be called with a size who's width is bounded by the width of the vStack? If this is the case, you can set textNode.flexBasis = ASRelativeDimensionMakeWithPercent(1) on your textNode, this will make sure it's calculateSizeThatFits method is called with a size that has a bounded width, which in your case is 164 (180 - the edge inset you have).

Now if you are looking to have calculateSizeThatFits called with something smaller, you'll just need to adjust the percentage on the flexBasis value. Setting it to 0.5 would give you something like this:

![screen shot 2016-03-17 at 11 07 48 am](https://cloud.githubusercontent.com/assets/1269011/13856027/8752f5cc-ec30-11e5-8f09-98adee10e832.png)

To get rid of the overflow you'd have to set your hStack to have flexShrink = true which would end up looking like this:

![screen shot 2016-03-17 at 11 08 57 am](https://cloud.githubusercontent.com/assets/1269011/13856061/b24d1bc2-ec30-11e5-9ea1-783ccb6d73ef.png)

However from reading your question it seems like you want something like this but with the entire layout to still take up your measuring size of CGSizeMake(180, 142), if this is the case you'll need to call measureWithSizeRange and supply a min size, otherwise calling measure will just use size zero as the min. 

So instead of calling, self.containerNode.measure(CGSizeMake(180, 142)) call, self.containerNode.measureWithSizeRange(ASSizeRangeMakeExactSize(CGSizeMake(180, 142)))

![screen shot 2016-03-17 at 11 03 09 am](https://cloud.githubusercontent.com/assets/1269011/13855918/dd1cc164-ec2f-11e5-9226-e461dbb1f335.png)

However if you had multiple children layouts in your hStack using 1 as the percent might not be what you'd want, you might just have to use the correct percent you want for each child.

is this along the lines of what you're looking for?

**Comment by wpK** [comment]
@jellenbogen Thanks for taking the time to help!

I think my question and code sample was way too bloated and confusing. I'm trying to get the vStack to shrink to the width of the hStack and the hStack to shrink to the width of the textNode.

The 180/142 was added to make sure what everyone else sees on their device matches my screenshot. Here is another screenshot showing what I would like to see happen given a containerNode with the MAX width/height being 180,142.

Thanks again for the help!

**Comment by jellenbogen** [comment]
Ah I see what you're asking here. However I'm trying to understand if there is a more complicated layout you're trying to achieve or is it just what you've posted here. 

I only ask because there are other simpler layouts to get what you've just shown here, as I'm sure you've tried, so I'd like to understand what you're ultimately trying to get to?

**Comment by wpK** [comment]
The real UI is a bit more complicated than this. Think iMessage bubbles. You have a ASTableView that contains a bunch of cells that are the width of the ASTableView. Inside is a text node which has a background. You want the text node to grow as much as possible, but at the same time you want the background to wrap the text perfectly.

Just like the example I have an HStack inside a VStack, and I want the text node inside the HStack to have it's size set to exactly as much room as it requests.

**Comment by hannahmbanana** [comment]
@wpK: were you able to solve your layout problem? If not, I can take a stab at it. I just want to know whether or not you've figured it out before I try it out myself.

**Comment by wpK** [comment]
@hannahmbanana not yet, I put it aside for a bit when my efforts failed. If you could figure it out that would be amazing.

**Comment by maicki** [comment]
@wpK I think your layout is totally fine. It's just the text node laying (we use internally Core Text) out your text this way as you have a sample text with very long words and wrapping it the right way is kind of complicated and so 

Just set your sample text to something different and I think you will have the right representation (look into the gist, you can also add some more character and you will see it)

Furthermore you don't need to wrap the layout in a static layout spec too :)

Here is a new gist: https://gist.github.com/maicki/f7e53bc4c93651c73b7faeb3f3d7afb5

Let me know if we understand it right what you wanna have. Maybe a more extended sample project would help that show's in what problems you are run into.

**Comment by wpK** [comment]
@maicki The static layout was my mistake from trying other layouts types before posting. Thanks for pointing that out.

I could work on creating a better example. A perfect example is the Pinterest chat bubbles. Do you think it would be possible to get the same behavior with AsyncDisplayKit using the ASLayoutSpec?

When the text node is initially offered an infinite width by the hstack, it returns back a size too large for hstack, so hstack then passes a new size to the text node, in which the the text node returns back a new size that fits within the hstack. The issue is, because the hstack already has it's width set, it ends up being bigger.

I'm not 100% sure that there is any simple solution using ASLayoutSpec. If the layout system did what I want, then the hstack would then see it needs to get smaller, and then the parent will have more room which would require another layout, which in return could cause more layouts potentially causing an infinite loop.

Thanks again everybody for your help. I haven't had time to work with it again but with all the activity here I think I'll give it another go.

**Comment by garrettmoon** [comment]
Hey @wpK I'm going to close this issue for now. If you need further help, please consider joining our [slack](http://asdk-slack-auto-invite.herokuapp.com/) and asking questions in the #general channel.
