### ISSUE TITLE
[Carthage] Static library archiving issue

### ISSUE THREAD

**Issue by Ronnel** [facebook/AsyncDisplayKit#1375]
While using the static library in iOS, you can't archive as it give you a message saying "AsyncDisplay/AsyncDisplayKit.h" not found. Changing the header search paths do not help. I did create a workspace and add the xcodeproj file to that.

**Comment by hannahmbanana** [comment]
@Ronnel I may be able to help you with this. Are you using Carthage? Not CocoaPods I assume? Or, are you trying to build a static library directly from the project and include it in yours? 

What version of ASDK are you building? I noticed a few PRs that fixed issues with the static library build, so it is probably worth trying building the master branch rather than any of the releases. 

Overall, if you can provide more information about your configuration and full output of your errors, I'm sure someone in the community can help you out!

**Comment by Ronnel** [comment]
I'm trying to build the static library in the program, im using the latest version of ASDK. I managed to fix it by moving the header files to the copy files but now for some reason, <AsyncDisplayKit/_ASAsyncTransactionContainer.h> is not found during archiving though it works fine when building for a simulator or an actual test device.

**Comment by hannahmbanana** [comment]
@Ronnel: AsyncDisplayKit now supports the standard way to use Carthage:

_The standard way to use Carthage is by having a Cartfile listing the dependencies, and then running carthage update to download them in the Cathage/Checkouts folder, and build each of those into frameworks located in the Carthage/Build folder, and finally the developer has to manually integrate in the project._

AsyncDisplayKit does not yet support the lighter way of using Carthage, in which you manually add the project files.

http://www.mokacoding.com/blog/carthage-no-build/
