### ISSUE TITLE
Public way to get a node from a UIView

### ISSUE THREAD

**Issue by supersv** [facebook/AsyncDisplayKit#1379]
Unless I'm missing something obvious, there's no public way to get a node (if any) from a `UIView`.

`_ASDisplayView` is private, so we can't use `-isKindOfClass:`, and `asyncdisplaykit_node` is private as well.

Getting a node from a view may be necessary, for example, to implement `-touchesShouldCancelInContentView:` in a `UIScrollView` subclass, in order to handle control nodes in a similar fashion as `UIScrollView` does.

A non-private method or property, or just a func like `ASNodeFromView()` simply returning `view.asyncdisplaykit_node` would do the trick.

Thank you.

**Comment by joostvandijk** [comment]
Is it `ASViewToDisplayNode()` you're looking for? (ASDisplayNodeExtras.h)

**Comment by supersv** [comment]
Thanks, @joostvandijk , that's exactly it. My bad for forgetting about seeing the func somewhere.

**Comment by appleguy** [comment]
@supersv @joostvandijk I just learned a few days ago that this header was marked public, which wasn't actually intended. :)

Although the function should behave as desired, it is important to know that you should not require this function in your application (certainly not in many places). For example, you might consider a delegate protocol or another technique to do this. 

Could you share a little bit more about your use case so that I can understand the best route to provide a fully supported API? 

Please be aware that this method may change and you may need to adapt your usage of it. However, if this happens, I will try to ensure that a similar alternative is provided.

**Comment by joostvandijk** [comment]
@appleguy I've actually been using it for quite some time in a node with a custom view. Since the view is a `UIScrollView` subclass, and thus doesn't inherit from `_ASDisplayView`, I needed to forward some view methods to its node.

**Comment by supersv** [comment]
@appleguy One use case is this - http://stackoverflow.com/a/3550157/362305

Basically, I want a `UIScrollView` to behave just like it does with a regular `UIButton` inside a table view cell. When you touch down on the button and start moving the finger around, the button is tracking the touches, but the scroll view doesn't scroll during this tracking.

Judging from the linked SO answer (and verified in practice), `UIScrollView` distinguishes between `UIControl`s and other `UIView`s when handling such situations. To replicate this behavior, a way to get a node, if any, from an arbitrary view  is necessary, and, in my opinion, `ASViewToDisplayNode()` does the job perfectly.

P.S. Thanks for AsyncDisplayKit, awesome stuff.

**Comment by supersv** [comment]
Getting nodes from `UIAccessibilityElementFocusedNotification` and `UIAccessibilityFocusedElementKey` is another use case.

**Comment by garrettmoon** [comment]
I think the use cases for this are reasonable but can be achieved in alternative ways to avoid exposing this internal method. I'm going to close this issue, thank you all for your input, we appreciate it!
