### ISSUE TITLE
[ASVideoNode] Is it time to add to the umbrella header?

### ISSUE THREAD

**Issue by ItamarM** [facebook/AsyncDisplayKit#1388]
Hi guys!
Can you mark ASVideoNode.h as a public header so I'll be able to import it?

p.s.
Maybe that's by intention so sorry in advance.

**Comment by appleguy** [comment]
@ItamarM indeed, this was intentional, as this class was just added to the framework in the release before the current one. Has now been improved enough that it is generally stable for regular use, although it is still at risk of having certain bugs because it has not been widely used for a long time (most of the rest of the framework has been used for several years in very intensive environments)

Will take care of it soon.

**Comment by appleguy** [comment]
Thanks @hannahmbanana !  cc @lappp9 congrats on your component becoming mainstream - lots of users already!  https://github.com/facebook/AsyncDisplayKit/pull/1402

**Comment by lappp9** [comment]
🎉
