### ISSUE TITLE
[transitionLayout] Assert "Can't start a transition when one of the subnodes is performing one."

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#1400]
I'm getting this assert in `transitionLayoutWithSizeRange:animated:shouldMeasureAsync:measurementCompletion:` and it's correct a subnode has also started an animation. In this case it's exactly what I want, two animations in flight at the same time (different items fading in at different rates.) How can I accomplish this or avoid this error?

**Comment by appleguy** [comment]
@eanagel - the reason this assertion exists is because transitions are capable of performing detailed animations and even addition and removal of subnodes at every level of the hierarchy beneath the call point. For obvious reasons, especially considering that the API is thread safe and that the measurement calculations can be easily performed on a background thread simply by calling transition there, it is important to ensure consistency. 

If you could elaborate on your use case, which is probably valid and worth supporting, we can think about the way to support it. The architecture in this area is actually in great shape to modify this behavior, potentially doing something like allowing a subtree that is animating to take precedence over animations of the parent, but we will need to think through certain threading implications. 

cc @levi @nguyenhuy (don't worry about implementing now, just something to brainstorm about for the longer term future of the transition API)

**Comment by appleguy** [comment]
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send us an email at AsyncDisplayKit@gmail.com or ping us on ASDK's Slack (#1582). If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Comment by master-nevi** [comment]
@appleguy One reason to allow this behavior is if you have a somewhat deeper node hierarchy and animating a subnode effects the position of a node higher up in the tree, ideally everything would shift in an animated fashion:

Example:
```
  Node A
+-------------------------------------+
|                                     |
|   Node B.1                          |
|  +-------------------------------+  |
|  |   Node C                      |  |
|  |  +-------------------------+  |  |
|  |  |                         |  |  |
|  |  +-------------------------+  |  |
|  |                               |  |
|  |   Node D                      |  |
|  |  +-------------------------+  |  |
|  |  |                         |  |  |
|  |  +-------------------------+  |  |
|  |                               |  |
|  +-------------------------------+  |
|                                     |
|   Node B.2                          |
|  +--------------------------------+ |
|  |                                | |
|  |                                | |
|  |                                | |
|  +--------------------------------+ |
|                                     |
+-------------------------------------+
```

Here, if we remove node D with an animated transition, node B.1 will shrink in size and node B.2 will shift up without animation. Ideally if the removal of C effects the positions or sizes of any nodes higher in the tree they should be able to animate also.
