### ISSUE TITLE
[ASVideoNode] new delegate methods and ASVideoNodePlayerState

### ISSUE THREAD

**Issue by Eke** [facebook/AsyncDisplayKit#1401]
Hello guys,

I have application based on video content, so there is video player in every corner :smile_cat: 

The whole app except video player is made with AsyncDisplayKit and i want to change this.

We have custom video player, like ASVideoNode and it has a lot of delegate methods, for many cases which we use.

I am trying to implement such thing in `ASVideoNode`, so i forked it and made few changes listed bellow.

It will be super if i can hear some ideas from you. If my changes will be useful and it's not bad what i did, i will continue and at the will make pull request :blush:

Here is [link](https://github.com/Eke/AsyncDisplayKit/commit/d8e752f3fafd697506428199639f49469030a9be) to my `ASVideoNode` branch latest commit, which implements everything listed bellow

Added `ASVideoNodePlayerState` and two delegate methods, `videoNode:willChangePlayerState:toState:` and `videoNode:shouldChangePlayerStateTo:`

 `videoNode:willChangePlayerState:toState:`  notifies delegate that `ASVideoNode` is going to change player state.

`videoNode:shouldChangePlayerStateTo:` asks delegate if `ASVideoNode` should change state to new one. for example in some cases you can disable video pause or play.

In `ASVideoNode` class replaced : 
`[self play]` with `self.playerState = ASVideoNodePlayerStatePlaying;` 
`[self pause]` with `self.playerState = ASVideoNodePlayerStatePaused;`

Added new method `setPlayerState:` which decides must `ASVideoNode` call play or pause methods.

If this changes are ok, must remove public play and pause methods from header file. Must use `setPlayerState:` instead

@appleguy Can you take a look?

**Comment by appleguy** [comment]
@Eke - sorry for the late response it's been a busy few weeks! 

This sounds like a definite improvement to the ASVideoNode API, and is something we would likely build upon at Pinterest as we are also interested in things such as a full screen playback state!

Please do proceed to a pull request. Please note, however, that we should include the play and pause methods near the bottom of the header and comment that they are deprecated. Internally, these can simply call the state change API, and we will remove them in a few months.

**Comment by Eke** [comment]
Hello @appleguy, happy to hear this. I have also few more ideas how to improve `ASVideoNode` with more delegate methods, will add them too. In few days will submit pull  request.

I am thinking about implementing layout object for `ASVideoNode`, which will contain everything needed for player layout, starting from play button icon ended with fullscreen button position (just idea for now). Will be happy to hear your thoughts about this.

About fullscreen, i was able to implement fullscreen playback with AsyncDisplayKit in my app (like Facebook from ASCellNode), app is in review now, can send link to you when it's published, if interested.

**Comment by appleguy** [comment]
Thanks @Eke for putting up the PR!  I think it is a step in the right direction.

That said, speaking with a few coworkers today, they pointed out that the scope of possible states are not all things that should be possible for a developer to set. For example, when playing is finished, this is not necessarily a state that should be available to set on the Player and I believe we will add other states in the future such as paused due to running out of video buffer.

So, for the time being I think it would make sense if we keep the play and pause methods, and then introduce the new state variable as a read only property. We're this still support most of your needs? It would still be fine to have a delegate method that can control whether or not the player can make certain state transitions, Although those state transitions would probably be initiated by a more direct method such as play or pause.

Another option is to introduce a different type of enumeration that has actions that can be set, and include play and pause in those

**Comment by appleguy** [comment]
@Eke - I really appreciate all of your activity on the ASDK Slack channel & as a ASVideoNode developer! We're in the process of moving to a new issue tracker / moving dev coordination to Slack, so I'm going to close this issue out. However, it does not mean that I am not dedicated to improving ASVideoNode and I look forward to seeing more ASVideoNode collaboration on Slack. :)
