### ISSUE TITLE
[SocialAppLayout] Disappearing divider line

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#1417]
1.In your SocialAppLayout exzmple, when I touch the nolmal word ,the node will not response to tableView:(UITableView *)tableView didSelectRowAtIndexPath: 
How can I touch the nomoal word can response to tableView:(UITableView *)tableView didSelectRowAtIndexPath:,But touch the rich word will not.

**Comment by wy19901227** [comment]
2.about zhe divider line，I set it's color red color,when I touch the cell,It will dissappear,when I untouch It will appear,Can make it not dissappear?

**Comment by hannahmbanana** [comment]
@wy19901227 - thanks for your question! I believe this is the correct behavior for the current implementation of the sample app. 

ASTextNode (like all ASControlNodes - including ASImageNode, ASButtonNode, ASTextNode) have `userInteractionEnabled = NO` by default. This is the same default behavior as UIImageView and UILabel, which also have user interaction disabled by default. This is why the avatar image view, username, post time, etc pass touches through to the ASCellNode, allowing cell selection. If you message `addTarget:action:` to any ASControlNode, it will automatically enable user interaction, which is why you might not have had to explicitly set `userInteractionEnabled = YES` for any nodes before.
 
When you have text that may contains links, this by default enables user interaction for an ASTextNode, thereby the ASTextNode will capture the touches and so the ASCellNode will receive them. This is why the center text paragraph ("normal words") captures the touch and does not pass touches.

HOWEVER, ASTextNode offers touch pass through for textNodes that have links but want to avoid capturing a touch unless the touch is on a link. To fix the sample app, you can add the following line to PostNode's init method:   '_postNode.passthroughNonlinkTouches = YES;'

**Comment by wy19901227** [comment]
thanks for you patient explain.

**Comment by hannahmbanana** [comment]
@wy19901227 - As for the `_divider' line which is manually implemented in the PostNode, it appears that the rasterization code in `didSelectRowAtIndexPath:` is causing it to disappear. It looks like there is some issue with `__unloadNode` ---> `pendingViewStateFromView:` (when the view is being reloaded from the _ASPendingState after disabling rasterization). I will investigate more later.

**Comment by wy19901227** [comment]
yeah,I found the ASTextNode only can support UITableViewCellSelectionStyleNone or gray,If is gray ,The divider will dissappear, when you solve this question,can you support set cellnode morecolor.

**Comment by hannahmbanana** [comment]
@wy19901227 - @maicki has fixed the disappearing divider line! Here's his explanation: 

_"UITableViewCell traverses through all its descendant views and adjusts their background color accordingly either to [UIColor clearColor], although potentially it could use the same color as the selection highlight itself. After selection, the same trick is performed again in reverse, putting all the backgrounds back as they used to be. But in our case, we don't want to have the background color disappearing so we reset it after highlighting or selection is done."_

**Comment by hannahmbanana** [comment]
@wy19901227 - It wouldn't make sense for ASTextNode to support a UITableViewCellSelectionStyle. I assume you mean ASCellNode or ASTextCellNode? This feature has not been requested before. Feel free to open a new issue if it is something you think would be useful. 

Thank you for contributing to the community by discovering these bugs!
