### ISSUE TITLE
[ASTextNode] Node inside of containing view - sometimes object may be deallocated

### ISSUE THREAD

**Issue by anhnd** [facebook/AsyncDisplayKit#1439]
Hello everyone. AsyncDisplayKit did boost my application performance but right now I'm having a problem and looking for help.
My application changes the attributedString property of an ASTextNode object frequently. I run it on an iPhone 4s(iOS 9.2.1) and sometimes it crashes. This is what I got:
<img width="1197" alt="screen shot 2016-03-27 at 12 09 23 am" src="https://cloud.githubusercontent.com/assets/4056189/14061327/3a3ba23e-f3b0-11e5-8fcc-6969178e1182.png">

**Comment by hannahmbanana** [comment]
@anhnd - this is a very interesting bug! what version of ASDK are you using? Have you had this problem on 1.9.7.1? 

Could you explain a bit more about the structure of your node hierarchy? From the debugger, you can do `po [[UIWindow keyWindow] recursiveDescription]` to get your view hierarchy. 

One last question - Is this inside an ASCellNode? Are you using the newer node block API or are you returning the cell block directly?

**Comment by anhnd** [comment]
@hannahmbanana The version of ASDK I'm using is 1.9.7.1. 
And this is not inside an ASCellNode. This is my view hierarchy(I removed things that are not relevant):
[structure.txt](https://github.com/facebook/AsyncDisplayKit/files/190586/structure.txt)
I use CLLocationManager to get heading values. With each value I do some calculation and update the attributedString properties of the ASTextNode objects

Regards,

**Comment by appleguy** [comment]
@anhnd thank you for the quick reply. This issue should be solvable, and I believe is caused by containing your text nodes within a view rather than in a node hierarchy. And example of An issue that can occur with this is that if you do not retain the text node objects directly and rely on the view hierarchy to retain them, if the view controller undergoes a transition for certain other instances, it can cause the node object to BD allocated.

If it is appropriate for the layout of the application, one good solution is to use either a table or collection view.  Otherwise, you should use an ASViewController, with a containing node that holds the other elements. If you still need to use UIViews, this is fine.  You can always add them _in -didLoad, not -init_ to the self.view if you're implementing a node subclass, for example the containing node..

If you were working on this today and would like to discuss, it may be quicker to do a  short audio call. Send me an email and we can Connect by iMessage.  asyncdisplaykit@gmail.com

best regards!

**Comment by appleguy** [comment]
@anhnd one quick thing to point out is that your application is creating a large number threads. Although the framework is responsible for potentially dozens of threats, your app has a bit over 200, which is a possible indication of an issue unless it had been running for at least several minutes of active usage by this time. If you look at what each of those threads is doing, by using bt all (feel free to post that here), it is probably the result of a very simple issue that would be quick to fix

**Comment by anhnd** [comment]
@appleguy The reason why my application created a large number of threads is my application have a mode that will insert a MKMapView instance below all other views.

About these text node objects, I'm using strong properties and write the getter like this

```
- (ASTextNode *)facingTextNode {
    if (!_facingTextNode) {
        _facingTextNode =[[ASTextNode alloc] init];
        _facingTextNode.layerBacked = YES;
        _facingTextNode.opaque = YES;
        _facingTextNode.backgroundColor = self.view.backgroundColor;
//        _facingTextNode.displaysAsynchronously = NO;
        [self.view addSubnode:_facingTextNode];
    }
    return _facingTextNode;
}
```

And the first time I access these properties (so they will be added to self.view) is in viewDidLayoutSubviews when I set those text node objects' frames.

I think I will consider using ASViewController.

**Comment by appleguy** [comment]
@anhnd -viewDidLayoutSubviews is not the best time to addSubview - even with UIKit - as it is called many times during the lifecycle.  Use -viewDidLoad instead.

Indeed, try out an ASViewController with a basic containing node.  Feel free to try out usesImplicitHierarchyManagement, described here:

**Comment by anhnd** [comment]
@appleguy That's why I only put  [self.view addSubnode:_facingTextNode] in the getter when _facingTextNode is nil. It's my habit to set the frames in viewDidLayoutSubviews(so when things like auto rotation happen, the frames will be changed). I think it should be ok.

Thank you for the link, I will try it as soon as possible and tell you the result. And I will try to get more information so you can reproduce the issue.

Regards,

**Comment by appleguy** [comment]
@anhnd: any updates? I would be happy to help out if you're still encountering the issue.

**Comment by Adlai-Holler** [comment]
@anhnd I hope everything worked out. Feel free to reopen if this is still an issue. Cheers!
