### ISSUE TITLE
[ASNetworkImageNode] placeholderColor doesn't work

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1442]
My `ASNetworkImageNode` is defined as below:

```objc
ASNetworkImageNode *imageNode = [[ASNetworkImageNode alloc] init];
imageNode.URL = someURL;

imageNode.placeholderEnabled = YES;
imageNode.placeholderColor = [UIColor hx_colorWithHexRGBAString:@"#7B8482"];
imageNode.placeholderFadeDuration = 0.34;

[self addSubnode:imageNode];
```

When the image is loaded from the network, it appears suddenly. It is as if all the `imageNode.placeholder* = ...;` lines aren't having having any effect.

Am I doing something wrong?

**Comment by appleguy** [comment]
@fatuhoku can you try implementing a subclass, and returning a value from -placeholderImage?  you can use UIGraphics to create a 1px context and draw with a fill color and return that.  Let me know if it doesn't work as expected.  If it does work, it is helpful for me to know that the bug is specific to placeholderColor and I can begin investigating.  If it doesn't work, then the issue is with the configuration, as I have recently changed this code and know that at least placeholderImage is working very reliably from a framework perspective (but this does expect to be inside of an ASCellNode or ASViewController's container node).

**Comment by fatuhoku** [comment]
Okay, I used [this snippet](http://stackoverflow.com/a/993159/590767) to create my 1px `placeholderImage` and made a subclass called `MYNetworkImageNode` and can confirm that the placeholder fading does indeed work. 

The declaration now looks like this:

```objc
        imageNode = [[MYNetworkImageNode alloc] init];
        imageNode.URL = viewModel.mainImageUrl;
        imageNode.delegate = self;
        imageNode.placeholderEnabled = YES;
//        imageNode.placeholder = [UIColor hx_colorWithHexRGBAString:@"#7B8482"];
        imageNode.placeholderFadeDuration = 2;
        [self addSubnode:imageNode];
```

**Comment by hannahmbanana** [comment]
@appleguy @fatuhoku: It looks like this might be a known issue -> #392

**Comment by fatuhoku** [comment]
Indeed it is!
