### ISSUE TITLE
`ASDisplayNode setNeedsLayout` - what's the expected behavior?

### ISSUE THREAD

**Issue by akathrowaway** [facebook/AsyncDisplayKit#1444]
1. `node:setNeedsLayout` changes the node's size -- that's very different from the UIKit-equivalent method; UIKit never changes the view's size whose `layoutSubviews` is being invoked (its subviews might change sizes, but never the view itself -- unless you do it yourself explicitly in the subclass) -- the size of the view is expected to be handled/updated by the view's owner.
2. now the behavior in 1 is troublesome because sometimes i do not want my root-node to be resized to the size that's returned by its calculateSizeThatFits... sizeThatFits is just that - size that just about fits the content - that's the definition by UIKit anyway; it can be different from the size that i actually want the node to be. if my root-node is a full-screen node w/ sub-nodes, i do not want its frames to change from being fullscreen - debugging w/ view-debugger, i see that it does. if i wanted my root-node to be resized to just fit its content, i would be calling sizeToFit myself; i wouldn't expect setNeedsLayout to be doing this job.
3. after the first measure-layout pass is done on the node, if we want to trigger that measure-layout pass again (due to content change), what's the function we need to call?

would it be `[node setNeedsLayout]`?

i'm actually sure if it is or not; because sometimes it does, other times it doesn't such as if calculatedLayout was invalidated earlier, etc.

also if i call `[node measure:]` explicitly myself before calling `[node setNeedsLayout]`, then `[node setNeedsLayout]` just discards that and calls `[node measure]` on its own again.

situations where this doesn't call `measure` are:

a. in case of ASTextNode as a root-node, if i change its string after the first measure-layout pass, then any subsequent `[textNode setNeedsLayout]` doesn't seem to measure the node again.

```
        ASTextNode *textNode = [[ASTextNode alloc] init];
        textNode.attributedString = [[NSAttributedString alloc] initWithString:@"hello"];
        CGSize textNodeSize = [textNode measure:self.view.bounds.size];
        textNode.frame = CGRectMake({0, 300}, textNodeSize);
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.view addSubview:textNode.view];
        });

        dispatch_after(some_time, bg_queue), ^{
            textNode.attributedString = [NSAttributedString.alloc initWithString:@"im back w/ longer string!"];
            [textNode setNeedsLayout]; 
        });
```

...which is ironic given the side-effect from the very first question;

b. assume MYNode function:

```
- (void)setNumStudents:(NSInteger)num {
    _numStudents = num;
    [self invalidateCalculatedLayout];
}
```

then if my viewController later invoke:

```
self.myNode.numStudents = 10;
[self.myNode setNeedsLayout];
```

this only invokes [myNode layout] w/o invoking [myNode measure] first... is that really the expected behavior?

c. if i've never called measure myself explicitly on the node...

```
myNode.frame = viewController.view.bounds; // just a full-screen node; no need for measure.
```

but i still want `[myNode measure]` to be called by framework before calling `[myNode layout]` because i need `myNode.subNode.calculatedSize` ...(the side-effect)

d. if i invoke `[myNode measure:]` right before `[myNode setNeedsLayout]` to workaround above issue, `[setNeedsLayout]` throws away my measure and re-invokes measure.. so... why should i call `[measure]` myself first if it's going to be thrown away?

... so i guess my bottom question is: how can i reliably make the framework trigger measure-layout pass again after the initial pass?

as of now, `[node setNeedsLayout]` seems to have these undesired side-effects, indeterministic behaviors that, i end up calling `[myNode measure:]` myself in bg-thread, then on the main-thread directly invoke `[myNode.view setNeedsLayout]` to skip all these side-effects.. so i'm not sure what the intended behavior of `[node setNeedsLayout]` was; why all the side-effect and indeterministic `[measure]`?

**Comment by appleguy** [comment]
@akathrowaway thank you for the detailed post. I have some important things to finish tonight and have not yet had a chance to fully understand all of the details here, but I definitely will do so at my soonest opportunity and really appreciate you taking the time to include the detail.

This framework is not widely tested for usage of nodes outside of some form of container / root element.  the reason is simple... in this configuration, there is no system that will trigger the asynchronous layout for display in advance of the content coming on screen, which essentially guarantees that content will "flash".

Could you explain a use case, or an example project that demonstrates one, whether one of the many projects in examples/ (feel free to modify one) or one that you create, that exhibits any inconvenient behavior when using ASCellNode with Table, Collection, or Pager - or using an ASViewController?  Also, I assume you're using the latest version of the framework?

These root container objects handled the responsibility of calling measure, as well as triggering display and proactively managing memory. Feel free to check out the description of these components in the NSSpain talk (sorry it's not the greatest - more docs on the way soon, @lappp9 would you be okay with linking your current version of the first tutorial here?)  https://www.youtube.com/watch?v=RY_X7l1g79Q

Anyway, the layout system of this framework is the most different aspect of its design from UIKit, although it is also tightly integrated. I have not actually encountered a case yet (from anyone in the community) that describes the resizing behavior as inconvenient, but this only increases my interest in understanding the use cases where it is problematic, and ensuring that this is not simply due to incomplete adoption of the framework such is lacking a root element. For example, when using a cell node, it is typically extremely convenient to be able to call setNeedsLayout and rely on the overall cell changing height automatically - even inside a table or collection.

It is even customizable whether those layouts should be performed in an animated or non-animated way, And it is also possible to write your layout in such a way that it does not rely on the size of its subnodes to determine its height, So as far as I'm aware of there is complete control over the behavior you want.

All this said, I want to reiterate that the layout system that has been in the framework and widely used for the past nine months is still a very poorly documented despite its high degree of testing and flexibility, which makes it almost impossible to jump into and completely understand the conventions and capabilities. This is one reason why I am so active in the Community and try to help everyone understand the best way to get a lot out of the framework, and why am looking forward to the documentation projects that members of the community have been willing to advance. It is now higher priority for me as certain critical projects in my day job are wrapping up.  I'm sorry for the trouble in understanding this stuff and hope to be able to help.  Reply here and email me any time at asyncdisplaykit@gmail.com !

**Comment by akathrowaway** [comment]
@appleguy thanks for response!

i just completed experimenting w/ ASViewController and did bunch of debugging;

1. ASViewController seems to be invoking [node measureWithSizeRange] in viewWillLayoutSubviews based on stack-trace. and this ends up masking the issue 3 because it's actually the same "work-around" i mentioned above:

> d. if i invoke [myNode measure:] right before [myNode setNeedsLayout] to workaround above issue, [setNeedsLayout] throws away my measure and re-invokes measure.. so... why should i call [measure] myself first if it's going to be thrown away?

so it "fixes" it the same way, but with the same wasteful `[measure]` call... 

2. root-node resizing logic from `setNeedsLayout` would be skipped because ASViewController passed in a sizeRange whose minSizeRange is the screen-size; so it would never clamp below the screen size... 

and that re-sizing logic would only apply to root-node (since subnode sizes are handled by the root-node), but ASViewController is basically preventing root-node from being re-sized; so that resizing-code would be a dead-code (assuming no-rotation) while using ASViewController... i guess that logic exists for ASCollection/TableView? 

i guess i could still use my own viewController and "fix" the problem i mentioned above by calling `measureWithSizeRange:{screenSize, screenSize}` in viewWillLayoutSubviews...but i dunno; seems a bit hacky solution; 

thanks for response again!

**Comment by lappp9** [comment]
Hey @akathrowaway, here's an early version of the first tutorial in the ASDK series coming out soon!

https://www.dropbox.com/s/spysl2h2hfhft6u/AsyncDisplayKit%202.0_%20Getting%20Started.html?dl=0

**Comment by akathrowaway** [comment]
thanks. all i meant was, commit: 56768a837ab9e3ebee08345822f8bf17fab429e9 from 8/1/2015 basically broke all the other use cases other than the one it specifically tried to fix: ASTable/CollectionView (kittens example).

**Comment by appleguy** [comment]
@akathrowaway I appreciate all the detail you provided in your report. Could you quickly synthesize it into a modification to anyone of our example projects, or post a new example project that reproduces the issue? If the issue is as broad as your description seems to indicate, I would hope that it is not too difficult to create a reproduction. I wish I could do this myself but am necessarily focused on the application rollout and some other competing priorities—but if you were able to create the example I should be able to create a resolution for you within a small number of days.

I don't believe it is accurate that any of the behavior is specifically customized for one use case, as we are successfully using the framework for a very wide variety of implementation requirements (everything the Pinterest app supports) — and there have been no other reports to my knowledge of having issues in this area.  My hope is that the answer is a quick fix for you, although it is also very possible that there is a quick improvement to the framework behavior that we can make. It should definitely not be required to have a wasteful call to -measure:.

**Comment by appleguy** [comment]
Please send me an email if you'd like to join our slack channel. There are several very active members in the channel, including myself, and we may also be able to coordinate more quickly on a reproduction and solution there.

**Comment by garrettmoon** [comment]
@akathrowaway Can you check that this still exists after #2597?

**Comment by maicki** [comment]
@akathrowaway 

With the changes within #2597 our main goal was to align the `setNeedsLayout` more with the UIKit behavior, but to not break the backwards behavior we had in place if node's are within a node container. Furthermore we also would like to support just setting the frame to a node and the node will automatically layout itself based on the frame set on it.

I think the problems and key changes are all listed in #2597 and should address most of the issues you listed above, but just quickly speak a bit about the main question what the expection is for `setNeedsLayout`:

Calling `setNeedsLayout` should behave the same way as in UIKit now. It just invalidates the layout of the node and does nothing else. You can even call it a couple of times and it will not immediately layout the node or resize it as it was the case before. If then the next layout pass in UIKit happens, UIKit will call `layoutSublayers` on the node's layer and this eventually calls `layout` on the node. Within layout the node, based on certain circumstances, decides to use a constrained size and a layout pass of the node will happen.

That said one side effect still exists if you use nodes in containers (ASCellNode, ASTableNode, ASCollectionNode, ASPagerNode etc.). If a size changes in a subnode it will automatically call up the root node and it re-layout based on the new size of the subnode. A good example is ASDKGram where we download further data from the network and if this data arrives we show certain nodes that where hidden before and call `setNeedsLayout` on the node that determines that the size of itself changes and tells the root node container about it (in this case the `ASCellNode`). The `ASCellNode` uses this information now to relayout itself based on the new information and a height adjustment animation for this `ASCellNode` will happen.
This behavior is only used if you use a container node though. If you set your bounds manually the node will use this size to layout itself.

I will close that issue, please reopen in case you have further questions or you think it's not clear enough. Please also not hesitate to come into our Slack channel to ask further questions or have a discussion around it, happy to help!
