### ISSUE TITLE
[ASNetworkImageNode] How do you distinguish between images loaded from network vs. from cache?

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1447]
I use [WebASDKImageManager](https://github.com/ide/WebASDKImageManager) with `ASNetworkImageNode` to cache and manage my cached images.

The behaviour I want:

I **fade in images retrieved from the network** (i.e. fade out the placeholder), whereas images retrieved from memory / disk (i.e. very likely to be the images that the user has already seen before) are displayed immediately (fade out is disabled).

However, by using the `.URL` setter, I'm unable to distinguish between these two cases. Delegate methods don't help me, because every image just looks like it was freshly loaded.

The only alternative is to manage caching behaviour separately and avoid using `.URL` — I reserve setting of the URL to times I know for sure my cache doesn't have the image to hand, and set the `.image` property directly if I do have it to hand.
 
This is really strange, given that `ASNetworkImageNode` clearly understands something about caches and downloads, though its `ASImageCacheProtocol` and `ASImageDownloaderProtocol`s.  It think the delegate methods should be extended to let us know if a recipe had been retrieved from cache or downloaded.

**Comment by smyrgl** [comment]
If you are using SDWebImage just query the cache directly using the `diskImageExistsWithKey:` method on SDImageCache and get the cache key for it using `defaultCachePathForKey:` using the absoluteString of the NSURL.

**Comment by appleguy** [comment]
@fatuhoku  WebASDKImageManager is actively dangerous to your application, And unfortunately should be avoided completely. Please take a look at the issue I filed with the project that I believe is still unresolved. It results in massive memory consumption that will cause most applications to crash within minutes.

The latest version of the framework should support all your requirements by simply doing alloc/init on the network image node.  It is fully integrated with PINRemoteImage.

This provides many advantages, including automatic prioritization of network requests that increases as the image gets closer to the screen or becomes visible, in three distinct levels of priority it also efficiently handles memory, and transparently manages a 50MB (configurable) image disk cache that is very effective.

Please let me know if you have the opportunity to try this out, especially since it should only require deleting code from your application. It would be very helpful to know if there are any inconveniences in the adoption, or negative behaviors that are not optimal for your application.

The manual handling of the fade will be unnecessary with this approach, as a properly working cash will provide Image loading and also display nearly always before the image is in the visible area. Because of that, you can rely entirely on placeholderImage (subclass networkimagenode and override) and placeholderFadesoOut -- we use this option very extensively and it is well tested in complex, varying circumstances.

**Comment by fatuhoku** [comment]
@appleguy By the 'latest' version of the framework I'm guessing you mean 1.9.7.1 specifically?

It wasn't clear that `ASNetworkImageNode` had any caching going on when I tested it. Odd. That was the only reason I went out of my way to find a cache, and went for something familiar — a bridge to SDWebImage.
