### ISSUE TITLE
4 integer version numbers are disallowed by iTunes Connect

### ISSUE THREAD

**Issue by smyrgl** [facebook/AsyncDisplayKit#1449]
So after pulling the 1.9.7.1 version and trying to upload a build to iTunes Connect I got this message:

> ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '1.9.7.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."

I think you have to stick to versioning schemes that are x.y.z.  The Facebook iOS SDK made the same mistake a few months back and they quickly switched back to 3 integer version numbers.  You can keep the internal versioning scheme but it needs to be rounded off in the plist.

**Comment by appleguy** [comment]
@smyrgl wow, I had no idea. Do you know how to override this behavior with Cocoapods?  Would it address your problem in the short term if I change the podspec in master, and you point your project to the specific commit on Master that you need? Send me a message on slack with the answer so I can follow up more quickly.

**Comment by appleguy** [comment]
@smyrgl: I changed the podspec in master to 1.9.8 so that should allow you to ship. Let me know if not.

**Comment by vandadschibsted** [comment]
We have the same issue and desparately need this pod spec to be updated in Cocoapods so we can use it please. When can we expect this? Thank you for the great job.

**Comment by appleguy** [comment]
@smyrgl found a simple workaround. Feel free to join us on slack, send me an email if you would like to. In the general room there is a lot of discussion on this issue.

https://github.com/Jonge/Cocoapods-frameworks-version-number-fix

**Comment by appleguy** [comment]
![image](https://cloud.githubusercontent.com/assets/565251/14584836/2f351a76-0410-11e6-9292-2a8c7b097123.png)

**Comment by appleguy** [comment]
@vandadschibsted  you can shoot me an email anytime, for a slack invite or anything else, at asyncdisplaykit@gmail.com

**Comment by vandadschibsted** [comment]
@appleguy thanks. When will we be able to get an official Pod fix for this please? Thanks. I am afraid of putting more and more hacks in our code/build system so prefer to avoid workarounds. I really appreciate the time you are putting into AsyncDisplayKit and your work is amazing.

**Comment by appleguy** [comment]
The framework is not ready for 1.9.8, and probably will not before another two weeks. A suggestion I made on slack, but was discouraged from executing, was to launch a version called 1.9.73 and then use 1.9.80 for the next release.

If this is a significant issue, I can go with this approach in the next few days. However, this fundamentally seems like a limitation with Cocoapods, and specifically dynamic frameworks, which have some pretty serious performance problems by themselves.  It's definitely a bummer to have to influence our versioning scheme for this case, so if the workaround is suitable for the next two weeks, let me know. Otherwise I will put out the release mentioned.

**Comment by vandadschibsted** [comment]
@appleguy thanks for the reply. I don't think this is a problem with CocoaPods! It is iTunes Connect that has problem with the version numbers in the plist file!

We have no problem bringing in the pod and installing the pod and even building an ipa files. The issue is when the binary is uploaded to TestFlight when Apple does validation on the binary and finds out that the version number of AsyncDisplayKit framework is 4 slices and is therefore invalid.

Thoughts?
