### ISSUE TITLE
[ASDisplayNode] Add assertion verifying 1-1 relation between nodes and views

### ISSUE THREAD

**Issue by zintus** [facebook/AsyncDisplayKit#1452]
In case user create multiple nodes with same view through `initWithViewBlock:`, ASDK will silently break on hierarchy management without any warnings.

Does it makes sense to assert that view doesn't have associated node during view loading process? Nice way to save some debugging time :)

**Comment by appleguy** [comment]
@zintus this is a good idea, but not something I had never even considered. As you can see, there are quite a few assertions in the CodeBase to detect a variety of different misunderstandings of the API or framework behavior, and it certainly fits within that in tent to add this one.

If you can think of an easy way to write this, Please put up a pull request and I would be happy to merge it. Typically, I would recommend strictly minimizing usage of this method (synchronous wrapping of custom views), and implementations that you do require should follow a functional style that minimizes its dependence on external state or view reuse.  I'd be interested to learn what use cases you have for it, though I'm sure they are prudent!

ASDK automatically spreads out do you creation cost through multiple rapid-fire turns of the runloop (many per frame), allowing touches and animations to get running time even if it is necessary to create or distribute. This makes a view reuse almost completely unnecessary, especially for the level of complexity and difficult bugs that it introduces in many apps.

BTW we have a Slack now, just email me if you want an invite :) - asyncdisplaykit@gmail.com

**Comment by appleguy** [comment]
@zintus - thanks for contributing to the AsyncDisplayKit community by suggesting this improvement. 

The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send us an email at AsyncDisplayKit@gmail.com or ping us on ASDK's Slack (#1582). If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
