### ISSUE TITLE
[Carthage] ASPINRemoteImageDownloader cannot easily be used when using Carthage

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1464]
When @appleguy asked me to check out `PINRemoteImage` in #1447 I understood that ASDK integrates with PINRemoteImage via a cache/downloader class called `ASPINRemoteImageDownloader`.

If you use Cocoapods, the `PIN_REMOTE_IMAGE` preprocessor flag does all the magic and things get compiled in the way that you'd expect. You get a tight integration.

However, when using Carthage you must include PINRemoteImage as a completely separate dependency to AsyncDisplayKit (by design).  Further, `ASPINRemoteImageDownloader.h` is not exposed as a public header, which means you can't just go `#import <AsyncDisplayKit/ASPINRemoteImageDownloader.h>` — the file won't be found.

So the only way to access `ASPINRemoteImageDownloader` at all is to copy its source code straight into your project, which would be managed separately from ASDK. Even then, you need to remove the PIN_REMOTE_IMAGE #if macros and fix some imports if you want it to compile.

This is the best solution right now and I can't help but think it should be handled better somehow.

I think a bit of documentation would be nice, because `ASBasicDownloader/Cache` is really not a sensible option for most apps.

**Comment by appleguy** [comment]
@fatuhoku: Thanks for reporting this. Unfortunately, none of the project maintainers are familiar with Carthage because it only supports iOS8 and above and most larger apps are still supporting iOS7 for at least a few more months. Also, dynamic frameworks have significant performance implications, especially for application startup time, which is critical for many app teams. 

We would love to better integrate with Carthage and will eagerly accept any contributions that address issues like this, but it is not a high priority for our extremely limited core engineering team, considering the breadth of projects being advanced. 

Let us know if you would be interested in implementing this. :)

**Comment by hannahmbanana** [comment]
@fatuhoku - were you able to get around copying the source code straight into the project? If so, I'd be happy to document your learnings on the website. :)

If not, it might be useful pinging the Slack channel now that we have 60+ devs on there.

**Comment by hannahmbanana** [comment]
@fatuhoku: Check out my message to you on Slack. We're investigating the Carthage / PINRemoteImage issue this week.

**Comment by hannahmbanana** [comment]
Closing this issue and consolidating the Carthage issues at #1780.

**Comment by hannahmbanana** [comment]
PR #1796 is attempting to fix this issue.
