### ISSUE TITLE
[Apple bug?] Loading certain images creates console warning about BOMStorage.

### ISSUE THREAD

**Issue by ItamarM** [facebook/AsyncDisplayKit#1480]
While rendering a list of endless network based images (iPhone 6, iOS 9.x)I sometimes see a 'glitch' in image loading which follows the following console warning:
[/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI_Sim/CoreUI-371.4/Bom/Storage/BOMStorage.c:522] <memory> is not a BOMStorage file

Everything else seems normal.

**Comment by maicki** [comment]
It seems like this is related how images are created (I guess in PINRemoteImage), but seems like it can be ignored based on an Apple Engineer entry in this Apple Developers Forum's thread https://forums.developer.apple.com/thread/21723: 

> this is a harmless message that can be ignored.

Still not optimal if you see a glitch as this is happening ...

cc @appleguy @garrettmoon

**Comment by garrettmoon** [comment]
By glitch do you mean that the images actually appear with artifacts or some such? I've seen this on the simulator with PINRemoteImage, but never on a device.

**Comment by appleguy** [comment]
@ItamarM thank you for recording this. Can you give additional detail, for example the URLs of the images that you're trying to load? If you insert these URLs into any one of the several example apps that contain a network image mode, do you see the same messages? Having a simple reproduction case would allow us to investigate this very quickly.

**Comment by ItamarM** [comment]
@appleguy I can't really give the real image URLs (internal content servers). However, I can say that they average mobile image uploads. Maybe we can mimic this somehow with Flicker API?
I can reproduce this with the Kittens sample.
By glitch i mean a sudden frame drop.
Last, it might correlate with the simulator. Don't recall seeing it on a device.

I'll try to find a time to fix you guys with a new kittens sample. One that work against a variety of image disk sizes.

**Comment by appleguy** [comment]
@ItamarM ah, knowing it is a frame drop helps dramatically :).

For one thing, logging to the console is actually quite slow so this can easily cause frame drops.  Also the simulator has very poor graphics performance despite great CPU, so it can drop frames randomly.

Can you please retest on a device, and let me know what device type you're using? You can easily use QuickTime player to record a screen capture video of the device as well. I would be happy to review an Instruments Time Profiler trays of scrolling in your app and make a few quick recommendations for how you can optimize it.

If there is any element in your scrolling view that does not require user interaction, such as if the images do not need to be tapped on, you should enable the node.layerBacked = YES and will definitely notice performance improvements on older devices.  Equally important, make sure you are using the nodeBlockFor[Row/Item]...: API; this is very simple to use, just make sure that you access your data model using the index Path outside of the block, and then return a block that creates the cell node and provides it the data model.  This helps both loading performance to be further increased over UIKit, and scrolling performance, because the cell allocation then occurs concurrently on multiple background threads.

There is an example app already posted which has an infinite feed of large photographs, so this would be a perfect place to reproduce the issue you're describing if it continues to affect your app in a user-visible way (a device).  Check it out!  https://github.com/facebook/AsyncDisplayKit/pull/1457

**Comment by ItamarM** [comment]
@appleguy i can't reproduce this so i suggest we will close the issue for now. 
In case I'll be able to reproduce the bug it will include a sample :)

p.s.
Thanks for the detailed replay.
