### ISSUE TITLE
Support for UIMenuController on ASCellNode or ASTextNode

### ISSUE THREAD

**Issue by DavidSchechter** [facebook/AsyncDisplayKit#1490]
Hello,
I found issues number #11 and #1017, but I need more clarification on this issue.
I want to be able to detect long presses on a ASCellNode (or ASTextNode) and when one does occur I want to open a UIMenuController.
I found a way doing it in the following manner:
override public func didLoad() {
        super.didLoad()
        let longPressRecognizer = UILongPressGestureRecognizer(target: self, action: Selector("longPressHappened:"))
        view.addGestureRecognizer(longPressRecognizer)
    }

longPressHappened will open the UIMenuController and by overriding these methods I will close it:

override public func touchesBegan(touches: Set<NSObject>!, withEvent event: UIEvent!) 
override public func touchesEnded(touches: Set<NSObject>!, withEvent event: UIEvent!) 
override public func touchesCancelled(touches: Set<NSObject>!, withEvent event: UIEvent!) 

However, this does not seem as the best approach.

I saw the @appleguy said in issue #1017 the following  - "I think it is possible to hook up the UIMenuController, though it is not very flexible and so there was some discussion about whether it would be best to build a custom callout bubble (that style of button selector)" - what is a custom callout bubble? what is style button selector?

Any help with this issue would be appreciated.

Thank you,
David

**Comment by appleguy** [comment]
@DavidSchechter thanks for searching and finding those other issues!

The approach you described is fine, although you may need to look at a more comprehensive way to trigger the menu to close. For example, if the user touches outside of the cell, you might not be able to detect that tap.

The other comments about a different style simply reference replicating the general the the Appearance of the menu controller but with a more customized implementation that allows a user to define their own images or for the menu controller. The menu controller is not a particularly complex component, and so building something custom could be reasonable. However, if it matches your application interface, it is certainly a fine approach to integrated directly. It might not make as much sense for the framework itself because many Applications using this framework have a very custom interface that would not readily match with the menu controller.
