### ISSUE TITLE
[Discussion] Question about the details of ASDK performance

### ISSUE THREAD

**Issue by muzammil-hussain** [facebook/AsyncDisplayKit#1554]
Hi,
I have a simple question about ASDK nodes usage. In quick start i can see allocation of node on background thread and then add to view on main thread. Which makes sense. 

**dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0) {
  let node = ASTextNode()
  node.attributedString = NSAttributedString(string: "hello")
  node.measure(CGSize(width: screenWidth, height: CGFloat.max))
  node.frame = CGRect(origin: CGPointZero, size: node.calculatedSize)
  // self.view isn't a node, so we can only use it on the main thread
  dispatch_async(dispatch_get_main_queue()) {
   self.view.addSubview(node.view)
  }
}**

But in all the example projects i don't see this approach followed. In all example projects nodes are initialised on main thread as well. So is there any difference or it does not matter where you initialize node ASDK takes care of itself.

**Comment by hannahmbanana** [comment]
@muzammil-hussain: This looks like code from ASDK's old website. The new website is a work in progress, but currently has some updated documentation.

If you are just using a _single_ ASDK node in a UIViewController, the code you have (which adds the node's view directly) is valid. However, it is highly recommended that you use a "node container" such as an ASTableNode, ASCollectionNode or ASViewController to get the maximum benefit of the framework. With these node containers, you would addSubnode: rather than dealing directly with the node's view. 

To see these node containers in action, the ASDKgram example app is a great place to start. It shows a comparison of a UIKit implemented photo feed vs a ASDK implemented photo feed. If you are trying to port an existing app, this is a good reference. 

When using these recommended node containers, the standard practice is to initialize nodes and add subnodes on the main thread. I believe this is because the cost of initializing an ASDK node is very minimal in comparison to rendering text, decoding images, etc. 

It would help to know a little more about what you a trying to do. Have you joined the ASDK Slack channel? If not, you should consider joining us as it is easiest to have conversations on Slack. :) Email AsyncDisplayKit@gmail.com for an invite.

**Comment by hannahmbanana** [comment]
@appleguy @maicki - can you comment on the main thread node initialization? Would this be something useful to have on the website?

**Comment by appleguy** [comment]
@muzammil-hussain although it is great to initialize nodes off of the main thread when possible, this is a small minority of the total amount of work that most applications have on the main thread.

Even when you allocate notes on the main thread, the framework will automatically move layout and display to concurrent background queues.  The layout operations are managed by a table, collection, or pager node.  The display operations are built into ASDisplayNode itself, and so even in the case that you use a node as a direct sub view of a regular review hierarchy, it will still render asynchronously (but this is discouraged, as no system will tell the node to render an advance as is the case in the other containers mentioned).

All that said, the framework has a variety of other advanced techniques to improve performance. Even with main thread work, the framework is able to dramatically reduce its impact on the user experience by way of the rather amazing ASRunloopQueue.  This breaks up operations that must be performed on the main thread into far smaller chunks, easily 1/10th of the size that they otherwise would be, so that operation such as allocating UIViews or even destroying objects can be spread out and allow the run loops to frequently turn.  This frequent turning allows the device to much more frequently check if a user touch has started or if an animation timer requires a new frame to be drawn, allowing far greater responsiveness even when the device is very busy and processing a large queue of main thread work.

It's a longer discussion why this kind of technique is extremely challenging to implement with UIKit, but it has to do with the fact that ASDK prepares content in advance, giving it a buffer of time where it can spread out the creation of these objects in tiny chunks.  If it doesn't finish by the time it needs to be on screen, then it finishes the rest of what needs to be created in a single chunk.  UIKit has no similar mechanisms to create things in advance, and there is always just one huge chunk as a view controller or cell needs to come on screen.

Please join us on slack and I would love to see any additional questions and discussion shared with the overall group. Let us know if we can help you get started.

**Comment by muzammil-hussain** [comment]
Thanks for quick response. I have sent request for slack invitation.

**Comment by appleguy** [comment]
@muzammil-hussain: Thanks for submitting this question! I'm going to close this issue as it appears we've answered it - if not, feel free to reopen this issue, file another, or ping any of us on the Slack channel.
