### ISSUE TITLE
Animated placeholders

### ISSUE THREAD

**Issue by debug29** [facebook/AsyncDisplayKit#156]
In ASNetworkImageNode, add the possibility to make a fade in downloaded image apparition with a property. 

Also with ASDisplayNode placeholder. 

Like this for example : 

```
ASNetworkImageNode *theNetworkImageNode = [[ASNetworkImageNode alloc] init];
theNetworkImageNode.placeholderEnabled = YES;
theNetworkImageNode.fadeIn = YES;
```

**Comment by ashikase** [comment]
The current implementation of this feature does not appear to allow for custom placeholder image removal animations as @secretiverhyme suggested might be done in `-didFinishDisplay` (now `-displayDidFinish`?).

The placeholder layer (`_placeholderLayer`) is an internal member and provides no API to access it (though it might be blindly obtained using `self.layer.sublayers` on the node that owns said layer).

When `placeholderFadesOut` is true, the placeholder will fade out with a (almost unnoticeable) fixed duration of 0.1. When false, the placeholder layer is immediately removed, leaving no chance for it to be animated.

Have I missed something, or does the current implementation indeed prevent custom animations?

**Comment by rnystrom** [comment]
@ashikase that's currently the case, yes. For the interim we thought it'd be beneficial to add some type of fade animation so that there is at least the option.

Allowing more advanced, or totally custom, animations has a lot of edge cases that will need to be covered. Exposing the `_placeholderLayer` entirely is something we want to avoid so that the inner machinery doesn't get out of sync.

We totally want to add custom placeholder animations, but it will involve some core changes. Fading is like a placeholder-placeholder.

**Comment by ashikase** [comment]
Thank you for the confirmation.

For reference, I'm currently able to achieve custom animations using the technique mentioned [here](http://www.raywenderlich.com/86365/asyncdisplaykit-tutorial-achieving-60-fps-scrolling) (explained in the "Fading in the Cells" section). Unfortunately, this uses a node instead of the (at that time unavailable) placeholder API, and provides a custom layer for the node by subclassing the internal class _ASDisplayLayer.

**Comment by secretiverhyme** [comment]
The current placeholder API is designed to be simple and lightweight — its chief out-of-the-box function is making sure that nodes look attractive and don't disrupt your app's appearance if they happen to appear onscreen before they've finished rendering.  We're happy to make simple improvements to this API, but for any sort of advanced custom animation, you should be working with nodes directly.

For example, Paper's story strip placeholders have a [shimmering effect](https://github.com/facebook/Shimmer).  This is implemented using placeholder *nodes*.  The story strip is initially populated with cheap but fully-functional placeholder cards (try expanding or shrinking the story strip and you'll see they scale correctly!) that have animated text placeholders.  Once the story nodes finish rendering, they're swapped out with the placeholders for a seamless transition.

You should be able to implement this yourself with the current version of AsyncDisplayKit, though it'll be a bit tricky (the APIs for manually enqueueing asynchronous display of a node, hooking into completion of an entire hierarchy's display, etc., are overdue for some love).  Making this much simpler is on our radar, though!  =]

**Comment by yxztj** [comment]
Is there an easier way to do this now? I took a look at the ASNetworkImageNode code, still the downloaded image is assigned directly:
```
if (responseImage != NULL) {
     strongSelf->_imageLoaded = YES;
     strongSelf.image = [UIImage imageWithCGImage:responseImage];
}
```
We haven't found a point to inject our custom transition animation code. Of course we don't want to write a view to do this instead of using ASNetworkImageNode. Any help would be much appreciated.
