### ISSUE TITLE
AUParameterNode Error When installing ASDK

### ISSUE THREAD

**Issue by JPROFFICIAL** [facebook/AsyncDisplayKit#1580]
I have a social media production app that I am going to incorporate ASDK into. When using cocoapods to install AsyncDisplayKit, I get a build error that completely baffles me. Without ASDK in my project, I do not get this build error. (I also removed/installed `pod 'AsyncDisplayKit', '~> 1.9'`instead of the regular pod name just to be sure it wasn't the basic pod name causing the error somehow)

`Value of type AUParameterNode has no member key`
I am receiving this error inside two "For in.. where" Loops. It should be of type "element" But instead changes to type "AUParameterNode".
I do not have AudioUnit imported, unless its automatically installed when importing UIKit.
Not sure if manually installing the framework might fix my error. I will give that a shot next.

I am more then happy to provide more information/screenshots of the error if need be. If anyone would be able to help or give insight, that would be fantastic. Thanks

UPDATE: My project is still `Indexing | Processing Files` , and Ive read that that can cause build errors. Will further update when it is finished processing (Going absurdly slow)

**Comment by appleguy** [comment]
@JPROFFICIAL AU is not part of ASDK, so the issue is probably unrelated.  When you do pod install, make sure you're seeing version 1.9.7.2 pop up though!

Also, try manually deleting your derived data directory and rebuilding.

Please do update here and close out the issue if you're good.  Send me an email if you'd like to join our Slack, and many folks including myself would love to help out live with issues!  Feel free to file more things here too.

**Comment by JPROFFICIAL** [comment]
Apologies on the late response. I ended up moving the code around and am
not receiving that weird error anymore, thanks for getting back to me so
quickly and closing the post for me :Thumbsup:
I would love to be included in the slackchat for ASDK! Would be a grand-ol
time.

Thanks so much!! -Jordan

**Comment by hannahmbanana** [comment]
@JPROFFICIAL - email AsyncDisplayKit@gmail.com to be invited to the slack channel!
