### ISSUE TITLE
[ASLayoutSpec] In an unconstrained stack, should layout be invalid if items return Inf. dimension?

### ISSUE THREAD

**Issue by adamastern** [facebook/AsyncDisplayKit#1611]
When a node with an unconstrained flex basis is added to a ASStackLayoutSpec, the layout process calls its calculateSizeThatFits: method with a constrained size where the value for the main axis is +Infinity (makes sense, as it is being asked to return its unconstrained intrinsic size along the main axis). The issue is that if the node simply returns the constrained width or height that was passed to it, then ASDK is unable to complete the layout pass because the calculated size includes an infinite value (This is detected here: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASLayout.mm#L44)

This issue occurs with at least one built-in node, ASEditableTextNode, where its implementation of calculateSizeThatFits returns the width from the constrainedSize parameter - https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASEditableTextNode.mm#L194

Should nodes be responsible for checking that they don't return an infinite width or height from calculateSizeThatFits?

**Comment by appleguy** [comment]
@adamastern Thanks for the great report.  I think we should treat these nodes specially, doing something like an implied flexBasis of 1 / numberOfItems or some other mechanism for automatically constraining them in the infinite dimension.

@nguyenhuy, @maicki how might we address this?  Is it tracked in whole or in part by a task in Ship, or related to any other planned changes?

**Comment by maicki** [comment]
This is tracked with Ship issue nr: 110

@appleguy I just run into that issue while fixing some layout issues with ASVideoNode see #1630 . The problem was that as constrainedSize in `layoutSpecThatFits:` an infinite width was passed in. As this issue is describing, layout nodes or set size ranges with infinite values is not possible and results with a crash. What we do is to catch that and see if a `preferredFrameSize` is given for the ASVideoNode otherwise assert out and let the consumer know to set a `preferredFrameSize` in this case.

To address the root issue in here I think we should catch infinite values in `layoutSpecThatFits:` or `calculateSizeThatFits:` constrainedSize values that do not make sense and let the developer know that they have to set values (like preferredFrameSize or sizeRange+ASStackLayout) for this kind of situations.

Btw we can have the same situation in `ASImageNode` if no preferredFrameSize or image size if given in time of layout.

**Comment by maicki** [comment]
@adamastern I fixed a related issue today: #1701 

The size does not return "Infinite" anymore. It should not crash anymore if you put a `ASEditableTextNode` within a unconstrained layout spec. The logic around size calculation is now the same as `ASTextNode`. Let me know if this resolves the issue.

cc @appleguy

**Comment by appleguy** [comment]
Wow, super-great!

**Comment by adamastern** [comment]
Thanks @maicki looks great! This resolves the issue for me.

**Comment by maicki** [comment]
Closing this issue as it seems to be resolved.
