### ISSUE TITLE
Question: ASDK internal details, curious about why pthread / GCD over NSThread / NSOperation.

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#1685]

**Comment by appleguy** [comment]
@wy19901227 that's a fair question :)  Would love if you could come talk to us on Slack; email me at asyncdisplaykit@gmail.com for an invite!  Are you there already?

ASDK actually makes very very extensive use of GCD.  NSOperation is used by PINRemoteImage, which is also included by ASDK by default.

NSOperation does have significant overheads, and very few benefits (priority is the main one).  This can be very clearly seen with profiling.

The custom thread pool used for asynchronous rendering was added recently, about 6 months ago.  See the commit log and then find the associated PR.  The author was able to show very substantial improvements over GCD.  GCD suffers from a problem called "thread explosion" (which Apple describes with warnings in WWDC sessions), in rare cases / certain access patterns.  So for rendering in particular it was found to not be suitable as the thread explosion creates overhead of a relevant amount for the oldest devices.

The upshot is that by using lower level APIs, in most cases we don't take on any unreasonable complexity (like testing pthread instead of isMainThread is extremely easy) -- yet we gain some of the best performance of any framework ever created for iOS, even on the oldest available devices :)

**Comment by appleguy** [comment]
@wy19901227 - thanks for contributing to the AsyncDisplayKit community by asking your question here! Let me know if you have any follow up questions, either by reopening this issue, or contacting any of us on Slack (#1582). 

@hannahmbanana: can you add this topic to your list for the website / documentation upgrade?
