### ISSUE TITLE
how to stop nstimer on ASCellNode

### ISSUE THREAD

**Issue by Serlight** [facebook/AsyncDisplayKit#1689]
I create a NSTimer in ASCellNode, when ASTableView's UIViewController pop, but the timer not be released.

    _timer = [NSTimer scheduledTimerWithTimeInterval:3.0 target:self selector:@selector(autoScrollBanner) userInfo:nil repeats:YES];
    [[NSRunLoop mainRunLoop] addTimer:_timer forMode:NSRunLoopCommonModes];

how can  i stop this timer?

**Comment by maicki** [comment]
@Serlight It seems like you creating a retain cycle. You have to remember that NSTimer is retaining it's target. One way to solve it is to create a helper NSTimer object that solves the retain cycle.

Sample implementation of a weak NSTimer: https://cocoa.tumblr.com/post/85818295418/weak-timer-targets

**Comment by appleguy** [comment]
@Serlight: thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time since this thread was active, I'm going to mark this issue as closed assuming that maicki's solution resolved your problem. If your problem was not resolved, feel free to reopen this issue and I'd be happy to help out!
