### ISSUE TITLE
How to handle ASCollectionView touches?

### ISSUE THREAD

**Issue by cdiscla** [facebook/AsyncDisplayKit#1940]
Hello,
i have an ASCollectionView for which i need to handle touch to invoke a Segue for next ViewController.
If i try to intercept 
    `collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {`
it's never invoked; if i try to catch in the ASCellNode
`override func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {
` 
it is invoked but in this event i need to call a Segue to change ViewController; if i was in the UIViewController i would do
`self.performSegueWithIdentifier("SegueName", sender: self)`
but in the ASCellNode i don't know how to get a reference to the UIViewController that contains the ASCollectionView that contains it.
I could pass to the ASCellNode a variable  with a reference to the UIViewController, but i hope there is a better solution, can anyone help me in finding 1) a way to catch didSelectItemAtIndexPath in the UIViewController or 2) a way to get the UIViewController from the ASCellNode.

Thanks in advance and greetings

**Comment by maicki** [comment]
Hi @cdiscla, `collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath)` should be called if you tap on a cell. I should not be necessary to overwrite `-[ASCellNode touchesBegan]`. Would you be able to provide a sample app? That would be great ... Thanks!

**Comment by hannahmbanana** [comment]
@cdiscla: what version of the framework are you using?

**Comment by cdiscla** [comment]
@hannahmbanana : I'm using 1.9.8 version

**Comment by hannahmbanana** [comment]
@cdiscla: Could you try out 1.9.81? Some improvements were made to cell selection in that version.

**Comment by cdiscla** [comment]
I've tried 1.9.81 but didSelectItemAtIndexPath is not invoked; actually i've bypassed the problem handling touchesBegan( ) in the ASCellNode

**Comment by maicki** [comment]
@cdiscla Would it be possible to create a small sample app that shows the problem? Thanks!

**Comment by Adlai-Holler** [comment]
@cdiscla I'm astonished that `didSelectItem` is not being called, if your view controller is set as the `ASCollectionView.asyncDelegate` (or `ASCollectionNode.delegate`), unless your cell node is eating touches (because there's a control inside of it) which does often happen.

Is there any update on this? In the future, if you need to get from a subview/subnode to the nearest view controller, your best bet is actually to use the responder chain (which is totally underrated!)

Please feel free to reopen this as needed. Cheers!
