### ISSUE TITLE
auto layout

### ISSUE THREAD

**Issue by MrReN** [facebook/AsyncDisplayKit#196]
Do you support the automatic layout, small teams will normally be used?if not ,why? Please answer .thanks

**Comment by debug29** [comment]
If i read correctly, actually AsyncDisplayKit does not support autolayout.

**Comment by kylehickinson** [comment]
There's been a bunch of questions around it before (e.g. just search "AsyncDisplayKit autolayout").  The general consensus is that you *shouldn't* use it even if it's possble. This is because AutoLayout forces synchronous layout on the main thread, which is half the reason you're using AsyncDisplayKit.

**Comment by rnystrom** [comment]
@kylehickinson is exactly right. The way that Auto Layout currently works is counter productive to what ASDK is trying to accomplish. Not to say you can't use Auto Layout in simple views and controllers in your app though! You could use AL for things like a signup workflow but then use ASDK for large, complex table views.

**Comment by MrReN** [comment]
If so, how should I adaptation iphone6 and plus

**Comment by kylehickinson** [comment]
You don't need, or have ever been required to use auto-layout to include iPhone 6/6+ support.  You just need to include the appropriate launch image (`Default-667h@2x.png`/`Default-960h@2x.png`) and then do regular layout math in the `calculateSizeThatFits:` and `layout` methods.
