### ISSUE TITLE
[Cocoapods] AsyncDisplayKitVersionNumber returns 1.0

### ISSUE THREAD

**Issue by zdenektopic** [facebook/AsyncDisplayKit#2048]
In Swift
`print("ASDK \(AsyncDisplayKitVersionNumber)")`
outputs

> ASDK 1.0

**Comment by hannahmbanana** [comment]
@zdenektopic: could you share the contents of your podfile?

**Comment by zdenektopic** [comment]
@hannahmbanana here:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ASDKTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AsyncDisplayKit'

  # Pods for ASDKTest

end
```
and Podfile.lock
```
PODS:
  - AsyncDisplayKit (1.9.81):
    - AsyncDisplayKit/PINRemoteImage (= 1.9.81)
  - AsyncDisplayKit/ASDealloc2MainObject (1.9.81)
  - AsyncDisplayKit/Core (1.9.81):
    - AsyncDisplayKit/ASDealloc2MainObject
  - AsyncDisplayKit/PINRemoteImage (1.9.81):
    - AsyncDisplayKit/Core
    - PINRemoteImage/iOS (>= 3.0.0-beta.2)
  - PINCache (3.0.0-beta)
  - PINRemoteImage/Core (3.0.0-beta.3):
    - PINCache (>= 3.0.0-beta)
  - PINRemoteImage/iOS (3.0.0-beta.3):
    - PINRemoteImage/Core

DEPENDENCIES:
  - AsyncDisplayKit

SPEC CHECKSUMS:
  AsyncDisplayKit: 011ea22a76a79a5bbfc14501fede6e0196a3c2f0
  PINCache: 9b66261ade3d4feb272df4b4dd2e035469909448
  PINRemoteImage: 308731aa6534500e58fc211b9cc2bb7252df25ba

PODFILE CHECKSUM: 3f8d68cf27694e0d3534dc8abcde7bfd2cff753e

COCOAPODS: 1.0.1
```

**Comment by hannahmbanana** [comment]
@zdenektopic: It looks like the latest AsyncDisplayKit - version 1.9.81 - was correctly installed, and the pod spec for that version has the correct name. Is this a Swift specific thing? 

```
  spec.version      = '1.9.81'
```

**Comment by hannahmbanana** [comment]
@zdenektopic: What are you looking to use this value for? It looks like the correct version was installed, so I'm wondering if this issue has to do with cocoapods.

**Comment by zdenektopic** [comment]
To log it for debugging when users/testers report us any issues or for crash reports.

**Comment by hannahmbanana** [comment]
@zdenektopic: do you use any other frameworks that this works for? I'm pretty confused as to why this happens.

**Comment by george-gw** [comment]
@zdenektopic:
`AsyncDisplayKitVersionNumber` in Cocoapods returns the project file's `CURRENT_PROJECT_VERSION` number and not the `CFBundleShortVersionString`, to view this:

- Click the Pods xcodeproj file
- Click on AsyncDisplayKit 
- Click on Build Settings
- Type "CURRENT_PROJECT_VERSION" in search
- Under Versioning, you will see: `Current Project Version: 1`

That is why you get 1, in fact all pods that I have tested always return 1, you can try modifying that entry to 4, and then check your print for `AsyncDisplayKitVersionNumber`, you will see the output to be 4.

Also note that: `AsyncDisplayKitVersionNumber` is a double, and doubles cannot have two decimal points, so even if that were to work, you would get something like **1.9** instead of **1.9.81** (you can test this by changing the `Current Project Version` to **1.9.81**).

In such a case, assuming that `AsyncDisplayKitVersionNumber` were to be functioning like you expected. I would suppose that you should be using `AsyncDisplayKitVersionString` instead of `AsyncDisplayKitVersionNumber` to view the number in string format (thus handling the two decimal points), but for some reason we don't have access to `AsyncDisplayKitVersionString`.

@hannahmbanana: I am unsure if this is doable right now with Cocoapods, so perhaps that is something that should be address to the Cocoapods team?

**Comment by hannahmbanana** [comment]
Thanks for the excellent investigation & answer! I'm going to close this issue because it seems like implementation is blocked on Cocoapods. 

If someone stumbles across this thread and would like to volunteer to follow up about this with Cocoapods, we would appreciate it!
