### ISSUE TITLE
[Question] why is ASDelegateProxy a proxy

### ISSUE THREAD

**Issue by Yue-Wang-Google** [facebook/AsyncDisplayKit#2082]
Hi, we'd like to know why ASDelegateProxy is a proxy, since it doesn't use any of the NSProxy's methods.

**Comment by hannahmbanana** [comment]
@garrettmoon @Adlai-Holler @maicki

**Comment by garrettmoon** [comment]
@Yue-Wang-Google not sure I understand the question. Are you asking why it's not a subclass of NSProxy? I wrote it to do exactly what I needed (break a retain cycle created by CADisplayLink) and nothing more. Subclassing NSProxy seemed more complex. Is there an issue you're seeing?

**Comment by Yue-Wang-Google** [comment]
Oh we were asking why ASDelegateProxy is a subclass of NSProxy rather than a NSObject. Since ASDelegateProxy and its subclasses do not use any NSProxy features. See https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASDelegateProxy.h#L28

**Comment by garrettmoon** [comment]
Whoops, I totally misunderstood and thought you were referring to ASWeakProxy.

Looking into it a bit, ASWeakProxy probably *should* inherit from NSProxy.

NSProxy doesn't inherit from NSObject and implements far fewer methods allowing your proxy object to override more points.

**Comment by jmig** [comment]
@garrettmoon as you pointed out, NSProxy implements a lot less methods than NSObject.

I had an issue in one of my app with ASDelegateProxy. I had some code that was testing the class of a UIScrollView delegate with `isKindOf:` and that will crash on an NSProxy object (because NSProxy doesn't implement isKindOf).
I ended up using `isProxy` to avoid the crash.

Back to the original question, if ASDelegateProxy doesn't actually use the NSProxy APIs, do we have a substantial added benefit of having it an NSProxy instead of an NSObject ?

Note: I'm not very familiar with NSProxy, so there is potentially one (or several) very valid reason to use it.

**Comment by garrettmoon** [comment]
What do you mean, it doesn't use the NSProxy APIs? NSProxy doesn't have specific APIs that a subclass would call, it's intention appears to be a minimal object to support proxying – more minimal than even NSObject (it doesn't even have an init method!). So the advantage is it is lightweight and allows for proxying methods on NSObject without explicitly overriding them. At least that's *my* understanding :)

**Comment by jmig** [comment]
Like I said I'm not an expert in `NSProxy` so I'm gonna lean toward your advice.

I was under the impression that the interesting APIs for NSProxy were 
`methodSignatureForSelector:` and `forwardInvocation:`. In the case of ASDelegateProxy, forwardInvocation is basically a no-op.

Thanks for the explanation, I definitely read more about NSProxy today than I ever did in the past 8 years ^^.

**Comment by jmig** [comment]
Thanks @garrettmoon

**Comment by Yue-Wang-Google** [comment]
Thanks @garrettmoon  for your explanation!
