### ISSUE TITLE
ASTextNode Flashing on Highlight

### ISSUE THREAD

**Issue by lavoy** [facebook/AsyncDisplayKit#213]
I'm seeing some weird flashing in an ASTextNode that I made. When I push down on the node to highlight it, the background color changes as expected, but the top left corner flashes a lighter color. Have you guys seen this at all or am I doing something wrong?

I can post the code if that would help, but I thought maybe you would know the issue without it. Also notable, this is a new issue since updating from 1.0.1 to 1.1.

**Comment by lavoy** [comment]
This is what it looks like. It flashes, on every highlight, but the frame rate on this GIF must not be fast enough.

![button-flashing](https://cloud.githubusercontent.com/assets/314876/5684445/1cad51e8-97f6-11e4-8c37-f1265e1eb323.gif)

**Comment by rnystrom** [comment]
Thanks for reporting this @lavoy! Out of curiousity, could you print your node hierarchy? Or even better yet, provide a sample project? My first hunch is that there might be a rogue node or something. The grey color looks like the default placeholder color that we use.

**Comment by lavoy** [comment]
Here's a project with the issue isolated. Turns out it needs to be added to a `UIScrollView` for it to flash like this.

https://github.com/lavoy/ASTextProject

**Comment by rnystrom** [comment]
@lavoy thanks so much! Taking a look at this ASAP.

**Comment by rnystrom** [comment]
@lavoy Ah, yup, the placeholders are at fault here. We're going to discuss if there needs to be an internal solution, but what appears to be the problem is that since `ASTextNode` has a placeholder by default (check out the [placeholders example](https://github.com/facebook/AsyncDisplayKit/tree/master/examples/Placeholders)) and interacting with the element is triggering the display process, the placeholder is being added then instantly removed from the view.

My recommendation would be to set `placeholderEnabled = NO` on any text nodes that don't need placeholders. I did this on your sample project and it removed the flickering issue.

Thanks again for reporting this! Really good find.

**Comment by lavoy** [comment]
Awesome, thanks for taking a look and finding me a workaround!
