### ISSUE TITLE
ASDisplayNode cannot be released on iOS6

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#216]
I try to use ASDisplayKit on iOS6, but ASDisplayNode cannot be released on iOS6 once I called `node.view`, I am not sure is there any difference of memory management between iOS6 and iOS7 in ASDisplayKit.  Thanks!

**Comment by secretiverhyme** [comment]
Since AsyncDisplayKit makes such heavy use of iOS 7 and 8 frameworks — e.g., ASTextNode is powered by Text Kit — we don't officially support iOS 6.  There shouldn't be substantive memory management semantics differences between 6 and 7, though.

A node's view maintains a weak reference to its node, and that reference becomes strong for as long as the view is in the view hierarchy.  This prevents nodes from being deallocated while they're in use, and is why the code snippet on the front page of asyncdisplaykit.org works (note that nothing else is maintaining a reference to that text node).

Simply accessing the node's `.view` property shouldn't trigger a retain cycle.  Does the same code behave differently on iOS 6 and 7?

**Comment by yufenglv** [comment]
Thanks ~  Yes, the same code behave differently on iOS6 and 7. It's really weird. I have implement the textNode by using CoreText and so it can be used on iOS6.

**Comment by secretiverhyme** [comment]
> Yes, the same code behave differently on iOS6 and 7. It's really weird.

Hm, that's odd.  This is on stock nodes, not custom ones, right?

> By the way, I have implement the textNode by using CoreText and so it can be used on iOS6.

ASTextNode was originally implemented using Core Text, but we switched to Text Kit in order to support some of Paper's design requirements.  If you need iOS 6 support, using Core Text will work fine — but do be aware that `CTFramesetterCreateWithAttributedString()` is not thread-safe, so you'll need to guard all calls to it with a global lock.

**Comment by yufenglv** [comment]
@secretiverhyme Vary appreciate! I figure it out, with the code below it will be fine on iOS6. I don't konw why `UIView (ASDisplayNodeInternal)` implement the `setter` and `getter`, but `CALayer (ASDisplayNodeInternal)` didn't.

And Thanks for your advice about `CTFramesetterCreateWithAttributedString()`.  Thanks!

	@implementation CALayer (ASDisplayNodeInternal)
	@dynamic asyncdisplaykit_node;
	- (void)setAsyncdisplaykit_node:(ASDisplayNode *)node
	{
	    objc_setAssociatedObject(self, ASDisplayNodeAssociatedNodeLayerKey, node, OBJC_ASSOCIATION_ASSIGN); // Weak reference to avoid cycle, since the node retains the view.
	}
	
	- (ASDisplayNode *)asyncdisplaykit_node
	{
	    ASDisplayNode *node = objc_getAssociatedObject(self, ASDisplayNodeAssociatedNodeLayerKey);
	    return node;
	}
	@end

**Comment by secretiverhyme** [comment]
@yufenglv — sure thing, glad you got it working!
