### ISSUE TITLE
Scroll didn't respond to stop on finger touch

### ISSUE THREAD

**Issue by dssheng** [facebook/AsyncDisplayKit#2177]
Swapping a ASTableNode up-down continuously, 
the tableView scrolling out and didn't respond the finger pin it to stop.
1.9.80 OK
1.9.81  bug (? 1.9.89 not quite clear of version)
1.9.90 bug

BTW, This bug have no relation with [Crash] ASDN::Mutex::~Mutex()#2017, but I don't how to unlink it.

**Comment by maicki** [comment]
@Adlai-Holler Any quick thoughts on that?

**Comment by Adlai-Holler** [comment]
Usually if a table view isn't reliably responding to touches, it's because there are update animations going on. When we requery the node heights, or when we insert some new nodes, we get an update animation. 

@dssheng This behavior sounds extremely frustrating so we want to get to the bottom of it, and thank you for taking the time to bisect between versions. Would you be willing to post some sample code that reproduces the issue?

**Comment by hannahmbanana** [comment]
@dssheng - Do you have any updates on this issue?

**Comment by dssheng** [comment]
I've just verified on v2.0.1, 
It works good.
