### ISSUE TITLE
[ASDisplayNode] ASDisplayNode resize API

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#225]
Say I have a node whose size depends on a writeable property:

```objc
@implementation FlexibleNode

- (CGSize)calculateSizeThatFits:(CGSize)constrainedSize
{
    CGFloat height = self.compact ? 100 : 200;
    return CGSizeMake(constrainedSize.width, height);
}

- (void)setCompact:(BOOL)compact
{
    _compact = compact;
    [self invalidateCalculatedSize];
    [self setNeedsLayout];
}

...

@end
```

When someone comes along and sets `flexibleNode.compact = YES`, is there a pattern for letting the node's parent know to recalculate its own layout (which may in turn notify the grandparent node, etc...)?

**Comment by rnystrom** [comment]
I don't believe there is a mechanism for invalidating layout *up* the node hierarchy. You might be able to write your own method in that setter to do so.

Something like this in the setter might get you on the right track:

```
ASDisplayNode *node = self;
do {
  [node invalidateCalculatedSize];
  [node setNeedsLayout];
  node = node.supernode;
} while (node != nil);
```

**Comment by ide** [comment]
Cool. I think what I want is some way for that to automatically happen in an efficient way. For example if you click a photo on facebook.com and expand a truncated comment ("... See More") in the lightbox, the comment needs to invalidate its parent UFI's layout, which needs to invalidate part of its parent lightbox's layout, which can stop there since it is fixed-positioned and doesn't need to invalidate its parent document's layout. It's good this is handled automatically since the comment component doesn't need to know anything about photos, feed stories, or any other place that embeds a UFI.

I suspect it might be an invasive change for ASDK to track these layout dependencies and propagate the invalidation efficiently but I'll think about it some more.

**Comment by rnystrom** [comment]
Another idea that came to mind would be to use two different nodes. Say you have two `ASTextNode`s: one as a placeholder that says "See more..." and another w/ the full content but with its alpha set to 0. When you tap the placeholder, in an animation block set its alpha to 0 while setting the full content's alpha to 1.

There's more work that would go into this, like positioning and such, but its an idea.

cc @secretiverhyme for any other thoughts

**Comment by secretiverhyme** [comment]
This is something we'd like to expand AsyncDisplayKit to support, though I haven't given much thought to the API design yet.  We'd discussed *downwards* propagation, for ASCellNode resizing (#214), but the general case is worth considering.  Let us know if you have any suggestions here -- it's quite possible you'll get to it before we can!  =]

**Comment by ide** [comment]
One rough idea is to call `invalidateCalculatedSize` and `setNeedsLayout` from the root node so that modifying the size of any node will automatically relayout all of its ancestors (and potentially its siblings -- I believe it is possible to construct a layout in which changing the frame of a node will affect the frames of every single other node). I believe this faciliates correct and consistent layouts.

To get the performance to be good by default I have a couple of thoughts:
 - Pruning the relayout calculations is super important.
 - The calculatedSize caching already in ASDK is great. Seems really important. Is there more that makes sense to cache?
 - If we know that a node's calculated size is not affected by one of its subnode's sizes, then we can call `invalidateCalculatedSize` starting at that subnode instead of the root.
 - Sometimes you want to opt out of the automatic layout invalidation and handle it yourself (e.g., hot code paths, nodes with very expensive layout) so exposing some overridable hooks or a layout delegate probably makes sense. Animations and interactive gestures might need more precise control over layout changes. I don't know what the API should look like but I think it's one of those things that gets refined over months as people discover new use cases.

**Comment by adly-holler** [comment]
I'm trying to build a table view that has growing editable text views inside some cells. I've got a stripped-down use case at https://github.com/adly-holler/AsyncDisplayKitGrowingTextCellDemo and I'd love any advice.

I've tried calling `invalidateCalculatedSize` and `setNeedsLayout` on everything I can, and I'm using `beginUpdates/endUpdates` and the table view correctly re-queries the cell height but the editable text node still returns one-line height.

**Comment by nguyenhuy** [comment]
@adly-holler Thanks for actively contributing to ASDK. You're awesome :+1: :cool: 

I tried to run your demo and it actually works. Based on your comment [here](https://github.com/adly-holler/AsyncDisplayKitGrowingTextCellDemo/blob/master/AsyncDisplayKitTableCellTextView/ViewController.m#L29), perhaps your question is: why calling `invalidateCalculatedLayout` doesn't cause a relayout. The answer is that `invalidateCalculatedLayout` simply marks the calculated layout of the node invalidated. It neither triggers a relayout nor propagates the invalidation to its supernode.

I was a bit surprised when [calling -setNeedsLayout on the cell node](https://github.com/adly-holler/AsyncDisplayKitGrowingTextCellDemo/blob/master/AsyncDisplayKitTableCellTextView/ViewController.m#L31) works. The rule of thumb for relayout is that developers should call `-setNeedsLayout` on the node that causes a layout change, in this case it is the editable text node. Failing to do that usually would cause the (text) node to use its old cached layout. The reason your demo works is that ASEditableTextNode invalidates its layout in `-textViewDidChange` ([here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASEditableTextNode.mm#L421)). And that leads to 2 interesting questions:
- Should editable text node calls `-setNeedsLayout` instead? This actually makes sense and will make relayout more robust-- i.e any layout changes originated from an editable text node automatically trigger a relayout. 
  - The only problem I see is that `ASCellNode` must then somehow trigger an empty batch editing transaction (so that the hosting table/collection view will animate to the cell node's new size). This can be done either by a delegation or allowing `ASCellNode` to have a weak reference to the hosting collection/table view.
- Should we eliminate `-invalidateCalculatedLayout` completely? Or at least, for backward compatibility, make it to call `-setNeedsLayout` internally?
  - One drawback of this approach is that relayout will be done very frequently-- i.e every time `-setNeedsLayout` is called on a node). We can fix this by scheduling the relayout to be done in the next layout call of the main run loop-- i.e the next time -layoutSubviews is called.

Would love to know your thoughts on this matter, @adly-holler, @appleguy and anyone else.

**Comment by appleguy** [comment]
@ide @Adlai-Holler - the framework behavior is significantly improved in this respect. For the past several months, it is now the case that calling setNeedsLayout on any subnode should result in its containing hierarchy being remeasured, and if it is inside of an ASCellNode (used by a ASTable or ASCollection) than this will automatically trigger the cell to resize. By default, the resize is animated, although there is an option that you can set on any subnode of the cell that results in all layout changes to that cell not being animated. 

@nguyenhuy - are there any other improvements to this behavior that you think we should be tracking? In particular, is there some kind of issue specific to ASEditableTextNode? 

For anyone who has been following this, please comment if you have experienced any issues or have a related request.

**Comment by appleguy** [comment]
@ide: ASDK now supports an automatic, asynchronous, purely Objective-C layout feature which is based on CSS' flex box model.

Layout docs: http://asyncdisplaykit.org/docs/automatic-layout-basics.html

**Beta** Layout Transition API docs (easy animation between a node's layouts in response to some internal state change in a node): http://asyncdisplaykit.org/docs/layout-transition-api.html

**Comment by peak77** [comment]
@rnystrom But how to update the ASCellNode height when switch  short content to long content?   Is it calling  -setNeedsLayout ?  Thanks advance
