### ISSUE TITLE
[ASVideoNode] Video node flickers when asset is set after the thumbnail image is set

### ISSUE THREAD

**Issue by master-nevi** [facebook/AsyncDisplayKit#2329]
Our app is using ASVideoNode with much success except for one hiccup which has been around since v1.9.81 . Currently our app gets and sets the video asset URLs on demand in order to avoid unnecessary network calls made by AVFoundation when creating AVAssets. Until the video plays we use a combination of `[ASNetworkImageNode defaultImage]` and `[ASNetworkImageNode URL]` for remote video thumbnails as well as `[ASImageNode image]` for local video thumbnails on `ASVideoNode`. 

Now as soon as we set the asset, internally `[ASVideoNode clearFetchedData]` is then called which clears the entire node momentarily until the video begins to play; which looks like a flicker.

This is demonstrated on my branch below in the video example project. In this project, the remote thumbnails are set immediately while the video assets don't get set until after a delay to simulate our scenario: 
https://github.com/master-nevi/AsyncDisplayKit/tree/dr/1.9.90-video-flicker/examples/Videos

Video demo: https://drive.google.com/file/d/0BxSzpqJ8X6gyQzVwZDZPdmo0cWs/view?usp=sharing

Our project has been able to work around this by only clearing the asset when a new asset is set, not the ASNetworkImageNode as demonstrated in this commit:
https://github.com/master-nevi/AsyncDisplayKit/commit/c05ff568f8307df1fcc8ffe7926c234edbedc13b

Please let me know if there's a better work around for this. We're willing to put time and effort in making sure this is right; please advise.

**Comment by master-nevi** [comment]
Video demo: https://drive.google.com/file/d/0BxSzpqJ8X6gyQzVwZDZPdmo0cWs/view?usp=sharing

**Comment by master-nevi** [comment]
Adding @appleguy @maxsz or @binl as they're mentioned to have AVFoundation expertise.

**Comment by hannahmbanana** [comment]
@master-nevi: Thanks for the very detailed description! A quick question: could you provide the backtrace of when the clearFetchedData is called before the video is played? Is this something you are triggering, or is it being called by the framework? 

As a short term fix, you may be able to avoid this by setting defaultImage to be the local video frame whenever you have a local frame available. Use it for the generic thumbnail if that is all you have, or override it with a locally cached image if available. 

There is a known issue with the .image property being cleared if it is not the same as represented as the URL (#2275), because ASNetworkImageNode was originally designed for these two to be related.

**Comment by master-nevi** [comment]
When our code sets the asset with `[ASVideoNode setAsset:]` , the framework internally calls `[ASVideoNode _setAndFetchAsset:url:]` which calls `[ASVideoNode clearFetchedData]`. The implementation of `[ASVideoNode clearFetchedData]` calls the super implementation `[ASNetworkImageNode clearFetchedData]` which is what clears the image.

![screen shot 2016-10-07 at 12 26 40 am](https://cloud.githubusercontent.com/assets/987706/19181875/c5b5573a-8c24-11e6-87e9-97b2dc6107dd.png)

**Comment by master-nevi** [comment]
Hence why our patch in https://github.com/master-nevi/AsyncDisplayKit/commit/c05ff568f8307df1fcc8ffe7926c234edbedc13b avoids calling `[super clearFetchedData]` when the `[ASVideoNode setAsset:` is called.

**Comment by maicki** [comment]
@master-nevi Hey, what about having a container node that contains an `ASImageNode` / `ASNetworkImageNode` and a `ASVideoNode`. The image node is having the thumbnail and whenever you set the asset you could fade (or some other transition) the thumbnail node out and the video node in. Let me know if this would work.

**Comment by master-nevi** [comment]
That's fine as a workaround but for long term, if consumers are expected to use an entirely separate image node as a thumbnail instead of the one baked into the video node, the video node might as well not subclass `ASNetworkImageNode` at all right?

Any reason my patch wouldn't be acceptable as a real fix. There isn't let me know, and I can submit as a PR.

**Comment by garrettmoon** [comment]
@master-nevi can you put up a PR and we can discuss it there? Thank you!

**Comment by master-nevi** [comment]
@garrettmoon PR opened!

**Comment by maicki** [comment]
@master-nevi Hey thanks for creating the PR!

I'm actually currently looking into a different solution already mentioned above. In my opinion (and also talking with a couple of other developer) instead of fixing the broken behavior of `ASVideoNode`, we should prefer composition over inheritance and let `ASVideoNode` inherit from `ASDisplayNode` instead of `ASNetworkImageNode`. This would allow any developer to use the core components and combine them the way they want without having an overhead like `ASVideoNode` and `ASNetworkImageNode`. We could than create a mother component that could combine these two, but my solution for this issue would still to not use the backing `ASNetworkImageNode` functionality at all.

@Adlai-Holler @garrettmoon @appleguy Any opinions?

**Comment by appleguy** [comment]
Would like to fix this -- check out my comments on the PR though, I think there is some misalignment in the new behavior between the two kinds of placeholders supported.  Asset's first frame, vs URL / separate placeholder image.

We need to make sure both work, and in the case of the asset providing the placeholder, it needs to clear out the previous placeholder when the asset changes.

https://github.com/facebook/AsyncDisplayKit/pull/2644

**Comment by Adlai-Holler** [comment]
It was decided in #2644 to go with the suggestion [here](https://github.com/facebook/AsyncDisplayKit/issues/2329#issuecomment-261432437) and so this is resolved.
