### ISSUE TITLE
[Question] ASDisplayNode keep alive reference

### ISSUE THREAD

**Issue by Y-fate** [facebook/AsyncDisplayKit#2339]
ASTextNode *title=[[ASTextNode alloc]init];
title.attributedString=Text;
 [self addSubnode:title];

retain cycles
(
        "-> _keepalive_node -> ASTextNode ",
        "-> _view -> _ASDisplayView "
  )

Why keep cycle.

**Comment by caophong94** [comment]
i face the same, anybody can help?

**Comment by hannahmbanana** [comment]
@Y-fate @caophong94: I was curious about this too and asked @appleguy. :) This is his response:

"This retain cycle is intentionally created because the node is in a "live" view hierarchy (it is inside the a UIWindow that is onscreen). 

To see why this is necessary, apple also creates this retain cycle between UIView and CALayer. If you create a UIView and add its layer to a super layer, and then release the UIView, it will stay alive even though the CALayer delegate pointing to it is weak. 

For the same reason, if the node's view is a descendant of a window, but there is no reference to the node, we keep the node alive with a strong reference from the view. 

Good application design should not rely on this behavior, because a strong reference to the node should be maintained by the subnodes array or by an instance variable. However, this condition occasionally occurs, for example when using a UIView animation API. This cycle should never create a leak or even extend the lifecycle of a node any longer than it is absolutely necessary. If you find something counter to this, please let us know!

**Comment by caophong94** [comment]
Hi @hannahmbanana, @appleguy  thanks for your support
i have a big problem with this issues, i saw the function keep node alive here, it's good, but when i dismiss a View Controller contain some nodes, it still alive

`- (void)willMoveToSuperview:(UIView *)newSuperview
{
  // Keep the node alive while the view is in a view hierarchy.  This helps ensure that async-drawing views can always
  // display their contents as long as they are visible somewhere, and aids in lifecycle management because the
  // lifecycle of the node can be treated as the same as the lifecycle of the view (let the view hierarchy own the
  // view).
  UIView *currentSuperview = self.superview;
  if (!currentSuperview && newSuperview) {
      self.keepalive_node = _node;
  } else if (currentSuperview && !newSuperview) {
    // Clearing keepalive_node may cause deallocation of the node.  In this case, __exitHierarchy may not have an opportunity (e.g. _node will be cleared
    // by the time -didMoveToWindow occurs after this) to clear the Visible interfaceState, which we need to do before deallocation to meet an API guarantee.
    if (_node.inHierarchy) {
      [_node __exitHierarchy];
    }
    self.keepalive_node = nil;
  } `

**Comment by hannahmbanana** [comment]
@caophong94: could you share a sample project showing this?

**Comment by caophong94** [comment]
let me create one, thanks for your help!

**Comment by caophong94** [comment]
@hannahmbanana , @appleguy : i just created new one, please take a look:
https://github.com/caophong94/alivecellnode

**Comment by dungnc** [comment]
i have same issue, my network image nodes not retain, so it make my app crash for memory leak

**Comment by maicki** [comment]
Hey @caophong94 This is in fact no ASDK issue. I looked into your sample project and you have a retain cycle in there. It's in `LayerAnimator` in `UIView+Radial.swift`. This prevents the deallocation of the `AliveViewController` what prevents the deallocation of the `AliveCellNode`, so they are sticking around. 

If you change `LayerAnimator` to the following you will see both `AliveViewController` as well as `AliveCellNode` will be deallocated:

```swift
class LayerAnimator : NSObject, CAAnimationDelegate{
    
    var complitionBlock:(()->Void)?
    var animLayer:CALayer?
    var caAnimation:CAAnimation?
    
    
    init(layer: CALayer , animation:CAAnimation) {
        
        self.caAnimation = animation;
        self.animLayer = layer;

    }
    
    func startAnimationWithBlock(block:(()->Void)){
        self.caAnimation?.delegate=self
        self.complitionBlock=block;
        
        self.animLayer?.addAnimation(self.caAnimation!, forKey: "anim")
    }
    
    func animationDidStop(anim: CAAnimation, finished flag: Bool) {
        self.caAnimation?.delegate = nil
        self.complitionBlock?()
    }
}
```

I will close this issue for now please reopen if you think it's not resolved.
