### ISSUE TITLE
Nested ASCollectionNode is reporting wrong collectionViewContentSize 

### ISSUE THREAD

**Issue by CR34L** [facebook/AsyncDisplayKit#2442]
Running a ASCollectionNode inside a ASCellNode has strange sizing issues.
The nested ASCollectionNode is configured as below:

```
collectionNode.style.minHeight = ASDimensionMake(50);
collectionNode.style.maxHeight = ASDimensionMake(300);
collectionNode.style.minWidth = ASDimensionMake(100);
collectionNode.style.maxWidth = ASDimensionMake(self.view.bounds.width);
```

The minHeight Value seems to be fixed. The node never reaches maxHeight even after spamming the async datasource. 

calling:
`
    let size = collectionViewLayout.collectionViewContentSize;
` 
is reporting **size.zero** -> here the calculated layoutsize is expected? Right?

The only way to get the correct size is a dirty hack with a manual repaint trigger:

```
/* testing */
repaintTimer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(self.repaint), userInfo: nil, repeats: true);

open func repaint() {
  collectionNode.waitUntilAllUpdatesAreCommitted();
  let size = collectionViewLayout.collectionViewContentSize;
  if collectionViewLayout.collectionViewContentSize.height > 0.0 {
    collectionNode.style.height = ASDimension(unit: ASDimensionUnit.points, value: size.height);
    collectionNode.setNeedsLayout();
    repaintTimer.invalidate();
  }
}
```

**Attached a simple Demo App for bug demonstration (Swift3.0, XCode8):**
[MediaCellTest.zip](https://github.com/facebook/AsyncDisplayKit/files/540479/MediaCellTest.zip)

**Comment by CR34L** [comment]
Update:

calling: **collectionNode.setNeedsLayout()**; on the nested node instead of **self.setNeedsLayout()** produces perfect sizes and layouts.

This is not really logic because the nested collection node has already done layout calculation and the parent not. But anyway its not a bug only a way how to do it right.

Ready to close this issue.

**Comment by appleguy** [comment]
@CR34L Indeed, ASCollectionNode is not self-sizing in terms of its own bounds, and you need to either force synchronous layout (not great) or wait for the layout completion block to be called if you want to know the contentSize and use this to set the bounds.

There are some other tasks filed on adding these capabilities to ASCollectionNode, but since the use case is rare, we haven't been able to prioritize them yet.

Typically I suggest finding a way to calculate the one constrained dimension (e.g. in a vertical view with horizontal nested view, you only need the height of the collection, and can usually make the collection bounds as wide as the screen).  You can do this by implementing calculateLayoutThatFits: (or even just calculateSizeThatFits:) on the ASCellNode that contains your collection, and iterate over the cell nodes of the collection to call layoutThatFits: on them.  This can be pretty efficient if done thoughtfully (providing the same constrainedSize to the cell nodes as the collection will later provide to them; returning the same instance to the collection that you create to provide the layout of the cell; etc).

Sorry we don't have a better technique at the moment, would love to eventually!

**Comment by CR34L** [comment]
Thx for answering. Working already on a workaround.

///
