### ISSUE TITLE
Layout Inspector scrollableDirections May Be Called when Not Implemented

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2471]
The method was recently added in #2381 . 

![screen shot 2016-10-24 at 9 47 28 am](https://cloud.githubusercontent.com/assets/2466893/19654912/0c270c4c-99cf-11e6-90ba-bafd9dd33c5d.png)
![screen shot 2016-10-24 at 9 47 44 am](https://cloud.githubusercontent.com/assets/2466893/19654913/0c3d45b6-99cf-11e6-999e-330f26bb26a4.png)

```
(lldb) po self->_layoutInspectorFlags.scrollableDirections
<nil>
(lldb) po self->_layoutInspectorFlags.didChangeCollectionViewDataSource
<nil>
(lldb) po self->_layoutInspectorFlags.didChangeCollectionViewDelegate
1
```

**Comment by garrettmoon** [comment]
Ok, I haven't gotten to the bottom of it, but one issue is we have a getter that can generate a new layoutInspector if _layoutInspector is nil. In that case, if the layoutInspector is nil'd out without updating flags, you could check the flags, see it responds to scrollable directions (which wouldn't matter if it was nil because messaging nil should be safe), but then calling the getter would get you a new layoutInspector to message which may have changed its flags.

**Comment by garrettmoon** [comment]
Oooh, ok, _layoutInspector is weak, if it gets nil'd out due to that, the above case could happen.
