### ISSUE TITLE
When I reloadData ASTablView scroll to the top

### ISSUE THREAD

**Issue by duxinfeng** [facebook/AsyncDisplayKit#251]
[_tableView reloadData];

**Comment by secretiverhyme** [comment]
This is expected behaviour due to the way ASTableView and ASCollectionView work.  The `-reloadData` call on these classes is substantially more expensive than on the UIKit versions, since it must…

* reallocate all nodes in your data source
* run a new measurement pass on all nodes
* re-enqueue asynchronous display of nodes in the working range

As such, you should try to use update methods (insert sections, delete rows, &c.) whenever possible.

(ccing @tanliboy in case he'd like to chime in)
