### ISSUE TITLE
[Question] Is PINCache necessary?

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2534]
If using pod, it will download dependency PINCache also.

But I just download the sourceCode 1.9.91 & build a StaticLibrary for my project, PINCache is not included, but works well so far.

Did I miss anything important, or should pay attention to?

**Comment by hannahmbanana** [comment]
@IvanChan - While AsyncDisplayKit _will_ work without PINCache, you will miss out on image cacheing. We highly recommend you use PINCache.

**Comment by Jauzee** [comment]
I think it's better to reopen this one and ask my question there:

What is the default behaviour of ASDK caching mechanism? In documentation i see that caching on `ASNetworkImageNode` is enabled by default, but looks like it doesn't cache images (or I misunderstood something).

I read on the site that: `If you choose not to include the PINRemoteImage and PINCache dependencies you will lose progressive jpeg support and be required to include your own custom cache that conforms to ASImageCacheProtocol.`
And then: `ASNetworkImageNode now uses PINCache under the hood by default to cache network images automatically.`

Does it necessary to add `PINCache` & `PINRemoteImage` to `carthage copy-frameworks` state?

Currently I am using ASDK 2.0 from `master` branch.

**Comment by garrettmoon** [comment]
@Jauzee I'm not 100% sure since I don't use Carthage, but I would guess you would want to make sure PINCache and PINRemoteImage are being copied in. Otherwise, you'll be missing a lot of performance features. If you figure out that something special needs to be done to get them included in your project with Carthage, I'd love to fix it or at least add documentation.

**Comment by hannahmbanana** [comment]
@Jauzee - were you able to include PINCache & PINRemoteImage in your Carthage project?

Did you have success following the [Carthage Installation](http://asyncdisplaykit.org/docs/installation.html) directions? If not, we should work together to update the doc so that others don't run into the same issue. 😃

**Comment by hannahmbanana** [comment]
@Jauzee - Due length of time since this thread was active, I'm going to close it. If you have any updates or solutions, we'd love to hear back from you on what worked or didn't.
