### ISSUE TITLE
[ASTableNode] issues with scrollToRow going to the last row on initial load with large number of cells

### ISSUE THREAD

**Issue by danielrhodes** [facebook/AsyncDisplayKit#2546]
Using AsyncDisplayKit at 62a0296148633c12575f051c6bebfcd0ea9b88d3 on iOS 10.1

I have an `ASTableNode` with a lot of rows (~4000). Data is already available. I want to load the view and immediately scroll to the end. Unfortunately, this leads to some undesirable behavior. First, is that when I do this (with `scrollToRow` animations on/off), every row is queried from the delegate (leading to lots of object creation and main thread usage) instead of just the last few rows which are going to be visible. As such, either the tableview does not do the initial draw and there is a delay for a few seconds and then the final few rows appear, or the first few rows are drawn, and then the delay occurs before scrolling to the end.

I have solved this in the interim by doing a transform on the `ASTableNode` and turning the whole thing upside down and then doing the opposite transform on the cells. But this is a hack (with negligible performance tradeoffs from what I can tell).

What would be a good way to trick the `ASTableNode` into immediately loading the last few cells and scrolling to the end?

**Comment by garrettmoon** [comment]
@danielrhodes that's a pretty clever hack :)

@Adlai-Holler Do you have any ideas for a better workaround now?

I know we're working on improving this situation, but it'll likely land after 2.0.

**Comment by Adlai-Holler** [comment]
@danielrhodes ASTableNode and ASCollection node are going to call `nodeBlockForRowAtIndexPath:` or `nodeForRowAtIndexPath:` for every row in the data source, from the main thread, whenever the initial data load happens.

By default, the initial data load will happen during the first `-layoutSubviews` call on the table/collection node's view. By calling `scrollToRow:` before that first layout pass, triggering the initial load at that time. Those calls to `nodeBlockForRow:/nodeForRow:` are not what is taking so much time.

Unfortunately, if you attempt to scroll to a row that has not been propagated into the view, we wait until the initial data load is finished before we can scroll. UITableView is not very good at virtualization – if we were to "fake it," that is insert the last 20 rows and then scroll you to the bottom of THAT, and then attempt to insert the other 3980 rows above those asynchronously, we would interfere with the user's scrolling because we would have to set the content offset of the scroll view.

What Apple's Messages app does, which we could eventually attempt to generalize, is to add a loading spinner above the first batch of content, and then _wait_ for the user to stop scrolling and insert the next chunk of content/adjust the content offset simultaneously at that time.

Short answer: at the current time, the best way of implementing this is inverting your table view as you have done. Slack does this as well, for what it's worth 🙂

**Comment by yanqinglove** [comment]
NSWYPageNumModel * model = [NSWYPageNumModel new];
     NSIndexPath *indexpath = [NSIndexPath indexPathForRow:self.contentArr.count-2   inSection:([_tableView numberOfSections]-1)];
                 
                               
    [model mj_setKeyValues:responseObject ];
    self.homeModel = model;
    for (int i =0 ; i<model.content.count; i++) {
      NSWYContent * content = [NSWYContent new];
      [content mj_setKeyValues:model.content[i]];
      [self.contentArr addObject:content];
      NSLog(@"%lu",(unsigned long)self.contentArr.count);
         }   

but display effect is not what i want

**Comment by yanqinglove** [comment]
16:40:43
严青 2016/11/10 16:40:43
 NSWYPageNumModel * model = [NSWYPageNumModel new];
     NSIndexPath *indexpath = [NSIndexPath indexPathForRow:self.contentArr.count-1   inSection:([_tableView numberOfSections]-1)];
            
 
    [_tableView reloadDataWithCompletion:^{
     
      [_tableView scrollToRowAtIndexPath:indexpath atScrollPosition:UITableViewScrollPositionMiddle animated:YES];

but the display effect is not what i want

**Comment by yanqinglove** [comment]
i have an idea ,what i can hide the tableview when it scroll to top,don`t allow the scrollotop display, give a false appearance

**Comment by yanqinglove** [comment]
The ASDK Dome give the answer; in ASDKgram 
```

-(void)tableView:(ASTableView *)tableView willBeginBatchFetchWithContext:(ASBatchContext *)context{
  [context beginBatchFetching];
  [self insertNewRowsInTableNode:context];
  }
 
 
- (void)insertNewRowsInTableNode:(ASBatchContext*)content 
{
  NSInteger section = 0;
  NSMutableArray *indexPaths = [NSMutableArray array];
  self.num = self.count;
  NSUInteger newTotalNumberOfPhotos = (self.count+=5);
  for (NSUInteger row = 0; row < newTotalNumberOfPhotos-self.num; row++) {
    NSIndexPath *path = [NSIndexPath indexPathForRow:self.num+ row inSection:section];
    [indexPaths addObject:path];
  }
  dispatch_sync(dispatch_get_main_queue(), ^{
    [_tableNode.view insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationNone];
  
  });
   [content completeBatchFetching:YES];
```

**Comment by garrettmoon** [comment]
Closing for now, please reply back if something else comes up.

**Comment by xor22h** [comment]
@danielrhodes how you managed to make that rotation? Setting CGAffineTransformMakeRotation(M_PI); on ASTableNode.view rotates a table upside down, but as soon as I try to apply reverse rotation inside nodeForIndexPath for a node.view it crashes assertion error.

Also, another way by setting: 
```
//        _tableNode = [[ASTableNode alloc] initWithStyle:UITableViewStylePlain];
//        _tableNode.transform = CATransform3DMakeRotation(M_PI, 0, 1, 0);
//        _tableNode.subnodeTransform = CATransform3DMakeRotation(-M_PI, 0, 1, 0);
```
makes rotation ok, but cell's become blurry.

**Comment by danielrhodes** [comment]
@xor22h didn't know about the `subnodeTransform` property.

Here's what I did:

On the `ASTableNode`:
```swift
node = ASTableNode()
node.view.transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1, tx: 0, ty: 0)
```

And in the `ASCellNode` itself:
```swift
open class YourCellNOde: ASCellNode {
   override open func didLoad() {
      super.didLoad();
      self.view.transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1, tx: 0, ty: 0)
   }
}
```
