### ISSUE TITLE
Consider providing an ASVideoNode.

### ISSUE THREAD

**Issue by secretiverhyme** [facebook/AsyncDisplayKit#255]
This could wrap AVPlayerLayer, which has tricky performance characteristics (expensive to allocate and destroy, habitually blocks threads, etc.).

**Comment by ide** [comment]
Similarly AVCaptureVideoPreviewLayer would be useful for camera previews. There might be an opportunity for a richer node that controls the camera and runs all the AVFoundation code on a background thread.

It could also make sense to publish these auxiliary nodes as separate CocoaPods (or subspecs) so that programmers can exclude portions of ASDK they don't need and reduce compile times, binary sizes, all that good stuff.

**Comment by secretiverhyme** [comment]
Agreed — a camera extension to this node would be worth considering, thanks for the suggestion!

Subspecs are on our radar, possibly for version 1.3 of the framework.  (@rnystrom and I were chatting about splitting out AsyncDisplayKitCore for the low level machinery and various UI subspecs for images, text, etc., but we haven't yet reached the point where the benefits would outweigh the maintenance costs.)

**Comment by toulouse** [comment]
I wrote substantial camera capture code (https://github.com/Basket/BKCameraController/blob/master/BKCameraController/BKCameraController.m and https://github.com/Basket/BKExample) and if @ide is okay with it perhaps we could take a look at integrating it into ASDK with the necessary modifications? I think it could exist in its own subspec/subfolder without substantial maintenance burden, unless you have specific concerns?

**Comment by secretiverhyme** [comment]
> perhaps we could take a look at integrating it into ASDK with the necessary modifications?

Sure, sounds worthwhile.

> I think it could exist in its own subspec/subfolder without substantial maintenance burden, unless you have specific concerns?

This is a tangent, but:  Facebook's source tree includes a mirror of the AsyncDisplayKit GitHub repository, along with some Facebook-only framework additions (e.g., custom logic for Paper's story strip).  All this is managed using a tool that's almost, but not quite, entirely unlike CocoaPods.  Keeping the two systems in sync with multiple subspecs will require some time to get right, so I'm holding off on splitting the framework until there's a definite advantage to doing so.  Filed #259 for further discussion.

**Comment by ide** [comment]
My current thinking is that parts of BKCameraController could be used in a camera display node though I think the API needs to be more generalized. There are a lot of iOS's image capturing functions (especially controls over focus, exposure, etc added in iOS 8) that aren't accessible. I think experimenting with a separate CocoaPod and working towards something shippable with ASDK is a good place to start.

If Instagram or VSCO were to build a camera component using ASDK we'd have a pretty good idea of what the API should look like and there would be a ton of interest to say the least.

**Comment by appleguy** [comment]
@lappp9 implemented this a few months ago, and it has gained new features and greater adoption ever since! There's a lot more to do with this component, but this task is done. I have filed a new issue in our regular task tracker to investigate binary size reductions and possible separation of a user interface component library to allow more selective inclusion of features.
