### ISSUE TITLE
Avoid creating placeholder image on the main thread.

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2620]
@appleguy has said that #2610 will likely cause a performance regression because placeholderImage is now being created on the main thread. We'll need to figure out how to avoid that while still checking the contents on the main thread *or* creating a thread-safe contents.

**Comment by appleguy** [comment]
So the great mystery is why this code worked since at least March without issues...in any case I will put up a PR shortly that should resolve the main performance issue.  This area has been due for some refactoring for some time, and my PR won't change that, but it'll allow us to read .contents in the case the node isn't loaded (since it's safe to do so at that time, and almost always will be nil).

**Comment by appleguy** [comment]
Diff is up, we can close this when #2651 is landed.

**Comment by appleguy** [comment]
This is fixed.
