### ISSUE TITLE
viewWillAppear called before layout occurs

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#2632]
Using layout layoutSpecThatFits: I set a breakpoint in both viewWillLayoutSubviews and inside of layoutSpec that fits and observe that layoutSpecThatFits is called first followed by viewWillLayoutSubviews.

**Comment by appleguy** [comment]
@KieranLafferty Can you include a backtrace or some screenshots? :)

Is the title of the task correct?  It says viewWillAppear, but did you mean layoutSpecThatFits?

**Comment by hannahmbanana** [comment]
@appleguy - isn't it expected behavior that `layoutSpecThatFits:` is called before `viewWillLayoutSubviews`?

**Comment by maicki** [comment]
@KieranLafferty @appleguy @hannahmbanana This is expected behavior. `layoutSpecThatFits:` Get's called in the measurement pass of the node, `viewWillLayoutSubviews` will be called in the layout pass of the node / view that happens after the measurement pass. Hope this makes it clear.

In the measurement pass `layoutSpecThatFits:` requests the layout specification to be able to create an `ASLayout` object that represents the node hierarchy. Based on this `ASLayout` all subnodes will be layed out in the layout pass that happens a bit later.

I will close this issue for now please reopen for follow up questions.

**Comment by KieranLafferty** [comment]
Oops, sorry for the bad description of the issue, updated the title. 

The situation I am trying to resolve is setting the appropriate navigation bar insets for the view using a layout spec.

I've added a UIEdgeInsets prop to my vc's view node and then call

```
- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];
    self.node.edgeInsets = UIEdgeInsetsMake(self.topLayoutGuide.length, 10.0, self.bottomLayoutGuide.length + 10, 10.0);
}
```

Then in layoutSpecThatFits: I do

```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    ...
    return [ASInsetLayoutSpec insetLayoutSpecWithInsets:_edgeInsets
                                                  child:spec];
}
```

**Comment by hannahmbanana** [comment]
@KieranLafferty - I think the answer depends on your UI. Are you using a scroll view? Do you want the content to be able to go under the nav bar or not?

**Comment by adamtait** [comment]
What's the best way to get an ASViewController to layout below the nav bar?

**Comment by appleguy** [comment]
It is expected for layoutSpecThatFits to be called before the other layout
methods.

ASVC is just like any other view controller -- I think it is
edgesForExtendedLayout that you want to ensure is set to None.

If you have any other questions, please move this issue to the Texture
project (and close this one in any case). Have a great weekend!
