### ISSUE TITLE
Insertion/Deletion animation on ASCollectionNode

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#2661]
Using a regular UICollectionView it's possible to change the animation timing/curve for inserting/deleting cells by doing the following: 

        [UIView animateWithDuration:0.3
                              delay:0.0
             usingSpringWithDamping:0.7
              initialSpringVelocity:0.0
                            options:UIViewAnimationOptionCurveEaseInOut
                         animations:^{
                             [_collectionView insertItemsAtIndexPaths:@[indexPath]];
                         } completion:^(BOOL finished) {
                             
                         }];

However, since the ASCollectionNode delegates to the ASCollectionDataController the insert action isn't captured within the block and does not impact the animation of the insertion. 

Any known workaround for this?

**Comment by Adlai-Holler** [comment]
@KieranLafferty Interesting – this behavior must be somewhat new because I believe UICollectionView previously always applied its standard animation timing.

For the time being, you can call `waitUntilAllUpdatesAreCommitted` inside the animation block and it should behave the same as UIKit. Note that this will block the main thread while the nodes for the new items are created and measured. Let me know how it goes!

**Comment by KieranLafferty** [comment]
Thanks!
