### ISSUE TITLE
CatDealsCollectionView example : No visible @interface for 'ASCollectionNode' declares the selector 'insertItemsAtIndexPaths:'

### ISSUE THREAD

**Issue by gurhub** [facebook/AsyncDisplayKit#2667]
I'm getting this error in CatDealsCollectionView example :

`/Users/****/AsyncDisplayKit/examples/CatDealsCollectionView/Sample/ViewController.m:121:24: No visible @interface for 'ASCollectionNode' declares the selector 'insertItemsAtIndexPaths:'`

here is my podfile : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target 'Sample' do
        pod 'AsyncDisplayKit'
end
```

**Comment by Adlai-Holler** [comment]
Hey @gurhub , since your podfile specifies `pod 'AsyncDisplayKit'`, CocoaPods is going to assume you want the most recent production version i.e. 1.9.90. The example code is meant to be paired with the same version of the framework that it is bundled with i.e. 2.0. `ASCollectionNode insertItemsAtIndexPaths:` was added for 2.0, and then it was added into the example code after that.

The Podfile that ships with CatDealsCollectionView looks like:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target 'Sample' do
	pod 'AsyncDisplayKit', :path => '../..'
end
```

Which pulls in the corresponding framework version from the working directory. It's important we keep those in sync. What's the use case/objective you desire, that you removed the `:path` specifier?

**Comment by hannahmbanana** [comment]
@gurhub - I'm going to close this, but please reopen if the fix suggested above does not work!

**Comment by gurhub** [comment]
Thank you @hannahmbanana. I'll follow the other issue.
