### ISSUE TITLE
Bug in ASTextNode when switching device orientation

### ISSUE THREAD

**Issue by szmathew** [facebook/AsyncDisplayKit#2734]
Hi guys,

our team discovered a strange bug appearing in some of our ASTextNodes located in an ASCollectionView. They contain a text, which is aligned CENTERED.

When we open another View, switch to landscape mode, press the back button to go back and simultaneously switch to portrait mode again, the text will be aligned LEFT as in the image below.

<img src="https://cloud.githubusercontent.com/assets/24455855/21014303/c06ca566-bd5d-11e6-8a35-621573d1b8e9.png" width="250">

The green part is the background of our ASTextNode. 

The bug appears on all our testing devices (e.g. iPhone 6 with iOS 10, iPhone 7 with iOS 10.1)
The AsyncDisplaykit-Version we currently use is 1.9.90, but the bug also appears in 1.9.92.
The programming language is Swift.

The bug seems to occur in ASTextNodes, which are not displayed yet - that means we have to scroll down first after pressing the back button to see the issue.

**Comment by hannahmbanana** [comment]
I wonder if this is related to #2677.

**Comment by hannahmbanana** [comment]
@szmathew - would you be willing to [upgrade to 2.0](http://asyncdisplaykit.org/docs/adoption-guide-2-0-beta1.html) and see if this is still an issue? So much has changed since 1.9.92. :) We are planning on releasing the final 2.0 cut later today (right now we're at RC 2). It's been tested for over a year at scale with Pinterest's app. 

Otherwise, it would be awesome if you could attach a sample project showing the issue. :)

**Comment by hannahmbanana** [comment]
@szmathew - I believe this issue is the same as #2677, which was resolved recently. Please re-open this issue if you are still seeing this bug.
