### ISSUE TITLE
How to add a Progress View inside ASCellNode ?

### ISSUE THREAD

**Issue by modLX4** [facebook/AsyncDisplayKit#2740]
Cannot figure out what wrong with this code
[LearnAsyncDK 2.zip](https://github.com/facebook/AsyncDisplayKit/files/642240/LearnAsyncDK.2.zip)

**Comment by hannahmbanana** [comment]
@modLX4 - were you able to resolve this issue?

**Comment by hannahmbanana** [comment]
`M13ProgressViewBorderedBar` is a `UIView` subclass. `UIViews` are limited to running on the main thread, whereas ASDK's `ASCellNode` nodes can run on a background thread. The `FeedCellStyleVote` `-init` method may be run before the node has had its view created. Thus, you shouldn't access `self.layer` in this method. Check out the [subclassing](http://asyncdisplaykit.org/docs/subclassing.html) documentation for more info.

When using views within an ASDK node, you have 2 options:

1. Create a node from the UIView by using the `-initWithViewBlock` initializer method on a node. A benefit of this is that the view can participate in the -`layoutSpecThatFits:` layout API via it's node. You MUST set some sort of size on the node - e.g. `node.style.preferredSize` or similar sizing option. ***(preferred)***

2. Create the view in the `-didLoad` method. Add it with `[self.view addSubview:<the view>]` and you will need to do manual layout by implementing the `-layout` method. ***(second best)***

Due to the length in time since this issue was active, I'm going to close this thread. Feel free to re-open this issue or another one if you have further questions. I hope you have enjoyed using the framework!
