### ISSUE TITLE
[2.0] ASSizeRangeMake is not friendly with CGFloat_MAX

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2770]
Code like below, always give me assert, but is quite normal to layout a textNode with size which has certain width & uncertain height?

```
CGSize textSize = [self.textNode layoutThatFits:ASSizeRangeMake(CGSizeMake(100, CGFLOAT_MAX))].size;
```

**Comment by IvanChan** [comment]
Using calculateSizeThatFits instead

**Comment by IvanChan** [comment]
ASButton is still has this problem

**Comment by maicki** [comment]
@IvanChan Hey, ASDK throws an assertion in this css because you are passing in CGFLOAT_MAX as min and max size. You have to  remember, that what you are passing in is a size range and if you it in the way you do in your example what you basically pass in is:

`CGSize textSize = [self.textNode layoutThatFits:ASSizeRangeMake(CGSizeMake(100, CGFLOAT_MAX), CGSizeMake(100, CGFLOAT_MAX))].size;`

So you pass in  for min and max size a value of `CGFLOAT_MAX` what is not allowed. instead try this:

`CGSize textSize = [self.textNode layoutThatFits:ASSizeRangeMake(CGSizeMake(100, 0), CGSizeMake(100, CGFLOAT_MAX))].size;`

Furthermore never use `calculateSizeThatFits:` directly!

I will  close that issue for now, please reopen if this not fix your issue.
