### ISSUE TITLE
[Question] Difference between .preferredLayoutSize vs .flexBasis

### ISSUE THREAD

**Issue by jennibunny** [facebook/AsyncDisplayKit#2842]
Hi,

I still do not know when to use `.preferredLayoutSize` with percent % and `.flexBasis`. What is the main difference between those?

**Comment by hannahmbanana** [comment]
@jennibunny - This is a great question! I don't have a great answer for you, however, I can point out a few differences. 

`.flexBasis` - specifies the initial size for this object, in the stack dimension (horizontal or vertical), before the `flexGrow` / `flexShrink` properties are applied and the remaining space is distributed. 

- Because flexBasis only works in the stack dimension, which could be either horizontal or vertical, `.flexBasis` could control either the width or the height of a flex object. 
- As far as I know, `.flexBasis` also doesn't apply to absolutely-positioned items - e.g. ones in an `ASAbsoluteLayoutSpec`.
- `.flexBasis` gives an initial size (either width or height depending on the stack dimension), meaning that if .flexGrow or .flexShrink are enabled, that size could grow or shrink.

`.preferredLayoutSize`  -  Provides a suggested relative size for a layout element. An ASLayoutSize uses percentages rather than points to specify layout. E.g. width should be 50% of the parent’s width. If the optional `minLayoutSize` or `maxLayoutSize` are provided, and the `preferredLayoutSize` exceeds these, the `minLayoutSize` or `maxLayoutSize` will be enforced. If this optional value is not provided, the layout element’s size will default to its intrinsic content size provided `calculateSizeThatFits:`

I'll see if I can find more info on the difference between the two.

**Comment by hannahmbanana** [comment]
additional info from our layout spec expert @maicki: "The main and important point is that the `flexBasis` value is considered while calculating the frame for the node that also involves `flexShrink` and `flexGrow`. Just using `width` / `minWidth` and `height` / `minHeight` this is not the case."
