### ISSUE TITLE
[Question] ASNetworkImageNode cache block should perform on thread if URL is nil?

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2872]
**@discussion If `URL` is nil, `completion` will be invoked immediately with a nil image. This method should not block
 the calling thread as it is likely to be called from the main thread.**

 ```
- (void)cachedImageWithURL:(NSURL *)URL
             callbackQueue:(dispatch_queue_t)callbackQueue
                completion:(ASImageCacherCompletion)completion
```

I got a little bit confused by  **immediately**  and  **should not block**
which one is correct?
```
  if (!URL)
    {
        dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
            
            completion(nil);
        });
    }
```

or 

```
  if (!URL)
    {
            completion(nil);
    }
```

**Comment by Adlai-Holler** [comment]
@IvanChan The second one is correct. The documentation could be clearer, but what it means is "this method should not block the calling thread [while accessing the cache] as it is likely to be called from the main thread." Since there's no cache access if the URL is nil, it's OK to invoke the completion handler immediately. Cheers!
