### ISSUE TITLE
[Question] Using ASCellNode initWithViewControllerBlock for long lists

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#2900]
I've gotten into the habit of using initWithViewControllerBlock and creating cell view controllers that offload a lot of the work of the data source itself. 

Wondering if this is a reasonable thing to do in lists of 500-1000 items?

**Comment by appleguy** [comment]
@KieranLafferty let me know if you have more questions on this!  The answer, briefly, is:

- Yes this is OK to do because the view controller won't be created until the view is, so it won't make the 500 of them
- However it's not recommended because both a) there is extra overhead from UIViewController, and b) most importantly it will mean that you can't use layout specs to calculate the size of the ASCellNode
