### ISSUE TITLE
Add -indexPathForNode: method to ASTableView, ASCollectionView

### ISSUE THREAD

**Issue by duxinfeng** [facebook/AsyncDisplayKit#291]
Hi, there are indexPathForCell UITbaleView:  get indexPath method, in ASTableView how do I get？

 NSIndexPath *indexPath = [_tableView indexPathForCell:cellNode];
        [_tableView deleteRowsAtIndexPaths:[NSArray arrayWithObject:indexPath]                         withRowAnimation:UITableViewRowAnimationFade];

There indexPath = nil;

**Comment by tanliboy** [comment]
If would be better to save all the CellNodes in an array associated with data source, find the indexPath in the cellNode array, and do the editing.
As we do the layout in async mode, the indexPath in data source may not match the index path that is displayed in the UITableView.

**Comment by secretiverhyme** [comment]
@tanliboy, what do you think about adding a `-indexPathForNode:` method to ASTableView / ASCollectionView?  The ultimate goal of these classes is to let you use ASCellNodes as a complete replacement for UI{Table,Collection}ViewCells, including replacing cell-specific methods like the one here.

**Comment by tanliboy** [comment]
Yes, it sounds a good move. I will put it after resolving the group animation issues.

**Comment by tanliboy** [comment]
Thought for a while, after moving the data fetching to background, it will be confusion to implement this method. Because the "indexPathForRow" in data source, allocation queue, and UITableView might be totally different, considering we are adding the delay in the allocation and UI updating.
On another hand, user could always get the index path of data source in the application code. I would prefer to still keep it in the application code now.

**Comment by appleguy** [comment]
@duxinfeng This was added recently; thanks for the request!  Please file a new issue if you see any challenges using it.

**Comment by duxinfeng** [comment]
Thank you all.

**Comment by spronin** [comment]
@appleguy in 1.9.90 it is 
`- (NSIndexPath *)indexPathForNode:(ASCellNode *)cellNode;` for ASCollectionView, while it's
`- (nullable NSIndexPath *)indexPathForNode:(ASCellNode *)cellNode;` for ASTableView

The first one is incorrect since there is no nullability but it should be there, because it may return nil if no such nodes found

**Comment by maicki** [comment]
@spronin Hey, we would appreciate for an PR that would clean that up! Thanks!
