### ISSUE TITLE
How to update a ASCellNode?

### ISSUE THREAD

**Issue by modLX4** [facebook/AsyncDisplayKit#2919]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack

For example, In the following image of ASCellNode, Just want update the Weather Reading (i.e. - 26C)
What would be best way to do it without any performance overhead

<img width="409" alt="screen shot 2017-01-23 at 8 26 10 pm" src="https://cloud.githubusercontent.com/assets/12533332/22208827/43009df0-e1aa-11e6-9c91-ec7f646724ca.png">

**Comment by hashemp206** [comment]
all you need to do is make cell observe weather change, then if you expect the size of textNodes or cell will changes based on new text length, call `setNeedsLayout` after updating textNodes. also enable `layerBacked = true` in your cell, so creating the cell will be almost 5 times faster. because it doesn't need to detect touches

**Comment by hannahmbanana** [comment]
Thanks for the answer @hashemp206! @modLX4 - check out the ASDKgram example app for more info.

**Comment by modLX4** [comment]
Thanks @hashemp206 and @ hannahmbanana
