### ISSUE TITLE
Node wrapped in ASLayoutSpec doesn't show in StackLayoutSpec

### ISSUE THREAD

**Issue by jellenbogen** [facebook/AsyncDisplayKit#2927]
Hi Guys, 

I'm using ASDK 2.0 and I'm rewriting a few things to use automaticallyManagesSubnodes and I'm seeing some odd behavior when using custom nodes that return a node inside an ASLayoutSpec from layoutSpecThatFits. 

**What I'm doing:**
1. I have a container node who's layouSpecThatFits method returns a stack layout spec.
2. Inside this stack layout spec are 2 subnodes that each implement layoutSpecThat fits.
3. Both node types set automaticallyManagesSubnodes = true

**What I'm seeing:**
Within the stackLayoutSpec the node who returns an ASWrappedLayoutSpec from layoutSpecThat fits shows up, in the stack. The first node however who returns an ASLayoutSpec from layoutSpecThat fits does not. That is the only difference between the two nodes inside the stack.

Some help would be appreciated, its not blocking me or anything, it just caused a lot of head-scratching until i narrowed it down to using the ASLayoutSpec directly. Thanks!

I've created a test project you can look at. It's super basic but demonstrates what I'm seeing. 

[LayoutSpecThatFitsTest.zip](https://github.com/facebook/AsyncDisplayKit/files/726683/LayoutSpecThatFitsTest.zip)

**Comment by hannahmbanana** [comment]
@jellenbogen - thank you for providing a concise example project! 

I asked @maicki about this and he said that this is expected behavior, although we could definitely improve our documentation around this. 

`ASLayoutSpec` is essentially an abstract class, _except_ for its one use as a flexible spacer (when used with no children). If you want to use `ASLayoutSpec`, you'll need to subclass it and implement a few methods (see any of the other layout specs for an example of that. 

If you just need to return a single node from your `-layoutSpecThatFits:` method, then use `ASWrapperLayoutSpec` as you did.

**Comment by jellenbogen** [comment]
Ok cool, ```ASWrapperLayoutSpec``` it is then. Thanks for responding so quickly!
