### ISSUE TITLE
Question(s): calculateSizeThatFits/layout for nodes and nodes in views

### ISSUE THREAD

**Issue by andyscott** [facebook/AsyncDisplayKit#294]
So I've been using ASDK for a while now but I realized I have no firm answer to the following  questions:

1. Is it appropriate to have nodes with layout implementations that assume `measure`/`calculatedSizeThatFits` has been called first? I have been writing my layout code under this assumption. It seems to hold true for nodes already within a node hierarchy but not necessarily so for nodes nested directly in views.

2. When placing a node directly in a UIView, when should I call `measure` on the node? I tend to write my `calculatedSizeThatFits` methods such that calling it `measure` once at the top level will cascade calls down the node hierarchy.

3. If the node layout method relies on cached calculated sizes, is it okay for the layout method to call `measure` directly? Is this a good solution for nodes at the top of the async hierarchy? It seems wrong to write node layout code differently depending on where you think the node will sit in the hierarchy. I've avoided doing this, so far.

**Comment by kylehickinson** [comment]
ASFAIK:

1. You should assume that `calculateSizeThatFits`/`layout` will always be called
2. You should call `measure:` which will end up calling `calculateSizeThatFits` and setting the cached `calculatedSize`
3. See 2.

**Comment by andyscott** [comment]
That's what I've been doing so far. In the original post I mistakenly wrote `calculatedSizeThatFits` in a few places where I should have said `measure`.

**Comment by rnystrom** [comment]
@andyscott I would avoid calling `-measure:` unless your node sizes itself based on content. Typically you would create an `ASDisplayNode` subclass and override `-calculateSizeThatFits:`, like we do [here](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/KittenNode.m#L127-136). In there you should call `-measure:` on subnodes. If you follow this pattern, no matter how deep your hierarchy is you should be just fine.

Adding a node's backing view/layer to another UIView will set the layer as needing display, the display runloop will eventually call `display` on the `CALayer`, which triggers the node machinery to do the async process. So you shouldn't have to worry about calling `-measure:` yourself.

Also remember that some of the benefit of using ASDK is to both asynchronously render **and size**. If you call `-measure:` in `-viewWillLayoutSubviews` you're sizing on the main thread.

**Comment by secretiverhyme** [comment]
To sum up:

1.  ASDisplayNode `-layout` implementations should assume that `-measure:` has been called (on both `self` and all subnodes).  Measurement, layout, and rendering occur strictly in that order; if the measurement pass hasn't been completed, your node will be of size `CGSizeZero` anyway!  You should perform expensive work in `-measure:` and cache it for use in later passes — for example, ASTextNode sets up its TextKit component at measure-time and uses it for rendering.

2.  ASDisplayNode `-calculateSizeThatFits:` implementations **must** call `-measure:` on all subnodes — note that we can't automatically do this for you because we don't know what `constrainedSize` you'll pass into each subnode.  You can skip the measure step for image nodes, because they are typically statically sized and positioned, but in general not measuring your subnodes will lead to undefined behaviour (remember, you're supposed to do heavy lifting at measure-time and cache it for later!).

    Effectively measuring nodes at the view→node transition point is complicated — this is more or less the entire point of ASTableView and ASCollectionView!  If you need to measure multiple node hierarchies in parallel, you should use a working range.  Sizing a single node hierarchy more or less comes down to two cases:

    1.  If your node hierarchy is something the user will see immediately, you should measure it synchronously.  In this case, you actually *should* call `-measure:` in `-[UIViewController viewWillLayoutSubviews]`.  In an app like Instagram, which has five tabs, you would do this for the hierarchy corresponding to the first tab.

    2.  Otherwise, create and measure your node hierarchy on a background queue, then trampoline to the main thread to do `[self.view addSubnode:_nodeHierarchy];`.  You should ensure your nodes are measured before they're added to the hierarchy so that they can display realistic placeholders.  In the Instagram example, you would do this for the remaining four offscreen tabs.

3.  `-layout` should never call `-measure`, because the measurement → layout → rendering passes are always executed in that order.

The [AsyncDisplayKit guide](http://asyncdisplaykit.org/guide/) touches on all of these points if you'd like more details (e.g., [realistic placeholders](http://asyncdisplaykit.org/guide/3/)).  Hope this helps!  =]

**Comment by andyscott** [comment]
I've read the guide, but it was quite a while ago and I didn't recall seeing those subjects covered. Your answer is very helpful, so thank you!
