### ISSUE TITLE
Add Screenshots/GIFs to all example projects

### ISSUE THREAD

**Issue by fruitcoder** [facebook/AsyncDisplayKit#2953]
I am new to ASDK and when looking through the screenshots in /examples I wondered why there isn't a visual representation of every example. Also, there are screenshots like EditableText which is actually in examples_extra. 
1. Why are there two folders, is there any difference between them?
2. Could they be combined?

I would like to create screenshots/GIFs (if there is an animation in the example) to all the example projects. For newcomers it's especially useful to have a visual overview of the examples (especially because there are so many), before pod installing through every one of them.
Would it be okay if I add the screenshots?

**Comment by hannahmbanana** [comment]
@fruitcoder - I put in those screenshots early last year and a few examples have been added since then without updating the screenshots file. I wasn't sure if the screenshots were useful, so it's very cool to hear that you appreciated them. 

1. The `examples` folder contains the most relevant and up-to-date (using ASDK 2.0) example projects. The `examples_extra` folder contains more obscure, possibly out-of-date examples. This folder is not included in our build script.
 
2. To combine them, we'd need to make sure that all of the examples_extra projects pass the build. Also, we'd need a way to highlight the most relevant examples since there are quite a few (we could do this in the README file or on the website). 

If you'd like to update them for us, that would be very much appreciated!

**Comment by hannahmbanana** [comment]
You may want to also add whether the example project is in Swift or Obj-C to each description.

**Comment by fruitcoder** [comment]
It seems like a multistep procedure. I'll get back to you when I know what I can do. But I'll probably start making Screenshots+Swift/Objc info to the /examples readme

**Comment by fruitcoder** [comment]
#2968

**Comment by fruitcoder** [comment]
Comments on projects not included:

**ASDKTube**
Took html5 example video since the one referenced wasn't available

**AnimatedGIF**
As noted by someone in the Slack channel the image doesn't load (neither on simulator or device)

**SocialAppLayout-Inverted**
Error in `SocialAppLayout-Inverted` project: `inverted not found on tableNode`
