### ISSUE TITLE
RFC: Deprecating Rasterization

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#3018]
Supporting rasterized subtrees is a useful way to reduce memory consumption, and I'm proud that we've achieved it.

But I advocate deprecating support, for a couple of reasons:
- We see virtually _zero_ usage of it in Pinterest.
- It complicates our hierarchy tracking and drawing.
- Unit testing is pretty scant – not sure how it handles edge cases, makes refactoring tough.
- Modern hardware devalues memory conservation.
- We're integrating more with Core Animation's layout pass/validation system, so we need layers!

I feel strongly that this is the right direction for the framework, but I'd like to hear from the community their thoughts @ay8s @MarvinNazari @GitGadd @harryworld

**Comment by ay8s** [comment]
Not using it either in Buffer right now and not sure we'd see much benefit nowadays if we added it in. Only time we did try it, it caused a couple of issues with image loading etc. Think if it simplifies things then 👍

**Comment by GitGadd** [comment]
It's not used in Auxy either, and I think it's easy enough to handle the few really good cases for this manually. Sounds like a good call!

**Comment by harryworld** [comment]
StaySorted starts using ASDK lately, thus has no concern as well.

**Comment by MarvinNazari** [comment]
We don't use it either. 👍🏼

**Comment by appleguy** [comment]
I do have use cases for this with my current projects, but agree with deprecating the feature -- at least until a non-core-team engineer wants to put in the effort to make it more independent of the rest of ASDisplayNode so that maintainability of the core classes isn't made more difficult because of rasterization.

I think getting rid of the isInHierarchy system (it can be folded into the newer interfacestate / hierarchystate systems) will significantly help this, as currently the greatest coupling between rasterization and displaynode is in the hierarchy change handling code.

Optimized corners are also one of the most common usages, mentioned on Slack yesterday:

![image](https://cloud.githubusercontent.com/assets/565251/23107238/3c62a3ee-f6ae-11e6-823f-333481d22f15.png)
