### ISSUE TITLE
[RFC] Make ASHierarchyState More Flexible

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#3060]
Right now it's a plain `NS_OPTIONS` which is pretty limiting – we can only manage _flags_ in the hierarchy. It seems like an Objective-C++ struct would be appropriately flexible and fast. It would allow us to store objects (root node? Layout engine?) as well as other data types.

Thoughts @maicki @nguyenhuy @garrettmoon @appleguy ?

**Comment by appleguy** [comment]
My 2c can be summarized as: 1. Beware of UIView-style performance, 2. consider if there is a clean separation between flag distribution and object distribution, 3. and evaluate whether ASEnvironment can be upgraded to provide the desired featureset.

1. We should be very cautious with overhead here.  When we say that UIView is expensive, it turns out that almost all of its cost beyond CALayer comes from hierarchy management things like didMoveToWindow:, willMoveToSuperview:, etc.  If ASDK is doing memory allocations in addition to making calls while traversing, it could start to become more expensive than UIView itself quite quickly.
2. I think there's a valuable set of use cases that need just the 1 bit provided in things like ASInterfaceState and ASHierarchyState.  We should list out some near-term as well as hypothetical use cases for more sophisticated types of state distribution (objects, etc).
- For small numbers of use cases, I'd suggest we consider if it is appropriate to use PerformOnAllSubnodes and simply set a node.property = object.  This will be more efficient, and plausibly less complex particularly if we have only a handful of object types that get distributed.
3. Lastly, we should consider reviving ASEnvironment if we'd like to go in this direction. I think it is a very amazing and valuable system that was design specifically for this set of use cases. Profile-driven optimization lead us to convert it from C++ structures (objects) to C structs (copy-by-value / stack mem / embedded in the instance var storage of existing objects). However, if we wanted to bring back the C++ structs, the systems built for ASEnvironment provide excellent extensibility options.
