### ISSUE TITLE
[ASTableView] Cannot remove a visible ASCellNode until all nodes have been measured.

### ISSUE THREAD

**Issue by phatmann** [facebook/AsyncDisplayKit#309]
Calling `deleteRowsAtIndexPaths` on an ASTableView will block until all of its cell nodes are measured. In a table with 1000 cell nodes, this can be a significant delay. Instead it should only block until the visible cell nodes and the cell nodes that will be animated into view have been measured.

If the proposal in #258 were implemented, the impact of this problem would be greatly reduced. These are closely related issues but different enough to keep both issues open.

See my comments in #303 for more background on this issue.

**Comment by phatmann** [comment]
Per [this comment](https://github.com/facebook/AsyncDisplayKit/pull/303#issuecomment-74116925), the problem is that measuring is done in a queue, and the node removal is pushed to the end of the same queue. Some ideas:

1. Cancel all operations in the queue when a removal is requested.
1. Use a different queue for removal requests.

**Comment by tanliboy** [comment]
Hmm, it is an interesting problem.

>> Cancel all operations in the queue when a removal is requested.
We may end with data inconsistent if we remove the existing operations directly. 

>> Use a different queue for removal requests.
The insertion and deletion are correlated. If we insert 200 nodes, remove 100 nodes, and then insert another 100 nodes. Different operations order may lead to different result.

One way that I thought about is to abstract each insertion/deletion into operation block. For each operation block, we could define the priority, and define the "swap" operation for two operation block. When we try to push a operation block into the queue, we sort it by "priority" in bubble sort (we need to use new defined "swap" operation).
For example, we have operation blocks: I1, D1, I2, D2. Then we want to push a new operation block D3 with higher priority to be : D3', I1', D1', I2', D2'. Notice these operation block need to be updated while bumping D3 ahead. 
It seems to be doable but complicated.

**Comment by phatmann** [comment]
My suggestion is to wait until #258 is implemented and see if this issue is still a problem in practice. If not, we can close this and see if anyone complains :-) If it is still an issue, then a solution such as @tanliboy's is something to explore.

_A side note: one thing I love about the ADK team is their relentless drive to unblock the main thread. It is a damn hard problem but they have made incredible progress so far. My proof-of-concept app was so fast that I have permission to bring ADK into the production app. Woot!_

**Comment by appleguy** [comment]
@phatmann: if you are still using the framework, check out the nodeBlock*: API. It allows the dataSource to return a block created on the main thread specifically so that any data model objects may be pulled out and preserved consistency with the indexPaths, but the cell node objects are then allocated and initialized concurrently in the background and subsequently also measured concurrently. 

This is a significant improvement over the previous behavior, but does not fundamentally address the fact that edit operations will block on unfinished concurrent background operations. This use case is far more painful in UIKit as it will block the main thread for the entire duration, and take roughly twice as long to complete text sizing as it is not concurrent. For the time being, the best solution is to "virtualize" the dataSource and inform the ASTableView about a smaller number of objects and add more as they are needed. 

This is a reasonable feature request, but will involve a pretty significant amount of work for a benefit that will not be at all detectable for most application access patterns. I will log the request in our internal bug tracker, and am happy to help you optimize out these kind of bottlenecks if your application is still being negatively affected by them.

**Comment by phatmann** [comment]
@appleguy: thanks for the explanation. I agree that fixing this is not needed if overall measuring performance is fast enough.
