### ISSUE TITLE
[ASTextNode] Replace CPU image drawing of smart placeholders with backgroundColor layers

### ISSUE THREAD

**Issue by phatmann** [facebook/AsyncDisplayKit#310]
When doing some profiling for #303, I noticed that a large part of the measuring cycle was being consumed generating the placeholder image for my ASTextNodes. When I disabled the placeholder image, the measuring time was cut in half.

It seems like generating the placeholder image is taking as long (or longer) than displaying the actual text!

At the very least I suggest that we disable the placeholder image in ASTextNode by default. The next step is to change the placeholder image generation to not be so time intensive; e.g. do not use the text rectangles.

**Comment by rnystrom** [comment]
Thanks for the feedback!

Placeholders are drawn as soon as a node [is measured](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L469). You're right that w/ `ASTextNode`, it is pretty expensive. The reason its *more* expensive than rendering the text is that the `ASTextNodeRenderer` is warmed up by calculating lines and rects for the placeholder. So when it comes time to draw the text, the hard stuff is mostly done.

Once we create an allocation range that limits the total number of nodes that are initialized, you should see a significant performance gain.

On a side note, you are free to override `[-placeholderImage](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode%2BSubclasses.h#L341)` for `ASTextNode` and return a `UIImage` of your choosing (like a drawn grey box). We default to the text-rect boxes because it's pretty cool!

All of our perf profiling is done on the iPhone 4, and, even with the old device, async text placeholder rendering is still speedy.

**Comment by phatmann** [comment]
Thanks for the fast and detailed reply. Getting your insight and justification for the design decisions is incredibly valuable.

So are you saying that the _overall_ time for measuring and displaying text is the same whether placeholder images are shown or not?

And as you allude to, the measuring cycle is blocking certain operations in ASTableView, so a longer measuring cycle that then leads to a shorter display cycle is still an issue. At least for now.

**Comment by rnystrom** [comment]
That's right, overall time should be pretty similar. Actually [drawing](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L687-707) the placeholder still incrues some cost, but it shouldn't be a ton. I haven't done profiling on this myself, but I wouldn't expect to see much variance using `ASTextNode` with and without placeholders. (If you do profile this, we would *love* to see results, even if I'm wrong!!)

And you're right, measuring everything is definitely an issue when you're dealing w/ tons of nodes. When we create the allocation range (i.e. only init *n* nodes +/- the visible range), there should be a huge perf win. This is high on our list #258.

**Comment by appleguy** [comment]
@phatmann hey, sorry it took literally months for me to reply here :).  I recently turned off placeholderEnabled by default on ASTextNode because of this.  You're absolutely right that there is some significant cost here.

My original intent for the text placeholder implementation was to use individual CALayers, with simple .backgroundColor values to avoid any memory allocation / backing stores as well as CPU drawing with CoreGraphics (both of which are happening with the current implementation).  There would be a way to do this super-efficiently by reusing a cache of CALayers maintained at the ASTextNode class level, where as soon as a node is finished rendering / can remove its placeholder state, the layers are tossed back in for reuse.  Layers are so vastly faster than views to add and remove (as well as create + destroy) that I'm pretty convinced this would be an extremely low overhead solution for this feature.

I'm going to repurpose this task to track implementing that improvement.  If anyone from the community can jump on this, I think it would be a pretty fun project :)

**Comment by appleguy** [comment]
@phatmann - thanks for suggesting this improvement! I'm going to move it to our new issue tracker. 

The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
