### ISSUE TITLE
[ASTextNode] Improve documentation on using links

### ISSUE THREAD

**Issue by toulouse** [facebook/AsyncDisplayKit#32]
```objc
- (void)textNode:(ASTextNode *)textNode tappedLinkAttribute:(NSString *)attribute value:(id)value atPoint:(CGPoint)point textRange:(NSRange)textRange
{
    if (_linkClickedBlock) {
        if ([value isKindOfClass:[NSURL class]]) {
            _linkClickedBlock((NSURL *)value);
            return;
        } else if ([value isKindOfClass:[NSString class]]) {
            NSURL *url = [NSURL URLWithString:value];
            _linkClickedBlock(url);
        }
    }
}

- (BOOL)textNode:(ASTextNode *)textNode shouldHighlightLinkAttribute:(NSString *)attribute value:(id)value
{
    return NO;
    // Test with:
    // return [attribute isEqualToString:NSLinkAttributeName];
}
```

Text node is configured as such (code from just before `NSLink` was made a default link attribute):
```objc
        ASTextNode *textNode = [[ASTextNode alloc] init];
        textNode.delegate = self;
        textNode.linkAttributeNames = @[NSLinkAttributeName];
        textNode.opaque = YES;
        textNode.userInteractionEnabled = YES;
```

Breakpoint configured for the first delegate method is never hit unless the link is also highlight-able.

**Comment by appleguy** [comment]
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
