### ISSUE TITLE
Title of ASButton with UIButton backed view, doesn't change

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#3221]
here it is:
``` swift
mapBtn = ASButtonNode { () -> UIView in
            let mapButton = UIButton(type: .system)
            mapButton.frame = CGRect(x: 0, y: 0, width: 40, height: 30)
            mapButton.contentHorizontalAlignment = .right
            
            mapButton.addTarget(self, action: #selector(self.mapBtnTapped(_ :)), for: .touchUpInside)
            return mapButton
        }
```

later:
``` swift
self.mapBtn.setTitle("city name", with: nil, with: nil, for: .normal)
```

it has no effect on ASButton.
its title doesn't change!

any idea?

**Comment by maicki** [comment]
@hashemp206 We don't call thought to the `UIButton` in this case. Embedding an `UIButton` in a `ASButtonNode` is currently not supported and should act kind of the same way if you would just embed it within a `ASDisplayNode`. Curious why do you want to embed a `UIButton` within an `ASButtonNode`?

**Comment by hashemp206** [comment]
what I want is default touch highlight of UIButton. ASButton doesn't have touch highlight indicator.

**Comment by maicki** [comment]
@hashemp206 Why not wrapping it than in a normal `ASDisplayNode`?

**Comment by hashemp206** [comment]
I wanted that result type be a UIControl not ASDisplayNode. so I can later change its target/action.
If touch highlight option is not feasible right now, you can close the issue

**Comment by maicki** [comment]
Hey, I think I know what is going on. Currently why `ASButtonNode` is not passing through the touches is that it has `userInteractionEnabled` to false if no target was added to it. This property will be bridged through to the view that is backing it what is in your case a `UIButton`.

As said above instead of wrapping your `UIButton` in a `ASButtonNode` why not wrapping it in a `ASDisplayNode`?

Something like that (maybe you have to tweak it a bit it's written down without having an example project setup yet):
```
let mapBtnNode = ASDisplaynode { () -> UIView in
          let mapButton = UIButton(type: .system)
          mapButton.contentHorizontalAlignment = .right
          mapButton.addTarget(self, action: #selector(self.mapBtnTapped(_ :)), for: .touchUpInside)
          return mapButton
        }
mapBtnNode.style.preferredSize = CGsizeMake(40, 30)

// Later
let mapButton  = mapBtnNode.view as! UIButton
mapButton.setTitle("title", forSate:.Normal)
```
