### ISSUE TITLE
It looks like ASImageNode ignores constrained size. Is this intended?

### ISSUE THREAD

**Issue by jonahneugass-ck** [facebook/AsyncDisplayKit#328]
Looking at ASImageNode.mm, I am seeing this:

    - (CGSize)calculateSizeThatFits:(CGSize)constrainedSize
    {
      ASDN::MutexLocker l(_imageLock);
      if (_image)
        return _image.size;
      else
        return CGSizeZero; 
    }

It looks like the constrained size is being completely ignored. Is this intended?

**Comment by secretiverhyme** [comment]
Thanks for the report!  Yes, this is intentional.

Images are typically positioned and sized independently of their contents' actual size — for example, ASNetworkImageNode doesn't even *know* its image's size at display-time, and ASMultiplexImageNode starts out with a much smaller image size than its final state.

As such, it's a standard pattern to not call `-measure:` on image nodes, instead using static layouts like…
* profile picture:  always 150⨉150pt
* photo in newsfeed story:  always a square, with width equal to "supernode's width minus padding"
* fullscreen photo:  always the size of the device's screen
