### ISSUE TITLE
[ASTextNode] Support NSDataDetectors

### ISSUE THREAD

**Issue by toulouse** [facebook/AsyncDisplayKit#33]
[Quote](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSRegularExpression_Class/Reference/Reference.html) from Apple docs:
> NSRegularExpression is designed to be immutable and thread safe, so that a single instance can be used in matching operations on multiple threads at once. 

UITextView property signature:
```objc
@property(nonatomic) UIDataDetectorTypes dataDetectorTypes
```

NSDataDetector factory method signature:
```objc
+ (NSDataDetector *)dataDetectorWithTypes:(NSTextCheckingTypes)checkingTypes error:(NSError **)error;
```

NSDataDetector's supported `NSTextCheckingTypes`:
> NSTextCheckingTypeDate, NSTextCheckingTypeAddress, NSTextCheckingTypeLink, NSTextCheckingTypePhoneNumber, and NSTextCheckingTypeTransitInformation

`UITextView`'s accepted `UIDataDetectorType`:
```objc
UIDataDetectorTypePhoneNumber   = 1 << 0,
   UIDataDetectorTypeLink          = 1 << 1,
   UIDataDetectorTypeAddress       = 1 << 2,
   UIDataDetectorTypeCalendarEvent = 1 << 3,
   UIDataDetectorTypeNone          = 0,
   UIDataDetectorTypeAll           = NSUIntegerMax
```

So basically, a very close correspondence in API. Seems like a pretty manageable add-in.

**Comment by appleguy** [comment]
@toulouse @ocrickard - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
