### ISSUE TITLE
[ASControlNode] Add locking for event dispatch table.

### ISSUE THREAD

**Issue by cfcommando** [facebook/AsyncDisplayKit#330]
No property lock or anything, just straight-up usage

**Comment by appleguy** [comment]
@cfcommando sorry this is taking so long; fortunately, in nearly all use cases, the object will have its targets and actions added during the initialization process (always single-threaded). It is incredibly rare to see concurrent access to target / action information in a real application, as they do not frequently change and only the main thread triggers the events.

However, this is not a good reason to leave out locking in this class, especially because it is a core component of the framework. We will make sure it is added soon

@maicki since you are familiar with this code from recent work, could you add a MutexLocker similar to how they are used in classes like the text, image, and display nodes?

**Comment by appleguy** [comment]
@cfcommando this work was completed, Let me know if you spot any other deficiencies. If you're still actively using framework, it would be great to see you on our slack channel! Send me an email if you want to invite.
