### ISSUE TITLE
[ASCellNode] Cannot change separatorInset

### ISSUE THREAD

**Issue by mtitolo** [facebook/AsyncDisplayKit#331]
Since ASCellNode doesn't inherit from UITableViewCell, there's no way to modify the separatorInset on a cell-by-cell basis. This should be configurable just like selectionStyle and backgroundColor.

**Comment by secretiverhyme** [comment]
Come to think of it — I didn't add this when originally plumbing through `selectionStyle` and `backgroundColor` because UICollectionViewCell doesn't have a separator (or a text label, or an image view, or …), and ASCellNode is intended to be drop-in compatible with both ASTableView and ASCollectionView.  I also seem to recall iOS 7 and 8 handling `separatorInset` inconsistently.

Since hairline views are so easy to create, and doing it manually allows for more flexibility, it doesn't seem worthwhile to support this in ASCellNode.  It may be worth adding auto-layer-backed hairline nodes to the base cell node, which would support ASCollectionView.

**Comment by lxcid** [comment]
Yes, I can confirm that iOS 7 and 8 handle `separatorInset` inconsistently. In iOS 8, they introduce a new `layoutMargin` in `UIView` which causes issue with `separatorInset `.

I don't fully understand `layoutMargin` behaviour yet but I know that if you are having trouble getting `separatorInset` to work, you might want to tweak that as well.

I, too, find that it creating my own hairline view is a saner a better solution.

**Comment by KevinVitale** [comment]
I'm just dipping into ASDK; can someone more clearly explain the strategy for adjusting/fudging the `separatorInset` on `ASCellNode` and subclasses? I'm on iOS 9.

**Comment by nguyenhuy** [comment]
@KevinVitale Sorry for this late response. The answer to your question is that `ASCellNode` currently doesn't support `separatorInset` and probably will never do. Instead, you can always create a hairline node, add it your cell node and style it. It's a bit more work but will give you much more control and will always work as expected across iOS versions.

Thanks everyone for the healthy discussion here. Another argument is that UITableView is slowing fading away (for good, IMHO). Let's not support `separatorInset`.
