### ISSUE TITLE
Case of data source being released prematurely when async

### ISSUE THREAD

**Issue by weibel** [facebook/AsyncDisplayKit#385]
When testing the datasource in async mode I consistently ran into the following assertion within ASTableView.mm 

> 'NSInternalInconsistencyException', reason: 'invalid node class, expected ASCellNode'

I dug around for some time and it turned out I by mistake allocated the tableview two times in a row (first from a storyboard segue, then in code after dispatching to the main thread), hence releasing the first instance quite fast. This meant the data source would be deallocated before entering  ```- (ASCellNode *)dataController:(ASDataController *)dataController nodeAtIndexPath:(NSIndexPath *)indexPath ```

Normally people would not deallocate this fast,  but there might still be a possible problem inside ```performDataFetchingWithBlock```.  We dispatch to the public queue when running in async mode. However it seems like it's possible to deallocate the data source before entering the queued block. The data source has a weak reference and if the tableview is deallocated before the block runs the data source will most likely be gone.

I'm on the current master (1dc4b42dce8c7eaaf3f2ad4cff70a0a35274bb9f)

**Comment by appleguy** [comment]
This code has been radically refactored as of yesterday.  Also, a couple months ago, proper support for initWithCoder: for ASTableView was added (it was not present before since using Interface Builder with ASDK is not really a great match).  Lastly, there was a deallocation / teardown issue found even earlier, I think in April, that resulted in a diff which fixed an issue very similar to this.

Thank you for reporting, and please do file another issue if you see this problem or any other one in the future!
