### ISSUE TITLE
Updating a subnode of an ASCellNode

### ISSUE THREAD

**Issue by jonahneugass-ck** [facebook/AsyncDisplayKit#390]
So I have an ASDisplayNode as a subnode of an ASCellNode that denotes whether or not the node has been seen by the user. I use didEndDisplayingNodeForRowAtIndexPath to determine if the cell has been seen, but how do I update the cell to remove the "Unseen" display node. I am trying to use

    [self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];

But I get really weird results when I scroll and eventually a crash with the error

    'The data source has already been locked'

**Comment by smeis** [comment]
When the user is scrolling the reloadRowsAtIndexPaths: method will be called in rapid succession, this causes the crash. When you update ASCollectionView or ASTableView the datasource will be locked, in the current implementation there will be a crash if you attempt to lock the datasource multiple times in a row. It's a bug (#369), it hasn't been fixed yet because it hasn't been decided wether or not the locking mechanism will stay in place (see #338 for discussion).

**Comment by appleguy** [comment]
@smeis thanks again for this report; please try again, and I'm pretty confident this is resolved.  If you can still cause an issue, can you try modifying ASTableViewStressTest (in the examples/ directory) to reproduce it, and I'll investigate?

**Comment by smeis** [comment]
Yes will do @appleguy!
