### ISSUE TITLE
Support exclusion paths on ASTextNode.

### ISSUE THREAD

**Issue by tberman** [facebook/AsyncDisplayKit#394]
Without this, it is hard to use it to replace all uses of UITextView, where the NSTextContainer/etc are exposed and usable.

**Comment by secretiverhyme** [comment]
ASTextNode abstracts away its Text Kit components because it relies on Text Kit — for example, client code is not permitted to set exclusion paths, because the text node uses them internally for truncation support.  We can certainly expand ASTextNode's APIs, though.  What use cases did you have in mind?

**Comment by tberman** [comment]
I am using exclusion paths to create empty areas in a text layout and then putting other UIView/ASDisplayNode subclasses into those empty areas.

I could instead use multiple ASTextNodes, which works (but isn't fun to maintain) in some of the cases (when the empty area spans the width of the device), but is pretty awful in others.

**Comment by appleguy** [comment]
@tberman Thanks for filing this task!  We just merged @tonklon's diff to address this.  Wish we got to it sooner, but I expect it will be useful to others with advanced text needs as well.
