### ISSUE TITLE
[ASCollectionView reloadSections:] crash

### ISSUE THREAD

**Issue by chicherin** [facebook/AsyncDisplayKit#416]
I show my sectionHeader (UICollectionElementKindSectionHeader) if object.count > 0. When array is modified I call this code:
```
// self.collectionView is ASCollectionView

if (needShowHeader != self.headerIsVisible) {

    self.headerIsVisible = needShowHeader;
    [self.collectionView reloadSections:[NSIndexSet indexSetWithIndex:self.sectionIndex]];
  } else {
     if (self.deletedIndexPaths.count > 0) {
        [self.collectionView deleteItemsAtIndexPaths:self.deletedIndexPaths];
      }

      if (self.insertedIndexPaths.count > 0) {
        [self.collectionView insertItemsAtIndexPaths:self.insertedIndexPaths];
      }
  }
```
"reloadSections:" method implementation:
```
// sorting indexPaths
  dispatch_async([ASDataController sizingQueue], ^{
    [self syncUpdateDataWithBlock:^{
      // remove elements
      NSArray *indexPaths = ASIndexPathsForMultidimensionalArrayAtIndexSet(_nodes, sections);
      DELETE_NODES(_nodes, indexPaths);
    }];

    // reinsert the elements
    [self _batchInsertNodes:updatedNodes atIndexPaths:updatedIndexPaths];
  }); 
```
After call "reloadSections:" method -[FPCompanySectionCollectionDataSource collectionView:layout:referenceSizeForHeaderInSection:] returns CGSizeZero and collectionView crashes:
```
2015-04-03 11:18:07.964 CatalogVL[2738:354308] *** Assertion failure in -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:], /SourceCache/UIKit/UIKit-3318.93/UICollectionViewData.m:866
2015-04-03 11:19:12.218 CatalogVL[2738:354308] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionHeader at path <NSIndexPath: 0x17c67b10> {length = 2, path = 0 - 0}'
*** First throw call stack:
(0x2be4d5a7 0x39b6bc77 0x2be4d47d 0x2cb485a9 0x2f4bda55 0x2f971955 0x2f510631 0x2f50d61f 0x2f50bb2d 0x246d5d 0x298673 0x269873 0x2984e1 0x24d369 0x24a84f 0x3a0e43a9 0x3a0d6c6f 0x3a0e2553 0x2be13891 0x2be11fb1 0x2bd5eb51 0x2bd5e963 0x332c41a9 0x2f3b0c91 0x86411 0x3a114aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
Signal: 6 (signal SIGABRT)
```

Why you don't use [UICollectionView reloadSection:] method in ASDataController? Can you implement a forced recalculation cell size?

**Comment by appleguy** [comment]
@chicherin Thank you for reporting this.  The ASDK on master does implement -[ASCollectionView reloadSections:] (note it is plural and takes an NSIndexSet, not a single NSIndexPath, just like UICollectionView).

Could you try this out (change your pod spec to use ASDK master) and confirm that it works as you would expect?  It's our fault that the stable version of ASDK has not been updated in quite some time despite significant improvements on master; confirming that this does address your issue will help us build confidence in bumping the stable version.

**Comment by morgan-buzinga** [comment]
I'm having the same issue; but I'm not sure the steps to take to use ASDK master (rather than the 1.1.1 tag).

**Comment by nguyenhuy** [comment]
@morgan-buzinga if you're using cocoapods, it's pretty easy. Detailed guide can be found [here]( https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo).

**Comment by chicherin** [comment]
@appleguy I made simple app for demonstrate crash: 
https://www.dropbox.com/s/z3uol5oxsjirjfc/AsyncCollectionViewTest.zip?dl=0

**Comment by appleguy** [comment]
Thanks for providing the test app, @chicherin!  I'm now using it as my next target to chase down any remaining oddities here.  My extensive testing and refactoring has been based primarily on ASTableView because it is more commonly used, and I have an ASCollectionView version of my test case that I am going to publish soon, but I'm actually quite happy to see that your test case is still able to crash 1.2.2.  This means I have a reproducible case to root out any remaining issue (which is likely collection view-specific).

**Comment by appleguy** [comment]
@chicherin sorry for the delay here, but I have rerun your test app on the latest master and have confirmed that the issue is resolved. I even increase the frequency of the timer by 20 times, reducing the interval to 0.05.  I did have to remove way that you integrated supplementary views, because it is not compatible with the frameworks' collection view, which expects supplementary nodes. This is unrelated however end is more in API usage thing, which I will follow up on ensuring is better documented so that a programmer who wrote code like this gets clearer feedback.
