### ISSUE TITLE
Swift: ARC forbids Objective-C objects in struct

### ISSUE THREAD

**Issue by WEIHOME** [facebook/AsyncDisplayKit#436]
After using CocoaPods 0.36.4 to add AsyncDisplayKit into project, I run the project then below Swift Compiler error comes up in ASTestNodeTestKitHelper.h (AsyncDisplayKit version (1.1.1)):

```
typedef struct {
  NSTextStorage *textStorage;  // ARC forbids Objective-C objects in struct
  NSTextContainer *textContainer;
  NSLayoutManager *layoutManager;
  UITextView *textView;
} ASTextKitComponents;
```

I am using Xcode Version 6.3 (6D570) with Swift 1.2 and iOS 8.3 as Deployment Target

Below is my Podfile:
```
platform :ios, '8.0'
use_frameworks!
pod "AsyncDisplayKit"
```

**Comment by appleguy** [comment]
@WEIHOME, thanks for reporting this.  I looked at the code and confirmed that in master, this has been revised so that ASTextKitComponents is a regular object type instead of a struct.  Can you try changing your podspec to build against master to confirm it is eliminated?

Sorry for the delay — we will get a new stable version out as soon as possible.
