### ISSUE TITLE
[ASTableView] crash when update the section header

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#454]
Since `	- (CGFloat)tableView:heightForHeaderInSection:`is called on main thread, but I will reload tableview's data and modify the `_array` on the background thread. Then it will cause crash.

	- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
	{
	    if (_array.count > 0) {
	    	UIView * header = [UIView alloc]init];
	        return header;
	    }else{
	        return nil;
	    }
	}
	- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
	{
	    if (_array.count > 0) {
	        return 42.f;
	    }else{
	        return 0.f;
	    }
	}

![2015-05-18 3 03 26](https://cloud.githubusercontent.com/assets/1837609/7676525/2d4aec86-fd77-11e4-8fe4-a2e9e4c890c5.png)

**Comment by yufenglv** [comment]
I found even I reload tableview's data on main thread, and modify _array on main thread, it also crash sometimes.The crash log is the same as above.

**Comment by appleguy** [comment]
@yufenglv thanks for this report.  Are you using asyncDataFetching on ASTableView?  Please check — it could cause an issue like this, and try it out with NO.  Also confirm that you're using ASDK v1.2 (I think it may have been finalized after you made this post, so unless you had been using ASDK master, you probably need to update).

I would love to help you debug this problem if you can reproduce it after updating to v1.2 and disabling asyncDataFetching.  Even if that fixes it, let me know!

**Comment by appleguy** [comment]
@yufenglv - thanks for contributing to the AsyncDisplayKit community by reporting your issue here. Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it. I'm curious if you were able to reproduce this issue on a later version of ASDK.

I hope you have been able to use the framework in your endeavors!
