### ISSUE TITLE
reloadSections(_, withRowAnimation:_) does not reload the section header view

### ISSUE THREAD

**Issue by mjgaylord** [facebook/AsyncDisplayKit#469]
I am using an `ASTableView` that consists of multiple sections. Each section consists of a reusable `UITableViewHeaderFooterView` and a list of rows. In the past, in order to update data inside the section header view, I would call `reloadSections` on the table view for the sections I wanted to update and it would update but in ASDK this is not the case. 

The table view delegate callback: `func tableView(tableView: UITableView, viewForHeaderInSection section: Int) -> UIView?` is not invoked which is telling me only the section contents are reloaded, not the header.

Is this a bug or is there a different way (short of reloading the entire table) to reload the section header view?

**Comment by appleguy** [comment]
Thanks for this report.  I have not tested this behavior, but AsyncDisplayKit does very little (if anything) to section headers and footers, as they remain standard UIViews.  It is definitely possible however that we are intercepting or not forwarding one of the calls you're expecting.

It would be helpful to have more details on what you are doing with the header (e.g. what exactly you are updating) and I might be able to recommend a better structure for ensuring it updates in the manner you want, without calling a -reload-type method.  Calling reload is fairly expensive for tables and it is especially expensive for AsyncDisplayKit because it throws out a bunch of calculated layout caches.  So while we should definitely fix the issue here so that it behaves as you had been expecting, it seems likely to me that you don't really want to use the callback for this purpose in an ideal case.

**Comment by mjgaylord** [comment]
Thanks @appleguy. We are basically trying to pin a section header to the top of the table as the user scrolls. Sometimes the header has information that needs to be reloaded. (Post title, username, privacy attributes etc.) An example of this would be the behaviour Instagram has in their feed. We have thought about removing sticky section headers, and just using a collection view, but this is quite a lot more work since they need to then be incorporated into the datasource differently. If this is the only/best solution though, we are prepared to go down this route, I was just hoping there was a quick fix I was missing.

**Comment by ryanfitz** [comment]
I also have an `ASTableView` with a pin to top setup and I've found that reloading sections and / or index paths does not currently work with `ASTableView`. However, I have found that deleting and inserting sections does work. I use this as a workaround to refresh rows when needed.

@mjgaylord I created a [ASTableViewManager](https://gist.github.com/ryanfitz/a79a5cae9501e9fb0698) class to help with a couple common tasks I need throughout my app. It might be of some help showing you how I handle adding / removing / moving rows.

**Comment by mjgaylord** [comment]
@ryanfitz thanks for the tip. It does indeed work.

**Comment by jaichaudhry** [comment]
@ryanfitz The way you suggested. Won't it do the work of reloading the nodes anyways. (Say when I have only one section and all my rows are in it.)
Because when you delete and then reinsert the section the datasource is anyways invoked for getting the nodes.

**Comment by ryanfitz** [comment]
@jaichaudhry correct, my solution is for use cases where you have many sections and typically only one or two rows per section.

**Comment by nguyenhuy** [comment]
Native reloads will be supported after the coming ASDataController refactor.  Assigning this to myself.
