### ISSUE TITLE
Swift ASCellNode with ASRangeController & ASTextNode makes CG raster data memory increase and leak

### ISSUE THREAD

**Issue by samw723** [facebook/AsyncDisplayKit#510]
Recently I met a situation while ASTableView render its ASCellNode, if I have a ASTextNode inside a customized ASCellNode with attribute string, append with ASRangeController, the memory of CG raster data will increase and leak, I create a Sample using your official Swift sample table view. 

https://github.com/samw723/AsyncDisplayKitTableViewLeak

![untitled](https://cloud.githubusercontent.com/assets/10149278/8348830/3c5e5938-1b4a-11e5-93b3-1c18437c5816.png)

I think the problem is CGDataProviderWithCopyOfData while render to UI. and swift will not release that memory. It increase so fast when you scroll the table view.

Please kindly help on this issue, thank you

**Comment by appleguy** [comment]
@samw723 thanks for reporting this!  I actually just discovered this issue in my testing with ASDataController and filed a more specific issue, but including the screenshot here may make this one a better task :).  I will try to fix this today, or at the latest, during this week.  It should not be too difficult, and I will roll a 1.2.2 of ASDK in the next week that includes this and other fixes.

Let us know if you have any other findings or questions!

**Comment by markmark1** [comment]
Great

**Comment by samw723** [comment]
@appleguy Thanks a lot! 
At current implementation, in order to reduce memory in un-used(not appear on UI) cell, I did release image node's image in "clearFetchedData" and reload them while "willDisplayNodeForRowAtIndexPath".

Will this action take care from AsyncDisplayKit after your modification of memory leak? because that behaviour cause extra network request from client, which is bad for user.

I want to have look N' feel as same as Facebook Feed list without manually reload those images

**Comment by appleguy** [comment]
@samw723, @markmark1 please feel free to test against the master branch.  I'll be releasing 1.2.2 later today which will contain the fix for ASTextNode _placeholderImage being properly released in -clearContents.  I think it is very possible that other objects are getting stuck (due to a circular reference, for example) and will prioritize resolving any such problems.

Since this specific issue is about ASTextNode, which represented the bulk of the overhead, I'm going to close and welcome you to file a new issue if you find a problem.

Thanks!  The memory change was part of one of the last diffs in the stack of https://github.com/facebook/AsyncDisplayKit/pull/529

**Comment by markmark1** [comment]
Ok apple guy I will test it
