### ISSUE TITLE
Cells do not relayout when edit mode is used in ASTableView

### ISSUE THREAD

**Issue by jaichaudhry** [facebook/AsyncDisplayKit#512]
When I try to set the edit mode of ASTableView to true, then the contentView size does not get layout again due to which it shifts to right, and when the minus button of edit mode is pressed the delete  view that comes on the right does not have proper layout.
The reason I think this is happening is because in the following method
- (CGSize)dataController:(ASDataController *)dataController constrainedSizeForNodeAtIndexPath:(NSIndexPath *)indexPath
the size that is returned does not considers the change in layout when edit mode is enabled. In actual tableView the contentView width is reduced.
![ios simulator screen shot jun 25 2015 11 53 49 pm](https://cloud.githubusercontent.com/assets/6908626/8362273/806d67a4-1b95-11e5-8378-bdbe2a69c35d.png)
![ios simulator screen shot jun 25 2015 11 53 51 pm](https://cloud.githubusercontent.com/assets/6908626/8362282/8603c1c2-1b95-11e5-9ee4-646e47d1bcc8.png)

**Comment by jaichaudhry** [comment]
I tried this in AsyncDisplayKit 1.2.2 in the Kitten Sample code. Still not working the labels overlapping over the delete button show in edit mode
![ios simulator screen shot jul 6 2015 12 38 54 pm](https://cloud.githubusercontent.com/assets/6908626/8517221/fd0e08ce-23db-11e5-967b-3181d0f435ab.png)

**Comment by appleguy** [comment]
Thanks for reporting this!  We will use this as an example case to improve with the "relayout" work that @nguyenhuy is working on for AsyncDisplayKit 2.0.  The current master branch is now "2.0 Beta" because it includes his extensive changes to the layout system, which will significantly help us deal with this situation.

That said, this is an area where AsyncDisplayKit 1.x requires some manual work from the programmer to set -invalidateCalculatedSize and perform a new -measure / -layoutIfNeeded pass.  One reason is that the relayout could either be done synchronously or asynchronously, and the original framework didn't make an assumption about what is best for all apps when the frame changes (so this behavior forces the app developer to explicitly implement the desired behavior — after calling -invalidate, you can either call -measure on the main thread to block synchronously, or you can call it on a background queue to prepare the new layout asynchronously).

**Comment by appleguy** [comment]
@jaichaudhry thanks for reporting this with all the details :).  @nguyenhuy has finished a lot of work here, and the Kittens example now does relayout both on rotation and on tapping cells.  Please retry your use cases, and please do open a new issue if you experience any problems!
