### ISSUE TITLE
layout() of ASCellNode not being called when orientation change(traitCollectionChange)

### ISSUE THREAD

**Issue by tiepvuvan** [facebook/AsyncDisplayKit#536]
I'm using an ASTableView to display custom ASCellNode sub-class, I override calculateSizeThatFits: and layout()
But when I rotate device, I expect layout() and calculateSizeThatFits: get called to re-layout but they aren't called. Am I missing something or it's a bug of AsyncDisplayKit?

**Comment by appleguy** [comment]
@tiepvuvan thanks for reporting this.  It turns out this is intentionally not done automatically, because relayout passes can be expensive, and are often not what the app developer wants (it is common for re-layouts to occur but result in the same positioning of elements, which can be hard to detect without careful profiling).

To deal with this situation, you should be able to call -invalidateCalculatedSize (if you start using the AsyncDisplayKit 2.0 Beta coming out soon, it is -invalidateLayout).  Then you can call -measure: and -layoutIfNeeded in succession.  One of the easier ways to do this is probably calling -reloadData on the table view.

This is a use case that a number of community members are interested in seeing better support for, so you're not alone!  In particular, PR #468 lays the groundwork for this and I would like to see transparent support for relayouts be part of AsyncDisplayKit 2.0.  Although the Beta is coming very soon (it may make it for today!), the final version may take until late August / shortly before my talk at NSSpain.

**Comment by appleguy** [comment]
@nguyenhuy is going to investigate this within the next couple weeks

**Comment by appleguy** [comment]
@tiepvuvan - thank you for contributing to the AsyncDisplayKit community by asking your question in this forum! I hope you have been able to use the framework! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. Hopefully, I was able to answer your question, but if not, feel free to reopen this.
