### ISSUE TITLE
[ASTableView, ASCollectionView] load all CellNodes into memory regardless of number of rows / sections

### ISSUE THREAD

**Issue by ryanfitz** [facebook/AsyncDisplayKit#540]
I'm not sure if this is a bug or working as expected. I'm testing out the latest changes on master and am seeing that every cell node is now getting loaded into memory when a table / collection view is initially rendered. None of the cells are getting deallocated either. 

I've updated the examples to contain 2000 rows and all 2000 are getting loaded. I've tried setting different tuning params, but they don't seem to have any effect.

**Comment by appleguy** [comment]
@ryanfitz thanks for the issue; I think it may be a duplicate, but I'll leave it open until I confirm.  In any case, this is actually expected behavior for the current implementation.  It's certainly an area that could be improved, but there's an important factor that make it less critical to change: AsyncDisplayKit is particularly useful for apps with variable row heights (a major indication that the content reaches a higher level of complexity where layout and rendering should really be asynchronous).  For those apps, before ASDK, UIKit would ask for the row / item heights for all items in the datasource anyway, and so they are likely already expecting to require a system that stages in the data so that this blocking doesn't happen all at once.

For the apps that previously did synchronous text layout for everything up-front, synchronously creating the cell nodes is typically less CPU time, as the layout then occurs asynchronously after that.

The use case that this really hurts are for /fixed-height/ tables with large local databases.  This sounds like the case you have?  I genuinely care about making sure the framework handles this elegantly, and it is absolutely possible with some additional effort.

Feel free to pass on any there details about your use case and workarounds you might try.  How tough would it be to stage in the data source by using the batch loading callbacks?  (check out where ASBatchContext is used).  The reason this is tricky is that we still need to trigger data fetching & rendering callbacks before cells come onscreen, even in the case that they are all the same height, and ASRangeController / ASDataController would need changes to be able to handle doing this while limiting cell allocation.

Other tasks may refer to this concept as the "allocation range".

**Comment by ryanfitz** [comment]
@appleguy thanks for the helpful info. The current implementation makes sense. My use case involves rows that can vary greatly in height, so ASDK is a huge improvement in handling different sized rows compared to to UIKits. I imagine its loading all nodes on background threads, calculating sizes and then loads the data into the backing ui table / collection view so it can do as little on the main thread as possible.

For some more info on my use case, I have different sized rows with complex cells that have lots of data and most importantly contains several unique images per row. As a user scrolls down the screen, more data is loaded off the network and then rows are getting inserted / removed / moved (not doing full reloads). 

I'm running into a two different memory related crashes. As a user moves around the app, images are getting downloaded off the network (using `ASMultiplexImageNode` and `ASNetworkImageNode`) and then stored as UIImage's. As a user scrolls away from these cells the images are still in memory, as the tope level `ASCellNodes` are not being deallocated. I eventually get a crash because of too much memory usage. The second issue is very similar, but is triggered when the next page of data is loaded off the network. As a user scrolls, I fetch the next 25 items of data and then insert these 25 rows into the tableview. What happens is even if current memory usage is very low, these 25 rows are getting loaded all at once, memory usage spikes and apple force closes the app because of a large spike in memory usage.

I believe I can work around these issues with a smarter implementation of my `ASCellNode`. I wanted to make sure that the current implementation of loading all cells into memory was expected, before I started diving into improving my cell nodes. 

I'll leave this issue open, but feel free to close it out. Thanks again for all the help

**Comment by ryanfitz** [comment]
@appleguy I can create another issue for this, but I'm seeing `ASDisplayNodes` are getting infinitely retained once measure is called on a node. I've been able to replicate this in both objective-c and swift. You can replicate it by allocating an `ASDisplayNode` call measure on it and then nil out the node. Dealloc will never be called.

```
  PostNode *measuredNode = [[PostNode alloc] init];
  [measuredNode measure:CGSizeMake(100, 100)];
  measuredNode = nil; // Dealloc never called
```

```
  PostNode *node = [[PostNode alloc] init];
  node = nil; // Dealloc called
```

**Comment by ryanfitz** [comment]
I sent pr #545 which fixes the memory leak when a node calculates its layout.

**Comment by appleguy** [comment]
Killer find, thank you @ryanfitz!  I think there may still be some retain cycles lurking as there has not been sufficient profiling work done on ASTableView and ASCollectionView (components written entirely for OSS, not originally used for large scale deployment in Facebook apps like the rest of ASDK has been).  I fixed an important one related to placeholderImage last week, but don't hesitate to report any other issues you detect (even if you don't have time to submit a PR).

**Comment by appleguy** [comment]
@ryanfitz reading your note, definitely test again using the latest version (either 1.2.2 or master) and check that -clearContents is being called on all of your ASNetworkImageNodes and ASMultiplexImageNodes as they fall outside of the working range.  You might also look to modify the .rangeTuningParameters for your use case, particularly for an image-heavy app running on older devices (a smaller render range could be important for the low-memory devices, although this increases the risk of seeing placeholders).  In particular you might want to cut down on the "trailing" range so things are deallocated more quickly.  Take a look at how ASRangeHandlerRender is implemented / used to understand this bit and please let me know right away if it's not working correctly for you, as this would be one of the issues I'd prioritize for this coming weekend.  I believe it should be working correctly on the latest version.

**Comment by ryanfitz** [comment]
@appleguy thanks for the info. I'll try out those suggestions shortly and let you know if I run into any issues. As I'm diving more into the implementation of the different components of ASDK I'm pretty confident I can get things working well for my use case.

**Comment by ryanfitz** [comment]
@appleguy Ive managed to get my app working really nicely with your suggestions and the recent changes on master. I sent one more pull request #551 which greatly reduces memory usage when using multiplex image nodes in table / collection views. I'm using sticky header nodes in my app, I had a really poor solution for this previously, but after diving into the internals of ASDK, I've managed to come up with a solution similar to how ASDataController loads, renders and then clears out nodes as it comes in and out of the rendering range. 

With these few changes to my app memory usage is staying low and performance high!

Thanks again for all the help and all the great work you (and everyone else) have done with ASDK. My app's experience wouldn't be possibly without this lib.

**Comment by huchunyu** [comment]
@ryanfitz Do you mind to give more details on your  ASDataController like solution ? Some sample code is really appreciated.

**Comment by ryanfitz** [comment]
@huchunyu I put together a quick [example project](https://github.com/ryanfitz/AsyncDisplayKitHeaderNodeExample) which shows off one possible solution for sticky headers with an `ASTableView`. The example will infinitely load more data as you scroll and batch update the table as more data is loaded. The majority of the logic is in [SectionedDataSource](https://github.com/ryanfitz/AsyncDisplayKitHeaderNodeExample/blob/master/AsyncDisplayKitHeaderNodeExample/SectionedDataSource.swift). The `SectionedDataSource` is mostly generic and can be used for working with any kind of data and display nodes.

**Comment by huchunyu** [comment]
@ryanfitz  Thanks a lot. I'll take a look. Appreciate your help.

**Comment by appleguy** [comment]
@ryanfitz - thanks for all of your contributions to ASDK! I hope you are still using (and loving!) ASDK. :)
