### ISSUE TITLE
Static library copy headers build phase is incorrect

### ISSUE THREAD

**Issue by JonasGessner** [facebook/AsyncDisplayKit#546]
The static library target has a "Copy Headers" build phase. This won't work when archiving and the docs for creating a static library explicitly advise against using a "Copy Headers" build phase in a static library (it is meant for frameworks). A "Copy Files" build phase should be used instead.

https://developer.apple.com/library/ios/technotes/iOSStaticLibraries/Articles/creating.html

"If your library target has a “Copy Headers” build phase, you should delete it; copy headers build phases do not work correctly with static library targets when performing the “Archive” action in Xcode."

It is a very easy fix and archiving will work once the "Copy Files" build phase is used.

**Comment by appleguy** [comment]
In your last sentence, just so I'm clear, you mean once the "Copy Files" build phase is used — right?

I'd be really happy to accept a PR that does this if you can whip it up.  This is an important issue that I would like to see fixed, but I have a pretty sizable list of slightly-more-important issues for the development time I can pull together in the next couple months.  Thanks for reporting it, and no worries if you can't get a PR up — I'd much rather know about the issue and put it on the to-do list.

**Comment by JonasGessner** [comment]
Sorry for the mistake in the last sentence, I fixed the comment. Sure, I'll open a PR! Thanks for the quick reply.

**Comment by JonasGessner** [comment]
I've forked the repo and I am updating the Xcode project right now. I noticed that all the headers are imported using #import <AsyncDisplayKit/xyz.h>, but shouldn't the library internally import with #import "xyz.h" and only projects that use the library use #import <AsyncDisplayKit/xyz.h>? I'm wondering because #import <AsyncDisplayKit/xyz.h> generates file not found errors when I try to build the static library with the new copy files phase.

Another thing I noticed, while trying if using #import "xyz.h" works with the framework target too (it does), is that the framework strangely builds less files than the static library, ending up with lots of linker errors ("_OBJC_CLASS_$_ASInsetLayoutSpec", ...). The static library builds 63 files, the framework 48. Those numbers should be equal, unless I'm missing something.

**Comment by JonasGessner** [comment]
I made all my suggested changes, it's working perfectly. I haven't opened a PR yet because the changes are quite substantial (I renamed every #import). I pushed the changes to my fork so you can check them out and let me know if agree with them: https://github.com/JonasGessner/AsyncDisplayKit

**Comment by nickvelloff** [comment]
There are a substantial amount of warnings using as a Framework currently. Does your changes happen to address those as well by chance?

**Comment by appleguy** [comment]
@JonasGessner @nickvelloff It's been some time now, and we've properly integrated Carthage support (along with the original Cocoapods, of course).  This is in fact tested on every build so that we can no longer forget to add new files to the framework target.

I am ready and willing to merge any proposed project file changes that will better support directly importing the project or manually building the framework for developers who prefer this approach, so if you find this is still an issue with the latest 1.9.1 or master, feel free to put up a PR!

**Comment by nickvelloff** [comment]
Thanks @appleguy!
Cc @paulyoung

**Comment by paulyoung** [comment]
The only warnings I'm currently aware of are:

- for `AsyncDisplayKit.xcodeproj` to update to recommended settings
- a warning related to the C++ "header pollution" issue described in https://github.com/facebook/AsyncDisplayKit/pull/632#issuecomment-140858968 which @appleguy let @rcancro know about

This is using an older release of AsyncDisplayKit, so these may have been addressed since then.

I'll try updating and report back soon.

**Comment by paulyoung** [comment]
I'm not seeing any warnings when using 1.9.2 with Xcode 7.1.1
