### ISSUE TITLE
Memory leak in CG Raster Data with ASImageNode

### ISSUE THREAD

**Issue by coenert** [facebook/AsyncDisplayKit#570]
I'm using ASDataController and ASRangeController to create a custom Swipe view. Within that Swipeview i have very big images that i show on an second screen(apple tv). But each time i reload my data controller the CG Raster data is increasing and a lot of data is never released.

![screen shot 2015-07-15 at 10 01 08](https://cloud.githubusercontent.com/assets/2033982/8694012/ddbedc4e-2adb-11e5-973a-5dc7c0e3a0d9.png)

**Comment by appleguy** [comment]
@coenert, the two classes you mentioned have never been tested with usages outside of ASTableView and ASCollectionView.  It's one reason they are in the Details folder and not documented as primary API integration points.  That said, I would love to help fix any bugs in this area and make them more usable by other classes, as they are designed to be able to do this.

Would you be able to share sample code reproducing the issue?  There are many factors in your implementation that could cause this.  It may well be an ASDK framework bug, or it could be a bug with your integration.

Check if the -clearContents method is being called on ASImageNode.  If it's not, then this will happen.  ASRangeHandlerRender is intended to call this and you'll notice it get called for anything in an ASCollectionView or ASTableView.

Thanks for using the framework; glad to have you as a member of the community!  Pinterest and a few other clients are starting to look at custom integrations with these two classes, but it is fairly cutting edge work, and we're happy to have someone else interested in doing that too :).

**Comment by TernTuring** [comment]
@appleguy ,I also encountered the same problem,  can I provide the codes to you?

**Comment by appleguy** [comment]
@coenert  - I'm very sorry you encountered this issue.  It turns out there is a bug with ASBasicImageDownloader, although it's hard to be certain if that is exactly what you're seeing here.  My hope was that few people would use this class, because there is a lot of value for an app to more closely control its use of the network (that's why the cache and downloader properties exist with a protocol that you can adopt for ASNetworkImageNode and ASMultiplexImageNode).  Still, it is a very serious issue to leak memory and so I apologize for this problem.

If you are able to provide any additional data here, especially if you can test your case against the fix we come up with for this retain cycle, I would greatly appreciate you opening a new task.

Follow along here and test out the solution with us: https://github.com/facebook/AsyncDisplayKit/issues/763
