### ISSUE TITLE
While rotating device, a crash  arises

### ISSUE THREAD

**Issue by kos9kus** [facebook/AsyncDisplayKit#583]
Hello guys.
I really appreciate the lib, but lately I encountered with problem.
 
-[UITextMagnifierCaret rotated]: unrecognized selector sent to instance 0x7ff04411d010
2015-07-25 14:56:06.626 TellIT[52349:1180030] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITextMagnifierCaret rotated]: unrecognized selector sent to instance 0x7ff04411d010'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107248c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108db3bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001072500ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001071a613c ___forwarding___ + 988
	4   CoreFoundation                      0x00000001071a5cd8 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x000000010721854c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x0000000107116a04 _CFXNotificationPost + 2484
	7   Foundation                          0x0000000107627968 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	8   UIKit                               0x0000000107d60e19 -[UIDevice setOrientation:animated:] + 282
	9   UIKit                               0x0000000107afc007 -[UIApplication handleEvent:withNewEvent:] + 1507
	10  UIKit                               0x0000000107afc49a -[UIApplication sendEvent:] + 79
	11  UIKit                               0x0000000107ae7b4f _UIApplicationHandleEvent + 593
	12  GraphicsServices                    0x000000010aba738c _PurpleEventCallback + 756
	13  GraphicsServices                    0x000000010aba6e74 PurpleEventCallback + 35
	14  CoreFoundation                      0x000000010717c6a9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	15  CoreFoundation                      0x000000010717c61b __CFRunLoopDoSource1 + 475
	16  CoreFoundation                      0x0000000107171e68 __CFRunLoopRun + 2200
	17  CoreFoundation                      0x0000000107171366 CFRunLoopRunSpecific + 470
	18  GraphicsServices                    0x000000010aba5a3e GSEventRunModal + 161
	19  UIKit                               0x0000000107ae78c0 UIApplicationMain + 1282
	20  TellIT                              0x00000001033dac07 main + 135
	21  libdyld.dylib                       0x0000000109ebe145 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)

I have a main controller with ASTableView, a rotating is fine
then i push new controller  by tapping on some cell, controller is created, i rotate, there is fine
then i go back to main controller from previous controller (by popping)
try to rotate and in this moment the crash arises 
Whats i do wrong? I don't override and embed any methods that handle a rotation

**Comment by appleguy** [comment]
It looks like this is not caused by AsyncDisplayKit directly — or at least, there's no sign in the stack that it is related.

From reading the stack, my guess is:
- You have code that subscribes to an NSNotification that gets triggered on device / interface rotation
- In your implementation of this method, you are getting some object that happens to be the UITextMagnifierCaret (which you should not be accessing directly).  You may be walking the -subviews array or something to do this, and that is generally not safe to do.
- Then you're calling a method "rotated" on that object.  This does not look like a method that UIKit uses internally, or exposes as an API anywhere, so it makes me think you have this call in your code.

Good luck debugging, and please file another task if you run into any issues with AsyncDisplayKit!

**Comment by kos9kus** [comment]
Thanks for reply,
Hm, thats weird, I plead that don't do something towards rotation.
Ok, I got it, will seek this call within third party library.
thanks
