### ISSUE TITLE
[ASCellNode] dealloc trying to free already deallocated objects

### ISSUE THREAD

**Issue by oks** [facebook/AsyncDisplayKit#586]
http://s.oks.im/ASDisplayNode.mm_2015-07-26_14-51-27-cpfh8.png

-[__NSDictionaryM __setSupernode:]: unrecognized selector sent to instance 0x7eb91bb0

I need help, please!

**Comment by appleguy** [comment]
This is a very odd crash that I have not encountered or seen reported before.

Are you able to reproduce it in your app?  Based on the exception, it's clear on the crashing line, "subnode" is not even an ASDisplayNode — it's an NSDictionary.  This could be caused by a pretty serious memory management bug, like a memory smasher or improper MRR code.

Do you use ARC throughout your project, or do some files have manual reference counting?

**Comment by oks** [comment]
ARC only.

**Comment by appleguy** [comment]
@oks any further information you can share?  Is the issue reproducible 100%, or does it only happen sometimes?  What steps cause it to happen?

I have not ruled out the possibility that this is a framework issue, and I take your report very seriously.  However, since we haven't heard any other reports and don't yet have a way to reproduce it, it's hard for us to make progress on debugging it unless you can provide fairly detailed information (of course a test project is ideal, but I understand that isn't always possible).

**Comment by oks** [comment]
Still the same, you can create ASCell and add to in node-hierarchy with more then 3 levels. 
For Example 
*Cell
 -ASDisplayNode
 --ASDisplayNode
  ---ASDisplayNode

When you will insert in one time more than 100 cells, and scroll it, you will get this crash.

Second problem - it's cells don't layout subnodes sometimes. So they have size zero, it means - that this node should be removed. I think this bugs somehow connected,

**Comment by oks** [comment]
I will try to provide test project to you asap

**Comment by appleguy** [comment]
@oks - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. However, if you are still having troubles, feel free to reopen this issue or ping us on ASDK's Slack channel (#1582) and I would be happy to help get to the bottom of this! I hope you have been able to use the framework!
