### ISSUE TITLE
[ASMapNode] Create MapKit snapshot node

### ISSUE THREAD

**Issue by jbejean** [facebook/AsyncDisplayKit#59]
It's possible to use AsyncDisplayKit with MKOverlayRenderer (MKPolygon or MKPolyline)?
It might be awesome!

**Comment by appleguy** [comment]
@aaronschubert0 ran across this old task...we should do it soon!

**Comment by appleguy** [comment]
We may even be able to support tapping (or at least a method call) to toggle to a live MKMapView.  The default state, and most useful one, would be for it to use -fetchData to trigger loading a snapshot — basically a convenient hook into the intelligent preloading system for map snapshots.  But instead of naming it ASMapSnapshotNode, calling it ASMapNode will give some option value in potentially supporting interaction later.

**Comment by aaronschubert0** [comment]
Ha, good find @appleguy ! This is would be a really awesome node to be honest. The live MKMapView sounds even better! I think I might actually go ahead and give this a shot! Any design considerations I should be aware of, before I start?

**Comment by appleguy** [comment]
@aaronschubert0 Thanks so much for implementing this.  It was an awesome "present" to hear from you on Nov 2nd (my birthday) that you would build this for the community.  Congratulations on it launching in 1.9.3!  Double win for closing one of our earliest feature requests.

**Comment by aaronschubert0** [comment]
Thanks @appleguy! That's awesome, I didn't know that. Yeah it's great to be contributing to the project. It's a really great environment to be part of. Hopefully more contributions to come in the future :)
