### ISSUE TITLE
iOS framework target broken

### ISSUE THREAD

**Issue by jflinter** [facebook/AsyncDisplayKit#591]
The iOS framework target (and thus, building with Carthage) is currently broken on master. It looks like it's broken for a few reasons:
- `AsyncDisplayKit/Info.plist` was moved to `AsyncDisplayKit-iOS/Info.plist` without updating the `.xcodeproj`
- abe98d5b09b37a70a406a2c8b5e07fb9bcfe66f6 appears to have introduced several compiler errors - I'm sorry, but I don't have time to dig further at the moment.

To reproduce:
`xcodebuild build -project AsyncDisplayKit.xcodeproj/ -target AsyncDisplayKit-iOS`

**Comment by nickvelloff** [comment]
This was merged and had it right: https://github.com/paulyoung/AsyncDisplayKit/commit/8fa6667d93fe164051f6afab70e134c9bb0b0313 
But somehow it subsequently got reverted.

**Comment by nguyenhuy** [comment]
Sorry, I think I messed this up while trying to fix conflicts in #468. Really appreciate if someone familiar with Carthage helps me to fix this.

**Comment by appleguy** [comment]
Thanks for reporting this.  This was the biggest diff landed to ASDK since it was publicly released, and it's a bummer to hear it broke the Carthage target.

I'll eagerly merge any fix.  Right now I don't have cycles to investigate, particularly because I've never used Carthage and don't have a test project, and am rushing to prepare for the ASDK 2.0 launch at NSSpain in a little over a month.

If you'd like to include an examples/ project that uses Carthage, it would be a great way to keep the target working.  The examples/ projects are built by Travis, too.

**Comment by marmelroy** [comment]
I looked into the build issue reported here and just pushed a pull request that should fix it. 

There were several reasons for the framework target failing but it was mostly a matter of the framework missing some recently merged changes (that were only added to the library target).

**Comment by nguyenhuy** [comment]
Awesome. Thank you!

**Comment by nickvelloff** [comment]
@marmelroy thanks for this!

**Comment by marmelroy** [comment]
No worries. 

As @appleguy suggested, an example that uses the framework will help keep the target working in the future. I will write one a little later this week (using Carthage too so that this use case is fully covered).

**Comment by appleguy** [comment]
Excited to see an example or test case!
