### ISSUE TITLE
Create a more readable/understandable syntax for ASLayoutSpecs

### ISSUE THREAD

**Issue by rcancro** [facebook/AsyncDisplayKit#605]
The ASLayoutSpecs are great, but a little cumbersome to use. I would love to see an updated implementation that allows for the creation of a mutable spec that gets marked as immutable as soon as it is returned from `- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize`.

For example, I would love to create a ASStackLayoutSpec via an interface similar to this:
```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
	ASStackLayoutSpec *stackSpec = [[ASStackLayoutSpec alloc] init];

	stackSpec.direction = ASStackLayoutDirectionHorizontal;
	_nodeA.alignSelf = xxxxx;
	[stackSpec addChildren:@[_nodeA, _nodeB, _nodeC]];

	if (_nodeD.hidden == NO) {
		[stackSpec addChild:_nodeD];
	}
	return stackSpec;
}

// meanwhile, in ASDisplayNode:
- (ASLayout *)calculateLayoutThatFits:(ASSizeRange)constrainedSize
{
	...
	id<ASLayoutable> layoutSpec = [self layoutSpecThatFits:constrainedSize];
	layoutSpec.mutable = NO;
	...
}
```

**Comment by appleguy** [comment]
Agreed, I think this would be a big improvement to the API — both in usability and in familiarity (in terms of how the code looks, not as foreign / unique pattern).

We would want to make sure the addChildren/addChild methods, and any other methods that support mutation, throw exceptions if they are called after mutable is set to NO.  When computing / flattening layout specs into layouts, we should assert that all the specs they traverse are not mutable.

I think it makes sense to add the mutable property to the base class for ASLayoutSpec, so that third parties implementing their own layout specs are able to participate in this pattern.  It may also make sense to put -addChild on the base layout spec, but not addChildren:.  Alternatively, it could be fine to have each subclass be responsible for declaring (as well as implementing, of course) the mutation / setup methods.

IMO this is the most important API change we've come up with while using ASLayoutSpecs in practice, and is thus a priority for implementing before the NSSpain presentation on these concepts.

**Comment by appleguy** [comment]
@rcancro any other changes going to happen here?  Please close if we're wrapped up.  Thank you for doing this!
