### ISSUE TITLE
Scrolling performance optimization for ASTableView

### ISSUE THREAD

**Issue by richardoti** [facebook/AsyncDisplayKit#649]
Swift 2.0, crash in ASTableView:
When I try to print out `tableView.tuningParametersForRangeType(ASLayoutRangeType.Count)`
I get a crash with stack trace:
```
2015-09-13 00:56:46.081 MyStore Staging[2432:1227873] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Requesting a range that is OOB for the configured tuning parameters'
*** First throw call stack:
(0x246d75a7 0x3269fc77 0x246d747d 0x253d25a9 0x367fbd 0x3d7bb9 0xa7063c 0xa7073c 0x27bdbb65 0x27c85785 0x27c856ad 0x27c84c31 0x27c8496b 0x27c846d1 0x27c84669 0x27bd9047 0x27602dcd 0x275fe7b9 0x275fe641 0x275fe027 0x275fde31 0x27bd1485 0x2469e275 0x2469b959 0x2469bd5b 0x245e8b51 0x245e8963 0x2bb251a9 0x27c3ac91 0x99cd8 0x32c48aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Accessing and setting any other tuning parameters works fine.

**Comment by appleguy** [comment]
This is expected.  The Count is just that--the total number of valid options if you are iterating over the range types.  They are zero indexed, so the value of Count is not a valid index.

There are some Apple APIs set up this way too.

**Comment by richardoti** [comment]
@appleguy thanx!
So seems that there is only two parameters - preload and render. This helps a lot :+1:

**Comment by appleguy** [comment]
Yes, that’s right, although I am about to add the Visible range in the next couple weeks — and have dreams of others :)

Be sure to let me know if you have any questions about ASDK!  GitHub issues are a fine way to do that, or post in Paper Engineering Community (Facebook) or the AsyncDisplayKit group (Google Groups)

**Comment by richardoti** [comment]
Thanks! Looking forward to VisibleRange feature as may help in tuning scrolling performance on slower devices.

**Comment by appleguy** [comment]
It would be tremendously useful to me if you’d be interested in writing up a little bit more on what you’d want to do with the visible range, and other feature requests / problem areas with ASDK in general.  A large amount of work is being done on it right now, and I’m in the design stages of a likely-significant overhaul of the working range system.

In particular, what kind of performance-tuning stuff might you be able to do with the visible range?

Another feature you might be interested in - “synchronous, concurrent rendering” - a mode that when enabled, prevents any un-rendered content from being scrolled onscreen.  UIKit does this 100% of the time, but 0% of the time performs preloading.  The cool thing with ASDK is that 90%+ of the time, preloading will be finished and no blocking will occur; in the other cases, the main thread would only be blocked for the remainder of the already-started rendering.  Awesomely, even if you were to disable the working range completely (0 leading / trailing screens), it would still be much faster than UIKit: different nodes in each cell will render concurrently on all cores while the main thread waits!  How sensible relative to using the main thread itself :).

		— Scott

**Comment by richardoti** [comment]
Scott, sorry for late reply.

From what I've figured out, the screen stalls occur when image is being rendered. So, lets say, if you have a bunch of images with different layout and they have to be fetched from the network, there are some glitches, probably, because of some CPU power is wasted on image decoding etc.

So what I would like to use is somehow stop decoding while user scrolls and start once scrolling is completed.

Of course, the issue with screen stalls affects mainly old devices (i.e. iPhone 4S, iPad 3), everything scrolls smoothly on, for example, 6+.

**Comment by appleguy** [comment]
What classes are you using to contain the images?  The behavior you've described would definitely be the case if you are using UIImageView anywhere, but it should not be the case with ASImageNode (or ASNetworkImageNode, ASMultiplexImageNode).  These are tuned such that even on an iPhone 4, with a slow single-core processor, ASDK can achieve 60FPS while scrolling through large images.

I'd love to help you analyze a Time Profiler trace (from Instruments) if you can capture the phenomenon.  Since uploading files can be tough, maybe you can start by taking a quick trace (just 10-30 seconds of experiencing the issue), and then paste here a screenshot of the top costs being charged to the main thread during that period (e.g., after application startup, just the scroll session highlighted).

Thanks @richardoti, looking forward to figuring it out!

**Comment by richardoti** [comment]
So, the trace looks like this:
![screen shot 2015-09-28 at 13 58 39](https://cloud.githubusercontent.com/assets/8013017/10134872/86365580-65e9-11e5-8f9e-52d54e25d072.png)

ASNetworkImageNode is being used, without any caching. But if downloaders is being implemented (Kingfisher), no difference in performance. The performance drop is only noticeable on 4S and iPad 3, in addition, other social network apps have such stalls sometimes as well, so I don't think it is related to AsyncDisplayKit, but more to the slow devices and complex views.

**Comment by appleguy** [comment]
The trace doesn't seem to show any rendering, so unless it's further down in the trace, it doesn't look like display / decoding of the images is to blame — right?

Although there is always some overhead from UITableView (even with ASTableView), you can reduce the trace above by making use of .isLayerBacked or .shouldRasterizeDescendents.  Even if you need touch handling on individual elements of your cell, try flipping on .shouldRasterizeDescendents = YES on your ASCellNode and run it again.  There are some tricks / suggestions I can give on how to be able to do event handling even with those options enabled, but it would be much easier to discuss if you could share a screenshot of your app, or a sketch of it on a napkin :)

**Comment by richardoti** [comment]
Adding `shouldRasterizeDescendents.` greatly improves performance, but breaks all the layout.
The app itself is a closed project, but I think "Facebook-like timeline" describes idea at its best.
The core timeline part is opensource and is available here:
https://github.com/hyperoslo/Wall

The scrolling issue is reproducible in InfiniteScrolling sample.
Interesting part is that when I try to scroll fast, the timeline scrolls quite snappy, but when I try to scroll with a moderate speed (inertial scrolling in both cases) and timeline starts loading attachments and performing layout screen stalls become more noticeable.

**Comment by appleguy** [comment]
@richardoti forgive me if I asked this, but what version of ASDK are you running?  There are several fixes to layout with shouldRasterizeDecedents that went in around the time of the last 1.2.x releases, and I'm not sure if all of them were in 1.2.3.  We were considering a 1.2.4 but it did not happen, so they may only be complete in the master / 2.0 Beta branch.

I have not had time to release an actual 2.0 Beta branch, but master is very stable at the moment (the notable exception being certain types of more complex batch edit operations with ASTableView, which are still better-handled in master than 1.2.3).  As we continue the discussion to get to the bottom of the issue, can you make sure your podfile is pointing to master and retry your test of rasterization?

**Comment by appleguy** [comment]
@richardoti thanks for the link to the project — that is really awesome!  I would love to get it running.  I got InfiniteScroll set up, with pods installed, but it crashes when I launch the app saying there is no JSON file for the english locale.  Do you have a local fork that I could run?

The behavior you describe is interesting and certainly useful to help debug the problem (fast scrolling is smooth, but slower scrolling is choppy).  This suggests to me that it /could/ be the image downloader or another system that is contributing to the frame drops.  It may also be ASDK, although I have not yet seen that behavior with ASDK in quite a few different apps.

I'll try to respond more quickly, but it's up to you if you'd like to continue debugging one step at a time or if you prefer I get set up with a working version of the app to proactively debug the issue.  I really would like to fully understand and fix it with you, so either way is fine to me.  Even if we fixed the layout of rasterization, and that fixed your issue, I'd love to see profiles of the slow case.

The image cache will mainly impact users revisiting images after they were initially downloaded, and memory usage.  In general an app should have a way to move images from memory into disk cache, and also manage the purging of the disk cache appropriately — otherwise there is a tendency to want to cache more in memory, which 1) puts the app closer to being evicted by the system, which is not always signaled before it happens; 2) shuts down other processes the user has open, slowing them down.  The symptom however would be greater LOAD TIMES for images, and to my knowledge should not have any impact on frame rates.

**Comment by richardoti** [comment]
About ASDK version: the test referenced in my last comment has been performed with v1.2.3
and the TimeProfiling test most probably with v.1.2.(?)
I may try to do tests with either master or 2.0-beta as well.

Checking layout code and removing extra layout passes for images has given some improvements as well.

You may want to check out this branch: https://github.com/hyperoslo/Wall/tree/improve/performance with some fixes already applied.

About language crash - yes, I do have a fix and it is a one-liner. It seems not to load data, but it is not relevant to performance. I will apply fix to the branch I've mentioned in a few minutes.

**Comment by appleguy** [comment]
Great, looking forward to it!  With access to a branch that is build-and-run ready, I'm happy to test it against ASDK 2.0.  However, your personal comparison of the performance would be very valuable and I'd love to hear about it if you get more time.

**Comment by richardoti** [comment]
@appleguy cool, thanks for the help.
One issue worth to be mentioned is significant per-device performance difference. For example, there are no issues at all on 6, 6+ and iPad Air 2 (and if running on PC in Simulator too).

The stalls are reproducible on 4S and iPad 3.

**Comment by appleguy** [comment]
Thanks for calling that out.  I’ll run it on an iPod 5G, which is the same clock speed / CPU / GPU as the 4S but has the larger number of pixels on the Retina 4.0” screen to render (same memory, more data!)  I also have an iPhone 4 readily available, which would probably be the best profiling device to increase the accuracy of the sampling (more time spent, more samples gathered to show accurate percentages).

**Comment by richardoti** [comment]
So, I've decided to remove fake data completely and replaced it with strings. Should not affect speed.
Link is the same: https://github.com/hyperoslo/Wall/tree/improve/performance
I think, iPod 5G should be perfectly fine - iPad 3 has slow hardware but high-dense screen as well.

**Comment by appleguy** [comment]
OK, fantastic, it is working now!  I will take a look on-device tomorrow, if at all possible.

I do see the layout issue, and still think it will be fixed by master, but after spending a full 15 minutes I have not been able to get the build setup pointed to EITHER my local AsyncDisplayKit checkout or master / a specific commit on this repo.  Pretty frustrating actually, the limitations of the podspec file (rather than "podfile") present in the Wall folder are overriding anything I put in the podfile of the InfiniteScroll example, and prevent the local copy from being referenced.

Let me know if you have the right fix for this (I'm basically incompetent with cocoapods, aside from the absolute basics — embarrassing, I know).  Otherwise I'll figure it out for sure this weekend with my normal ASDK work.

**Comment by richardoti** [comment]
There is a workaround to this issue. Although, there is no way to specify git/branch/commit in podspec, it is possible to do so in a Podfile of the demo project.

To prevent podspec settings from overriding Podfile you should ... Just move dependencies from podspec to podfile. That's it.

But then, `AsyncDisplayKit` is not being linked to `Wall`, so you get compile errors like this:
![screen shot 2015-10-01 at 10 02 34](https://cloud.githubusercontent.com/assets/8013017/10215620/8dce68aa-6823-11e5-896a-68827b173b76.png)
That's true, because  `AsyncDisplayKit` is being linked to the project itself rather than to the `Wall` framework.

So, we have to link it manually:
1. Go to `Pods` project in your workspace
![screen shot 2015-10-01 at 10 04 42](https://cloud.githubusercontent.com/assets/8013017/10215666/de8fd828-6823-11e5-9ba0-ecd067bed965.png)
2. Select Wall
![screen shot 2015-10-01 at 10 04 47](https://cloud.githubusercontent.com/assets/8013017/10215675/ebf800e4-6823-11e5-9c63-6c9bfea9ed7d.png)
3. And link `AsyncDisplayKit` to it as you do with any other frameworks.
![screen shot 2015-10-01 at 10 04 23](https://cloud.githubusercontent.com/assets/8013017/10215692/09bd0e80-6824-11e5-9103-65898e8ff978.png)


I've already modified podspec and podfile in this fork: 
https://github.com/richardoti/Wall/tree/asdk-beta-development

So, the rest left to you is to specify needed branch and  link the framework.

In this particular case adding Pods to a source control may be a good idea not to link framework after checkout.

**Comment by appleguy** [comment]
@richardoti hey I really appreciate that walkthrough, in addition to the ready-to-run repo!  You description makes perfect sense to me, particularly the linker errors that would result, and I feel better equipped to fix a problem like that next time.  I will take a look at this.

**Comment by appleguy** [comment]
I was able to reproduce the issue thanks to your help, @richardoti .  It does appear that using the latest ASDK changes the symptoms of the layout problem with rasterization, but there is still a problem, particularly the size of the image.  I am having trouble debugging it because I have not yet used the debugger with Swift, and it is preventing me from printing out simple variables from a breakpoint in CellNode.swift:

"(lldb) po actionBarNode
error: <EXPR>:1:1: error: use of unresolved identifier 'actionBarNode'
actionBarNode
^
(lldb) po self.actionBarNode
error: <EXPR>:1:1: error: use of unresolved identifier 'self'
self.actionBarNode
^
(lldb) po footerNode
error: <EXPR>:1:1: error: use of unresolved identifier 'footerNode'
"

Anyway, I will definitely debug this before the end of the weekend (possibly tomorrow), through debugging / logging installed in the Objective-C layers of ASDK that I know well.  I expect it won't be hard to fix.

**Comment by richardoti** [comment]
Thanks for debugging, @appleguy.
The Swift debugging possibilities are far from perfect, that's true.
What about image size? Is it related to the resizing&image layout?

**Comment by appleguy** [comment]
@richardoti could you give me any pointers on why I am not able to print out even basic variables that are clearly in the scope of the method, using the debugger?  It's very odd to me, and I'm not sure how anyone could use Swift if it didn't allow debugging, so I must be doing something wrong...

The actual input image size should not matter, but preferredFrameSize is a good property to set if you know the size it should display, but don't have a subclass where you can easily override -calculateLayoutThatFits:.

**Comment by richardoti** [comment]
Seems that `preferredFrameSize` is a good idea to set, I didn't know that.
I will check the debugger issue right now, seems that you're trying to `po` something in `Wall` pod. As the `po` should work fine.

**Comment by appleguy** [comment]
@richardoti ok, I'm in the midst of debugging.  The debugger is occasionally working, in different method scopes, and I'll add NSLogs for other areas...a bit frustrating, still not sure what's up with that.

Important questions for you, though:
- What is the intent / need for the "height" and "width" properties on PostComponentNode?  I am not yet sure how these are used, but I'm pretty confident they are not hooked up properly to integrate with ASDK's layout system.
- You should be able to use -calculatedLayout (and just call the size property), or -calculatedSize, on any ASDisplayNode.  This is set after -measure: is called on them, which is what triggers the pass of ONE of the following methods, depending on which you've chosen to use: -calculateSizeThatFits: / -calculateLayoutThatFits: / -layoutSpecThatFits.
- If you're interested in using the newer layout components (e.g. ASLayoutSpec), they would work perfectly for this app and make the layout code MUCH cleaner.  Implementing only -layoutSpecThatFits: would eliminate both -calculateSizeThatFits: AND -layout, and be more readable.
- If you'd prefer the additional manual control, I'd recommend at least porting to -calculateLayoutThatFits:.  This allows you to eliminate the -layout method entirely.

I don't yet know if the behavior difference with rasterization on is due to a bug in ASDK, or is a side-effect of your implementation not fitting with the assumptions that ASDK makes (e.g. intended structure / usage of the API).  I would like it to behave the same even if API usage is not quite correct, so I'll investigate further, but I think one of the best things you could do is refactor the layout code a bit to use some of the new 2.0 concepts.

**Comment by appleguy** [comment]
I've noticed the layout code is calculating fractional values, including frames set on a 0.5pt, and this y-value in the CellNode's layout method:
2015-10-04 17:41:15.752 InfiniteScroll[53794:10016969] y value before footer = 367.166667

You probably don't care about non-retina screens (mainly iPad mini 1), but certainly things that don't lie on a 0.5pt will cause blurry appearance.

**Comment by richardoti** [comment]
Thanks for the pointing out flaws in API usage.
On answering your question about h/w properties on PostComponentNode - I will check them out right now.

**Comment by richardoti** [comment]
About width/height properties:
They're used to return width of content which is calculated based on padding and width of the node itself. Something like this:
```Swift
    var contentWidth: CGFloat {
    return width - 2 * paddingValue
  }
```

**Comment by appleguy** [comment]
@richardoti what made me a bit concerned is it seemed some things had width / height /in the initializer method/, rather than just properties that the node computes.  That's not a normal pattern and may be contributing to the issues here.

I'd recommend refactoring that stuff, and completely eliminate the height / width properties.  Any issues you run into from deleting them should lead you to the areas that would benefit from refactoring.

BTW, for the inset, a great pattern would be to create an ASInsetLayoutSpec in the cell node's -layoutSpecThatFits: method.

**Comment by appleguy** [comment]
Make sure you are indeed still running against master, as when I switched from 1.2.3 to my locally checked out copy of master, the rendering of the rasterized version significantly improved.  It's not all that far from correct...there are some components of the cell that are at the wrong y-position, but I believe these issues may be related to how you're integrating with the layout system.

Once you're comfortable building against master as a dependency of the project, then adopting /either/ -calculateLayoutThatFits: or -layoutSpecThatFits: will really help us isolate the issue.  Right now, with code split across -calculateSizeThatFits: and -layout, it's much more difficult to tell.

Of course, I'm sure you'd like to contribute some of this back upstream to Wall (which would be really, really cool!  I'd love to have it as an example app here too!) — so I will continue expediting the work to get a 2.0 stable version out.  My current plan is to have the 2.0 final build out later this month, rather than originally scheduled November.

However, because so many people are using 1.2.3 with some bugs that have been fixed in master, I'm going to push a 2.0-beta in the next couple days and mark it as the stable project version.  The thinking behind that is unusual, but simple: all of the 1.2.3 areas of the API are very stable (indeed, moreso than 1.2.3), and there are only a couple small details of the 2.0 API that may change before the GM (simple property name changes, for somewhat less commonly used things like .flexGrow or -recursivelyEnsureDisplay ... all of which would be trivial to fix if we determine better names).

Let me know as soon as you have any updates here and I'd love to take a second look.  It is very important to me that rasterization is working correctly in all cases we can find, and it is possible you have identified a framework bug here.  In the event that you're not interested in refactoring the code to use the newer layout patterns, just let me know that too, and I will spend more time next weekend trying to suss apart whether it is an app or framework issue.

**Comment by richardoti** [comment]
While trying to introduce `ASInsetLayoutSpec` in `FooterNode`, which, I think, the easiest for trying it out, I got a question:
In docs it's mentioned that `ASInsetLayoutSpec` should have only one child. Am I correct, that then I should wrap all the subnodes into one parent node and apply `ASInsetLayoutSpec` to it? Similarly, how `UICollectionViewCell` has a property `contentView` ?

**Comment by appleguy** [comment]
@richardoti I'm so glad to report that this was in fact a framework bug.  It is now FIXED!  Thank you, @garrettmoon!

The change that resolves it is https://github.com/facebook/AsyncDisplayKit/pull/710.

I tested your code locally and it works fine with this.  As I alluded to before, I was pretty torn by the fact that there were any visual differences with the rasterize mode on, as it should not be the case even if the layout code is not ideally factored.  I can imagine certain substantial misuses of the API that might cause that, but although I didn't completely understand the layout implementation in your test code, it did implement both -calculateSizeThatFits and -layout — so it should work.

That said, I'd love to help you adopt the 2.0 layout constructs if that is something you're interested in.

Depending on your layout, indeed it may be important to set a non-zero minimum size.  Call -measureWithSizeRange: instead of -measure:.  This is also a new API in 2.0.  We will likely discontinue the -measure API (mark it deprecated) because it is somewhat confusing to have this behavior, where the min size is set to zero by default if you use -measure.

Could you open a new task for us to continue the interesting discussion on the new layout patterns, and then close this one?  The feedback from following your experience trying out the new API is very useful.  Of course, given that there is no documentation, I apologize it will be a rough road to learn some of this stuff — that's entirely not your fault!  So I encourage frequent questions if you find them helpful :)

**Comment by richardoti** [comment]
@appleguy Nice to hear that the bug is fixed!

The point about minimum size makes sense, as now it is zero and this is most likely causes layout bugs.

I will create a new task with better description of the desired layout. BTW, I think it is a good way of writing docs, as there is non-zero probability that somebody is having similar troubles - these newsfeed-like layouts are essential for iOS and mobile in general.

**Comment by appleguy** [comment]
Inset should have only one child, BUT it is very common for it to contain another spec.  Try to avoid creating nodes if their only purpose is containing for layout.  See if you can have the inset spec contain a stack spec or something else instead :)
