### ISSUE TITLE
Potential deadlock from ASDispatchOnceOnMainThread

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#681]
If the main thread is waiting on another thread which creates the first ASDisplayNode, you will get a deadlock from `ASDispatchOnceOnMainThread()` as ASDisplayNode tries to read the screen scale. 

"Why is the main thread waiting on a background thread! Sacrilege!" I hear you say. In my case, what's going on is there's a main queue managed object context that is merging changes from a private queue managed object context, and that latter is the one creating the first node (I create my nodes based on an FRC hooked to that private queue context).

I'm gonna see what I can do to workaround (probably going to create an ASDisplayNode in didFinishLaunching: for the time being, since I've got a lot of work to do), but I wanted to get this issue out there

**Comment by appleguy** [comment]
@adly-holler very interesting!  I'm also engaged to learn you are using ASDK with Core Data, as I have some experience doing that at Facebook (Paper originally used Core Data, but a major port removed it in the second year of development; Facebook used CD in production for a long time, but has also ported to a custom stack).  It is definitely one of the most likely cases I can see that would hit this bug.

It is a reasonable thing to block the main thread on a background queue, naturally just as long as the background queue structurally has no reason to ever want to block on main.  Incidentally, the implementation of the "synchronous concurrency" features I talked about at NSSpain will require blocking the main thread on completion of in-flight rendering in certain cases.  Would love to accept any fix you develop!  Otherwise I will definitely address this in the next week or so.

**Comment by appleguy** [comment]
@Adlai-Holler In general, I try to avoid using +initialize, but I think this could be a valid scenario to use it.

Could we simply call ASScreenScale() in +initialize on ASDisplayNode?  If you could:

- Try that locally in your app just to confirm it addresses the issue in a real-world use case with asynchronous node allocation (sadly, no current example app does this, as I have not finished implementing ASTableView/ASCollectionView-driven async allocation).
- Let me know if you have any suggestions for a more elegant fix than this.

**Comment by appleguy** [comment]
Fixed in https://github.com/facebook/AsyncDisplayKit/pull/1404 .  Please try it in your app too!
