### ISSUE TITLE
EXC_BAD_ACCESS in dispose of ASAsyncTransaction

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#682]
Hrm. This is an intermittent one, pretty rare.
<img width="1719" alt="screen shot 2015-09-23 at 7 59 16 pm" src="https://cloud.githubusercontent.com/assets/2466893/10064509/f63e487a-622d-11e5-8515-699ec4b17de7.png">

**Comment by appleguy** [comment]
How many times have you seen it?  What is the UI flow at the time—scrolling an ASTableView?  ASCollectionView?  Quickly, normally?

Fortunately I am very actively working in this code and have it fresh in mind.  If I can get as much information as you have on this, even without a test case, I may be able to fix it.

**Comment by Adlai-Holler** [comment]
Cool! So I had an ASTableView up, scrolling through it normally. Very rare (only happened once). It's possible the table view was being updated – at the time I didn't have good logging around the table view update process

**Comment by appleguy** [comment]
@Adlai-Holler I spent some time looking at this, don't have a conclusive solution yet but the diff above may help.

You should definitely uncheck the "collapse stacks" thing in the Xcode side window...there are a few stack frames that I really want to see to better understand this, but appear lost forever :).

Thanks again for the report, hope to fully understand this one as soon as we see it again and collect more details.  Pinterest's work is just now generating large new implementations based on ASDK (the first screen of which is now in a public experiment), so in a few months we will have a better sense of even the rarest crashes.

One reason I'm so interested in this is that I haven't seen an ASDK crash outside of the Table / Collection classes for a very, very long time.  It needs to be structurally impossible for this framework to crash, and so I want to follow up on any examples otherwise.  I think there are still some rare cases where Table / Collection can crash, so implementing better thrash tests that expose any issues is high on my list.

**Comment by Adlai-Holler** [comment]
OK I'll definitely get you all the data available if it happens again. 

Since you mention table/collection stability, I've opened up #684 which I think is one of the only remaining sources of data integrity problems with those famously-tricky classes.

**Comment by Adlai-Holler** [comment]
Haven't seen this since the one instance and I've used ASDK a lot. @appleguy Naturally you're welcome to reopen it you want
