### ISSUE TITLE
ASLayoutSpecs should use bounds and position to layout as opposed to frame if transform is non-identity

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#700]
Currently, ASLayoutSpecs use frame to layout layers and views, however if laying out a layer with a non-identity transform, setting the frame isn't valid (and in fact asserts in ASDisplayNode+UIViewBridging), instead bounds and position should be set.

Any chance you'd be interesting in looking at this @nguyenhuy?

**Comment by nguyenhuy** [comment]
Well, firstly, just to be 100% precise, ASLayoutSpecs don't layout backing stores (--i.e layers/views). If you are talking about laying out subnodes, it's actually done by the parent node ([here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L1640)). 
But yeah, frame is used while laying out subnodes. And it has been like that since the beginning. I don't have the knowledge of why it was decided that way in the first place (perhaps @appleguy or someone else does?). That's said, I agree with you that setting frame isn't safe in some cases. And since frame is just a computed value (calculated from position, bounds and anchorPoint), I think we can instead use bounds and position.

Do you have a diff ready to go? I can give it a try if you don't have time for this :)

**Comment by appleguy** [comment]
Right, makes sense that we are just computing ASLayout objects and then it is actually an ASDisplayNode task to set the values on subnodes.

Huy, if you have time to draft a patch, it would be appreciated--we haven't attempted yet.  I have a few other things higher on my ASDK list.  I'm hoping this change is simple because it should have essentially that one override point, and not require changing each layout spec.

**Comment by nguyenhuy** [comment]
Yes, the change should be pretty simple. I will work on this in the next couple of days.
