### ISSUE TITLE
ASTableview and contentSize

### ISSUE THREAD

**Issue by petrpavlik** [facebook/AsyncDisplayKit#702]
Hi, I'd like my `ASTableView` to scroll to bottom after it's content was updated but the table view seems to have it's old content size when the completion block of `endUpdatesAnimated ` is called. How would you suggest to implement what I want?

```Swift
tableView.beginUpdates()
tableView.reloadSections(NSIndexSet(index: Sections.TypingIndicator.rawValue), withRowAnimation: .Automatic)
tableView.endUpdatesAnimated(true) { (completed: Bool) -> Void in
        // Content size has not been updated yet so this does not work
        self.scrollToBottom()
}
```

**Comment by nguyenhuy** [comment]
Hi there. It looks like a vlid approach. How do you implement `scrollToBottom`? I use `-scrollToRowAtIndexPath:atScrollPosition:animated` and it works at expected.

**Comment by appleguy** [comment]
@petrpavlik thank you for reporting this!  Indeed, I've confirmed you are correct.  This is definitely not ideal behavior, although I can understand why it's happening and am wondering if there is a better fix than the most obvious one.

A workaround would be to use the method @nguyenhuy mentioned.  It should solve your problem and is a stable solution.  In fact, I'd argue that it is more readable code than using contentOffset manually anyway.

However, the reason you're seeing this is that UITableView has not performed its layout pass yet, which happens at the end of the runloop.  It's only there that the new contentSize will be set.  I would be interested if you could test this with a regular UITableView, but I believe right after you call -endUpdates (obviously it has no completionBlock) you will see the same thing!!

The fix would be to force layout (-layoutIfNeeded) on the table view.  We could also implement a test to check that the contentSize is updated in time.  The downside is that this could very well trigger unnecessary layouts and have a performance cost associated.

**Comment by appleguy** [comment]
This diff does resolve the behavior, ensuring contentSize is updated in the completion block.  HOWEVER, simply calling -layoutIfNeeded does not resolve it as I expected.  Deferring the callback to the next runloop turn has an important downside, which is that some operations the developer may wish to perform which must happen in the same runloop in order to guarantee no flicker / jumping may not be possible to implement...

I don't have an idea yet for an ideal solution to this, as it's particularly unusual to me that UITableView is not updating the contentSize even with an opportunity to lay out.  I would say we need to check what the base UITableView class does after begin/endUpdates (does it update the contentSize immediately, or is it on the next runloop?).  If UITableView does update it right away, there is probably a mechanism to get this to work as desired.  If not, we'll have to call it expected behavior that is limited by the internals of UIKit.

[Around like 676 in ASTableView.mm]

diff --git a/AsyncDisplayKit/ASTableView.mm b/AsyncDisplayKit/ASTableView.mm
index 7c36c77..4391c66 100644
--- a/AsyncDisplayKit/ASTableView.mm
+++ b/AsyncDisplayKit/ASTableView.mm
@@ -673,7 +673,9 @@ void ASPerformBlockWithoutAnimation(BOOL withoutAnimation, void (^block)()) {
   });
 
   if (completion) {
-    completion(YES);
+    dispatch_async(dispatch_get_main_queue(), ^{
+      completion(YES);
+    });
   }
 }

**Comment by petrpavlik** [comment]
Thanks, @nguyenhuy's solution seems to work just fine.
