### ISSUE TITLE
Regression on "ASCellNode sized incorrectly by ASTableView if delegate not set"

### ISSUE THREAD

**Issue by RuiAAPeres** [facebook/AsyncDisplayKit#703]
**Note:** This is related to #299. 

The sample project can be found [here](https://dl.dropboxusercontent.com/u/14102938/TestDelegate.zip) and it was build with the following:

* Xcode 7.0.1 (7A1001)
* Carthage 0.8.0
* The AsyncDisplayKit framework was build using [c8518c7fa6304f99db84b5480afce8f0b6ddb66e](https://github.com/facebook/AsyncDisplayKit/commit/c8518c7fa6304f99db84b5480afce8f0b6ddb66e)
* Tested on simulator iPhone6s Plus with iOS 9.0

**Expected results:**

* Independently of line 21 on ViewController.swift (`self.tableView.asyncDelegate = self`) being commented or not, the cells will have a random size.

**Actual results:**

*  If it's commented, the cells height will use the default one (49points). If not, they will have a random size.

![test5](https://cloud.githubusercontent.com/assets/949286/10265972/2d53a554-6a3e-11e5-83c9-17600a7af7c8.gif)

**Comment by appleguy** [comment]
@RuiAAPeres Thanks for the test project!

I think what's happening here is that ASTableView is not properly implemented to handle a nil asyncDelegate.  Clearly that is a bug, because it doesn't trigger an assertion or anything as it exists today.  Looking at the code, what will happen is that key UITableView delegate methods don't get hooked up, because those are done via a proxy object that currently relies on asyncDelegate being set.

You may not like this as a solution, but the easiest fix would be to enforce that asyncDelegate gets set.  There are certainly other ways to fix it that don't require that, but it would take a little more work — and I'm not sure it is the best use of time (relative to other improvements, supporting a nil delegate in ASTableView / ASCollectionView seems of low value).

If you have any interest in attempting a patch that would allow it to support a nil asyncDelegate, by all means, give it a shot!  If not, just let me know and I'll add some assertions to make sure the delegate gets set, a make a TODO or Github Issue to track further improvement.

**Comment by RuiAAPeres** [comment]
@appleguy in order to keep the internals simple, an `Assert` could be the best course of action. Although I will have a look later, on how the proxy is being done and how much changes would be needed to support a `nil` delegate.

**Comment by appleguy** [comment]
@RuiAAPeres I went ahead and fixed it the right way.  Could you please test the PR?  It works with both a table and collection test project, but I didn't take the time to figure out how to run a local build against a Carthage project (something I'd like to know how to do, just not a Sunday evening thing :) ).

https://github.com/facebook/AsyncDisplayKit/pull/706

Once you give it the go-ahead, I'll land.  Thanks again for reporting!

**Comment by appleguy** [comment]
@RuiAAPeres ping - let me know if you have a chance to hit the "checkout locally" button and try out the PR with your use case.  Since I don't have a comparable one locally I want to be sure it works properly for your case.

**Comment by RuiAAPeres** [comment]
@appleguy sorry for the delay. It works! :star:

**Comment by appleguy** [comment]
Phenomenal, thank you!!
