### ISSUE TITLE
Facebook Timeline layout in ASDK 2.0

### ISSUE THREAD

**Issue by richardoti** [facebook/AsyncDisplayKit#712]
This discussion is moved from #649.
Initial working branch (Fork for ASDK 2 development): https://github.com/richardoti/Wall
Stable version of the Wall: https://github.com/hyperoslo/Wall

The repo for ASDK 2 development would not build after checkout.
Instructions, how to make it work are in #649 

The desired layout looks like this, which is close to Facebook Timeline layout.
![artboard 1](https://cloud.githubusercontent.com/assets/8013017/10299303/b7d4156e-6be8-11e5-9494-cdb5f0f3eccc.png)

Violet - header/footer (more complex nodes)
Blue - images (they're wrapped into separate node)
Yellow - ASTextNode
Gray - empty space.

By replacing manual layout code with the following I've managed to get almost the same layout as before. Now there is a need to replace manual layout in children nodes as well.

```Swift
  public override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec! {
    var nodes = [headerNode, attachmentGridNode, textNode, footerNode, divider, actionBarNode]

    if !hasAttachments {
      nodes.removeAtIndex(1)
    }

    let stack = ASStackLayoutSpec(direction: .Vertical,
      spacing: verticalPadding,
      justifyContent: .Center,
      alignItems: .Center,
      children: nodes)

    let insets = UIEdgeInsets(top: verticalPadding,
      left: horizontalPadding,
      bottom: 0,
      right: horizontalPadding)

    let insetSpec = ASInsetLayoutSpec(insets: insets,
      child: stack)

    return insetSpec
  }
```

**Comment by appleguy** [comment]
@richardoti how very cool!  I would love to use the code you end up with as an example.  Having the colored box representation drawn up is a big help too.  If you were supportive of the idea, we may even integrate it into the eventual programming guide / walkthroughs for ASDK 2.0.

Let me know as soon as you run into any questions / issues with the remaining conversion.

**Comment by richardoti** [comment]
@appleguy that's nice to hear! I guess, other iOS guys at Hyper may be happy of that as well.
I think, a good docs could be extracted from these discussions afterwards.

So, my next step is to refactor layout in each of `nodes`.
If I start from the bottom one (violet) `actionBarNode`:
Where should I call `measureWithSizeRange` ?
If I call it in `layoutSpecThatFits` of parent node, the output of `constrainedSize` in method `layoutSpecThatFits` of child node has still minimum of `zeroSize`, the node collapses.

But when I specify `preferredFrameSize` inside the node itself, it does own layout more or less correctly.

**Comment by appleguy** [comment]
@richardoti note that it is valid to mix and match the layout types.  You /should/ be able to have subnodes use -calculateSizeThatFits / -layout (or better, port them to the manual-but-consolidated version, -calculateLayoutThatFits:, which eliminates -layout).  That's true even if the containing node uses -layoutSpecThatFits:.

-measureWithSizeRange will be automatically called on the ASCellNode by the containing table / collection.  The actual call is in ASDataController.mm if you are interested to understand it.  There may now be an API to provide a full size /range/ for constraining the cell nodes — I think this was added recently.  If not, it would be trivial to add.

That said, by using preferredFrameSize, you should normally not need to use the minimum size on the size range.  If you encounter any problems with the layout system where it's not clear how to achieve the right layout, please post here.

**Comment by richardoti** [comment]
I've already managed to port almost all of the layout  to `calculateLayoutThatFits` and it seems to work more or less fine.

I have a question about specific layout of photogrid. What my aim is this layout of the last picture.
![screen shot 2015-10-07 at 01 18 32](https://cloud.githubusercontent.com/assets/8013017/10325393/5d5a7f20-6c91-11e5-8afb-d351c943b3b2.png)![screen shot 2015-10-07 at 01 03 26](https://cloud.githubusercontent.com/assets/8013017/10325155/486c4b22-6c8f-11e5-8675-20eca1db98d4.png)

Right now it consists of 3 nodes:
* ASNetworkImageNode
  * ASDisplayNode (black transparent)
   * ASTextNode (+4)

And my questions are as follows:
Is this implementation too costly performance-wise (rendering semi-transparent nodes)
Is there any way to eliminate black transparent node (2nd in the hierarchy) by some way making ASNetworkImageNode a bit darker?

**Comment by appleguy** [comment]
@richardoti very cool!

Have you taken a look at .imageModificationBlock yet?  This should be able to do what you're demonstrating, and on older devices, will help scrolling performance...at the cost of /slightly/ longer time to prepare the image.  It's a pretty good tradeoff overall.

Note, if you are enabling shouldRasterizeSubnodes on the parent (e.g. cell) anyway, then this essentially won't matter because the whole hierarchy will be collapsed.

Important note about shouldRasterizeSubnodes: ideally, you should structure your hierarchy in a way that allows you to AVOID including network-loaded images (particularly big ones) and large blank areas in the rasterization.  If a big network loaded image is included, then when it loads, it will cause everything else in the rasterization area to have to be redrawn.  Plus, blank space is part of the same rasterization area, and memory is spent on it.  In the scheme of things, these are actually smaller optimizations, and you will still notice big performance improvements from rasterization in many cases even without doing it.  But the rule of thumb is that views are not ALWAYS bad, and you may want to have a rasterized node for your feedback interface at the bottom of the cell, a rasterized node for the header information at the top, and leave the photo itself (and padding around it) outside of a rasterized zone.

The +4 example you give here, even if you have it network-loaded, would be pretty reasonable to rasterize as re-drawing the +4 is not particularly expensive, and the rasterization will collapse the overlay effect for you.  But I think it's probably better overall to use imageModificationBlock and leave rasterization off, unless you had the asset locally stored rather than network-loaded..

**Comment by richardoti** [comment]
After refactoring `AttachmentGrid` to use new layout system - `calculateLayoutThatFits`, removing middle semi-transparent black node and adding `ASTextNode` with "+4" text directly in `AttachmentGrid` performance improved a lot even without enabling rasterization.

I think, using CoreGraphics for making last image darker inside `imageModificationBlock ` has given quite big boost. Enabling nodes to be `layerBacked` also played not the last role here.

I thought about node structure and came up with one compromise: 
What do you think about enabling `shouldRasterizeSubnodes` in all the post elements, but not post itself? This will prevent ASDK from rasterizing whole post when, for example, only author's avatar has been downloaded. If speaking related to the picture I've provided it means enabling rasterization on every node except `Gray` area.

The one issue I've come along with is when enabling  `shouldRasterizeSubnodes` on separate imageNodes, or on `AttachmentGrid` as a whole, there is some slight delay (0.3 - 0.5 sec) in image rendering, but the scrolling becomes extremely smooth. What I mean is when I scroll fast and then stop, I have to wait for the rendering and I see only placeholders.

Without rasterizing, scrolling is almost stall-free but no delays in rendering are observed at all.

**Comment by appleguy** [comment]
@richardoti rasterizing each of the individual components, without doing it for the cell itself, is a good approach.

You may consider extending your working range (rangeTuningParameters, for either network or rendering) if you are seeing blank placeholders onscreen too frequently.  If you scroll extremely quickly though, you have to choose: either you drop frames, or you allow some unrendered content onscreen.  I'd encourage you to experiment with the rather amazing new property, .neverShowPlaceholders, on ASCellNode.  If you set it to YES, it should prevent placeholders from ever being onscreen.  The effect is that slow and normal speed scrolling remains perfectly smooth (as long as the working range is big enough), but high speed scrolling starts dropping frames in order to ensure there is never a totally blank element onscreen.

**Comment by zdenektopic** [comment]
I was trying really hard to find branch or repo for ASDK 2.0 that you are talking about here, but I wasnt able to find neither. Where can I get it?

**Comment by richardoti** [comment]
@zdenektopic It's just the master. As ASDK 2.0 is not released yet (some part of API naming may change.
Described here: https://github.com/facebook/AsyncDisplayKit/issues/649#issuecomment-145416994
In that issue you can also find the way how to point dependency (for example, Wall) to a specific commit of ASDK.

**Comment by richardoti** [comment]
Answering own question about aligning `TextNode` (big yellow box):

"Also, I would like to fix `textNode` width to be always 100% as well, even if it has only one line of text. Subclassing and overriding `layoutSpecThatFits` will solve the problem, but I guess, a better solution exists."

If using `ASStackLayoutSpec` it is as easy as `textNode.alignSelf = .Start` while all the other layout is being aligned with `.Center` parameter.
![screen shot 2015-10-09 at 10 08 45](https://cloud.githubusercontent.com/assets/8013017/10388847/bf3acb54-6e6d-11e5-8361-2ef67ab7e035.png)

**Comment by appleguy** [comment]
@richardoti thanks for all the discussion here, and especially the visual aids — both for others' reference and for this conversation?

I fell behind a bit, but could you ping my username if you have a further question?  Reopen this task or open a new one if so.

**Comment by richardoti** [comment]
@appleguy I've finished the layout and performance optimization, but still there are some stalls on iPad 3. I find the reason for stalls is high CPU usage, but not blocking the main thread (in that case CPU usage is usually low).

I haven't looked at ASDK architecture in deep, but it seems that the high amount of view initializations being performed during high-speed scrolling is the case for slowdown. 

This is the same layout implemented in UIKit with cell reuse and it seems to be stall-free:
https://github.com/RamonGilabert/Wall

I think that ASDK was simply not best fit for this kind of layout - the cells are exactly the same, without any layout difference. ASDK would fit views that have rich content layout that is different across the elements of collection, where cell-reuse pattern is difficult to implement.

Here are all performance improvements made by me:
https://github.com/hyperoslo/Wall/pull/94
and some of the ideas can be applied to both ASDK and UIKit performance optimizations.

But I still continue to follow the ASDK project as it is interesting and it will find place in my future iOS apps for sure :smile:
