### ISSUE TITLE
ASCollectionView with UIViewControllers as cells.

### ISSUE THREAD

**Issue by RuiAAPeres** [facebook/AsyncDisplayKit#716]
I started replacing my previous solution (a `UIPageViewController`) with a `ASCollectionView`,since it would allow me create cells ahead of time (working range). The thing I am seeing and is validated by this #540, is that the cells won't be deallocated, so the `UIViewController` it has as a subview, will be kept alive. After scrolling  for about 50 cells, the app eventually gets killed due to memory constrains. What would be the best approach in this case? 

After seeing @ryanfitz's approach by keeping a reference to the header node and then calling `recursivelyClearContents` is something I am contemplating, but I wonder if I am missing something here.

The cell itself is quite simple and the mechanism maybe slightly archaic:

```swift
class ViewControllerCellNode : ASCellNode {
    
    let size : CGSize
    let viewController : UIViewController
    
    init (size: CGSize, viewController: UIViewController) {
        
        self.size = size
        self.viewController = viewController
        
        super.init()
        
        self.backgroundColor = UIColor.lightGray()
    }
    
    override func layout() {
        super.layout()
        
        self.viewController.view.frame = self.view.bounds
    }
    
    override func calculateSizeThatFits(constrainedSize: CGSize) -> CGSize {
        super.calculateSizeThatFits(constrainedSize)
        return size
    }
    
    override func didLoad() {
        super.didLoad()
                
        self.view.addSubview(viewController.view)

    }
    
    deinit {
        print("ViewControllerCellNode deinit")
    } 
```

I understand the need to get all the different cells in order to calculate the size of each cell. But my expectations were: if a cell is out of the working range, it should be purged.

**Comment by appleguy** [comment]
@RuiAAPeres This is actually a high priority feature that I would like to add to the framework, and has an immediate use case in the Pinterest app.  I would like to provide an out-of-the-box paging component that can take either nodes or view controllers (especially ASViewControllers, as they provide the important -neverShowPlaceholders option that some developers may need).  Supporting regular UIViewControllers wouldn't be hard.

I think the right approach is a subclass of ASCollectionNode, called ASPagerNode or something, which sets up the UICollectionViewFlowLayout automatically.

Assuming you are talking about full-screen paging, it may be important to change the default values for rangeTuningParameters to dial back how much is done to render-ahead, and how long it waits to clear contents for stuff going offscreen.

You should definitely override the -clearContents or -clearFetchedData methods to participate in the memory-culling features.  The existence of the UIViewController object itself, along with the ASCellNode itself, should be an absolutely negligible amount of memory — even with over 1,000 objects, it should be at most a few megabytes, nowhere close to enough to be the primary cause of memory pressure.  I would love to help debug any memory pressure issues if you are unable to determine why they are happening.  If you have everything hooked up with nodes, without the UIViewController in between (e.g. you use an ASCellNode directly), then all the image nodes / text nodes / etc will free their large memory-hogging backing stores automatically (they override the methods I mentioned).

There is a little bit of trickiness to working with UIViewController in this context.  It breaks the node hierarchy and so that could affect delivery of these critical recursive notifications.  One solution for this would be to provide an ASViewControllerNode, taking a UIViewController and providing a "node" object that you can put in the node hierarchy.  We would want to think a little bit about the API here and how it relates to ASViewController, understanding that some superclasses (UITableViewController, etc) can't be easily switched to be ASViewController-deriving.  The medium-term strategy I've had here is to provide AS versions for those small numbers of key Apple-provided classes where the superclass can't be changed (table, collection, etc view controllers).  For other controllers, developers should generally have the ability to do the trivial swap of the superclass from UIViewController to ASViewController without breaking /any/ existing use cases, so I think that could be the right strategy as some of this comes together.

If we did rely on ASViewController, then we could provide a .node property in a built-in way, and wouldn't need the confusing-sounding ASViewControllerNode.  Another way to avoid that unfortunate class would be manually implementing a -node method on your own UIViewController subclasses (maybe this could be done in a category method on UIViewController!), and creates the node with -initWithViewBlock:, where it sets the node.view = self.view (view controller being self) — that could work really well.

Sorry for the rambling, writing from a meeting (lol).  I would really love to work with you or anyone else interested in pulling together an official solution for the "paging" use case, as it is a phenomenally impactful use case for ASDK (avoiding the universally problematic interaction stall on each swipe as the next offscreen controller is loaded on the main thread).  Let me know what you think, and if you're interested in doing some of the work to commit back to the project (it should be a medium-sized project, not huge).  Don't worry at all if you can't do that right now, as I'll start asking around the community to look for someone who might be able to help.  Since you have a use case in addition to Pinterest's, that's enough for me to feel like it is time to prioritize this work and reach a solution in the next week or (max) two.

**Comment by RuiAAPeres** [comment]
> You should definitely override the -clearContents or -clearFetchedData methods to participate in the memory-culling features

Okay, so that's what I missed.

>  If you have everything hooked up with nodes, without the UIViewController in between (e.g. you use an ASCellNode directly), then all the image nodes / text nodes / etc will free their large memory-hogging backing stores automatically (they override the methods I mentioned).

The whole thing would look like this: 

-> ASCollectionView 
     |
      -> ASCellNode
           | 
            -> UIViewController
                 |
                 -> ASTableView
                  |
                   -> ASCellNode
                   -> ASCellNode
                   -> ASCellNode

So I am missing the "connection" between the first `ASCellNode` and the `ASTableView`.

> One solution for this would be to provide an ASViewControllerNode

There is a class named [ASViewController](https://github.com/facebook/AsyncDisplayKit/blob/c8518c7fa6304f99db84b5480afce8f0b6ddb66e/AsyncDisplayKit/ASViewController.h) which I tried to use, but I would just get a crash every time the `view` property would be accessed. So instead of dealing with my VC, I just used a `ASViewController` instead an added the node to the cell's hierarchy. 


I am really interested on digging into AsyncDisplayKit and being able to contribute with something. I will have a bit more time in the next week, right now I am completely tied up. :/

**Comment by appleguy** [comment]
@RuiAAPeres thanks for the details!  I better understand your use case now that I see the ASTableView there.

Unfortunately, this will be a little more complicated than I described, mainly because of the table view.  If you were to use a vertically-scrolling ASCollectionNode instead, it would work more smoothly.  I am planning to add an ASTableNode, which will be very trivial to create (10 minutes or so), but it's not there.  So, not going to obscure the facts: this use case (particularly containing UIViewControllers) is NOT well supported by ASDK today, and there are a slew of small and medium-sized changes needed to enable it.

I'll make it a priority to map out the work needed here, such as some of the more tricky API design questions.  Is this an active blocker for your work today, or would it be OK if we started making progress on it next week?  It will probably take me until the end of this weekend to properly design an API direction here, although I may be able to also execute some of that direction.  With luck, next week we can have a couple community members (maybe 1-2 others and yourself, if available), to finish up the work within a few days.

**Comment by RuiAAPeres** [comment]
> Unfortunately, this will be a little more complicated than I described, mainly because of the table view.

Moving to a `UICollecitonView` from my side would be straightforward. 

> Is this an active blocker for your work today, or would it be OK if we started making progress on it next week?

Yeah, it's definitely ok for now. The current solution with a `UIPageViewController`, is performing well.

>  With luck, next week we can have a couple community members (maybe 1-2 others and yourself, if available), to finish up the work within a few days.

That would be awesome, please just ping me.

**Comment by RuiAAPeres** [comment]
@appleguy ping. Any update on the ASViewControllers? :dancers:

**Comment by appleguy** [comment]
@RuiAAPeres sorry for falling off the grid on this.  I got sick twice, and still am under the weather...have to prioritize catching up on Pinterest work first :).

This work is still critical.  I think it is one of the best / most valuable extensions in the project feature set to be done this year.

If you have time or interest to take a pass at it, feel free.  If you email me at asyncdisplaykit@gmail.com I'll give you my iMessage info so we can coordinate on API design, etc.  We will ultimately need this for Pinterest, so if no one else gets to it, later this year we will need to.  Heads up that if I don't get the time to do it personally (as I had planned, and still hope to / but is looking uncertain now), it could take through November for another engineer at Pinterest to have time.

**Comment by RuiAAPeres** [comment]
Hey @appleguy, would you recommend a different approach, while there is no ViewControllerNode?

**Comment by appleguy** [comment]
This is now implemented - thanks @lappp9 !  -[ASCellNode initWithViewControllerBlock:].

**Comment by appleguy** [comment]
We're using it at Pinterest to pretty great effect, since it calls the lifecycle / appearance methods automatically and integrates perfectly with ASPagerNode.

**Comment by appleguy** [comment]
@RuiAAPeres please email or message me if you do try this out and find any problems with it!! (or open an issue)
