### ISSUE TITLE
General UIKit question: Animating to reveal an image's full contents

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#730]
so its clear. I have positioned nodes in `ASCellNode` subclass using `ASLayoutSpec`.
then I select cell and toggle nodes position. I want this repositioning be animated. I wrap the toggle method in a UIView block based animation. just a **popcorn effect**! 

if I use pop framework, I have to manually set `toValue=[NSValue valueWithCGSize:CGSizeMake(self.calculatedSize.width, 10)];` first: it doesn't animate  second: I have used `ASLayoutSpec` to not calculate final frame manually!

so any idea?

**Comment by hashemp206** [comment]
here is what I do:

```objective-c
- (void)toggleImageSize
{
    _imageNode.preferredFrameSize = CGSizeMake(self.calculatedSize.width, 40);
    //from view final frame should be selectedCell final frame
    POPSpringAnimation *springAnimation = [POPSpringAnimation animation];
    springAnimation.property = [POPAnimatableProperty propertyWithName:kPOPLayerSize];
    springAnimation.springBounciness=4;    // value between 0-20 default at 4
    springAnimation.springSpeed=5;
    springAnimation.toValue = [NSValue valueWithCGSize:CGSizeMake(self.calculatedSize.width, 40)];
    [_imageNode pop_addAnimation:springAnimation forKey:@"pop"];

    [self setNeedsLayout];
}```
![collectionview expand](https://cloud.githubusercontent.com/assets/3206748/10412331/35570c18-6f8f-11e5-9aab-a4dbdf2f6ef4.gif)

why _imageNode height doesn't animate?

**Comment by appleguy** [comment]
@hashemp206 what effect are you trying to achieve here?  Presumably you do not want the image stretch out to the taller height, right?  Do you want it to "reveal" more of a clipped image?

If you think about it, that's a very different interaction than just expanding a view with an existing backing store.  You need some mechanism for the system to have the fully-decoded image in memory, but dynamically clipping it, then animate the area that is clipped to reveal more.  This is possible, in two separate ways that can be recommended, but can't be done by setting the bounds of the image (try it with UIImageView, or CALayer with its contents set, too — it won't work there either).

The two approaches, easiest and then slightly harder but more efficient:
1. Put the image node inside of another node (same for an image view, inside of another view).  Enable .clipsToBounds on the outside / containing view.  At the start of the animation, set the frame of the inside image node to the full size it needs to expose, and then call -displayImmediately on it to force the full thing to display before the animation starts.  You could leave the inside image node always at full height, and it would look correct because the containing element has clipsToBounds enabled, but this would mean that a large amount of additional memory is used even if the user never expands the image.  ASImageNode is smart enough to automatically save memory by decoding the image directly to the size available to the node, so it will be more efficient if you set its frame to be smaller.
--- Then once the image is fully displayed (the containing node will still be clipping it), you can simply animate the bounds / size of the containing node, and it will smoothly reveal the rest of the image.

2. Something you can do with a single element (whether layer, view, or node) — is a special property on CALayer called contentsCenter that allows you to specify what part of the backing store should be used.  It takes some careful manipulating but you can use this to achieve the effect.  Probably not the best way to go for this implementation though.

As always, feel free to upload a test project so we can work more quickly on this stuff.

**Comment by hashemp206** [comment]
my goal is to animate layout changes!
Here is a sample code:
(Cell Alignment)[https://www.dropbox.com/s/btci3i0fcvc58dl/ASCollectionView%20Cell%20Alignment.zip?dl=0]
I want to by tapping cell animate new alignment.

I have another sample with exact same code  but cell selection not work. and also imageNode corner radius doesn't apply!! 😳
(cell selection)[https://www.dropbox.com/s/yliwgmw47yzle43/layoutSpec%20cell%20selection.zip?dl=0]

**Comment by appleguy** [comment]
@hashemp206 thanks a lot for providing the sample code!  I apologize that I have not been able to get to this question yet.  There have been a lot of questions asked recently, which is really exciting and makes me quite happy :).

Other community folks - @eanagel, @levi, @nguyenhuy et al - feel free to take a look if you have a few minutes before I do.  This weekend will probably be my best chance.

**Comment by appleguy** [comment]
Heh, sorry I /still/ haven't gotten to this.  @hashemp206 are you still working in this area/would an answer be useful?  If so, just reopen the task and someone in the community will likely be able to help you out soon.  Cheers!

**Comment by hashemp206** [comment]
thanks for looking into discussion. I just only used ```- (CGSize)calculateSizeThatFits:``` and ```- (void)layout``` methods. when I change cell frame and their contents, cell and its subviews animate well. but using ```- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize```  animating items doesn't work.

thanks 
let it be closed.
