### ISSUE TITLE
How make a square on ASNetworkImageNode 

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#732]
Guys help pls. I try make `ASLayoutSpec` for build layouts in my cell and have a task:'Make square image depend of screen size.width". Yes i can just get UIApplication.window... and get size in `self.bigImage.preferredFrameSize`, but its not good style. i think so :/ What i need do for solve this tsks with rules of ASLayoutSpec and etc instruments?

**Comment by nguyenhuy** [comment]
Firstly, the rule of thumb is that your layout spec should depend on the constrained size, instead of the actual screen size or UIApplication window.

To make a square node, you can use ratio layout spec. 

To calculate the image width based on the constrained width, you can use [`Percent`](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASDimension.h#L20) type of `ASRelativeDimension`. If your image node is wrapped inside a (horizontal) stack layout spec, you can use [flexBasis](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASStackLayoutable.h#L48). Otherwise, you can use [sizeRange](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASStaticLayoutable.h#L21) inside a static layout spec. Example code:

```objective-c
ASRatioLayoutSpec *squareImageSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:1 child:_imageNode];
squareImageSpec.flexBasis = ASRelativeDimensionMakeWithPercent(0.4);
  ```

That's said, in many cases, it's actually easier to calculate the width yourself and use `preferredFrameSize`.

**Comment by nguyenhuy** [comment]
And of course, you can always create a custom layout spec that encapsulates your width calculation.

**Comment by appleguy** [comment]
@bimawa @nguyenhuy has you covered!  Great advice, including the focus on driving this stuff with constrainedSize.  At the top level, do you have a table view, collection view, view controller?  Whatever is at the top should be where you apply the more traditional layout, e.g. setting the frame size to be as wide as the window.

Close out this task when your question is answered, but feel free to ask us more stuff either here or in a new task.

**Comment by bimawa** [comment]
Thx a lot guys! I try it on next week.

**Comment by bimawa** [comment]
@nguyenhuy Thx its:
```
ASRatioLayoutSpec *squareImageSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:1 child:_imageNode];
squareImageSpec.flexBasis = ASRelativeDimensionMakeWithPercent(0.4);
```
what i need ! thx a lot!
