### ISSUE TITLE
General ASLayoutSpec Questions

### ISSUE THREAD

**Issue by lappp9** [facebook/AsyncDisplayKit#739]
Hey @nguyenhuy, here's the issue as promised.  

I experimented a little more tonight but didn't make much progress.  I'm sure it'll be easy for you to see where the mistakes are.  Here's a demo project of what I have so far on the cells.  The only problems at the moment are that the +1 isn't inside the gray circle for the profilePictureGroupNode, the likes aren't aligned to the right, and when the message has an image, the text should be added to the bottom of that image.  

Oh, also, I can't get the profileGroupNode to layout without wrapping it in a staticLayoutSpec which doesn't seem like it should be necessary.  I assume I'm doing something with its layout wrong too but maybe thats just the way it works?

[Demo App](https://github.com/lappp9/layoutPractice)

Thanks again and let me know if I need to clarify anything!

<em>What I have so far</em>
![current](https://cloud.githubusercontent.com/assets/432875/10496685/90bb5c1c-7287-11e5-8524-016d324c4a6a.png)

<em>What the table view should look like</em>

<img alt="desired" src="https://cloud.githubusercontent.com/assets/432875/10497074/9b37f612-7289-11e5-8740-7fba30215de3.png">

**Comment by appleguy** [comment]
@lappp9 thanks a lot for providing a test project!  This is a cool one — someday if you wanted to include it in our examples/ directory, it could be a great addition (don't worry, wouldn't do that without you).

The +1 does appear to be within the grey circle.  You mean it's not exactly centered?  Note that "visual" centering of text is pretty hard, because the actual bounding box (space required by the font to accommodate both ascenders and descenders of other characters) is not identical to the visual extent of the character.

I think there is a special property on ASTextNode that allows you to get the visual bounding box, but I'm not sure offhand and would have to look.  It would not be very hard to implement, as the figures are available from lower level CoreText calls.

Same question about the likes — what are they supposed to be aligned with?  It is likely the same kind of issue; text alignment doesn't always work in the way that you want, which is of course equally true with UILabel.  If you were able to get the alignment working perfectly with UIKit using -layoutSubviews or similar, you should also feel confident about not using ASLayoutSpecs for a design that requires careful positioning of text (usually text is not inside of an element that is so small as that circle that it needs to be pixel-centered; the text inside of buttons is often not exactly visually centered).  Instead you could use -calculateLayoutThatFits: or even -calculateSizeThatFits: + -layout, and either approach would allow you to avoid using explicit Static layout specs.

I don't have a chance to run the project until probably this weekend, but do recommend that you set a .backgroundColor on all the important elements involved here to see visually where the extent of their bounds is and therefore observe the rectangles being used by the layout system for positioning.

**Comment by nguyenhuy** [comment]
@lappp9: I've just made a PR in your repo that fixes these layout problems. It's not perfect, but I think it's pretty close to your layout requirements:

![simulator screen shot 14 oct 2015 11 17 02 pm](https://cloud.githubusercontent.com/assets/587874/10496496/d05cf3ac-72c9-11e5-9e73-09b2498c6541.png)


The code aligns text nodes based on their bounds, so they may not be perfectly visually aligned (as discussed by @appleguy). And yes, do set background color on those nodes if you suspect anything wrong :) Let me know if you have any follow-up questions.

**Comment by lappp9** [comment]
Oh sorry, @appleguy, I should have clarified that the image is what I had so far using manual layout.  I should probably include a picture of what the sample project looked like before Huy got it.  Oh also, I'd be totally fine with including this in the examples directory!  Do you want me to just add it once I've got more of the layout stuff figured out?

Thanks @nguyenhuy!  I'm looking through the code now and it's definitely helping me understand this stuff better.  

One thing I noticed is that you're setting `placeHolderColor` on the profile circles but they don't seem to have any kind of placeholder or background color when the image is loading.  I tried just setting the background color but the image's corners aren't rounded anymore so it just shows a gray square in that case.

**Comment by nguyenhuy** [comment]
Yeah I forgot, placeholderColor isn't used while loading image. Setting a solid defaultImage should do.

Image modification block is applied to image (and supposedly defaultImage). If the background color is rendered, it will just fill the entire node, which is a rectangle.

**Comment by lappp9** [comment]
Ok cool, I just used that `imageWithColor` method you added to generate a defaultImage and that worked.

**Comment by appleguy** [comment]
@lappp9 thanks for asking your questions here, and I look forward to answer any other issues you file :).
