### ISSUE TITLE
pod 'AsyncDisplayKit' not pulling down entire pod (1.2.3)

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#742]
The Layout, Details and Private folders are not installing via cocoa pods via pod 'AsyncDisplayKit'

I tried modifying my Podfile to match Kittens example and got the following.
Fetching podspec for `AsyncDisplayKit` from `../..`
[!] No podspec found for `AsyncDisplayKit` in `../..`

Any thoughts please? Thank you

**Comment by appleguy** [comment]
the ../.. specification is for a local path…that’s what the sample apps use to refer to the AsyncDisplayKit implementation that contains them (e.g. it will only work if you are running a project from within the examples directory of ASDK itself).

Are you just trying to point to the latest master or what?

**Comment by robmontesinos** [comment]
Thanks for the quick response. Yes, 

#import <AsyncDisplayKit/ASInsetLayoutSpec.h> gives a file not found error in BlurbNode.m and KittenNode.mm when imported into my project

**Comment by appleguy** [comment]
So you're just trying to run the Kittens app?  Sorry - I am not yet sure what you are indeed working on accomplishing :).

Make sure you run "pod install" from the AsyncDisplayKit directory itself, and then also go into examples/Kittens and run pod install there as well.  If that doesn't work, paste the console output from that process here

**Comment by appleguy** [comment]
if you are just trying to run an example project rather than making your own, the other question is how you got AsyncDisplayKit downloaded in the first place; the instructions above should work whether you download a .zip file, or use the GitHub app to check out the repository.  Neither of those require cocoa pods, and both should pull down the Details, Private, etc directories.

Also make sure you only ever open the workspace file, not the project file, after running pod install.

**Comment by robmontesinos** [comment]
Thank you - I am working off the workspace. I have Kittens example running. I was trying to replace a UITableView with an ASTableView in an app getting ready to submit for review and I am having all sorts of problems populating a simple table with tweets. Currently the tweets are working on my app but the scrolling is crappy.

 What I wanted to do is just get the tableView running with the Kittens code. I'm pulling my hair trying to simply populate an ASTableView with tweets, never mind laying them out and using the range controller. I tried this library before and had to give up - losing money to implement. Trying again cause my scrolling is really crappy - Ray Wenderlich's tutorial uses a CollectionView which doesn't work for my - I would like to use ASCellNodes but first this install. I'll just copy over the library folder from Kittens.

**Comment by appleguy** [comment]
@robmontesinos Hey Roberto - sorry to hear you've had so many problems.  I'd love to help fix them (honest).  I need a lot more specific information, though.

For example, it should never be necessary for you to even be aware of the existence of the range controller to properly use ASTableView.  Any performance issues you see are likely very straightforward to fix, especially if you could take one Time Profiler run in Instruments.

What issue are you running into trying to populate the table?  Specifically, what is occurring?

**Comment by appleguy** [comment]
@robmontesinos if you email me at asyncdisplaykit@gmail.com, I can give you my iMessage so we can chat live.  Could do a screen share if that's helpful.

**Comment by robmontesinos** [comment]
@appleguy you are amazing!!

**Comment by robmontesinos** [comment]
When I try to install via cocoa pods, the console reads "Installing AsyncDisplayKit (1.2.3)"

The pod spec reads 1.2.2 and the Layout subfolder is not downloaded, hence the runtime error for file not found: AsyncDisplayKit/ASInsetLayoutSpec.h

SO I haven't been able to install the ASDK thoroughly because the Kittens node is using layout methods

Pod::Spec.new do |spec|
  spec.name         = 'AsyncDisplayKit'
  spec.version      = '1.2.2'
  spec.license      =  { :type => 'BSD' }
  spec.homepage     = 'http://asyncdisplaykit.org'
  spec.authors      = { 'Scott Goodson' => 'scottgoodson@gmail.com', 'Ryan Nystrom' => 'rnystrom@fb.com' }
  spec.summary      = 'Smooth asynchronous user interfaces for iOS apps.'
  spec.source       = { :git => 'https://github.com/facebook/AsyncDisplayKit.git', :tag => '1.2.2' }

  spec.documentation_url = 'http://asyncdisplaykit.org/appledoc/'

  spec.public_header_files = [
      'AsyncDisplayKit/*.h',
      'AsyncDisplayKit/Details/**/*.h',
      'AsyncDisplayKit/Layout/*.h',
      'Base/*.h'
  ]

  spec.source_files = [
      'AsyncDisplayKit/**/*.{h,m,mm}',
      'Base/*.{h,m}'
  ]

**Comment by iamchenchen** [comment]
@appleguy I'm having similar problem.  
I've use pod to install AsyncDisplayKit (1.2.3).  
While trying to mimic HorizontalWithinVerticalScrolling, I've encounter multipule files missing from pod library.  
Such as ASCollectionNode, ASStackLayoutSpec etc.

**Comment by appleguy** [comment]
@iamchenchen can you post your Podfile?  @robmontesinos aren't you supposed to put the dependency in the Podfile, not the podspec?  I am not a cocoapods expert, but I'm pretty sure projects such as apps need to specify dependencies in the Podfile, whereas libraries that themselves have dependencies use the podspec.

**Comment by appleguy** [comment]
Example: Pinterest's Podfile currently contains this line:

	pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :commit => 'ca5780f6f4c4310ec31840573ac7f5f555f36f84', :inhibit_warnings => true

It actually has no podspec, of course, because it isn't a library (it isn't /itself/ a cocoapod).

**Comment by robmontesinos** [comment]
My Podfile has the following entry: pod 'AsyncDisplayKit' - this is right from ASDK Readme page. The console tells me that version 1.2.3 was installed. But when I read the pod spec from ASDK on github (AsyncDisplayKit.podspec) - it specifies 1.2.2. I think your pod spec needs to be updated for the latest version.

I'll try the Pinterest Podfile entry even though it is a specific commit - I am just trying to see ASDK run in my project - my next step is to comment out all the layout references but currently am in cocoa pods hell with library not found runtime error from good old clang.

**Comment by appleguy** [comment]
@robmontesinos I misunderstood your post — I see what you are suggesting is that we modify the ASDK podspec.  That makes more sense.

I'm aware that the master version number is set to 1.2.2, even though the latest release branch is 1.2.3.  That is just an error, although one that doesn't affect functionality.  I'll update it now.

I'll also look at the source_files piece, but the thing that concerns me is that other developers have not had this issue and are building against ASDK master...including Pinterest, NFL, Yahoo, and others.

Importantly, 1.2.3 (or if you just do "pod AsyncDisplayKit") does NOT include the Layout directory...it does not support many of the newer features that are on master.  You need to point to a commit, or another way of specifying it in the Podfile, if you want that newer version of the framework.

**Comment by appleguy** [comment]
@robmontesinos reading your comment more carefully, it does indeed indicate what I suspect.  Because the console is saying 1.2.3 installed, that definitely means that your configuration is not pointing to master, or indeed any version that has the Layout directory available.  So, if you want to use something like ASLayoutSpec (new developments past 1.2.3), you need to point to master and the console will (for the current moment) say 1.2.2 installed.  Apologies for the slight inaccuracy of the version number, as we've been focused more on getting the functionality built out and planning future releases than the state of the pod config in the master branch (since that's not a real release at all, it does not have a version number).

What functionality are you trying to use that is not present in the 1.2.3 version?  ASTableView is certainly there...

**Comment by robmontesinos** [comment]
@appleguy Thanks so much for your prompt attention to this matter.

I imported KittenNode.mm and BlurbNode.m into my project and was just trying to get them to work from my view controller. Those files are importing Layout files so I was going to use them to convert into my needs. If I have to comment them out I will but now it seems that the Pinterest entry you pointed me to does have the layout files included even though the console says version 1.2.2.

Since attempting to install ASDK with this out-dated pod spec, I've been getting cocoa pods related errors of library not found - libPods-TargetName.a - I don't know if its related but it would be a helluva coincidence. 

In any case, if the versions don't match up, ASDK 1.2.3 provides an incomplete download it would seem. Thanks so much for your help. Wrapping up for today and will try again tomorrow

**Comment by appleguy** [comment]
Aha, now I understand.  Yes, those files will definitely not work with 1.2.3.  They are of course pulled from the latest master branch, in how you’ve imported them.

Feel free to check out the 1.2.3 branch (you can download a zip here for convenience: https://github.com/facebook/AsyncDisplayKit/tags <https://github.com/facebook/AsyncDisplayKit/tags>) and you could pull those two files from that version, and they should build fine.

I just created a new tag, 1.9, if you want to try to point to that instead.  Most developers who want to use the latest ASDK features are pointing to a random specific commit on master and are using the new classes like ASLayoutSpec, but if you are not actively looking at the functionality that has been added since 1.2.3, this wouldn’t be necessary.

**Comment by robmontesinos** [comment]
Thank you @appleguy  - I will give that a try tomorrow and report - I really appreciate your help

**Comment by appleguy** [comment]
@robmontesinos I'm going to close this issue, but /please/ do create a new issue or ping me via email if you encounter any further issues getting the framework set up.

**Comment by robmontesinos** [comment]
Thanks so much @appleguy. Turns out that somehow my project's cocoa pods configs got scrambled. I built a new project brought over all the files from the corrupted project and I am happy to say that ASTableView is running sweetly. It is taking some work to get off of auto layout and implement/understand calculateSizeThatFits: and layout but so far it has been worth it in terms of smoother scrolling. I am going to try to do fade in animation with POP since placeholderFadeDuration doesn't seem to be doing anything but that is a different issue. @appleguy  - YOU ROCK!!

**Comment by appleguy** [comment]
@robmontesinos haha, very glad to hear it!  I have a git tag set for the 1.9 release now — working hard to get the release out ASAP, but I keep running out of time due to other things.  Please make sure you are pointing to that tag (or any commit on master in recent days) to ensure you have the most refined version of ASDK.

If you are going to start converting other code to ASDK, I strongly recommend you use the new layout functionality.  E.g., don't use -calculateSizeThatFits + -layout; instead, using -layoutSpecThatFits (best for most cases), or use -calculateLayoutThatFits: (allows fully manual layout, but still eliminates the duplication between calculateSize / layout).  Either of these two new approaches gets rid of the repeated code between size calculation and layout, which is a big win for brevity, maintainability, and allows the framework to achieve really excellent layout-related performance.

**Comment by robmontesinos** [comment]
Thanks @appleguy - I'm using the pinterest commit you posted above and it is working beautifully.

 Could you post an example of the layouts you're talking about? I have a bunch of view controllers to convert to ASTableView and some code would be a great help.

**Comment by appleguy** [comment]
@robmontesinos please reference slide 20 through 30 in this attached slide deck.  I'll post the video in the next few days.

The other attached file is a deeper dive on ASStackLayoutSpec.  Sorry we don't have much in between these two things right now.

You can look at the examples/Kittens app, as KittenNode does use layout specs for its layout.  There is also a project URL mentioned in the slide deck later on (on the Swift slide) where ASLayoutSpec is used extensively, but it is written in Swift.

Looking forward to the next issue you open with questions!
[ASLayoutSpecs 10-12-15.pdf](https://github.com/facebook/AsyncDisplayKit/files/15787/ASLayoutSpecs.10-12-15.pdf)
[AsyncDisplayKit 2.0 Beta - October 2015 Slides.pdf](https://github.com/facebook/AsyncDisplayKit/files/15788/AsyncDisplayKit.2.0.Beta.-.October.2015.Slides.pdf)

**Comment by appleguy** [comment]
@bimawa you may also be interested in the slide deck — sorry if I already sent it to you and forgot! ^^

**Comment by robmontesinos** [comment]
Thank you @appleguy !!

**Comment by bimawa** [comment]
@appleguy thx a lot!

**Comment by bimawa** [comment]
@appleguy is https://vimeo.com/140409084 video?

**Comment by appleguy** [comment]
@bimawa I'd like to avoid sharing that link, because it has a few key problems that will be fixed in the upload that I post about.

Unfortunately I got sick not just once, but twice back-to-back in the past 2 weeks, and many of my plans have been disrupted.  The final video should go up in the next few days: most likely Wednesday, but at the latest this next weekend.

In more positive news, I met @levi in person on Sunday, which was really fun!  Thanks for your understanding about the delays.  If you can wait until the final version is up before sharing the link, it would be great having your help distributing the properly edited version to any friends you think may be interested in it.

**Comment by bimawa** [comment]
@appleguy 
> I'd like to avoid sharing that link, because it has a few key problems that will be fixed in the upload that I post about.

np my friend sry for that.

>Unfortunately I got sick not just once, but twice back-to-back in the past 2 weeks, and many of my plans have been disrupted. The final video should go up in the next few days: most likely Wednesday, but at the latest this next weekend.

omg its very sad news, I wish you health, and as soon as possible. We need you ^_^!

>If you can wait until the final version is up before sharing the link

Of course don't worry.

**Comment by appleguy** [comment]
@robmontesinos @iamchenchen @bimawa Here's the video, as promised—sorry for the big delay compared to what I expected on this!

https://www.facebook.com/groups/551597518288687/permalink/846140678834368/

**Comment by bimawa** [comment]
@appleguy We are all love you so much that it's not so scary
