### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#747]
can use autolayout ？

**Comment by appleguy** [comment]
@wy19901227 No, UIKit auto layout is not supported.  However, ASDK provides a variety of ASLayoutSpec objects that allow implementing automatic layout which is more efficient (multithreaded, off the main thread), easier to debug (can step into the code and see where all values come from, as it is open source), and reusable (you can build composable layouts that can be shared with different parts of the UI).

Because of the way that UIKit auto layout is implemented, it actually prevents all major UI frameworks for iOS from integrating with it.  So, the story is the same with React Native and ComponentKit, for example.

Lastly, I think it's worth noting that using UIKit Autolayout is not permitted in large / experienced iOS development environments, including Facebook, Instagram, and Pinterest.  It is too computationally inefficient and difficult to debug.

**Comment by wy19901227** [comment]
thank you for explaining to me.
