### ISSUE TITLE
Animate node's view

### ISSUE THREAD

**Issue by petrpavlik** [facebook/AsyncDisplayKit#749]
I'm trying to animate a subnode of `ASCellNode` with a simple fade in/out animation but I must be missing something obvious. What is the proper place to fire up the animation? Is there some flag I need to set to keep the view updating?

```Swift
UIView.animateWithDuration(1, delay: 0, options: [.Autoreverse, .Repeat], animations: { () -> Void in
    self.view.alpha = 0.5
}, completion: nil)
```

**Comment by appleguy** [comment]
@petrpavlik there shouldn't be any tricks here; let me know if you're able to share a bit more code.

If you don't have the animation, does the node's contents properly show up in the cell?  E.g., it is being positioned and sized properly in layout, and is not marked hidden or something else?

Where are you actually triggering / starting the animation?  Naturally, make sure it is not on a background thread, as some ASDK callbacks are run on.

**Comment by petrpavlik** [comment]
Sure, please have a look at this class https://github.com/petrpavlik/AsyncChat/blob/master/Chat/Classes/TypingCellNode.swift

It's supposed to be a classic cell notifying that the other user is typing in a chat. The view just jumps to it's 50% alpha without any animation and stays like that. This is just one of multiple approaches I've tried with no luck so far.

**Comment by appleguy** [comment]
@petrpavlik thanks for the link to the code!  Reading through, I can see how incompetent I am with Swift.  I don't fully understand the method that contains the animation call, because it is creating a UIView, yet is somehow related to ASDisplayNode...this doesn't seem right, as you should be accessing the view property of the ASDisplayNode rather than creating one.

In addition / more importantly, it's not OK to call into UIKit from the -init method.  This may be called off the main thread, and for example cell nodes are initialized and then go through a concurrent background measurement pass before they're even added to a view hierarchy.  Your animation may be short-circuiting in some way because the views / layers aren't actually in a hierarchy so the animation couldn't have an affect immediately (not totally sure what UIKit is designed to do in that edge case).

It is also unusual to have animations start automatically just because something is created, but I understand you want this to be an infinite animation.  Still, classes like UIActivityIndicatorView have some kind of -start method for this, so you should consider that possibility.

If you'd like it to begin automatically, try using either -willEnterHierarchy or -didLoad method (each is called by ASDK automatically).  Make sure you call super.

Please let me know if you aren't able to solve the issue, and bring any additional details about the behaviors you observe.  I will try to modify the app to make it work if you aren't successful.  Good luck and thanks for asking!

**Comment by petrpavlik** [comment]
@appleguy This piece of code
```Swift
ASDisplayNode { () -> UIView! in
        let view = UIView()
        //...
        return view
    }
```

Is just Swift syntax for `- (id)initWithViewBlock:(ASDisplayNodeViewBlock)viewBlock;` so I suppose that it's a correct implementation.

I spent some more time digging into the implementation and found out that adding an item is wrapped inside `ASPerformBlockWithoutAnimation` which explains why I could get my view to animate :).

I made it work by triggering the animation in dispatch_async inside layoutSubviews to jump out of the performWithoutAnimation block.

```Swift
private class DotView: UIView {
        
        override func layoutSubviews() {
            super.layoutSubviews()
            
            dispatch_async(dispatch_get_main_queue()) { [weak self] in
                UIView.animateWithDuration(1, delay: 0, options: [.Autoreverse, .Repeat], animations: { () -> Void in
                    self?.alpha = 0.5
                }, completion: nil)
            }
        }
    }

private let circleNode0 = ASDisplayNode { () -> UIView! in
        let view = DotView()
        view.layer.cornerRadius = 6
        view.backgroundColor = .blackColor()
        return view
    }
```

**Comment by appleguy** [comment]
@petrpavlik ohhhh, thanks for explaining the initWithViewBlock thing.  That really didn't make much sense hehe.

This can definitely be done without using initWithViewBlock.  Using layoutSubviews as a trigger is not exactly ideal, although will definitely work.  You might want it to be a dispatch_once as relayout passes may occur without warning and could reset the animation.

Additionally, it is very important to avoid using .cornerRadius whenever possible.  This and several other layer properties (like borders, paths, etc) is extremely expensive; it is applied in the compositor, on every frame (even if the content isn't changing, merely scrolling a .cornerRadius view will cause the clipping to be re-applied on every frame).  This is disastrously expensive for any scrolling view up through at least iPhone 5, and I have seen it degrade performance below 60FPS on iPhone 5S.  The severity of the effect depends on a number of factors, including the size of the view, so if there were a case to use it during prototyping...this would be the one.

Recommend that you create a simple drawing routine using UIGraphicsBeginImageContext() and create the dot, then toss it in an ASImageNode, for example.

**Comment by petrpavlik** [comment]
Thanks for mentioning those layer properties being slow.

Regarding the animation, the only option that has worked for me in the end is to launch animations on a cell when 
`willDisplayNodeForRowAtIndexPath ` is called. The animation is always reset then given cell goes off the screen.

The animation also seems to stop when the app goes background, so I guess that I'll have to reload the table view when the app goes foreground or something like that.

**Comment by appleguy** [comment]
@petrpavlik I'm not sure what the normal behavior of autoreversing animations is on backgrounding the app, but I wouldn't be surprised if it does pause / cancel them.  Instead of reloading the table, which is quite expensive, I'd strongly encourage you to come up with a more targeted solution.  One would be to subscribe to the NSNotification sent by UIApplication when the app is foregrounded, and you can restart the animation there.  Make sure you unsubscribe from the notification when the cell is not onscreen.

Please feel welcome to open new issues as you continue with your app development, with questions of any kind!
