### ISSUE TITLE
Setting custom widths for ASCellNodes

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#757]
why these textCellNode are not same?
![0f31e5e74ac284e5ed27f75f8a0219db](https://cloud.githubusercontent.com/assets/8086633/10601982/26366d26-7748-11e5-9574-12830add844c.png)

**Comment by appleguy** [comment]
@wy19901227 do you mean, why are they not the same width?

The reason is that the text is actually not exactly the same width.  The width of a given character, in this case the digit, does vary a little in most fonts.  Only in true Monospace fonts is that not true.

The right way to solve this depends on how you want the design to look.  For example, if you really did want the grey region to not reach to the left and right sides of the screen, you would need to have a mechanism to determine the text that is maximum width and then make sure that all the other ones also adopt that width.

@rcancro I bet there is a way to do this with layout specs, automatically, but I'm not totally sure what it would be...if you imagined that the 0-9 cells were actually all subnodes of a single ASCellNode, and the ASCellNode returned an ASStackLayoutSpec from -layoutSpecThatFits, would it work to set the .flexBasis = ASRelativeDimensionMakeWithPercent(1.0) on each of the text nodes contained by the stack?

**Comment by appleguy** [comment]
@wy19901227 happy to help, if you can clarify your question / use case a bit more.  Something important to keep in mind here is that there are fewer layout options available for positioning multiple ASCellNodes relative to each other...as compared to positioning things that are a subnode added to an ASLayoutSpec.

In a case like this you might want to subclass UICollectionViewLayout to provide additional logic, if it's not possible / desirable to return a single ASCellNode for each group of 10 objects and then position the 10 objects using an ASLayoutSpec.

**Comment by wy19901227** [comment]
beacuse the demo use the ASTextCellNode. so how can I write a Node to make it's width is a regular value。

**Comment by wy19901227** [comment]
UIColectionView has a method to return the item‘s size，but I try, It doesn't work.

**Comment by appleguy** [comment]
@wy19901227 The demo isn't designed to make them all the same width while centered, of course, but it is definitely possible to do this.

If you want to set a static size, you should be able to do so in a few different ways.

- Subclass ASTextCellNode (better yet, create your own subclass from ASCellNode) and return an ASStaticLayoutSpec from the -layoutSpecThatFits: method.
- Alternatively, your subclass may use -calculateSizeThatFits: (returns a simple CGSize, where you can set any value you want the cell to be).  This approach requires that you also define a -layout method to position the text node (just like layoutSubviews).
- You might be able to use preferredFrameSize.
- We could definitely extend ASTextCellNode to provide a property to support this without subclassing.  However, ASTextCellNode is not a very useful class - it's basically a demo / test class not intended for real use cases - so i'm not sure it makes sense to expand its feature set rather than have you create your own cell if you want custom behaviors such as a size that is not defined by the text.

Lastly, you should experiment with properties like .flexGrow; setting this on the text node or cell might make it default to spanning the screen width.

**Comment by wy19901227** [comment]
despicable ， can you show me code. I can not make it work. thank you.

**Comment by wy19901227** [comment]
![img_0157](https://cloud.githubusercontent.com/assets/8086633/10631059/d2671fee-780d-11e5-9239-990d5af337ae.PNG)

**Comment by wy19901227** [comment]
![a08d75af-1a6a-4204-80d3-24770ecb327e](https://cloud.githubusercontent.com/assets/8086633/10631091/1e934898-780e-11e5-8f22-2f0ec754d8ac.png)

**Comment by appleguy** [comment]
@wy19901227 your code is missing a few things.

You need a -layout method if you are going to use -calculateSizeThatFits:.  Refer to pages 20-30 of the attached slide deck.

The screenshot doesn't show the rest of the file but it is not clear if you are adding the _textNode as a subnode of the cell, or allocating it properly.

Please share a test project so that we can debug it and get to a solution.  Otherwise, think about the amount of information you're providing and try to give more so that someone without the code could take a guess at what is wrong.  For example, you should print out the view hierarchy and include that here so we can at least see that the text node is present.  This is as simple as "po [[UIWindow keyWindow] recursiveDescription]" (or using Xcode's capture view hierarchy command in the debug menu, or other techniques).

Hope I'm able to help, thanks for helping me help you by focusing on sharing code to improve together!
[AsyncDisplayKit 2.0 Beta - October 2015 Slides.pdf](https://github.com/facebook/AsyncDisplayKit/files/18127/AsyncDisplayKit.2.0.Beta.-.October.2015.Slides.pdf)

**Comment by wy19901227** [comment]
I just modify the code in ASTextCellNode.m file. but the test doesn't show.

**Comment by appleguy** [comment]
@wy19901227 ah, I see.  Yes, that makes sense, because you have removed the code that sets the position of the text node.

If you use -calculateSizeThatFits:, you must also implement a -layout method to set the frame of any subnodes (such as the text node.

-layoutSpecThatFits:, as well as -calculateLayoutThatFits:, handle this task for you (do not need to implement a -layout method).

If you want to use one of the options that doesn't require -layout, consider using an ASStaticLayoutSpec to replace the ASInsetLayoutSpec.  Or, implement -calculateLayoutThatFits: (look at ASLayout to understand the data type it returns).

If you keep -calculateSizeThatFits, it will be a very short method.  Just call [super layout], and then set the frame of the text node in the exact same way you would in -layoutSubviews.

**Comment by wy19901227** [comment]
oh yeah! It works.Really,Thank you for explaining to me so patiently。

**Comment by wy19901227** [comment]
do you have some viedo to teach about AsyncDisplayKit?

**Comment by smeis** [comment]
@wy19901227 Here's a video from a year ago where @appleguy talks about the first version of ASDK: https://vimeo.com/103589245.

Here's another one from about a month ago where he talks about the new features in ASDK 2.0: https://vimeo.com/140409084.

**Comment by appleguy** [comment]
Hi @smeis!  You found my terrible, stutters presentation from NSSpain :-P hahah.  I'm going to post an edited / fixed version of it soon (have never needed to do that for my other talks, but I was way under-prepared for that one).

Hang tight while I get that video ready in the next couple days.

**Comment by wy19901227** [comment]
Can share the PPT?@appleguy

**Comment by wy19901227** [comment]
what's the relation to ComponetKit?

**Comment by appleguy** [comment]
@wy19901227 @smeis Here's the edited video.  It's a bit hacked up, but definitely less jarring to watch than the original.  Please feel free to share it around!

Looking forward to any questions you have posted in new Issues.

https://www.youtube.com/watch?v=RY_X7l1g79Q

**Comment by appleguy** [comment]
@wy19901227 the video does describe a comparison to ComponentKit.  There's a brief callout to that here too: https://www.objc.io/issues/22-scale/facebook/

Let me know if you didn't find the slide deck, but I think you did.
