### ISSUE TITLE
Way to synchronously update ASDataController

### ISSUE THREAD

**Issue by zintus** [facebook/AsyncDisplayKit#761]
It would be nice to block main thread in case of very first data load, so we can run animations on initial ViewController's content.

Are there any ways to implement this on client code side, or library changes are required? If got this right, core of changes are adding `async` property on ASDataController and then conditional scheduling of tasks to `_editingTransactionQueue`.

**Comment by levi** [comment]
@zintus this will require some updates internally to ASDataController such that anything pushed to a background queue (ie. node batch loading and editing transaction queue work) is done on main. While this is indeed a possible feature we could add to the data controller, I would caution against this approach if you're dealing with a lot of cells. The up front rendering cost could potentially block main for a longer period than desired and result in poor initial performance.

**Comment by appleguy** [comment]
@zintus funny that you bring this up, because @garrettmoon just encountered a use case for this earlier today :).  This does make it a priority for the project overall.

The most important thing is to come up with the right API for doing this.  I think in many use cases, what is desired is a single method call that can do a one-shot synchronous load (akin to a -reloadDataImmediately), although a persistent mode that enables always-synchronous behavior is something to think about (I think there are more risks / considerations with this...we'd probably want to force on neverShowPlaceholders for all cell nodes in such a case).

**Comment by appleguy** [comment]
The actual implementation change here shouldn't be terribly challenging.  The core change is to make sure the layout work for the cells, which is indeed done on the editing transaction queue, is handled synchronously.

Important: I suggest that we /block on the completion of that work/ rather than actually move it to the main thread.  This will allow multiple "chunks" of cell layout to be run concurrently, even though main is synchronously waiting on them, and will vastly reduce the amount of time spent waiting on the layout / height calculations.

**Comment by zintus** [comment]
Totally agree on having only one synchronous method to do all job related to rendering visible portion of table (taking huge tables in consideration, as pointed by @levi).

Here is how such method could look like:
1) query nodes batch of predefined size on main thread;
2) do batch layout on them, blocking main thread;
3) repeat 1,2 if batch is too small to fill the table;
4) proceed as usual, relying on `neverShowPlaceholders` to render nodes content.

Step 1 implies support for partially updated internal state for table's data, which maybe non-trivial to implement.

Maybe it's worth thinking of this process as of pipeline with heavily parallel stages: query data source for nodes, layout nodes, render nodes. We can easily block main thread, waiting for any stage to complete, similarly to current implementation of batch layout.

**Comment by appleguy** [comment]
@zintus welcome to the design of this capability!  Thanks for contributing to the reasoning process, as your thoughts are clearly articulated and solid.

I'm pretty sure Step 1 will be an easy implementation.  The batch layout system already does something similar; we would need to slightly refactor that mechanism, but it should be pretty feasible to do (the code is very explanatory when read).

It's definitely the right idea to have the method only block on laying out as much content is as needed to fill the screen.  Ironically, the simpler approach I was mentioning before (blocking on sizing everything) would still be faster than UIKit...by parallelizing the height calculations.  It would use more memory, though, and be pretty terrible for large tables.

The only consideration is that it may be necessary to allow specifying an amount of preloading to be synchronous for (this could be expressed in a screen height).  We may just do this by default, but if you loaded only enough for an exact screen height, then on any medium-performance device a natural but brisk swipe upon arriving at the view would be quicker than the next layout batch, and the user could see what looked like an end-of-content scroll bounce.

**Comment by appleguy** [comment]
I'm not sure who will first be able to implement this.  If you are willing to try, I can guarantee you that we will be enabling the functionality in Pinterest shortly thereafter :).  No pressure though!

**Comment by levi** [comment]
I'll have some time this afternoon to look into modifying the data controller. Will put up a work in progress diff to help facilitate discussion around the API and its requirements.

**Comment by zintus** [comment]
I'll be able to help with this during next week, happy to contribute :+1:

**Comment by appleguy** [comment]
This is now implemented, which is awesome.  We do need documentation for ASTableView and a clear description of all the different loading conditions (e.g. what happens after inserting vs deleting, reloading with a completion block, synchronous loading, etc)
