### ISSUE TITLE
Couldn't ASDisplayNode.name Be Thread Safe?

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#767]
It seems like there's more than a couple good use cases for this. Otherwise it'd be unsafe to log instances of `ASDisplayNode` since `description` relies on `name`.

Right now `name` is implemented as a property of the underlying `CALayer` but is there some reason we couldn't make it a stored property on the `ASDisplayNode` class?

**Comment by appleguy** [comment]
@Adlai-Holler of course.  I've run into this before, just delayed addressing it because of a desire to implement the threading model that Paper uses with ASDK (eliminate the current thread affinity assertions).  However, conditions have changed, and I am not going to have time until later this year or early next to do that.

I'd be happy to take any submissions that achieve this.  It's a pretty rarely used property for most people, but making it practical to actually use could encourage adoption :-P

**Comment by Adlai-Holler** [comment]
@appleguy Very cool. I'm stoked to learn about that threading model, since the thread affinity assertions are so dumb :grin:
