### ISSUE TITLE
[ASScrollNode] Enable layout specs to calculate & set contentSize separately from bounds.

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#780]
Seems like a match made in heaven, however, the constrained size range used by `measureWithSizeRange` is constrained to the size of the view bounds from the view controller. I have been thinking about splitting the measurement and layout pass of ASScrollNode into two parts:
1. `layoutSpecThatFits:` measures the frame size of the scroll node, constraining the scroll view's content size to a specified view port (it's currently already doing this).
2. `layoutContentSpecThatFits:` the exact same behavior of `layoutSpecThatFits:`, but is responsible for returning a layout spec that measures the `contentSize` of the backing scroll view. In order for this to function correctly, a method `calculateContentLayoutThatFits:`, which is called before `calculateLayoutThatFits:`, performs the exact same behavior, but is an override point for subclasses to modify the passed `ASSizeRange`. The most common instance of a scroll view is fixed width, but vertically scrolling content. Overriding `calculateContentLayoutThatFits:` and modifying the size range max to `CGSize(width: constrainedSize.max.width, height: CGFloat.max)` would then measure the contentSize to achieve this common scrolling behavior.

The results of `calculateContentLayoutThatFits:` set the `contentSize` on the layout pass and also set the frames of the scroll view's children. 

I wanted to bring this up before putting up a diff because it adds an extra API step that is not common amongst other ASDisplayNodes. Moreover, it will require `_flags.isMeasured` to be exposed somewhere to achieve the same behavior as measure/layout on `ASDisplayNode`. Open to feedback and suggestions. If it's not initially clear what I'm talking about, I'll put up a quick diff to better explain my intentions.

**Comment by appleguy** [comment]
To me this seems like a good idea, although a bit dicy haha :).

This would only work for scrollers where you can position everything they'll contain up-front, and thus size them together too.

Are you able to share any specifics on your use case?  That would help us assess the very best API direction (e.g. @nguyenhuy & @eanagel & @rcancro)

**Comment by levi** [comment]
Yes, dicy is a good description :smile:. Open to more flexible solutions that allow for easy integration of ASScrollNode with ASViewController. I'm going to dig into the ASViewController implementation to see if there is a way in which we can order the layout logic for subclasses to control the measure pass more specifically without duplicating a lot of the internal logic.

**Comment by appleguy** [comment]
Maybe you could create an ASScrollNode subclass that sets contentSize in its own -layout method?  There might be a way to do that in the base class…you could get the scroll node’s own layout spec, compute its size with unlimited bounds in the scrollable directions, set that as the contentSize.

The tricky part is that the returned layout (which you could probably influence within -calculateLayoutThatFits or something) needs to then report to the super-element that the scroll view should be sized smaller so its bounds are set appropriately.

I think the key question is how the bounds size of the scroller are actually determined.  If we can count on something like the constrained size sent in to measure being == to the bounds, and just return those values directly, then we could internally hijack the ASLayoutSpec as being focused on defining the contentSize.  I think that actually makes logical sense as default behavior for a scrollable region like this, insofar as it is also how ASCollectionNode is supposed to behave.

		— Scott

**Comment by appleguy** [comment]
@levi I merged your patch, but does it completely address this?  If so, could you elaborate just a bit?  I'm not seeing all that many uses for the method for typical developers, but could be missing something too; we should add some additional comments in a future diff with examples of common use cases, especially the scrolling one.

**Comment by samhsiung** [comment]
I ran into this also when I was creating a horizontal ASScrollNode which fit the width of the screen but who's contents could extend infinitely in the horizontal direction.

In this case I needed to calculate a contentSize independant of node size that wasn't constrained in the horizontal direction. My work around was to sum up the area of the children's calculated sizes + spacing and insets in `[self layoutDidFinish]` to calculate the contentSize. 

Having a way to do this via spec layout with a customized constrainedSize would have been cool so I wouldn't have had to write a separate method for manual calculation.

**Comment by appleguy** [comment]
@levi is it fair to say that this issue should be solved independently from ASViewController, just as long as the solution does work elegantly with ASVC?

Any ideas on how we can accomplish this?  @nguyenhuy you may have the best intuition.  Clearly ASLayoutSpec is capable of performing all the calculations needed; we just need to determine what a reasonable specialized behavior is for ASScrollNode and how to integrate it seamlessly in a way that is intuitive.

One way might be: children of ASScrollNodes are given unbounded size in the direction of scrolling, if we can determine the scroll direction at layout time.  Then we need a way to actually set the contentSize, which might be based on using CGRect unions of all of the layout specs / nodes within the scroll node and using the maximum width of that joint rect?

**Comment by nguyenhuy** [comment]
I think another way would be to implement a new layout spec, say ASScrollLayoutSpec. The spec should be a subclass or a wrapper of ASStackLayoutSpec and its children are forwarded to the stack. Its measure method simply calls the underlying stack to calculate with an unconstrained size on the scrollable direction. Since the stack is responsible for laying out children, we can make use of spacing and other ASStackLayoutable options, excepts flexible-related ones. ASScrollLayoutSpec then returns a calculated size equals to the constrained size given to it, but its children have the exact size and position reported by its stack. The result is that the children are laid out beyond the node's bounds.

Then we need to correctly set the contentSize. I think we can do this in -layout, or -layoutDidFinish. But the important thing is that, in a horizontal scroll node, its contentSize's width is the max X of the last children rect (and in a vertical one, contentSize's height is the max Y).

Let me know what you guys think on this idea :)

**Comment by levi** [comment]
@nguyenhuy from my quick skimming, seems like a really cool approach! Will all ASScrollViews require that the returned spec is an ASScrollLayoutSpec? How will it identify at layout time that the spec is specific to the content size?

**Comment by nguyenhuy** [comment]
Sorry for the long delay @levi. I think what we need is an ASScrollNode that holds an UIScrollView and returns an ASScrollLayoutSpec. The node will also take care of setting its contentSize, either in -layout or -layoutDidFinish (not sure yet). I reckon those are the only responsibilities of this new node, so it will be a simple one.

I can put up a new PR contains these new classes so that you guys will have a better idea and give some feedbacks. Since this issue is set to milestone 2.1, I won't work on it immediately though. @appleguy It will be easier for me to keep track if you assign this issue to me :)

**Comment by appleguy** [comment]
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send us an email at AsyncDisplayKit@gmail.com or ping us on ASDK's Slack (#1582). If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Comment by appleguy** [comment]
We are pulling back some of our tasks from Ship to GitHub :).  I'm very pleased to say that this is finally implemented.  I've wanted it for a really long time, and alas, it wasn't that tough to implement.  Please review and try out this PR: https://github.com/facebook/AsyncDisplayKit/pull/2753

**Comment by appleguy** [comment]
The main diff for this is landed.  A final, small tweak is going in with: https://github.com/facebook/AsyncDisplayKit/pull/2759

Closing, as we have tested this and are able to start using it in Pinterest: https://phabricator.pinadmin.com/D138889

**Comment by 8ofproject** [comment]
It would be cool to have at least one ASScrollNode (not table / collection) example with long scrollable content.

**Comment by mikhailmulyar** [comment]
I'm trying to use this in one of my scroll nodes with layoutSpecBlock containing simple vertical stack. However resulted contentSize is always limited to constrainedSize(parent size) of node. How can i achieve content size to be bigger than scroll node size?

**Comment by Kuluum** [comment]
@mikhailmulyar see pre-last comment here https://github.com/facebook/AsyncDisplayKit/issues/1165.
It helps me with same problem.
