### ISSUE TITLE
CGColor leaks in _ASPendingState

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#782]
If you take a look at _ASPendingState we correctly release/retain CGColors in our setters but we fail to release them on dealloc (in fact there is no dealloc.) The end result is that any CGColor set in an _ASPendingState will live on forever.

@appleguy We should probably hit this before release. I won't have time to actually take this on myself for a couple days yet.

**Comment by appleguy** [comment]
@eanagel hmm, this must be an ARC bug I guess?  Do we take the CGColor out of a UIColor in order to standardize on CGColor for layer-backing?

I'm not super familiar with how to deal with these edge cases under ARC (antiquated MRR guy here...), so I'll let this hang out until there is more time to investigate.  The retain cycle with ASBasicImageDownloader is a far more serious memory issue anyway, for any users of that component.

**Comment by eanagel** [comment]
No problem, the fix is easy (just release the items on dealloc.) I have that integrated into my branch, I'll see if I can push it out your way easily.

**Comment by eanagel** [comment]
Fixed.
