### ISSUE TITLE
Discussion - How to fix ASRangeController cell node leaks

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#797]
I've been tracking leaking ASCellNodes in my application and, thanks to reading up on #791, I think I'm on the right track. 

The first issue seems pretty simple to fix - we don't always exit all our ranges in tear down. 

The second issue is deeper and is more of a structural problem. This has to do when we perform updates (inserts/deletes, etc). The ASRangeController is maintaining an array of index paths for each range (Render and Preload) and as the range of visible index paths change we update these arrays and call enter or exit for each underlying node. This all works fins until we insert or delete items. At that point our index paths become invalid. Currently we set a flag (_rangeIsValid = NO) and discard all the old index paths. The problem is that we don't exit these index paths, so it's possible we will either enter them twice or never exit them at all. Failing to exit nodes in the Rendered range will cause the cell nodes to be retained in memory forever (they will accumulate in the ASRangeHandlerRender's workingWindow.)

I could totally be wrong about this (maybe all the issues I'm seeing are entirely from the first issue), I'd love to get some additional eyes on this. I'm looking specifically at  [ASRangeController.mm:117](https://github.com/facebook/AsyncDisplayKit/blob/a1dee22a0959b81835706caef510ae62df26c30e/AsyncDisplayKit/Details/ASRangeController.mm#L117). Funny thing about that part of the code base (_rangeIsValid handling), I think I was the last one to touch it. @appleguy, @levi and @nguyenhuy, what do you think, am I right about this being a problem?

I've been considering a couple fixes for this:

1. exiting all ranges/nodes when we first have changes is probably safest but would likely cause other issues and have a significant performance cost.

2. Somehow tracking the nodes either instead of or in addition to the indexPaths for each range. This could allow us to handle this edge case, but we would have to be careful not to retain the cellNodes too long.

3. A hybrid approach. While everything is valid we work off of index paths the way we do today but we track nodes during changes. So it would look something like the following

 - When we first start making changes (begin updates), capture the nodes associated with all current ranges.
 - When we are done making changes, grab the current visible index paths and get the nodes for each. Compare the previous nodes with the new ones and make sure we exit/enter the deltas.

**Comment by ERussel** [comment]
@eanagel 

Thank you for brief issue description. This exactly what i wanted to explain in original task, but unfortunately my English needs more practice :(. Sorry for this.

**Comment by appleguy** [comment]
I agree 3) - or 2) - is the best solution.  It's not really an option to always exit the ranges as this will cause backing stores to be blown away, resulting in either flickers or long stutters depending on if neverShowPlaceholders is set.

Although ASDataController has been improved a lot, ASRangeController was written by the same person at the same time, and has not been renovated.  It definitely needs it, and has been on my hitlist for some time now as there are specific additional features that I want from it (including "visible range" notifications sent to nodes, which would also better-factor the implementation of neverShowPlaceholders).

Beyond that, we need to formalize these calls that nodes get (like fetchData, clearFetchedData, the display variants, and the proposed visibility variant) in order to be able to trigger them for ASViewController as well.  This may mean defining a new protocol for things that can be controlled by a range.  Then it would be easier to trigger an ASViewController to preload itself to a certain level of completeness (either just fetching network data, or all the way through rendering).

The takeaway for me is that we should come up with a relatively simple bolt-on retrofit for the existing code and then take a step back on ASRangeController in general.  This may be a project we can take in-house at Pinterest because it is a larger job, although if anyone out there wants to lead it, it would be a huge help.

@eanagel for the sake of the immediate-term retrofit, are you on a path to be able to implement 2) or 3) — or should we pass off the implementation piece?  Thanks a ton for doing some additional debugging, and especially for @ERussel for surfacing the issue!

**Comment by eanagel** [comment]
I'm really under the gun here at work and won't have the time to do this right for at least a week. In light of the complexity of the issue, I'm looking at a hack style approach along the lines of what @ERussel came up with. I'd be happy to look at it a little later or if someone else wants to take charge, I can test it in my app which is a good test case for this issue. (And of course I'd help however I could!)

**Comment by nguyenhuy** [comment]
I agree that 3) should be the best solution. Better yet, on `master`, we already have `externalCompletedNodes` that [captures and stores](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASDataController.mm#L518) (old) nodes for external access during batch updates. So we will only need to store (old) visible index paths for the deltas calculation after all changes are done.

**Comment by appleguy** [comment]
I'm going to merge this into #791
