### ISSUE TITLE
[ASDisplayNode] Support .transform and .subnodeTransform in point conversion methods

### ISSUE THREAD

**Issue by toulouse** [facebook/AsyncDisplayKit#8]
Tried updating this for a couple of hours yesterday (10-19). I realized that .transform isn't supported either, in addition to .subnodeTransform.

Technically, this could be seen as a bug when either .transform or .subnodeTransform aren't the identity matrix.

After banging at it for a while, I think that it's the right solution to reorient the methods to recursively call convertPoint/convertRect methods rather than trying to correctly compose arrays.

It's easier to understand and check, and any sane screen dimensions aren't going to be large enough numbers - floats should be accurate to within .5 up to 2^23 , and doubles up to 2^52 (per http://stackoverflow.com/questions/872544/precision-of-floating-point); the built up error from applying, say, seven transforms simply won't going to be that large - and this is for point conversion, not display.

That, or I could continue trying to figure out the right incantations to build the correct transform matrix, this time accounting for .transform and .supernode.subnodeTransform.

**Comment by appleguy** [comment]
@toulouse - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
