### ISSUE TITLE
[ASLayoutSpec] New Feature: Animate between specs, including Node addition & removal

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#803]
Animating between ASLayoutSpecs should not be hard to implement.  What would be more difficult, and far more powerful to become a core mechanic used by most ASDK clients, would be supporting the ability for an ASLayoutSpec transition to add and remove nodes as well.

All of the necessary information is in the ASLayoutSpec.  If a node is present in the spec hierarchy that wasn't previously, it needs to be added (and by default, fade in).  If one was present in the old spec but no longer, it needs to be removed (and fade out).  Because ASLayoutSpecs are only designed to handle immediate children of the current node, this makes it clear where in the hierarchy the subnodes should be added.

Naturally an important consideration is to figure out how to execute the transition recursively, but without undue performance overhead.

Community thought leaders who might want to think about this and weigh in on API naming details or implementation approaches: @nguyenhuy, @rcancro, @garrettmoon, @eanagel, @levi

**Comment by nguyenhuy** [comment]
The first thing came to my mind is that right now we don't enforce the rule that ASLayout of a parent node must contain *all* subnodes. The idea is that, in some cases, it is easier to layout a subnode  manually, while the other subnodes are still handled by automatic layout. For example, it's easy to position and size a cell separator manually, while doing so with ASLayoutSpec would require an extra combination of static and stack specs. So the first thing we need to do is either enforce the policy (via documentation and/or asserts), or allow developers to indicate that some certain subnodes are not present in the parent node's spec.

Figuring out recently added/removed subnodes by comparing the calculated and flattened ASLayouts are not difficult. I'm still thinking about the best way to support custom animations, with fade in and fade out being the default ones. We may accept animation blocks, or notify an animation delegate?

Regarding recursion, I think we can achieve that by triggering animation form the root node down to all (still present) subnodes. The nice thing is that once layout of the root node is calculated, other nodes in the tree also have their new layouts available. Although we have to somehow tell all the nodes to store their old layouts for a little while, instead of throwing away.

I'm not sure about how the new API should look like. I will let you know once I have better ideas.

**Comment by KieranLafferty** [comment]
Any best practice around this currently? 

I am trying to animate a keyboard showing inside with a collection view (similar to iMessage) and running into issues getting it to animate. My approach so far has been to add a bottomOffset property to the view that tells an ASInsetLayoutSpec to move all the content up by the size of the keyboard. Then on keyboard show/hide I set the bottom offset and invalidate layout which works but I can't seem to find a way to animate this a bit more smoothly. Any thoughts?

**Comment by eanagel** [comment]
@levi This is some great stuff! Super excited to use it!

**Comment by bimawa** [comment]
Awesome work! Thx guys!
