### ISSUE TITLE
Relayout Cell Node Causes Row to Be Reloaded

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#808]
Post-#793, having a cell node with an editable text node inside, and resizing that node as the user types, causes the table view cell to get reloaded which dismisses the keyboard and causes the view to flash.

Is there any way I can update the layout of a cell node without the dismiss & flash? Maybe bypass the `[super reloadRowsAtIndexPaths:withRowAnimation:]` call that comes from `ASTableView` in the `ASCellNodeDelegate` method?

**Comment by Adlai-Holler** [comment]
Correct me if I'm wrong, but wouldn't replacing `[super reloadRowsAtIndexPaths:withRowAnimation:]` in that method with `[super beginUpdates]/[super endUpdates]` (using ASPerformBlockWithoutAnimation if needed) give us the same behavior without reloading the containing `UITableViewCell`? It'd cause the table view to requery the data source for the heights of nodes and we'd return the new height. I've been doing that on the client side for a little while now

**Comment by appleguy** [comment]
@Adlai-Holler great question.  This is absolutely a valid use case and we need a way to support it...ideally automatically as it should always be the case that relayouts triggered by ASEditableTextNode have this concern.

@nguyenhuy what do you think?  It seems important to me that we not have the delegate method called (e.g. nodeForRowAtIndexPath: should definitely not be called due to a -setNeedsLayout on the cell)...and likewise, because removing a node from the hierarchy may cause its contents to be purged, we should also not move the node from one UITableViewCell to another one (if UITableView asks ASTableView for a new cell upon "reload")

**Comment by nguyenhuy** [comment]
@Adlai-Holler: sorry for this breaking behaviour. The reason I used -reloadRowsAtIndexPath:withRowAnimation:` is that I wanted to make use of `UITableViewRowAnimation` and provide a default, familiar and work-out-of-box way for animating relayouts. After considering your comments, I think you guys are right. Thanks for your great feedbacks and questions. 

I will submit a PR that changes ASTableView and ASCollectionView to trigger empty transactions after relayouts. Developers can always wrap `-setNeedsLayout` inside an animation block anyway. Animating will take a bit more work, but it's safer that way.

**Comment by Adlai-Holler** [comment]
@nguyenhuy @appleguy Thanks for responding to this so quickly! PR looks good to me!
