### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by zdenektopic** [facebook/AsyncDisplayKit#809]
Hi,

I would like to ask if it is possible to use ASDK with tvOS or if the support is planned/in the roadmap?

**Comment by appleguy** [comment]
@zdenektopic great question and I'd be really curious to know the answer.  I have not looked deeply into tvOS.

Does it provide access to Core Animation / CALayer in addition to UIView?  Is the UIView API the same as the iOS UIKit one?  If both of those are true, it's very likely that it can be made to work with little effort.

**Comment by clooth** [comment]
@appleguy It actually does give you support to those. I've already created a random project for tvOS with Core Animation and custom layer styling and such.

**Comment by zdenektopic** [comment]
I can confirm that.

**Comment by clooth** [comment]
With a very quick trial I managed to create a tvOS target and it *did* compile after I removed some things for the tvOS target:

- exclusiveTouch is not available on tvOS
- Photos.framework and AssetLibrary.framework are not available on tvOS

It did build after removing references to those in files like ASMultiplexImageNode(and Request) and some others as well as the target's linked frameworks.

**Comment by appleguy** [comment]
Thanks a lot @clooth & @zdenektopic :).  I just created my first tvOS app today and am very very excited to get ASDK working on it.  Unfortunately I'm bogged down with a bunch of other stuff that I absolutely have to prioritize (even though it would be so much more satisfying to hack on this for the weekend, seriously hard to resist lol!!)

Please do let me know if you end up creating a sample app with it.  I definitely anticipated the Photos and AssetLibrary issues (@Adlai-Holler knows that code well and may be able to help us gate the frameworks).  exclusiveTouch is a funny thing to specifically remove...I could imagine a future TV having a bigger trackpad with multitouch...but fair enough, should also be easy to work around.

**Comment by appleguy** [comment]
Pulling this forward to 2.1 as it is probably not horribly difficult and would be really awesome, so I'd like to see it happen in the next 2-3 months!

**Comment by aaronschubert0** [comment]
tvOS 9.2 supports MapKit so this has got significantly cleaner! Now I don't need to gate out ASMapNode :)

**Comment by appleguy** [comment]
@zdenektopic @clooth @aaronschubert0 - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
