### ISSUE TITLE
How to Fix Sizing of a Cell Node?

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#813]
I'm working on making some content placeholder cells using AsyncDisplayKit. The contents are in a stack, and I'd like to center that stack in a container whose size I can manually control. 

I'm stuck trying to get the cell size to be manually controllable. I've reduced it down to this toy project https://github.com/Adlai-Holler/ASDKPlaceholderTest . I've tried
- Setting `cellNode.preferredFrameSize`
- Setting `layoutSpec.sizeRange = exact(mySize)`
- Fiddling with `ASCenterLayoutSpec`'s sizing options. Since table views measure cells constrained to `(screenWidth, +inf)`, if I specify `Default` then the cell is infinitely tall and if I specify `Minimum` the cell is only as tall as the content.

Any help would be appreciated. Also, if any of you top-tier engineers know of a framework/library/pattern that handles these error/loading/no content placeholders please let me know!

**Comment by Adlai-Holler** [comment]
![simulator screen shot nov 3 2015 2 45 48 pm](https://cloud.githubusercontent.com/assets/2466893/10924144/a2252f7a-8239-11e5-8ffb-f79b6626a8be.png)
![nooo-meme-darth-vader-04](https://cloud.githubusercontent.com/assets/2466893/10924163/c90bb730-8239-11e5-96a7-197497c7cf5b.jpg)

**Comment by nguyenhuy** [comment]
@Adlai-Holler Thanks for asking this question. It is definitely a common layout and this issue might be helpful for other developers later on.

Let me try to go through each of the options that you tried and explain why it doesn't work/what is missing.

> Setting cellNode.preferredFrameSize

`preferredFrameSize` won't be picked up because the cell node already implements `-layoutSpecThatFits:`, which is the preferred layout approach. Implementation details can be found [here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L1574)

> Setting layoutSpec.sizeRange = exact(mySize)

`sizeRange` is *only* picked up if the layoutable object (ASLayoutSpec, ASDisplayNode and their subclasses) is a child of an `ASStaticLayoutSpec`. My guess is that you didn't create a static spec. Below (tested) piece of code should work:

```swift
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
  let horizontalStack = ASStackLayoutSpec.horizontalStackLayoutSpec()
  horizontalStack.spacing = 8
  horizontalStack.justifyContent = .Center
  horizontalStack.alignItems = .Center
  horizontalStack.setChildren([textNode, spinner])
  horizontalStack.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeDimensions(
    ASRelativeDimensionMakeWithPercent(1), // Fill parent width
    ASRelativeDimensionMakeWithPoints(300)) // 300 pts height
  return ASStaticLayoutSpec(children: [horizontalStack])
}
```

> Fiddling with ASCenterLayoutSpec's sizing options. Since table views measure cells constrained to (screenWidth, +inf), if I specify Default then the cell is infinitely tall and if I specify Minimum the cell is only as tall as the content.

These look like the correct behaviours of sizing options to me. You can always use an inset spec (between the stack and center specs) to add extra *vertical* space to your node. This might be a better option over the previous one, since you don't make assumption about the node height (i.e the text can take more space (or even another line) if the font size is bigger, or in different languages, etc)

[DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet) seems to be a solid library. Since I haven't used it myself (and am not a top-tier engineer), please take this suggestion with a bit of salt :)

**Comment by Adlai-Holler** [comment]
@nguyenhuy Thank you for this insightful answer! Code works great and I understand the layout system much better now. You'll always be _my_ top-tier engineer! =P

**Comment by nguyenhuy** [comment]
Thanks so much for the kind words. Although I genuinely think I'm far from being a good engineer, your compliment really helps boost my confident :)
