### ISSUE TITLE
Unexpected Crash in ASCellNode using ASStackLayoutSpec

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#820]
I have a fully functioning ASCellNode using ASStackLayoutSpec that works great.

I decided to build the node hierarchy on a background thread using GCD as described in ReadMe and I get a crash - *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

When I set an exception breakpoint, it turns out that the first node on the first stack in - (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize is nil.

How does one manage this race condition between the node hierarchy being built and being laid out?

**Comment by appleguy** [comment]
@robmontesinos Debugging an issue like this would require the project.  This can be caused by a wide variety of memory errors and indeed could easily happen without AsyncDisplayKit.

Could you at least share the code that is passing in the nil value?  Nil cannot be stored inside an array, so it must be some code that is creating an array with specific variables.  It sounds like this is your own layoutSpecThatFits: method, not inside ASDK?

**Comment by robmontesinos** [comment]
@appleguy Never mind - this was due to operator error, i.e. me - I didn't fully understand node hierarchy building sequence - reading everything and watching the videos again helped tremendously. Thank you again

**Comment by appleguy** [comment]
No worries, really glad it worked out @robmontesinos !
