### ISSUE TITLE
How correctly use ASViewController

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#833]
Yea i know its not release, but how better way for write layoutSpec's in for self.view? For a less refactor in fututre.

**Comment by appleguy** [comment]
@bimawa Good question.  There isn't currently a way to use layout specs at the ASViewController level.  For now, you must subclass the ASDisplayNode that you create the ASViewController with and use layoutSpecThatFits: there.

In the future I'm most likely going to make "node" a writable property (similar to "view" in UIViewController), rather than required only at init time.  This won't really affect layout, but is just FYI since you're interested.

We'll probably eventually introduce a layoutSpecForNodeThatFits: or something similar, but this is less certain and wouldn't be part of 2.0 (more likely 2.1 or later).

**Comment by appleguy** [comment]
Please reopen or create a new task if you have any other questions!

**Comment by bimawa** [comment]
@appleguy cool I did the same ) thx! Will be wait.
