### ISSUE TITLE
ASButtonNode setBackgroundColor:forState:

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#859]
Guys what do u think about add this method? 
Like as https://github.com/mattlawer/BButton for example or https://github.com/pepibumur/PPiAwesomeButton

**Comment by appleguy** [comment]
Hmm, interesting!  @bimawa this seems like a pretty good feature to have :).  It could be simulated by creating images for the states, using UIGraphicsBeginImageContext() etc, but it is pretty inconvenient to create those images manually.

If you are interested in putting up a PR for this, we can definitely get it ready for merging!  If you don't have time to do this, no worries.

I am going to close this task simply because we have a lot of them open, so for things that will turn into a pull request, we can track further discussion on the PR :)

**Comment by bimawa** [comment]
@appleguy  yea I'm haven't a time now, just interesting future plans about Buttons
