### ISSUE TITLE
[Discussion] Instructions on how to synchronously reload an ASTableView

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#863]
When a ASTableView reloads data，the view flickers.How can solve this problem.
Code:
@interface ViewController () <ASTableViewDataSource, ASTableViewDelegate>
{
    ASTableView *_tableView;
    NSMutableArray *_socialAppDataSource;
}

- (void)reloadData
{
    [_tableView reloadData];
}

**Comment by nguyenhuy** [comment]
This question has been asked multiple times and every time it comes up, we have something new to say :) The view flickers because reloadData destroys existing nodes, loads new ones and measures them asynchronously. 

So, before committing to reloadData, perhaps it's worth to consider whether you really need it in the first place or not. [Here](https://github.com/facebook/AsyncDisplayKit/issues/600#issuecomment-129499491) is my opinion on this matter.

If you indeed want to reload everything, you might want to try the new reloadDataImmediately method (#761). It works similarly to UIKit's reloadData-- it blocks the main thread while reloading cells. Since I haven't used it personally, I'm not sure whether it's more or less expensive compare to UIKit counterpart (anyone?). My impression is that because nodes are laid out asynchronously, it blocks the main thread for a shorter period of time if the number of nodes is small, but it gets more and more expensive when that number grows.

And [here](https://github.com/facebook/AsyncDisplayKit/issues/616#issuecomment-133422166) is a trick to hide the flicker if you stick to reloadData.

**Comment by appleguy** [comment]
Yes, this is essentially expected - the alternative is to do the UITableView behavior where, during the processing related to the reload, the user is blocked from any interaction with the app.  If this is what you desire, then reloadDataImmediately is what you need :).

If you don't want the placeholder states to be shown, you'll also need to enable .neverShowPlaceholders on ASCellNode.  This is a very cool option that still allows concurrent background rendering - it just has the main thread wait if any of those elements are onscreen.  As opposed to UIKit which is single threaded and blocks main, this is a big optimization as it does use all cores and reduces the amount of time main is blocked.

More importantly, avoiding -reloadData altogether is the best option.  Using the editing commands of insert, delete, reload, move, etc are the best option if you can manage it.

@tuyuan2012 does that solve your problem or do you have further questions?

**Comment by tuyuan2012** [comment]
Thank you very much,I will try your methods rightnow.....@appleguy @nguyenhuy

**Comment by tuyuan2012** [comment]
I have try many ways to solve the problem....Finaly，I use reloadDataImmediately and the editing commands of insert, delete, reload, move, etc to meet different situations.....Thank you very much@appleguy @nguyenhuy

**Comment by appleguy** [comment]
@tuyuan2012 - thank you for contributing to the ASDK community by posting your question here! I hope you have been able to use the framework!
