### ISSUE TITLE
How can guarantee [subnodes.layer display] after setting frame directly?

### ISSUE THREAD

**Issue by molon** [facebook/AsyncDisplayKit#864]
Sorry for may poor english.

I have subclass `ASDisplayNode` named `TimelinePopoverNode` as a container for some image nodes.
I init it in `[vc init]` and add it to a `vc.view` in `viewDidLoad`.

Then I add a button which can be clicked to call a method.
In the method, `setFrame` for the `TimelinePopoverNode` is called.
But after clicking, the popovernode's subnode.layer won't be displayed.

This is a simple demo for the issue: https://github.com/molon/ASDKIssue864

Maybe this is a solution below:

```
- (void)__setSafeFrame:(CGRect)rect
{
  ASDisplayNodeAssertThreadAffinity(self);
  ASDN::MutexLocker l(_propertyLock);

  BOOL useLayer = (_layer && ASDisplayNodeThreadIsMain());

  CGPoint origin      = (useLayer ? _layer.bounds.origin : self.bounds.origin);
  CGPoint anchorPoint = (useLayer ? _layer.anchorPoint   : self.anchorPoint);

  CGRect bounds       = (CGRect){ origin, rect.size };
  CGPoint position    = CGPointMake(rect.origin.x + rect.size.width * anchorPoint.x,
                                    rect.origin.y + rect.size.height * anchorPoint.y);

  if (useLayer) {
    _layer.bounds = bounds;
    _layer.position = position;
     [_layer setNeedDisplay]; //!!!!!  add this line. !!!!!!
  } else {
    self.bounds = bounds;
    self.position = position;
  }
}

```

I am a novice for `AsyncDisplayKit`,so I'm not sure whether used a wrong usage.

:)

**Comment by appleguy** [comment]
@molon Good question, I will give you a more comprehensive answer as soon as I have time (it may be this weekend).

Some options include disabling displaysAsynchronously on any of the nodes that do rendering (you can enable / disable this at will - but it is not recursive, has to be on each node) - or you can call -recursivelyEnsureDisplay.

Depending on the situation you may be able to use neverShowPlaceholders on ASViewController or ASCellNode, too.

Thanks so much for including a test project!  That is tremendously helpful and also considerate of you to provide to the community to make it easier for us to help out.  I will do my best to get you a solution by the end of the weekend, although with some Thanksgiving travel involved, worst case it might take into next week.

If you need a solution right away, I recommend the displaysAsynchronously = NO route (even if you have to set that upon creating the nodes rather than changing it dynamically).  Even with this setting, you will still get the benefit of concurrent calculation of layout in the background, and it will be easy for us to re-enable asynchronous display with a more targeted fix later.

**Comment by molon** [comment]
@appleguy Thanks so much for your answer. I'm very sorry for your travel. :)

With the answer, I have checked the source with `recursivelyEnsureDisplay` , it just call `[subnode.layer displayIfNeed]`. But in my issue , the reson is no `[subnode.layer setNeedsDisplay]` be called.

I have update my test project to describe better with the issue, and my current solution in `TimelinePopoverNode.m`->`- (void)layout`.

Because I'm not familiar with ASDK much.
So I wanner to know whether the solution I gived in floor 1(add `[_layer setNeedDisplay]` in `__setSafeFrame `) will take some adverse effects.

A good trip is more important than work. so don't put it in your heart with the issue please.

Wish you a good trip. :)

**Comment by molon** [comment]
This bug has fixed.
I have test it with commit https://github.com/facebook/AsyncDisplayKit/commit/aefff563bdfa2b482e403a5a99e0efd8ed887362 just now.
