### ISSUE TITLE
[UILabel wrapping] Why do I need to set preferredFrameSize?  ASTextNode doesn't need it.

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#872]
I build a ASCellNode like this, but the AStableView didn't show the cell.
![Uploading 7D9D3684-9428-4A65-B14F-47AF4D915F97.png…]()

**Comment by wy19901227** [comment]
![7d9d3684-9428-4a65-b14f-47af4d915f97](https://cloud.githubusercontent.com/assets/8086633/11296365/9f5f5970-8fac-11e5-8ce3-651a730f49c7.png)

**Comment by wy19901227** [comment]
![31f6800aacad570c76cd4d5d98ce51a5](https://cloud.githubusercontent.com/assets/8086633/11296378/b5af2d0e-8fac-11e5-81fb-ca10e2d9292b.png)

**Comment by molon** [comment]
@wy19901227 
You need provide the `preferredFrameSize` for subnode. Because the layout dont know tranditional view's fit size.

**Comment by appleguy** [comment]
@wy19901227 why are you wrapping UILabel?  This is /very/ negative for performance compared to using ASTextNode.  I'm very interested to know if there is a feature that UILabel has that you want to be able to use, that ASTextNode doesn't have!

@molon is correct that because you are using UILabel, you need to provide a preferredFrameSize.  A good place to do this would be in -didLoad on your cell node, and call -sizeThatFits on the labels.  But basically when you are wrapping the UILabel with a generic ASDisplayNode, the node has no way to know how the generic UIView should be laid out.

This problem should disappear if you use ASTextNode - you should NOT need to set preferredFrameSize.  You may want to set .flexShrink = YES if you want the text nodes to wrap, though.

**Comment by wy19901227** [comment]
I just want to use the method to know more about ASDK. It's just a demo.~~

**Comment by alexvbush** [comment]
@appleguy I'm currently working on rewriting our Newsfeed to use AsyncDisplayKit and my use case for wrapping `TTTAttributedLabel` in `ASDisplayNode`. We have a lot of legacy logic using `TTTAttributedLabel` and rewriting it would be an extra effort.

**Comment by maicki** [comment]
@alexvbush As @molon already mentioned if you wrap a UIKit component ASDK cannot reason about the layout of the wrapped UIKit component. What you could do in fact is subclass `ASDisplayNode` that contains an `TTTAttributedLabel` and in `calculateSizeThatFits:` return the fitting size.

You have to be careful though as `calculateSizeThatFits:` is called on the background thread. So I guess more sense would be to every time the string changes calculate the new size, store it within the node, and trigger a relayout. Return the stored size within `calculateSizeThatFits:`.
