### ISSUE TITLE
[ASLayoutSpec] Asynchronous layout calculation for ASCollectionNodes and ASTableNodes

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#883]
I have an ASCellNode which has two subnodes:

```
MyCustomCell : ASCellNode
    - ASDisplayNode
    - ASCollectionNode
```

And am using layout specs to stack the two subviews as follows

```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    ASStackLayoutSpec *stackLayout = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                             spacing:0
                                                                      justifyContent:ASStackLayoutJustifyContentStart
                                                                          alignItems:ASStackLayoutAlignItemsStretch
                                                                            children:@[_itemView, _collectionNode]];
    return stackLayout;
}
```

The problem is that I end up getting a thread affinity error thrown inside the ASCollectionNode at the following location:
- (ASLayout *)__measureWithSizeRange:(ASSizeRange)constrainedSize
  {
  ASDisplayNodeAssertThreadAffinity(self);

What is the common approach for using layoutSpecs with UIViews wrapped in an ASDIsplayNode as is the case for ASCollectionNode?

**Comment by appleguy** [comment]
@KieranLafferty Hey there - thanks for posting, would love to help!

In general, simply wrapping a UIView doesn't mean the node needs to be created or sized off the main thread, as the UIView itself isn't created until the view property is accessed (which must always be on the main thread).

The issue you're describing could happen if you are saving your ASCellNode and reusing it on multiple calls of nodeForRow/ItemAtIndexPath: (at the higher level - the thing containing the cell which contains the collection node).

Could you share the full backtrace, as well as more details about your use case?  Is the ASCollectionNode a fixed height element that scrolls horizontally, or is it intended to lay out items vertically but not scroll at all because it is inside of another cell?  Or is the cell inside a horizontal collection and you want the collection node to scroll vertically?

All this said, you have discovered a true limitation / rough edge of ASDK in master that I am working to fix up in the next ~3-4 weeks before the full 2.0 release (the first stable release of the ASLayoutSpec stuff).  The very best way to handle layouts containing ASCollectionNodes or ASTableNodes is to use either an ASStaticLayoutSpec, or what often ends up being easier is to implement a very simple -layout method.

As long as your -layout method calls [super layout], you can still use ASLayoutSpecs / -layoutSpecThatFits: to size and position everything else.  Then after calling super, simply set the frame of the _collectionNode to whatever it should be.  You can even rely on reading the value of _itemView.frame or do a convertRect at this stage if necessary.

Thanks for sending on some screenshots / backtrace details / description of your use case, or perhaps modifying a sample project to drop in the relevant sections of your code, if this description doesn't immediately solve your issue!

**Comment by appleguy** [comment]
BTW, there are mechanisms like reloadDataImmediately that are expressly intended to force layout calculations to occur on the main thread in the same way that UIKit normally does.  However, this does not (and unfortunately cannot) apply on a per-node basis.

If you're curious why, the reason is thus: the ASDK threading model states that the main thread may wait on background threads to implement features like neverShowPlaceholders (or indeed reloadDataImmediately), but that background threads must never wait on the main thread.  This is to ensure deadlocking is not possible.  Although in certain cases it may be safe to do this, it is risky and something I'd like to avoid pretty much indefinitely.  Since there are very few use cases for only a certain type of node requiring main thread layout, I'll look for other solutions first and then revisit this if it turns out to be necessary to support this (and if so, there is a technique that could rely on first using the main thread to check for any such main-only nodes, and do some careful coordination with the background thread).

I believe this specific issue will be elegantly resolved by upcoming changes for ASCollectionNode and ASTableNode, at least for UICollectionViewFlowLayout-based ASCollectionNodes, since they can rely on the ASFlowLayoutController implementation which is thread safe to drive the computation of the overall content size where it is essential to the layout.  However, since it is often so trivial to compute the bounds of the collection / table - and frequently not needed to know the full content size - I'd suggest the -layout implementation idea above as a stable long-term fix too.

**Comment by stowy** [comment]
Hey @appleguy I have also found this problem in my sample project, which you can find here - https://github.com/stowy/AsyncDisplayKit/tree/stowy/deal-sample - if you build and run it it will crash due to this issue.

Is there a workaround for this scenario? Funnily enough a very similar scenario in my main project is not crashing.

**Comment by stowy** [comment]
Ok, I resolved this issue. It turned out i was accessing the node's UIView prior to the layout occurring, making it assert main thread when it went to measure it's size.

**Comment by garrettmoon** [comment]
Looks like this issue can be closed? Please reply back if not!
