### ISSUE TITLE
[ASTextNode] How to change the ASHighlightOverlayLayer color

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#885]
How to change the ASHighlightOverlayLayer color in NSTextNode？Thank you very much....In the code，I find the color can't be changed....

**Comment by tuyuan2012** [comment]
I have achieve the function by using [ASTextNode rectsForTextRange:textRange].I can get the an array which is full of NSValue.Then,I create many ASDisplayNodes with different NSValue.Finally,I insert the node at the index of 0.The follow is the code.
@interface LLHighlightCoverNode : ASDisplayNode
@end

- (void)addHighlightCoverNodes:(NSRange)textRange
{
    for (NSValue *rectValue in [_textNode rectsForTextRange:textRange]) {
        LLHighlightCoverNode *cover = [[LLHighlightCoverNode alloc] init];
        cover.backgroundColor = LLColorSelectSpecial;
        cover.frame = (CGRect){rectValue.CGRectValue.origin,{rectValue.CGRectValue.size.width,[UIFont systemFontOfSize:_data.fontSize].lineHeight}};
        cover.layer.cornerRadius = LLCornerCommon;
        [self insertSubnode:cover atIndex:0];
    }
}

- (void)clearHighlightCoverNodes
{
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.25 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        for (ASDisplayNode *child in self.subnodes) {
            if([child isKindOfClass:[LLHighlightCoverNode class]]) [child removeFromSupernode];
        }
    });
}

**Comment by appleguy** [comment]
@tuyuan2012 thanks for posting about your solution!  I haven't seen a request for this before, but I think it's likely the implementation just didn't support it / provide an API.  You're welcome to submit a PR that adds support for this.

Note: there is a large patch that is landing very soon (see the open PRs) that affects ASTextNode and many related classes.  We should probably wait for this to land first, or plan to rebase any diff you provide.

If you're not able to do a PR for the community at this time, I totally understand.  Just let me know so I can mark this as a future task.

**Comment by tuyuan2012** [comment]
I am glad for your invitation,but I think that I need much more development practices so that I can do a much better PR for our community.Well,I am so sorry that  I can not able to do a PR for the community at this time.In the future,I hope I can do much better for you....@appleguy

**Comment by appleguy** [comment]
@tuyuan2012 - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Comment by appleguy** [comment]
@tuyuan2012 - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!).

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us.

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
