### ISSUE TITLE
A bug in SocialAppLayout.

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#908]
![img_0259](https://cloud.githubusercontent.com/assets/8086633/11557036/664ba9e8-99e5-11e5-9f9c-6b2cffc10974.PNG)
I just make the rows a lot and  slde ,this will appear.

**Comment by wy19901227** [comment]
![img_0259](https://cloud.githubusercontent.com/assets/8086633/11557110/ea8b533e-99e5-11e5-998b-99a02eee1330.PNG)

**Comment by appleguy** [comment]
@wy19901227 that UI looks like the Accessibility menu.  It appears with a special gesture, anywhere in the system — I'm not exactly sure what it is, something like a double-tap with three fingers.  What happens when you tap on it?

Please reopen this task if you think I am incorrect.  If it is the accessibility menu, there isn't anything that ASDK can (or should) do to prevent it from appearing.

**Comment by vitalybaev** [comment]
@wy19901227 @appleguy I've observed this issue since ASDK was 1.2.2 and it appears randomly.
But it can be fixed with setting cell's selectionStyle to none.
