### ISSUE TITLE
[ASTextNode] Details on the wrapping / truncation behavior when using maximumNumberOfLines.

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#923]
The full text is as follow：
        1
        2
        3
        4
        5
        6
        7
        8test test test test test test test test test test
        9

When I set the maximumNumberOfLines of some ASTextNode to be 8, the result of the ASTextNode is as follow：
        1
        2
        3
        4
        5
        6
        7
        8test test test test test test test test...

 I think the result of the show is not right. The eighth line does not show the whole text of the line, but ends with '...'.

**Comment by appleguy** [comment]
@tuyuan2012 thank you for the report!  Is this issue new in 1.9.3?  You've compared it to 1.9.2?  That would be tremendously useful information if so.

Can you provide the layout code?  That is necessary to know whether this behavior is expected or not.  For example, if you're not allowing enough width for the "8test test ..." line, then it having an ellipse at the end is expected.  Since you're preventing it from wrapping to a 9th line, it can't just wrap.

What behavior do you expect in this case?  The layout code will really help - any -layoutSpecThatFits: and -layout implementations you have.

**Comment by tuyuan2012** [comment]
@appleguy thank you very much. In 1.9.2, I have no such issue. I user the method of '-boundingRectWithSize:(CGSize)size options:(NSStringDrawingOptions)options context:(nullable NSStringDrawingContext *)context' calculates the size of the text. I don't use autolayout in my project.

**Comment by tuyuan2012** [comment]
The issue has disappeared in the version 1.9.4. Thank you @appleguy

**Comment by levi** [comment]
@appleguy close this one when you get a chance :)
