### ISSUE TITLE
[ASDataController] Layout thread affinity for cells with nested view-based nodes

### ISSUE THREAD

**Issue by zintus** [facebook/AsyncDisplayKit#927]
Current implementation of ASDataController detects possibility of background layout by checking `isNodeLoaded` property on a cell node. In case such node, by the time of layout, have any subnode with   loaded view, background layout will fail.

What do you think about ensuring that whole cell node subtree have no loaded view/layer before doing background layout?

**Comment by levi** [comment]
I was thinking about this issue too when running into a cell node trying to access view properties on a child collection node. The current work around is to access the properties in `didLoad`, which allows the cell to be loaded with background thread affinity.

Your suggestion is an interesting one that could be accomplished by inspecting a nodes sub layouts. At layout spec compilation time, the `calculateLayoutThatFits` method flattens the tree into a 1 level deep hierarchy of sublayouts. The data controller could then inspect these layouts to identify if the current cell has a synchronous child node somewhere in its hierarchy. Of course, this is a time complexity issues adding at least O(n) search time to the node look up for each node. Results could be pre-cached, but might be stale, especially since the flattened list of nodes are currently computed with `measureWithSizeRange:`.

**Comment by zintus** [comment]
While layout flattening doing things structurally resembling our task (recurse into subnodes), i don't think it's good idea to mix layout and affinity calculations. Layout is cached differently and needed in different situations and it would clog layout.

Could we introduce `detachedFromMainThread` (not sure about naming here) implemented in spirit of `ASInterfaceState` and `ASHierarchyState` but propagating up over nodes tree.

**Comment by appleguy** [comment]
I guess this is the opposite problem that ASHierarchyState solves.  We might want to introduce something comparable that up-propogates information / state of this nature as it changes, so that recursion is not necessary at access time.  However, I think it would be fine to add this check now, as it is very difficult for individual developers to understand and work around thread affinity assertions.  Adlai and I are meeting next week to discuss a next-generation threading model.

**Comment by appleguy** [comment]
@zintus @levi - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
