### ISSUE TITLE
[Memory] Investigating an app-level memory bug

### ISSUE THREAD

**Issue by singno** [facebook/AsyncDisplayKit#943]
My app is crashed by generating too many ASCellNodes, how can I reuse the ASCellNode?

**Comment by appleguy** [comment]
@singno AsyncDisplayKit doesn't use cell reuse, for a number of specific reasons.  However, this should not cause an app to crash, because cell nodes use only a few hundred bytes each.

Could you run a memory profile on your app?  There are a few common mistakes that can cause this issue.  For example, if you are downloading images and then using a system that decodes them (like SDWebImage) and then setting them on an ASImageNode?  Or are you using an image downloader (provided to ASNetworkImageNode) that provides decoded images?  This would mean that the only reference to the image that ASDK has is decoded, substantially hurting its ability to intelligently manage decoding and memory reclamation.

If you're able to share your project (or a test project) with me at asyncdisplaykit@gmail.com, I'm happy to do the memory profiling myself.

**Comment by smiLLe** [comment]
@appleguy Are there any best practices on how to download, **cache** and display images?

**Comment by singno** [comment]
@appleguy  Yes, I use SDWebImage to download, decode and cache network image. The format of my image is webp. I use `SDWebImageDownloader.sharedDownloader().downloadImageWithURL` to download image and then setting it to ASImageNode. I also init ASNetworkImageNode using `SDWebImageManager`.

**Comment by appleguy** [comment]
@smiLLe - you mainly just need to implement a cache and downloader to provide to ASNetworkImageNode's initWithDownloader:cache: method (or ASMultiplexImageNode).  Please feel very welcome to open a new issue or email me at asyncdisplaykit@gmail.com with any questions!

@singno WebP is not directly supported, and that will definitely cause a problem to decode the image before ASDK gets it.  This is the first day I've heard a request for WebP support in ASDK, and yet two people have now asked on the same day!  We are tracking WebP support now here, and since there is interest, we can try to add it within the next month or so.  https://github.com/facebook/AsyncDisplayKit/issues/955

It would not be all that difficult to do, but it isn't an out-of-the-box solution today.
