### ISSUE TITLE
[Question] Patterns to ensure my ASCellNode subclasses don't use too much memory on init.

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#950]
Hey again, quick question here regarding loading in async data into ASCollectionNode

I have found that loading a collection with many items (> 100) causes mem usage to spike significantly). 

What I am doing currently is loading up the data from server then performing a reloadData on the ASCollectionView once the data comes in. This triggers the load of all items in the collection view at the same time.

My initial thought was that calling recursivelyFetchData on the collection node in place of reloadData would do the trick but no cells are loaded. My guess is that ASRangeController is probably the solution to this but I can't figure out a way to perform the initial load of the collection node without calling reloadData first.

Ultimately my goal is to only load a screenful of cells at a time without prefetching cells that are outside of the range controllers configuration. Any suggestions?

Bonus question: 

I am using a collection view with multi select enabled (to show a check mark when the item is selected). On didSelect/didDeselect I reload the index path using reloadItemsAtIndexPaths however this causes all items below the selected item to momentarily shift up and then back down again causing the collection to 'flash' as the cell size is recalculated. Is there any way to simply get a reference to the node (calling collectionView:nodeForItemAtIndex: would alloc a new cell so that doesn't seem like an option to get a reference to the node currently being displayed)

Thanks!

**Comment by appleguy** [comment]
@KieranLafferty Hey there - this should definitely be solvable.  If you could share at least a memory profile, that would be super helpful.  Much better yet, I'd be able to work very quickly to come to a solution with you if you'd be willing to share the code.  I'll keep it confidential and private if you're willing to email it to asyncdisplaykit@gmail.com, and will give you my iMessage for coordination.

Anyway, allocating nodes should be extremely cheap - cheaper even than allocating layers, and well over an order of magnitude cheaper than views.  They should only take a few hundred bytes each, not even a few kilobytes.  So it should absolutely not cause memory problems simply to load the nodes.

Things to check for:

*** Make sure you are not accessing the .view property in the -init method of the node classes, nor doing anything related to UIKit (gesture recognizers, etc).  Move all that stuff to the -didLoad method.

*** Be careful what you load in -fetchData, as this range is fairly large by default (I think about 3 screens).  Feel free to change the size of the range with setTuningParameters:forRangeType:.

*** Make sure you do not provide decoded images to ASImageNode or ASNetworkImageNode, and let them do their own loading rather than kicking off image loads & decodes for everything up front.

Please let me know your findings / progress as I want to be certain you solve this issue.  There should not be any particularly difficult hurdle to ensuring that memory is very responsibly managed with AsyncDisplayKit.

**Comment by KieranLafferty** [comment]
Hey turns out it was being caused by another piece of code that was unrelated to ASDK :) Thanks for your willingness to help! 

Kieran
