### ISSUE TITLE
[ASTextNode] Add `linkTextAttributes` for customizing link attributes

### ISSUE THREAD

**Issue by samhsiung** [facebook/AsyncDisplayKit#967]
This would model `UITextView` interface which has a `linkTextAttributes` property for customizing link text attributes. `NSForegroundColorAttributeName` is otherwise ignored if `NSLinkAttributeName` is set.

http://stackoverflow.com/questions/25457131/setting-nslinkattributename-font-color

**Comment by appleguy** [comment]
@samhsiung do you happen to know what is causing these attributes to be ignored in the ASDK implementation anyway?  I haven't looked at it in detail yet, but I'm wondering if it is necessary for them to be skipped and if we absolutely need new API or if we can just allow them to be respected while still handling the entire multi-styled substring as a link if it is so attributed.

**Comment by samhsiung** [comment]
According to this writeup: https://www.cocoanetics.com/2015/03/customizing-uilabel-hyperlinks/  

>NSLayoutManager has a internal color hard-coded for glyph ranges belonging to a hyperlink. It ignores the NSForegroundColorAttributeName, we believe wrongfully so. All drawing functions are called with the CGContext already configured by layout manager. This includes setting the fill color for the glyphs.

They were able to work around this behaviour by subclassing `NSLayoutManager` and overriding `showCGGlyphs...`
```
- (void)showCGGlyphs:(const CGGlyph *)glyphs 
           positions:(const CGPoint *)positions 
               count:(NSUInteger)glyphCount
                font:(UIFont *)font 
              matrix:(CGAffineTransform)textMatrix 
          attributes:(NSDictionary *)attributes
           inContext:(CGContextRef)graphicsContext
{
   UIColor *foregroundColor = attributes[NSForegroundColorAttributeName];
 
   if (foregroundColor)
   {
      CGContextSetFillColorWithColor(graphicsContext, foregroundColor.CGColor);
   }
 
   [super showCGGlyphs:glyphs 
             positions:positions 
                 count:glyphCount 
                  font:font 
                matrix:textMatrix 
            attributes:attributes 
             inContext:graphicsContext];
}
```

We could do something similar if we wanted to support using `NSForegroundColorAttributeName` for ranges with `NSLinkAttributeName` set without adding a new API.

In CSS, if a color is specified for a div, it won't apply to the links underneath it. There has to be a specific rule targeting links in order to style them. Perhaps Apple wanted to mirror the way link styling is handled in CSS.

**Comment by bsmith11** [comment]
For others running into this problem, a temporary workaround is to use a custom link attribute name instead of the default `NSLinkAttributeName`

**Comment by appleguy** [comment]
@bsmith11 - we did fix the color issue and it should now respect that attribute. We would love to support linkedTextAttributes and perhaps a native API for specifying the ranges of links if this seems cleaner. Feel free to make a PR if you would like to attempt implementing this. It would be a great contribution!

------------------

The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
