### ISSUE TITLE
Provide a UIScrollView wrapper node.

### ISSUE THREAD

**Issue by Morgan-Kennedy** [facebook/AsyncDisplayKit#99]
Hey I know we can do an ASDisplayNode, and have it of class: UIScroll view, but I've got scroll views within ASCellNodes and really want to have those cells laying out asynchronously (which gets screwed up if I use UI anything. Is there are possibility of ASScrollNode?

**Comment by Jercik** [comment]
Thinking out loud: What do you think about reimplementing ASScrollView from scratch instead of wrapping UIScrollView? I understand that wrapping is probably only reasonable thing to do with UITableView and UICollectionView because this classes are very big and complex, but reimplementation of UIScrollView should be smaller than e.g. ASTextNode. Am I missing something?

**Comment by toulouse** [comment]
Added some thoughts to the commit referenced. Should I port that over to this issue?

**Comment by secretiverhyme** [comment]
@Jercik, you're right that [re-implementing UIScrollView](http://oleb.net/blog/2014/04/understanding-uiscrollview/) is [pretty straightforward](http://oleb.net/blog/2014/05/scrollview-inertia-bouncing-rubberbanding/).  The critical distinction here is that ASTextNode substantially benefits from asynchronous sizing and rendering, but any UIScrollView implementation will only ever be concerned with synchronous behaviour.  Since ASTableView and ASCollectionView are not nodes and will still inherit from UIScrollView even if we build a custom scroll node, we're not left with a compelling enough reason to reinvent this particular wheel.
